### PR TITLE
Fix incomprehensible error message when git revision doesn't exist

### LINKED ISSUE #13295: Improve error message when git revision doesn't exist
When we give a non-existent revision to a repository or pin stanza, the revision store spits out the following error:

```
  $ dune pkg lock 2>&1 | dune_cmd subst '/[^ ]*/bin/git' 'git'
  Error: Command returned nothing: cd
  $TESTCASE_ROOT/.cache/dune/git-repo
  && git rev-parse
  --verify --quiet nonexistent-branch^{commit}
  [1]
```

This is an implementation detail and not a good user error. We should instead tell the user that their revision could not be found together with the location of the offending url.

Reproduction case:
- #13294

### PR DESCRIPTION
**Pull request by ElectreAAS**
Fixes #13295, incorporates the tests from #13294

`Process.run_capture_lines` (with an 's') gives a much better error message than the without-s counterpart

### CODE REVIEW

File: src/dune_engine/process.ml [hunk 1]
```diff
@@ -1238,7 +1238,7 @@ let run_capture_line
            User_error.raise
              ?loc
              ~annots
-             [ Pp.textf "command returned too many lines: %s" cmdline
```
Comment (Alizter) [inline src/dune_engine/process.ml:1241]: Let's do this some other time. (We might even get rid of this function all together)

**Review by Alizter — APPROVED** [review]
