### PR TITLE
fix(10685): display hint when no action field in rule

### LINKED ISSUE #10685: Point to (alias) when action field is absent
Sometimes, I use `rule` stanzas to consolidate two inner targets, e.g.:

```clojure
(rule
 (alias parent)
 (deps
  (alias child_one)
  (alias child_two)))
```

But I get `Error: field action missing` from Dune, so I end up using something like this:

```clojure
(rule
 (alias parent)
 (deps
  (alias child_one)
  (alias child_two))
 ; empty action
 (action (progn)))
```

I wonder why is the `action` field required? Is there anything wrong with having a rule with no action, but just putting together a bunch of `deps`? And as a side question: is there a better way for empty actions than using `progn`?

### PR DESCRIPTION
**Pull request by maiste**
This PR allows `dune` to display a hint when trying to use `rule` without an `action` stanza.

Closes #10685

### CODE REVIEW

File: src/dune_rules/stanzas/rule_conf.ml [hunk 1]
```diff
@@ -153,6 +153,18 @@ let long_form =
              ];
          Standard, true
      in
+     let action =
+       match action_o with
+       | Some action -> action
+       | None ->
+         let hints =
+           if List.is_non_empty aliases
```
Comment (rgrinberg) [inline src/dune_rules/stanzas/rule_conf.ml:161]: you can reverse this condition is `List.is_empty`

File: test/blackbox-tests/test-cases/github10685.t [hunk 2]
```diff
@@ -0,0 +1,55 @@
+
```
Comment (emillon) [inline test/blackbox-tests/test-cases/github10685.t:1]:
```suggestion
```

**Review by emillon — APPROVED** [review]
