### PR TITLE
Fix #4936

### LINKED ISSUE #4936: test stanza with C stubs raises an exception
Hi!

(the body of this issue is a cram test)

I'm noticed that trying to attach C stubs to a test raises an exception:

This is an executable with C stubs attached:

    $ touch e.ml stubs.c
    $ cat > dune << EOF
    > (executable
    >  (name e)
    >  (modes exe)
    >  (foreign_stubs
    >   (language c)
    >   (names stubs)))
    > EOF

The build works:

    $ dune build

But with a test stanza, it crashes:

    $ sed -e s/executable/test/ -i dune

    $ dune build
    Internal error, please report upstream including the contents of _build/log.
    Description:
      ("Map.find_exn: failed to find key", { key = "e"; keys = [] })
    Raised at Stdune__Code_error.raise in file
      "otherlibs/stdune-unstable/code_error.ml", line 11, characters 30-62
    Called from Fiber.O.(>>|).(fun) in file "src/fiber/fiber.ml", line 288,
      characters 36-41
    Called from Fiber.Execution_context.apply in file "src/fiber/fiber.ml", line
      182, characters 9-14
    Re-raised at Stdune__Exn.raise_with_backtrace in file
      "otherlibs/stdune-unstable/exn.ml", line 36, characters 27-56
    Called from Fiber.Execution_context.run_jobs in file "src/fiber/fiber.ml",
      line 204, characters 8-13
    Re-raised at Stdune__Exn.raise_with_backtrace in file
      "otherlibs/stdune-unstable/exn.ml", line 36, characters 27-56
    Called from Fiber.Execution_context.run_jobs in file "src/fiber/fiber.ml",
      line 204, characters 8-13
    Re-raised at Stdune__Exn.raise_with_backtrace in file
      "otherlibs/stdune-unstable/exn.ml", line 36, characters 27-56
    Called from Fiber.Execution_context.run_jobs in file "src/fiber/fiber.ml",
      line 204, characters 8-13
    -> required by ("load-dir", In_build_dir "default")
    -> required by ("build-alias", { dir = "default"; name = "default" })
    
    I must not crash.  Uncertainty is the mind-killer. Exceptions are the
    little-death that brings total obliteration.  I will fully express my cases. 
    Execution will pass over me and through me.  And when it has gone past, I
    will unwind the stack along its path.  Where the cases are handled there will
    be nothing.  Only I will remain.
    [1]

### PR DESCRIPTION
**Pull request by rgrinberg**

### CODE REVIEW

File: src/dune_rules/foreign_sources.ml [hunk 1]
```diff
@@ -124,23 +124,57 @@ let check_no_qualified (loc, include_subdirs) =
...
+          , exes )
+        | Executables exe
+        | Tests { exes = exe; _ } ->
+          let all = eval_foreign_stubs d exe.buildable.foreign_stubs ~sources in
+          (libs, foreign_libs, (exe, all) :: exes)
+        | _ -> acc)
+  in
+  let () =
+    let objects =
+      List.unordered_concat
```
Comment (snowleopard) [inline src/dune_rules/foreign_sources.ml:148]: I'm not sure using the unordered variant is a good idea here: we'll end up with a hard to understand order of objects, which might end up in a link command line or error message or somewhere similarly bad (even if it's not the case now, it might happen after a future refactoring). All this just to avoid a couple of `List.rev`s? Just the mere existence of `List.unordered_concat` makes me nervous :)

Comment (snowleopard) [reply src/dune_rules/foreign_sources.ml:148]: (Same concern about all the `List.rev_map`s below: this seems like a wrong thing to optimise in a build system.)

Comment (snowleopard) [reply src/dune_rules/foreign_sources.ml:148]: P.S.: Actually, if this is indeed worth optimising (say, it shows up in profile), then we could introduce a separate data structure for managing (some) lists in Dune, which would provide stable order and fast `concat_map`.

Comment (rgrinberg) [reply src/dune_rules/foreign_sources.ml:148]: > hen we could introduce a separate data structure for managing (some) lists in Dune, which would provide stable order and fast concat_map.

Like a dlist? I suppose it's worth trying.

Amusingly, the error messages after this PR are actually improved in my view. The duplicate "thing" pointed out by the error is now the second rather than the first occurrence of the thing.

I'm still a bit annoyed by how we do all this extra work that is only useful in the tiny minority of cases when the error occurs.

Comment (rgrinberg) [reply src/dune_rules/foreign_sources.ml]: > P.S.: Actually, if this is indeed worth optimising (say, it shows up in profile), then we could introduce a separate data structure for managing (some) lists in Dune, which would provide stable order and fast concat_map.

In my profiling, a 1/3rd of all work in a zero build is just GC'ing. Last time I did some deforestation, I managed to shave off 100ms off a zero rebuild for some moderate workspace. Nothing to scoff at. Especially given that the potential to optimize more is huge given all that trash we currently produce.

I removed the optimizations for now.

Comment (snowleopard) [reply src/dune_rules/foreign_sources.ml]: > Last time I did some deforestation, I managed to shave off 100ms off a zero rebuild for some moderate workspace. Nothing to scoff at.

I agree, it's definitely worth looking at more efficient data structures for various things (ordered lists, paths, etc.). I was just a bit taken aback by seeing these optimisations pollute the business logic -- we should try to hide them behind some abstractions or it will become pretty difficult to read Dune's code.

Comment (snowleopard) [reply src/dune_rules/foreign_sources.ml]: (Actually, we already have appendable lists in Stdune, perhaps, we could just switch to them in a few key places.)

File: test/blackbox-tests/test-cases/foreign-library.t/run.t [hunk 2]
```diff
@@ -310,11 +310,11 @@ Testsuite for the (foreign_library ...) stanza.
...
 
   $ ./sdune build
-  File "lib/dune", line 6, characters 1-22:
-  6 |  (archive_name addmul)
+  File "lib/dune", line 2, characters 1-22:
+  2 |  (archive_name addmul)
        ^^^^^^^^^^^^^^^^^^^^^
   Error: Multiple foreign libraries with the same archive name "addmul"; the
-  name has already been taken in lib/dune:2.
+  name has already been taken in lib/dune:6.
```
Comment (snowleopard) [inline test/blackbox-tests/test-cases/foreign-library.t/run.t:317]: Hah, the above errors are an improvement (we point to the duplicates), but this one goes the other way. I wonder if it's easy to make this more consistent.

**Review by snowleopard — APPROVED** [review]
Looks good, thanks! Regarding error messages: two got better, one got worse. Can we do anything about it?

**Comment by rgrinberg** [comment]
> Regarding error messages: two got better, one got worse. Can we do anything about it?

For now I just reverted to the old messages. We'll figure out a better way to handle this stuff later.
