### PR TITLE
Fix global evaluation in external dirs

### LINKED ISSUE #5540: Confusing error related to include_dirs inside foreign_stubs with Dune 3.0.3
Hi,

I have been getting this error message with Dune 3.0.3 on OCaml 4.13.1 when trying to build some FreeType wrapper with [this dune file in my project](https://github.com/SylvainBoilard/Peril/blob/e1a0627a2aac1ca2b4d8b713ae8baebff2e9cf73/libs/dune):

```
File "libs/dune", line 8, characters 18-32:
8 |   (names          FreeType_stubs)
                      ^^^^^^^^^^^^^^
Error: File unavailable: /usr/include/freetype2/freetype
This is not a regular file (S_DIR)
```

This dune file used to work just fine in 2.9.3 . I was able to fix the build by changing this ([line 9](https://github.com/SylvainBoilard/Peril/blob/e1a0627a2aac1ca2b4d8b713ae8baebff2e9cf73/libs/dune#L9))

`(include_dirs /usr/include/freetype2)`

into this

`(flags -I/usr/include/freetype2)`

but I was wondering why this error message was appearing now. Nothing caught my eye in the recent changelogs that would explain this, and I find the error message itself quite unhelpful. Could this be a regression? Or maybe I am missing something?

Cheers,

### PR DESCRIPTION
**Pull request by rgrinberg**
As mentioned in the test, globs should only match against files.

Fix #5540

### CODE REVIEW

File: src/dune_engine/load_rules.ml [hunk 1]
```diff
@@ -32,7 +32,7 @@ module Loaded = struct
     }
 
   type t =
-    | Non_build of Path.Set.t
+    | Non_build of { files : Path.Set.t }
```
Comment (snowleopard) [inline src/dune_engine/load_rules.ml:35]: Do I understand correctly that paths here can only be source or external? If yes, I think it's worth making the types more precise.

Comment (snowleopard) [reply src/dune_engine/load_rules.ml:35]: Oh, wait, looks like they can only be source files, right? Then why isn't this `Path.Source.Set.t`?

Comment (snowleopard) [reply src/dune_engine/load_rules.ml:35]: For example, we could have two constructors `Source` and `External`, with corresponding sets of paths, instead of one `Non_build`.

File: test/blackbox-tests/test-cases/glob-deps.t/run.t [hunk 2]
```diff
@@ -8,3 +8,21 @@ to the output but [foo/new-dir] is ignored.
...
+  > EOF
+  $ mkdir -p _foo/dir
+  $ touch _foo/file
+  $ cat >dune <<EOF
+  > (rule
+  >  (alias foo)
+  >  (deps (glob_files "$PWD/_foo"))
+  >  (action (echo %{deps})))
+  > EOF
+  $ dune build @foo
```
Comment (snowleopard) [inline test/blackbox-tests/test-cases/glob-deps.t/run.t:28]: Wait, why is `_foo/file` not shown?

Comment (rgrinberg) [reply test/blackbox-tests/test-cases/glob-deps.t/run.t:28]: Oops, I wrote the glob wrong. It should work now.

File: src/dune_engine/load_rules.ml (hunk 1 above)
Comment (rgrinberg) [reply src/dune_engine/load_rules.ml:35]: > Do I understand correctly that paths here can only be source or external? 

Actually, it can only be external. In the test, i'm referring to source paths by an absolute path, so dune doesn't care where they actually exist and just treats them as external.

> If yes, I think it's worth making the types more precise.

Good point, but there's a bit of a trade-off here. It means that we'll need to convert it to `Path.Set.t` anyway when loading the rules. It seems like a bit of an extra conversion that doesn't pay off.

Comment (snowleopard) [reply src/dune_engine/load_rules.ml:35]: > Actually, it can only be external.

Wow, even better!

I am confused. Why would the caller of `load_rules` want a less precise type? If you get a `Path.t` you have to accommodate for all possibilities, perhaps, filling out the corresponding branches with some `assert false`s. If you've got a `Path.External.t`,  then you don't need the `assert`s, and turning it to a `Path.t` is trivial: just append the `External` constructor.

Comment (rgrinberg) [reply src/dune_engine/load_rules.ml:35]: >  and turning it to a Path.t is trivial: just append the External constructor.

It is trivial for paths, but not for sets of paths! And that's the only use case we actually care about here.

By the way, it's not even obvious on how precise we should go. We could do:

```ocaml
| Non_build_external of Path.External.Set.t (* loading external paths *)
| Non_build_source of Path.Source.Set.t (* loading source paths *)
```

Or what you originally suggested:

```ocaml
| Non_build of { external : Path.External.Set.t ; source : Path.Source.Set.t }
```

The former is the most precise, but again this precision isn't being used anywhere.

So I propose we leave things as is and perhaps leave a comment for now.

Comment (snowleopard) [reply src/dune_engine/load_rules.ml:35]: Of course, maybe I missed something in my quick look. If you really think that we can't afford to use the right API because of performance, let's use the above type but with `Path.Set.t`s instead and a comment explaining why we have to do that, and what needs to happen to avoid this (I guess, we need a better type for sets of paths?).

Comment (snowleopard) [reply src/dune_engine/load_rules.ml:35]: (The reason I am so persistent about such a seemingly trivial matter is that I spent hours of debugging time figuring things out around the build systems engine and its interaction with loading rules, and I'm sure that having more precise APIs would help me a lot just to make sense of things. This is just one such spot but there are many! Pushing type precision slowly through the code base will pay back in saving development time, I'm sure.)

Comment (rgrinberg) [reply src/dune_engine/load_rules.ml]: Alright, I refactored it.

**Review by snowleopard — APPROVED** [review]
Awesome, thank you for the refactoring!
