### PR TITLE
Fix Merlin configuration server in a non-default build context

### LINKED ISSUE #4125: Merlin does not work when enabled in a non-default build context
## Expected Behavior

When using `(merlin)` to enable merlin in a non-default build context, merlin should work.

## Actual Behavior

Merlin/ocaml lsp don't work. `dune ocaml-merlin --dump-config=$(pwd)` returns nothing. It looks like the merlin files are correctly generated in the chosen build context directory. However `dune ocaml-merlin --dump-config` seems to always look for the files in the default context. 

## Reproduction

Use a cross-compilation `dune-workspace` file:
```
(lang dune 2.0)

(context (default))

(context
 (opam
  (name cross)
  (switch default)
  (merlin)))
```

## Specifications

- Version of `dune` (output of `dune --version`): 2.8.1
- Version of `ocaml` (output of `ocamlc --version`): 4.11.1
- Operating system (distribution and version): Archlinux

### PR DESCRIPTION
**Pull request by voodoos**
This PR fixes #4125.

The workspace initialization was wrong in the `dune ocaml-merlin` binary.
I added a test which is disabled by default as it requires a global switch `default` to exist.

### CODE REVIEW

**Comment by rgrinberg** [comment]
It should be possible to get the tests to work by default. Have a look at the workspace tests for multi contexts tests.

**Comment by voodoos** [comment]
> It should be possible to get the tests to work by default. Have a look at the workspace tests for multi contexts tests.

Looking at other tests (grep `(opam `) I only found two:
- One (`workspaces.t/opma`) is disabled, saying 
> A workspace context can be defined using an opam switch. This test is disabled
because we don't really have a way to mock an opam switch.
- And the other uses a switch named `default` so dune's test-suite already assumes such a switch is present on the system. I will use that switch then.

File: bin/ocaml_merlin.ml [hunk 1]
```diff
@@ -28,14 +28,12 @@ let term =
...
   in
-  Common.set_common common ~targets:[];
+  Common.set_common common ~log_file:No_log_file ~targets:[];
   Scheduler.go ~common (fun () ->
-      Dune_engine.File_tree.init ~recognize_jbuilder_projects:true
-        ~ancestor_vcs:None;
-      Dune_rules.Workspace.init ();
-      ( match dump_config with
+      let open Fiber.O in
+      let+ _workspace = Import.Main.scan_workspace common in
```
Comment (jeremiedimino) [inline bin/ocaml_merlin.ml:34]: This is going to scan the workspace and load all the dune files. This can be quite expensive in a large workspace. It feels like the `dune ocaml-merlin` command shouldn't do this. WDYT?

Comment (voodoos) [reply bin/ocaml_merlin.ml:34]: I agree that `dune ocaml-merlin` should not do that.

I there a more lightweight way to detect the workspace configured for Merlin ?

Comment (jeremiedimino) [reply bin/ocaml_merlin.ml:34]: This should work: `(Workspace.workspace ()).merlin_context`

Comment (voodoos) [reply bin/ocaml_merlin.ml:34]: This is what was already done: 

https://github.com/ocaml/dune/blob/78707ffa288bc45dc61de05af481e7ec935f586b/src/dune_rules/merlin_server.ml#L51-L54

However without the previous call to `scan_workspace` this seems to always return `default`, and that was the reason the issue was opened in the first place.

Comment (jeremiedimino) [reply bin/ocaml_merlin.ml:34]: Was it loading the right workspace file?

**Comment by voodoos** [comment]
I cherry picked the commit from https://github.com/ocaml/dune/pull/4132 adding the possibility to specify which variant of the `default` context is used for Merlin configuration.

File: src/dune_rules/context.ml [hunk 2]
```diff
@@ -743,9 +743,10 @@ let instantiate_context env (workspace : Workspace.t)
       ; fdo_target_exe
       ; dynamically_linked_foreign_archives
       ; instrument_with
+      ; merlin
       } ->
     let merlin =
-      workspace.merlin_context = Some (Workspace.Context.name context)
+      workspace.merlin_context = Some (Workspace.Context.name context) || merlin
```
Comment (jeremiedimino) [inline src/dune_rules/context.ml:749]: Do we still need this? IIRC, the code that parses the workspace file in workspace.ml ensures that there is exactly one context that has `merlin` set to true.

**Comment by jeremiedimino** [comment]
> I cherry picked the commit from #4132 adding the possibility to specify which variant of the default context is used for Merlin configuration.

I don't think we should do this. It is going to make it more difficult to backport only the bugfix in 2.8. We could backport both the bugfix and the new feature, but that is going to break our usual compatibility rules. Let's be strict here and add the `(merlin)` field in 2.9. If we want this feature soon, we can just release 2.9 soon.

File: test/blackbox-tests/test-cases/merlin/github4125.t/run.t [hunk 3]
```diff
@@ -0,0 +1,39 @@
+  $ unset INSIDE_DUNE
+  $ dune build
```
Comment (jeremiedimino) [inline test/blackbox-tests/test-cases/merlin/github4125.t/run.t:2]: Something doesn't seem right here. If you unset `INSIDE_DUNE`, then `dune build` is going to:

- read the user configuration file
- lookup the root outside of the test
- and a few other things

Which is going to make it difficult to keep this test reproducible.

Why do you need to unset `INSIDE_DUNE`?

**Review by ghost — CHANGES_REQUESTED** [review]

File: test/blackbox-tests/test-cases/merlin/github4125.t/run.t (hunk 3 above)
Comment (voodoos) [reply test/blackbox-tests/test-cases/merlin/github4125.t/run.t:2]: Because without it the Dune in the test file doesn't tries to reach the root of the test project and thus the test where I launch `dune ocaml-merlin` from a subfolder fails because the `dune-workspace` file at the root of the project is not loaded. It is a test about root discovery...

With `INDISE_DUNE` unset in the test dune does find the correct root for the test, that is `$TESTCASE_ROOT` and not the root of the real dune project.

Other tests already being at the root pass without problem so i can just remove this one if you prefer.

https://github.com/ocaml/dune/blob/bebb7a9432b149fce95ac820757216372afb8f0f/bin/workspace_root.ml#L90-L93

File: src/dune_rules/context.ml (hunk 2 above)
Comment (voodoos) [reply src/dune_rules/context.ml:749]: Yes it is still needed because the merlin context, when chosen by default, is not reflected in the context `merlin` field, only in `workspace.merlin_context`.

However the `|| merlin` part of the test is superfluous as if the user chose a context to enable merlin this should already be checked by the `workspace.merlin_context` test.

**Comment by voodoos** [comment]
> > I cherry picked the commit from #4132 adding the possibility to specify which variant of the default context is used for Merlin configuration.
> 
> I don't think we should do this. It is going to make it more difficult to backport only the bugfix in 2.8. We could backport both the bugfix and the new feature, but that is going to break our usual compatibility rules. Let's be strict here and add the `(merlin)` field in 2.9. If we want this feature soon, we can just release 2.9 soon.

You are right, I dropped it.

File: test/blackbox-tests/test-cases/merlin/github4125.t/run.t (hunk 3 above)
Comment (jeremiedimino) [reply test/blackbox-tests/test-cases/merlin/github4125.t/run.t:2]: > With INSIDE_DUNE unset in the test dune does find the correct root for the test, that is $TESTCASE_ROOT and not the root of the real dune project.

This is because `dune-workspace` has precedence over `dune-project`. If you add a `dune-workspace` file at the root of dune, then the test will pick this as root.

If we want to test this properly, we need a way to tell Dune to stop the search at `$TESTCASE_ROOT`. But unsetting `INSIDE_DUNE` seems too dodgy.

Comment (voodoos) [reply test/blackbox-tests/test-cases/merlin/github4125.t/run.t:1]: For now I removed the test in question.

File: CHANGES.md [hunk 4]
```diff
@@ -4,6 +4,9 @@ Unreleased
 - Fixed a crash in watch mode introduced in 2.8.0 (#4118, fixes #4117,
   @rgrinberg)
 
+- Fixed wrong workspace discovery from `dune ocaml-merlin` and allow custom
+  context based on default to be used for merlin. (#4127, fixes #4125, @voodoos)
```
Comment (jeremiedimino) [inline CHANGES.md:8]: Seems like the last commit should be reverted

**Review by ghost — APPROVED** [review]
Looks good to merge once changelog is updated

File: CHANGES.md (hunk 4 above)
Comment (voodoos) [reply CHANGES.md:8]: I forgot to drop it when rebasing, good catch.

File: test/blackbox-tests/test-cases/merlin/github4125.t/dune-workspace [hunk 5]
```diff
@@ -0,0 +1,9 @@
+(lang dune 2.0)
+
+(context (default))
+
+(context
+ (opam
+  (name cross)
+  (switch default)
+  (merlin)))
```
Comment (bobot) [inline test/blackbox-tests/test-cases/merlin/github4125.t/dune-workspace:9]: I believe this test only work if we have a switch named `default` in our opam configuration. @voodoos

Comment (voodoos) [reply test/blackbox-tests/test-cases/merlin/github4125.t/dune-workspace:9]: Sorry for that, I thought other tests were already relying on such a switch but they must have been disabled since.
@rgrinberg said it might be possible to test this kind of feature but I did not found examples of such things in the test-base.

I think disabling this test is fine if don't find a workaround.
