### PR TITLE
Fix hash collision once and for all

### LINKED ISSUE #1524: Hash collision error after upgrading to dune 1.5
After upgrading dune to 1.5, I started getting a hash collision error when running dune build in watch mode. The error does not occur when running dune build without the `-w` flag.  

The full error:

```
Hash collision between set of ppx drivers:
- ppx_compare, ppx_deriving.std, ppx_sexp_conv, ppx_variants_conv
- ppx_compare, ppx_deriving.std, ppx_sexp_conv, ppx_variants_conv
Had errors.
```

I am running OCaml `4.07.0`, dune `1.5.0`, and OPAM `2.0.1` on macOS Mojave `10.14`.

### PR DESCRIPTION
**Pull request by ghost**
It should be easier to check the correctness of the new code. We no longer need to clear the reverse table between builds given that the values stored in it are pure.

Fixes #1524

### CODE REVIEW

File: src/preprocessing.ml [hunk 1]
```diff
@@ -45,52 +55,39 @@ end = struct
...
+      else begin
+        let to_string { pps; scope } =
+          let s = String.enumerate_and (List.map pps ~f:Lib_name.to_string) in
+          match scope with
+          | None -> s
+          | Some scope ->
+            sprintf "%s (in project: %s)" s
+              (Dune_project.Name.to_string_hum scope)
+        in
+        die "Hash collision between set of ppx drivers:\n\
```
Comment (emillon) [inline src/preprocessing.ml]: Do you think it's feasible to add a test case covering this failure mode?

Comment (diml) [reply src/preprocessing.ml]: The function that is being reverse is simpler now, before it was `Lib.t list -> Digest.t`, while now it's just `string list * string option -> Digest.t`, so the same results can be reused between scopes/build contexts/builds

**Review by rgrinberg — APPROVED** [review]
