### PR TITLE
Fix rpc not transferring promotion warnings to the client

### LINKED ISSUE #12577: dune promote + watchmode clears promotion database
When running `dune promote` with a watchmode build, it clears the promotion database after the first invocation. This is annoying and requires a restart of the build server. We need to somehow stop the server from flushing the promotion database after a promote request over RPC.

### LINKED ISSUE #12578: dune promote doesn't fail when not available in the promotion database
When the file we wish to promote isn't in the promotion database we typically print a warning:
```
$ dune promote bin/main.ml
Warning: Nothing to promote for bin/main.ml.
```

but when connecting to watch mode:
```
$ dune promote bin/main.ml
Success
```
which is both uninformative and misleading.

### PR DESCRIPTION
**Pull request by ElectreAAS**
Fixes #12578, and only looks like it fixes #12577, but doesn't, it was a red herring. See discussion on latter PR.

## What was missing
- A proper way for RPC requests to return warnings encountered during build.

### CODE REVIEW

File: bin/rpc/rpc_common.ml [hunk 1]
```diff
@@ -77,12 +77,13 @@ let establish_client_session ~wait =
...
 let warn_ignore_arguments lock_held_by =
   User_warning.emit
-    [ Pp.paragraphf
-        "Your build request is being forwarded to a running Dune instance%s. Note that \
-         certain command line arguments may be ignored."
-        (match lock_held_by with
-         | Dune_util.Global_lock.Lock_held_by.Unknown -> ""
-         | Pid_from_lockfile pid -> sprintf " (pid: %d)" pid)
+    [ Pp.tag User_message.Style.Warning
+      @@ Pp.paragraphf
```
Comment (Alizter) [inline bin/rpc/rpc_common.ml]: Using |> will save indentation here

File: src/promote/diff_promotion.mli [hunk 2]
```diff
@@ -27,7 +27,17 @@ end
...
-val filter_db : Dune_rpc_private.Files_to_promote.t -> File.t list -> File.t list
-val diff_for_file : File.t -> (Print_diff.Diff.t, User_message.t) result Fiber.t
-val promote_files_registered_in_last_run : Dune_rpc_private.Files_to_promote.t -> unit
-val display : Dune_rpc_private.Files_to_promote.t -> unit Fiber.t
+
+val promote_files_registered_in_last_run
+  :  Dune_rpc_private.Files_to_promote.t
+  -> Path.Source.t list
+
+val display_diffs
```
Comment (rgrinberg) [inline src/promote/diff_promotion.mli]: Could you look for a way to do this that avoids introducing a higher order function? Perhaps introduce a function that extracts that missing sources separately?

**Review by rgrinberg — CHANGES_REQUESTED** [review]

File: src/promote/diff_promotion.mli (hunk 2 above)
Comment (ElectreAAS) [reply src/promote/diff_promotion.mli]: What's wrong with higher-order functions? The constructor `Files_to_promote.These` used to include a function with the same type, this is moved towards the place it's actually used.

> Perhaps introduce a function that extracts that missing sources separately?

Something like `display_missing : Files_to_promote.t -> unit Fiber.t`?
Since it would be used right before the other `display_*` functions, that would mean the function `sort_for_display` (which includes a call to `load_db`) would be called twice, ignoring half its output each time.
Maybe that's premature optimization in a codepath that is never performance critical anyway, but it still looks wrong to me

Comment (ElectreAAS) [reply src/promote/diff_promotion.mli]: A different way to solve this is just to have `on_missing` be a public value in `Diff_promotion`, and call it when necessary

Comment (rgrinberg) [reply src/promote/diff_promotion.mli]: There's nothing wrong with higher-order functions when they're used appropriately. The problem at hand seems simple enough that it can be solved with a first order approach. So I would prefer to stick to simpler tools when possible. It is quite easy to misuse and abuse higher order functions.

> Since it would be used right before the other display_* functions, that would mean the function sort_for_display (which includes a call to load_db) would be called twice, ignoring half its output each time.

I agree that this would be a problem. Ignoring the performance considerations, it would be bad to read the db twice without a guarantee that we'd get the same value anyway. How about making the db an explicit value?

```ocaml
type db
val load : unit -> db
val missing : db -> Files_to_promote.t -> Path.Source.t list
val display_diffs : db -> Files_to_promote.t -> unit
```

You don't necessarily need to stick to this API, but it's the simplest thing I could think to avoid the higher order function.

File: src/dune_rpc_impl/server.ml [hunk 3]
```diff
@@ -369,8 +369,11 @@ let handler (t : _ t Fdecl.t) handle : 'build_arg Dune_rpc_server.Handler.t =
       (* A 'successful' formatting means there is nothing to promote. *)
       | Success -> ()
       | Failure ->
-        Promote.Diff_promotion.promote_files_registered_in_last_run
-          Dune_rpc.Files_to_promote.All
+        let _is_necessarily_empty =
+          Promote.Diff_promotion.promote_files_registered_in_last_run
+            Dune_rpc.Files_to_promote.All
+        in
+        ()
```
Comment (ElectreAAS) [inline src/dune_rpc_impl/server.ml]: Don't know how to explain clearly and succinctly that the return value of `promote_files... All` will always be `[]`

File: src/promote/diff_promotion.ml [hunk 4]
```diff
@@ -149,47 +147,61 @@ let do_promote db files_to_promote =
...
-        | Some srcs ->
-          promote_one fn srcs;
-          Path.Source.Map.remove by_targets fn)
-    in
+  let remaining =
     Path.Source.Map.to_list by_targets
     |> List.concat_map ~f:(fun (dst, srcs) ->
       List.map srcs ~f:(fun (src, staging) -> { File.src; staging; dst }))
+  in
+  let sorted_missing = List.rev missing in
```
Comment (ElectreAAS) [inline src/promote/diff_promotion.ml:180]: `group_by_targets` will sort all files, but the `fold` above reverses the list of missing files.
The absence of this reverse is what had lead to a swap in `test-cases/promote/old-tests.t` that was present in this PR before I noticed

File: src/promote/diff_promotion.mli (hunk 2 above)
Comment (ElectreAAS) [reply src/promote/diff_promotion.mli]: I get what you mean. I did a version of that, without a specific type for `db` as I think `File.t list` is clear enough

File: src/promote/diff_promotion.ml [hunk 5]
```diff
@@ -149,47 +147,61 @@ let do_promote db files_to_promote =
...
+let do_promote_these db files =
+  let by_targets = group_by_targets db in
+  let by_targets, missing =
+    let files = Path.Source.Set.of_list files in
+    Path.Source.Set.fold files ~init:(by_targets, []) ~f:(fun fn (map, missing) ->
+      match Path.Source.Map.find map fn with
+      | None -> map, fn :: missing
+      | Some srcs ->
+        promote_one fn srcs;
+        Path.Source.Map.remove map fn, missing)
```
Comment (ElectreAAS) [inline src/promote/diff_promotion.ml:169]: Non-trivial note about this change:
```diff
  Path.Source.Set.fold files ~init:by_targets ~f:(fun fn map ->
-   match Path.Source.Map.find by_targets fn with
+   match Path.Source.Map.find map fn with
    | None -> [...]
    | Some srcs ->
      promote_one fn srcs;
-     Path.Source.Map.remove by_targets fn
+     Path.Source.Map.remove map fn, missing
```
I believe the previous code was erroneous, `Path.Source.Map.remove` is a pure function and we were throwing away its output at every loop iteration. However, I was unable to create a test case showcasing the bug

Comment (Alizter) [reply src/promote/diff_promotion.ml:169]: Why do you think they were being thrown away? Aren't we folding over the `files` and accumulating it's output?

Comment (ElectreAAS) [reply src/promote/diff_promotion.ml:169]: we are folding over `files` (each file named `fn`), and the accumulator (initial value `by_targets`) is named `map`. The value of `map` should evolve over the course of the iterations, with `Map.remove map x`.

In the previous code, if at iteration n we did `Map.remove by_targets x`, that value was then fed into iteration n+1 as `map`, which is ignored in the body of the loop. In iteration n+1 we do `Map.remove by_targets y`, so x is still in there.

Comment (Alizter) [reply src/promote/diff_promotion.ml:169]: Ah right. I was confused and reading the new one.

**Comment by ElectreAAS** [comment]
I just rebased on main.
I believe I addressed your request @rgrinberg, and this is ready for a second pass

File: src/dune_rpc_impl/server.ml [hunk 6]
```diff
@@ -369,8 +369,11 @@ let handler (t : _ t Fdecl.t) handle : 'build_arg Dune_rpc_server.Handler.t =
       (* A 'successful' formatting means there is nothing to promote. *)
       | Success -> ()
       | Failure ->
-        Promote.Diff_promotion.promote_files_registered_in_last_run
-          Dune_rpc.Files_to_promote.All
+        let _is_necessarily_empty =
```
Comment (rgrinberg) [inline src/dune_rpc_impl/server.ml]: This ignored value needs a type annotation.

**Review by rgrinberg — APPROVED** [review]
Haven't looked too closely, but everything seems sensible at first glance.

File: src/promote/diff_promotion.ml [hunk 7]
```diff
@@ -149,47 +147,61 @@ let do_promote db files_to_promote =
...
-    | Some Automatically -> do_promote !File.db All
+    | Some Automatically ->
+      do_promote_all !File.db;
+      []
     | Some Never | None -> !File.db
   in
   dump_db db
 ;;
 
+(* Returns the list of files that were in [files_to_promote]
```
Comment (shonfeder) [inline src/promote/diff_promotion.ml:202]: Thanks for adding the comments!

File: src/dune_rpc_impl/server.ml [hunk 8]
```diff
@@ -423,16 +426,30 @@ let handler (t : _ t Fdecl.t) handle : 'build_arg Dune_rpc_server.Handler.t =
...
+        Fiber.return (Dune_rpc.Build_outcome_with_diagnostics.Warn warnings)
     in
     Handler.implement_request rpc Procedures.Public.promote_many f
   in
   let () =
     let f _ path =
       let files = For_handlers.source_path_of_string path in
-      Promote.Diff_promotion.promote_files_registered_in_last_run
-        (These ([ files ], ignore));
+      let _ignored =
```
Comment (shonfeder) [inline src/dune_rpc_impl/server.ml]: Another place where an ignored value needs an annotation (I think we talked about this when reviewing together last week too?)

File: test/blackbox-tests/test-cases/watching/promotion-db.t [hunk 9]
```diff
@@ -0,0 +1,71 @@
+Demonstrate bug where the RPC promotion doesn't print a warning where the normal promotion does.
```
Comment (shonfeder) [inline test/blackbox-tests/test-cases/watching/promotion-db.t]: It the test "demonstrating a bug"? Or is it testing functionality to prevent regression of a bug?

File: src/dune_rpc_impl/server.ml (hunk 3 above)
Comment (shonfeder) [reply src/dune_rpc_impl/server.ml]: We talked about this sync last week, but IMO the correct way to express this is with an `assert` or a `failwith` after checking that the expected value is what you think it will always be.

The reason to *ignore* a value is because you don't what it is and so it doesn't matter what you expect it must always be.

File: bin/rpc/rpc_build.ml [hunk 10]
```diff
@@ -13,6 +13,7 @@ let term =
   in
   match response with
   | Success -> print_endline "Success"
+  | Warn _ -> print_endline "Warn"
   | Failure _ -> print_endline "Failure"
```
Comment (Alizter) [inline bin/rpc/rpc_build.ml:17]: What happens if a build contains both warnings and failures?

**Comment by Alizter** [comment]
I think it would be better to split the two changes here. I'm fairly certain the promotion database clearing bug has been solved here, so I think that can be reviewed and merged quickly. The warning forwarding however has some potential issues and I think need a more careful review.

**Comment by ElectreAAS** [comment]
I just did a pass, moving the warning state from a variant in `Build_outcome_with_diagnostics.t` to a field in `Compound_user_error.t` according to discussions we've had in passing.
During that pass, i *tried* to only keep the warning changes and to **not** fix #12577, but according to the tests, the fix is still there, so I'm puzzled.

I tested locally and it doesn't seem to be the fold problem mentionned above (https://github.com/ocaml/dune/pull/12604#discussion_r2481153162)...

**Comment by Alizter** [comment]
@ElectreAAS in that case it sounds like there is some racy behaviour. Could you intersperse some `sleep` commands to make sure things are finishing before you go onto the next command? Recall that `dune build` connecting to a watch server may exit before the server is done doing stuff to the promotion database.

File: test/blackbox-tests/test-cases/watching/promotion-db.t [hunk 11]
```diff
@@ -0,0 +1,71 @@
...
+  File "a.t", line 1, characters 0-0:
+  Error: Files _build/default/a.t and _build/default/a.t.corrected differ.
+  File "c.t", line 1, characters 0-0:
+  Error: Files _build/default/c.t and _build/default/c.t.corrected differ.
+  Error: Build failed with 2 errors.
+  [1]
+
+Make sure that the above build command has finished, and also that the server
+has finished dealing with the promotion database.
+  $ sleep 1
```
Comment (rgrinberg) [inline test/blackbox-tests/test-cases/watching/promotion-db.t]: I don't think we should have tests like this in CI. They will invariably flake and waste other people's time. We should either try to write this test in a non flaky way or disable it in CI.

File: otherlibs/dune-rpc/private/exported_types.mli [hunk 12]
```diff
@@ -227,12 +227,19 @@ module Compound_user_error : sig
...
 
   val sexp : t Conv.value
   val to_dyn : t -> Dyn.t
   val annot : t list Stdune.User_message.Annots.Key.t
-  val make : main:User_message.t -> related:User_message.t list -> t
+
+  val make
+    :  main:User_message.t
+    -> related:User_message.t list
+    -> severity:Diagnostic.severity
```
Comment (rgrinberg) [inline otherlibs/dune-rpc/private/exported_types.mli:251]: How about adding a warning constructor instead? While you're still working on this feature, you can work on it without having to make large changes across the codebase.

File: test/blackbox-tests/test-cases/watching/promotion-db.t (hunk 11 above)
Comment (Alizter) [reply test/blackbox-tests/test-cases/watching/promotion-db.t]: This should be temporary, we just want to make sure the bug is happening as intended.

Comment (ElectreAAS) [reply test/blackbox-tests/test-cases/watching/promotion-db.t]: I removed said sleep, as I made sure to explain that we only care about warnings here.

**Comment by ElectreAAS** [comment]
The fact that it looked like we solved the promotion database clearing bug was due to weird races happening. I changed the test to make it clear that we are testing the warnings, not this other behaviour.

File: otherlibs/dune-rpc/private/exported_types.ml [hunk 13]
```diff
@@ -777,7 +786,15 @@ module Compound_user_error = struct
       in
       let main = make_message (report.loc, report.message) in
       let related = List.map report.related ~f:make_message in
-      make ~main ~related)
+      let severity : Diagnostic.severity =
+        match report.severity with
+        | Error _ -> Error
+        | Warning _ -> Warning
+        | Alert _ ->
+          (* FIXME: tests expect this, but it's unclear if that should change. *)
```
Comment (Alizter) [inline otherlibs/dune-rpc/private/exported_types.ml]: Which tests expect this behaviour?

File: test/expect-tests/dune_rpc/dune_rpc_tests.ml
Comment (ElectreAAS) [inline test/expect-tests/dune_rpc/dune_rpc_tests.ml:1]: All the noise in this file is due to the adjunction of the `Alert` constructor in `exported_types.ml`

File: test/expect-tests/dune_rpc_e2e/dune_rpc_diagnostics.ml
Comment (ElectreAAS) [inline test/expect-tests/dune_rpc_e2e/dune_rpc_diagnostics.ml:1]: Same comment as above, blame `Alert`

**Comment by ElectreAAS** [comment]
We did a pass with @Alizter yesterday (thanks again btw) to not break the hashes in `test/expect-tests/dune_rpc/dune_rpc_tests.ml`, which required outputting a new version of the diagnostics RPC, which is rather verbose. This is necessary to maintain backward compatibility.
Now the hashes aren't broken, we just have a v3.
This is ready for what I hope is the final round of review

File: bin/rpc/rpc_common.ml [hunk 14]
```diff
@@ -106,6 +106,7 @@ let warn_ignore_arguments lock_held_by =
         (match lock_held_by with
          | Dune_util.Global_lock.Lock_held_by.Unknown -> ""
          | Pid_from_lockfile pid -> sprintf " (pid: %d)" pid)
+      |> Pp.tag User_message.Style.Warning
```
Comment (Alizter) [inline bin/rpc/rpc_common.ml]: We already add the tag in `User_warning.emit` for the `Warning:` text. Otherwise this entire message will be purple which I don't think we want.

**Comment by shonfeder** [comment]
@Alizter are you OK with the state of this? Anything needed for a :heavy_check_mark:

**Comment by Alizter** [comment]
I will give it another review.

**Comment by ElectreAAS** [comment]
After some considerations, we decided that the alert parsing code didn't need to be in this PR.

**Comment by ElectreAAS** [comment]
- [x] has a changelog entry

File: bin/rpc/rpc_common.ml [hunk 15]
```diff
@@ -150,22 +150,49 @@ let fire_notification
   send_request connection name ~f:(fun client -> notify_exn client notification arg)
 ;;
 
+let print_err_warn (nb_errors, nb_warns) =
```
Comment (shonfeder) [inline bin/rpc/rpc_common.ml]: what is `nb` in `nb_*`?

File: bin/rpc/rpc_common.ml [hunk 16]
```diff
@@ -150,22 +150,49 @@ let fire_notification
...
+            Console.print_user_message main;
+            nb_errors + 1, nb_warnings
+          | Warning ->
+            User_warning.emit_message main;
+            nb_errors, nb_warnings + 1)
     in
-    List.iter errors ~f:(fun { Dune_rpc.Compound_user_error.main; _ } ->
-      Console.print_user_message main);
-    User_error.raise [ error_msg |> Pp.tag User_message.Style.Error ]
+    if counts == (0, 0)
```
Comment (shonfeder) [inline bin/rpc/rpc_common.ml]: Is there a reason to prefer physical equality over the structural


```suggestion
    if counts = (0, 0)
```

(or a `match`?)

File: bin/rpc/rpc_common.ml [hunk 17]
```diff
@@ -150,22 +150,49 @@ let fire_notification
...
+    then
+      Code_error.raise
+        "Build via RPC failed, but the RPC server did not send an error message."
+        [];
+    print_err_warn counts
```
Comment (shonfeder) [inline bin/rpc/rpc_common.ml]: I think this actually just makes the logic easier to follow:

```suggestion
    match counts with
    | (0, 0) -> 
      Code_error.raise
        "Build via RPC failed, but the RPC server did not send an error message."
        []
    | _ -> print_err_warn counts
```

No need to consider the single case if, or the fact that the raise will stop control flow, we just see there are two alternative paths.

File: src/dune_rpc_impl/diagnostics.ml [hunk 18]
```diff
@@ -24,12 +24,13 @@ let diagnostic_of_error : Build_system_error.t -> Dune_rpc_private.Diagnostic.t
...
     absolutize_paths ~dir loc
   in
-  let message, related =
+  let message, related, severity =
     match Build_system_error.description m with
     | `Exn e ->
       (* CR-someday jeremiedimino: Use [Report_error.get_user_message] here. *)
-      User_message.make [ Pp.text (Printexc.to_string e.exn) ], []
-    | `Diagnostic { Compound_user_error.main = message; related } -> message, related
+      User_message.make [ Pp.text (Printexc.to_string e.exn) ], [], Some Diagnostic.Error
```
Comment (shonfeder) [inline src/dune_rpc_impl/diagnostics.ml]: Is that comment still relevant, I wonder?

File: src/dune_rpc_impl/server.ml [hunk 19]
```diff
@@ -369,8 +369,16 @@ let handler (t : _ t Fdecl.t) handle : 'build_arg Dune_rpc_server.Handler.t =
...
+        let missing =
+          Promote.Diff_promotion.promote_files_registered_in_last_run
+            Dune_rpc.Files_to_promote.All
+        in
+        if List.is_non_empty missing
+        then
+          Code_error.raise
+            "promote_files_registered_in_last_run All should always return an empty list"
+            [];
+        ()
```
Comment (shonfeder) [inline src/dune_rpc_impl/server.ml]: you might consider whether a match again makes the logic clearer. E.g.,:

```suggestion
         match 
           Promote.Diff_promotion.promote_files_registered_in_last_run
              Dune_rpc.Files_to_promote.All 
         with
         | [] -> ()
         | _ :: _ -> Code_error.raise
            "promote_files_registered_in_last_run All should always return an empty list" []
```

**Review by shonfeder — APPROVED** [review]
I have some stylistic suggestions, but nothing essential. LGTM.

Given your work on this with @Alizter over such a long stretch, he should probably give the final review tho.

I hope we can land this for you ASAP!

File: bin/rpc/rpc_common.ml (hunk 15 above)
Comment (Alizter) [reply bin/rpc/rpc_common.ml]: Here it stands for `number` I believe.

File: src/dune_rpc_impl/diagnostics.ml (hunk 18 above)
Comment (ElectreAAS) [reply src/dune_rpc_impl/diagnostics.ml]: given that `get_user_message` doesn't exist anymore, I'm going to assume that no.
Some answers might be found in #2349, but it's so old and long that github struggles to display anything in the changes :(

File: bin/rpc/rpc_common.ml (hunk 16 above)
Comment (ElectreAAS) [reply bin/rpc/rpc_common.ml]: the physical equality was a mistake, good eye!
the match makes this indeed cleaner

File: bin/rpc/rpc_common.ml (hunk 15 above)
Comment (shonfeder) [reply bin/rpc/rpc_common.ml]: I'd never guess that. `num_` or `n_` would have been obvious to me tho. Or maybe even just `errors : int, warns : int` .

Comment (ElectreAAS) [reply bin/rpc/rpc_common.ml]: Ah that's gotta be a frenchism then. Changed to `num_*`

File: test/expect-tests/dune_rpc_e2e/dune_rpc_diagnostics.ml [hunk 20]
```diff
@@ -388,12 +388,40 @@ let%expect_test "optional promotion" =
     ] |}]
 ;;
 
-let%expect_test "warning detection" =
+(* Non-fatal warnings aren't transferred to the RPC client. *)
```
Comment (Alizter) [inline test/expect-tests/dune_rpc_e2e/dune_rpc_diagnostics.ml]: "compiler warnings"

File: test/expect-tests/dune_rpc_e2e/dune_rpc_diagnostics.ml [hunk 21]
```diff
@@ -388,12 +388,40 @@ let%expect_test "optional promotion" =
...
     "./foo.exe";
+  [%expect
+    {|  
+    Building ./foo.exe
+    Build ./foo.exe succeeded
+    <no diagnostics> |}]
+;;
+
+(* Alerts aren't transferred to the RPC client. *)
+let%expect_test "alert non-detection" =
```
Comment (Alizter) [inline test/expect-tests/dune_rpc_e2e/dune_rpc_diagnostics.ml:406]: "compiler alerts"

File: src/promote/diff_promotion.ml (hunk 4 above)
Comment (Alizter) [reply src/promote/diff_promotion.ml:180]: Can you add a CR to do this all in a single pass over the files. I don't want to hold up this PR any longer since this isn't code you introduced, but it would be good to get rid of the fragile reversal and needless set conversion at some point.
