### PR TITLE
Fix separate compilation of jsoo

### LINKED ISSUE #3622: Discrepancy between jsoo whole program compilation and separate compilation.
There's a discrepancy between jsoo whole program compilation and separate compilation. You need to add a compile of `std_exit.cmo` at the end of the link phase, see this issue in [`js_of_ocaml`](https://github.com/ocsigen/js_of_ocaml/issues/1033). 

```shell 
> echo 'let () = print_string {|bla|}' > main.ml   
> echo '(executable (name main) (modes js))' > dune
> dune build --profile=release ./main.bc.js        
> node _build/default/main.bc.js 
bla
> dune build --profile=dev ./main.bc.js
> node _build/default/main.bc.js  
>
```
Versions:
```
> js_of_ocaml --version 
3.6.0
> dune --version 
2.5.1
```

### PR DESCRIPTION
**Pull request by rgrinberg**
Compile std_exit to js and link it last

Fix #3622

### CODE REVIEW

File: src/dune/js_of_ocaml_rules.ml [hunk 1]
```diff
@@ -137,27 +146,26 @@ let setup_separate_compilation_rules sctx components =
...
         let archives =
+          let archives = (Lib_info.archives info).byte in
           (* Special case for the stdlib because it is not referenced in the
              META *)
-          match Lib_name.to_string (Lib.name pkg) with
-          | "stdlib" -> Path.relative ctx.stdlib_dir "stdlib.cma" :: archives
+          match lib_name with
+          | "stdlib" ->
+            let archive = Path.relative ctx.stdlib_dir in
+            archive "stdlib.cma" :: archive "std_exit.cmo" :: archives
```
Comment (hhugo) [inline src/dune/js_of_ocaml_rules.ml:157]: I would expect std_exit to go last

Comment (hhugo) [reply src/dune/js_of_ocaml_rules.ml:157]: I misread the diff

**Review by hhugo — APPROVED** [review]
