### PR TITLE
Nested dune call fix (execution environment part)

### LINKED ISSUE #10019: Dune should run itself when a package build command tries to run `dune`
If the dune executable currently running isn't what `dune` resolves to in `PATH`, packages that invoke `dune` in their build command should still start a copy of the current dune rather than the one from `PATH`. This situation arises when running a development version of dune where the exe is named `main.exe`.

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
This is a companion PR to #12902. Where #12902 resolves the `dune` binary to be called to be correct, this PR prepends an extra entry to the `PATH` variable so the environment will point to the right dune instead of whatever was captured in the environment (potentially by accident).

It has a non-essential dependency on #12916 to show that the Dune binary is correctly resolved in all cases.

### CODE REVIEW

File: src/dune_rules/run_with_path.ml [hunk 1]
```diff
@@ -141,11 +141,21 @@ module Spec = struct
           |> String.concat ~sep:"")
       in
       let metadata = Process.create_metadata ~purpose:ectx.metadata.purpose () in
+      let dune_folder =
```
Comment (rgrinberg) [inline src/dune_rules/run_with_path.ml:144]: This is going to be executed once per action. That seems a bit suboptimal. How about just creating this folder somewhere in _build and reusing it everywhere?

Also, when you're executing this dune binary, we should add a dependency on it. So when we're creating this action, we need to add a path dependency (as an external path).

Comment (Leonidas-from-XIV) [reply src/dune_rules/run_with_path.ml:144]: I wanted to avoid creating a random folder in `_build` to avoid managing its state. But I can create an action that creates it, that way it is managed via the build system. Does this sound like a better solution to you?

Comment (rgrinberg) [reply src/dune_rules/run_with_path.ml:144]: Actually, maybe we can save this optimization for later. 

Let's just make sure the dependency is added correctly so that these actions re-run if dune changes.

Comment (Leonidas-from-XIV) [reply src/dune_rules/run_with_path.ml:144]: Is that the right thing to do? I am a bit worried that if I add e.g. an dependency on the path of the dune executable then all packages will be rebuilt when the dune executable changes or it is invoked via a different path.

Comment (rgrinberg) [reply src/dune_rules/run_with_path.ml:144]: That’s what happens with opam when dune changes. It is the right thing to do because a new version of dune might interpret the rules differently so they would need to be re-executed.

if you’re worried about the recompilation being slow, I think it’s just a matter of turning on the shared cache for the sub process dunes that we launch.

Comment (Leonidas-from-XIV) [reply src/dune_rules/run_with_path.ml:144]: I've implemented it (added the path to the Dune executable to the action, thus a change should change the digest and rerun it) and added an `Action_builder.path` dependency.

However, the implementation is not very nice as I am inspecting the input and only guessing whether the expander will expand into a `Run_with_path` action. Is there a good way to determine what action the expander has returned? I could return the fact from the expander but it makes for an ugly API if I could know it from the returned value.

File: src/dune_rules/run_with_path.ml [hunk 2]
```diff
@@ -120,11 +124,11 @@ module Spec = struct
              | String s -> Sexp.Atom s
              | Path p -> path p)))
     in
-    List [ List ([ prog ] @ args); path ocamlfind_destdir ]
+    List [ List ([ prog ] @ args); path ocamlfind_destdir; path dune_exe ]
```
Comment (rgrinberg) [inline src/dune_rules/run_with_path.ml]: The way the path is included in the digest is wrong here. It means that moving dune from one path to another would change this action's digest. I don't think we want that.

File: src/dune_rules/run_with_path.ml (hunk 1 above)
Comment (rgrinberg) [reply src/dune_rules/run_with_path.ml:144]: How about instead of looking at the action you just look at the package dependencies of the package that corresponds to this action. If the package dependencies contain dune, then we should introduce this dependency. This way we don't need look at the action itself at all.

This way, you can also skip doing this setup for packages that do not depend on dune.

File: src/dune_rules/run_with_path.ml (hunk 2 above)
Comment (Leonidas-from-XIV) [reply src/dune_rules/run_with_path.ml]: Then I must've misunderstood you. I thought that's exactly what you wanted: if the dune location changes then the actions digest changes and it would need to be rerun?

Comment (rgrinberg) [reply src/dune_rules/run_with_path.ml]: It is the content of the executable that's important here. Whether it's in /usr/bin or /usr/local/bin (to give an example) should make no difference.

I think you've done the right thing with `Action_builder.path` already though. This is all that is required and the modification to the action's own digest is what gives us this undesired sensitivity to the path.

File: src/dune_rules/run_with_path.ml (hunk 1 above)
Comment (Leonidas-from-XIV) [reply src/dune_rules/run_with_path.ml:144]: That's a good idea, I started implementing it. However I noticed we currently don't record the dune dependency (as it made no sense to do so before, since we don't want to build another dune), should I extend the code to record dune as a dependency in the lock dir?

Comment (rgrinberg) [reply src/dune_rules/run_with_path.ml:144]: Yeah, that seems reasonable. I thought we did record the dune dependency in the lock directory but then just ignored it when parsing. Keeping it in the lock dir seems fine.

Comment (Leonidas-from-XIV) [reply src/dune_rules/run_with_path.ml:144]: Ah, you're right, we do indeed record it, it's just that this test doesn't do it (I'll update it to do so). Will investigate where we drop the dependency to recover that information.

File: test/blackbox-tests/test-cases/pkg/different-dune-in-path.t [hunk 3]
```diff
@@ -2,22 +2,42 @@ Clarify the behavior when the `dune` in PATH is not the one used to start the bu
...
   > EOF
   > cd ..
   > tar cf $1.tar tmp
   > rm -rf tmp
   > }
 
   $ make_test_package foo
+  $ mkpkg foo <<EOF
+  > depends: [ "dune" ]
+  > build: [ "dune" "build" "-p" name "@install" ]
```
Comment (rgrinberg) [inline test/blackbox-tests/test-cases/pkg/different-dune-in-path.t]: Could you please not rely on the solver to test this?

Comment (Leonidas-from-XIV) [reply test/blackbox-tests/test-cases/pkg/different-dune-in-path.t]: Undid the change. Turns out I only needed to add a `(depends dune)` stanza.

File: src/dune_rules/run_with_path.ml (hunk 1 above)
Comment (Leonidas-from-XIV) [reply src/dune_rules/run_with_path.ml:144]: I decided to add an extra field to record whether the package depended on Dune, because the dependency is filtered out fairly early and delaying the filtering broke a lot of assumptions.

**Comment by rgrinberg** [comment]
Thanks!
