### PR TITLE
fix(mdx): record runtime dependency to prelude

### LINKED ISSUE #7077: MDX does not rebuild when the prelude changes
## Expected Behavior

When using `(mdx (preludes prelude.ml) ...)`, changing `prelude.ml` should cause the tests to be run again.

## Actual Behavior

It ignores this and you have to do `dune clean` first.

## Reproduction

```
$ ls
dune  dune-project  prelude.ml  README.md

$ cat dune
(mdx
  (preludes prelude.ml)
  (files README.md))

$ cat dune-project 
(lang dune 3.6)
(using mdx 0.3)

$ cat prelude.ml 
let foo () = 1

$ cat README.md 
```ocaml
# foo();;
- : int = 1

$ dune runtest

$ echo 'let foo () = 2' > prelude.ml
$ dune runtest

$ dune clean; dune runtest
File "README.md", line 1, characters 0-0:
...
```

## Specifications

- Version of `dune` (output of `dune --version`): 3.6.2
- Version of `ocaml` (output of `ocamlc --version`): 5.0.0
- Operating system (distribution and version): Debian 11

### PR DESCRIPTION
**Pull request by emillon**
When mdx is used in program-generation mode (version >= 0.2), the paths used as preludes are recorded in the executable, but the contents of files are only read when the program is executed. This adds the missing dependencies.

Fixes #7077

### CODE REVIEW

File: src/dune_rules/mdx.ml [hunk 1]
```diff
@@ -145,13 +145,20 @@ module Prelude = struct
     in
     enter decode_env <|> decode_default
 
+  let bpath ~dir p = Path.build (Path.Build.append_local dir p)
```
Comment (rgrinberg) [inline src/dune_rules/mdx.ml:148]: Let's inline this function. It doesn't have a good name nor any logic but it exists in a much larger scope.

**Review by rgrinberg — APPROVED** [review]
Needs a Change list entry.
