### PR TITLE
fix(trace): use microseconds for chrome trace timestamps

### LINKED ISSUE #13906: `dune trace cat --chrome-trace` has wrong timing units
In c01c7d19748 the timing units were changed but this does not convert `--chrome-trace` output correctly.

### PR DESCRIPTION
**Pull request by Alizter**
Chrome Trace Event Format requires timestamps in microseconds, but `json_of_event` was emitting seconds. We therefore now convert for both the `ts` and `dur` fields in chrome trace mode.

- Fixes #13906

### CODE REVIEW

File: bin/trace.ml [hunk 1]
```diff
@@ -183,26 +183,38 @@ let json_of_event ~chrome (sexp : Sexp.t) =
...
+    let base =
+      [ "cat", Json.string cat
+      ; "name", Json.string name
+      ; "ts", Json.float (Time.to_secs ts)
+      ; "args", Json.assoc rest
+      ]
+      @
+      match dur with
+      | None -> []
+      | Some k -> [ "dur", Json.float (Time.Span.to_secs k) ]
```
Comment (rgrinberg) [inline bin/trace.ml]: Can we do this without essentially replicating this block? We could insert the chrome_trace check where we're producing `ts` and `dur`?

Comment (Alizter) [reply bin/trace.ml]: Sure

**Review by rgrinberg — APPROVED** [review]
Thanks. A CHANGES entry would be appropriate as well.
