### PR TITLE
Fix #1729

### LINKED ISSUE #1729: assertion failed in Dyn module arg parsing
Looks like a regression from #1719 possibly:

```
File "tests/test-constants/dune", line 4, characters 25-49:
4 |    test_constantss_stubs test_constantss_bindings tests_common))
                             ^^^^^^^^^^^^^^^^^^^^^^^^
Error: Library "test_constantss_bindings" not found.
Hint: try: dune external-lib-deps --missing @all
File "src/arg_spec.ml", line 56, characters 15-21: Assertion failed
Backtrace:
Raised at file "src/build_system.ml", line 1361, characters 9-14
Called from file "src/fiber/fiber.ml", line 91, characters 8-15
```

the line in arg_spec.ml is the assert false in:

```
let expand ~dir ts x =
  let dyn_deps = ref Path.Set.empty in
  let add_dep path = dyn_deps := Path.Set.add !dyn_deps path in
  let rec loop_dyn : Nothing.t t -> string list = function
    | A s  -> [s]
    | As l -> l
    | Dep fn ->
      add_dep fn;
      [Path.reach fn ~from:dir]
    | Path fn -> [Path.reach fn ~from:dir]
    | Deps fns ->
      List.map fns ~f:(fun fn ->
        add_dep fn;
        Path.reach ~from:dir fn)
    | Paths fns ->
      List.map fns ~f:(Path.reach ~from:dir)
    | S ts -> List.concat_map ts ~f:loop_dyn
    | Concat (sep, ts) -> [String.concat ~sep (loop_dyn (S ts))]
    | Target _ | Hidden_targets _ -> die "Target not allowed under Dyn"
    | Dyn _ -> assert false
    | Hidden_deps l ->
      dyn_deps := Path.Set.union !dyn_deps (Path.Set.of_list l);
      []
  in
```

I have the development tree that causes this saved if needed; there were several typos in dune files as it was a wip.

### PR DESCRIPTION
**Pull request by rgrinberg**
We are likely doing `Dyn (fun _ -> Dyn ...)` via one of the `Arg_spec.of_result` calls. This PR cleans things up by:

* Allowing to error out inside of Dyn using an explicit constructor. Actually, things were like this before, but @diml for some reason got rid of this constructor. I can't recall what the reasoning was.

* Add a phantom parameter so that we don't mix constructors incorrectly. It's not possible to nest Dyn, and it's not possible to add targets via Dyn. We can enforce that statically. This can feel a bit heavy weight, so I can remove this if there's too much objection.

Note: It's very likely that this error is present in 1.6, but it's not so easy to reproduce. I'm thinking we should just add it to the CHANGELOG regardless.

### CODE REVIEW

File: src/arg_spec.ml [hunk 1]
```diff
@@ -1,19 +1,23 @@
...
-  | Concat   of string * 'a t list
-  | Dep      of Path.t
-  | Deps     of Path.t list
-  | Target   of Path.t
-  | Path     of Path.t
-  | Paths    of Path.t list
-  | Hidden_deps    of Path.t list
-  | Hidden_targets of Path.t list
-  | Dyn      of ('a -> Nothing.t t)
+type static = Static
```
Comment (emillon) [inline src/arg_spec.ml]: are the constructors necessary here?

**Comment by emillon** [comment]
Does this fix the issue on your tree @avsm ?

File: src/arg_spec.ml (hunk 1 above)
Comment (rgrinberg) [reply src/arg_spec.ml]: Probably not, but it's in line with how we do things elsewhere (see OSL for example). AFAIK this is done to make sure that the type checker can prove the two phantom types are unequal.

Comment (emillon) [reply src/arg_spec.ml]: Oh, I see. Neat!

**Comment by avsm** [comment]
Yes confirmed this fixes #1729's failing case for me. I tagged that issue with the working tree that exhibited the issue

**Comment by rgrinberg** [comment]
@diml ping on this one. We already have a review, but since I'm undoing a change that you've done before, I'd like to make sure you're aware.

**Comment by diml** [comment]
Ok, I'm having a look

**Comment by diml** [comment]
LGTM
