### PR TITLE
fix: Correctly set os-distribution on Windows

### LINKED ISSUE #13310: Improve os_distribution detection in dune pkg on Windows
Currently, the implementation has [stub code](https://github.com/ocaml/dune/blob/f3844fb5fda0febdee49394a7fd0f44402cb6dc9/src/dune_pkg/sys_poll.ml#L197) where it simply returns the value for os as the os-distribution. This breaks the dependencies computed by the solver and prevents the compiler from getting correctly compiled on Windows.  To observe this issue, you'd need to try to build a repository using `dune pkg` on top of #13293 .

### PR DESCRIPTION
**Pull request by punchagan**
Currently, we return a stub value that matches the OS name on Windows. But, the `os-distribution` needs to be `cygwin` or `msys2` when building in Cygwin or MSYS2, respectively, to detect dependencies correctly for various packages.

We assume that the `uname` executable is on `PATH` when running under Cygwin or MSYS2, and use that to correctly detect the `os-distribution`.

Closes #13310

### CODE REVIEW

**Comment by punchagan** [comment]
`opam` [uses](https://github.com/ocaml/opam/blob/40d198913c9daffd882be12d058ccb25aa4bfbae/src/state/opamSysPoll.ml#L110-L143) a utility function [`get_windows_executable_variant`](https://github.com/ocaml/opam/blob/40d198913c9daffd882be12d058ccb25aa4bfbae/src/core/opamStd.ml#L1193-L1261) to detect if the `cygpath.exe` binary is Native, Cygwin or MSYS2 binary, based on whether it links to the  the `cygwin1.dll` or the `msys-2.0.dll` or depends on a library that links to one of them. The utility function seems to have been [originally written](https://github.com/ocaml/opam/commit/c22ca23b4cfe7d1a03ac4c80ebf3d661618090d5) to detect if exectuables like `tar` or `rsync` being used by `opam` were Cygwin tools since they don't accept Windows like paths.  

I'm not sure we need to use the same method. I think it's just assuming `uname` would be on `PATH` when building under Cygwin or MSYS2, and using that to determine the `os-distribution` seems reasonable to me.

File: src/dune_pkg/sys_poll.ml [hunk 1]
```diff
@@ -192,6 +192,14 @@ let os_distribution ~os ~android_release ~os_release_fields ~path =
                    (match Scanf.sscanf s " %s " Fun.id with
                     | Error _ -> linux
                     | Ok s -> norm s)))))
+     | Some "win32" as os ->
+       uname ~path [ "-s" ]
+       >>| (function
+        | Some s when String.starts_with s ~prefix:"cygwin" -> Some "cygwin"
```
Comment (Leonidas-from-XIV) [inline src/dune_pkg/sys_poll.ml:202]: Could you add a comment documenting what what kind of outputs are usually returned in these cases?

**Review by Leonidas-from-XIV — APPROVED** [review]
I don't have `cygwin` nor `msys` at hand, but it seems ok to call `uname` instead of inspecting a binary.

File: src/dune_pkg/sys_poll.ml (hunk 1 above)
Comment (punchagan) [reply src/dune_pkg/sys_poll.ml:202]: Make sense, thanks!

**Review by Alizter — APPROVED** [review]
I've checked on Windows and it is doing the right thing.
