### PR TITLE
Better name detection

### LINKED ISSUE #1360: `jbuilder subst -p name` leads to an error
when I execute the following command: `opam pin add charrua-core --dev` (using opam2, jbuilder.transition, dune.1.3.0 here), I get the following error:

```
#=== ERROR while compiling charrua-core.0.10 ==================================#
# context     2.0.0 | freebsd/x86_64 | ocaml-base-compiler.4.06.1 | pinned(git+file:///usr/home/hannes/devel/mirage/charrua-core#HEAD#83d7c15c)
# path        /usr/home/hannes/.opam/4.06.1/.opam-switch/build/charrua-core.0.10
# command     /usr/home/hannes/.opam/4.06.1/bin/jbuilder subst -p charrua-core
# exit-code   1
# env-file    /usr/home/hannes/.opam/log/charrua-core-88899-60459a.env
# output-file /usr/home/hannes/.opam/log/charrua-core-88899-60459a.out
### output ###
# Error: cannot determine name automatically.
# You must pass a [--name] command line argument.
```

from the opam file in question:
```
build: [
  ["jbuilder" "subst" "-p" name] {pinned}
  ["jbuilder" "build" "-p" name "-j" jobs]
  ["jbuilder" "runtest" "-p" name "-j" jobs] {with-test}
]
```

IIRC #954 was the reason to add `"-p" name` to a wide range of opam packages, and #960 adjusted `subst` behaviour. from what I can tell, one solution is to move the package to dune (but that won't fix the opam files in opam-repository).

### PR DESCRIPTION
**Pull request by rgrinberg**
The old name detection is confusing and also incorrectly detects situations where the prefix is unintended. This new scheme is more resilient and understands that many packages have a `-` as a separator.

Fix #1360

### CODE REVIEW

**Comment by diml** [comment]
Note that this heuristic doesn't work for `xenstore_transport`, since it defines two packages `xenstore-tool` and `xenstore_transport`.

**Comment by emillon** [comment]
If that's the only package in the list for which that heuristic doesn't work, it seems acceptable to just fix that one by hand.

**Comment by diml** [comment]
I guess. TBH I'm a bit wary about such automatic name detection altogether and I think it's better if the user explicitly specifies a project name in the `dune-project` file. That said, this is only when using the `jbuilder` binary which is now deprecated, so it seems fine if it helps minimizing the churn for already released packages.

File: src/stdune/string.ml [hunk 1]
```diff
@@ -185,6 +185,19 @@ let longest_map l ~f =
 
 let longest l = longest_map l ~f:(fun x -> x)
 
+let longest_prefix = function
```
Comment (diml) [inline src/stdune/string.ml]: This function is quadratic, it should be linear. I suggest to add a function that returns the longest prefix of two strings and fold it through the list.

**Review by ghost — CHANGES_REQUESTED** [review]

File: src/stdune/string.ml (hunk 1 above)
Comment (rgrinberg) [reply src/stdune/string.ml]: On the other hand, my implementation does not allocate intermediate strings. Anyways, this is not a critical path so I can change it as you said.

Comment (diml) [reply src/stdune/string.ml]: What about a function that returns the length of the longest prefix of two strings?

**Comment by rgrinberg** [comment]
I can improve it for xenstore as well. `-` are more common, but `_` should be supported as well.

File: src/stdune/string.ml (hunk 1 above)
Comment (rgrinberg) [reply src/stdune/string.ml]: It's possible but it will be harder to fold it. What would you expect our folding function to be? I think that we'd have to get current longest prefix as a string to use it with:

```
val longest_prefix : string -> string -> int
```

Which would defeat avoiding the intermediate allocation.

Comment (emillon) [reply src/stdune/string.ml]: If this function is called once only in `dune subst` for jbuilder projects, I don't think that this is worth optimizing it. Just a note about complexity in the `.mli` should be enough.

Comment (rgrinberg) [reply src/stdune/string.ml]: Also, I'm not really sure that the complexity of the current function is strictly worse. For example, it should be preform quite a bit better on lists of strings like:

```
let x = "long string here"
[ x; x; x; ...; "f"]
```

Comment (diml) [reply src/stdune/string.ml]: My bad, I read too fast and thought `loop` was called inside the `fold_left`

**Review by ghost — APPROVED** [review]
