### PR TITLE
fix(pkg): pass explicit -z/-j flags for non-auto-detecting tar

### LINKED ISSUE #10123: `tar` on OpenBSD
On OpenBSD, opam uses `gtar` rather than `tar`. We should do the same, or figure out how to use `tar` from OpenBSD.

### PR DESCRIPTION
**Pull request by Alizter**
OpenBSD tar doesn't auto-detect compression format and requires explicit -z (gzip) or -j (bzip2) flags.

This adds tar implementation detection via --version output:
- 'bsdtar' or 'libarchive' -> BSD tar (auto-detects compression)
- 'GNU tar' -> GNU tar (auto-detects compression)
- Otherwise -> Other (needs explicit flags)

Fixes #10123

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
What about archives that are compressed with `xz`? opam-repository has a few of those. Also, [opam supports](https://github.com/ocaml/opam/blob/6770101f1d77731f5c371e0fd94a23693d2756f4/src/core/opamSystem.ml#L877) `xz` as well as `lzma`.

**Comment by Alizter** [comment]
I think supporting these compression formats explicitly should be a separate issue. Can you open an issue (for each)?

**Comment by Leonidas-from-XIV** [comment]
#13715 and #13716

File: src/dune_pkg/archive_driver.ml [hunk 1]
```diff
@@ -2,6 +2,12 @@ open Stdune
 module Process = Dune_engine.Process
 open Fiber.O
 
+(** Tar implementation type, detected via --version output *)
+type tar_impl =
+  | Bsd (** BSD tar / libarchive - auto-detects compression, can extract zip *)
```
Comment (Leonidas-from-XIV) [inline src/dune_pkg/archive_driver.ml]: I would suggest to call it `Libarchive` as it is a very specific one, that's only used on FreeBSD and as far as I know doesn't historically share ties with BSD tar that the one that OpenBSD ships evolved from.

File: src/dune_pkg/archive_driver.ml [hunk 2]
```diff
@@ -16,8 +22,38 @@ type t =
 
 let which bin_name = Bin.which ~path:(Env_path.path Env.initial) bin_name
 
-let make_tar_args ~archive ~target_in_temp =
-  [ "xf"; Path.to_string archive; "-C"; Path.to_string target_in_temp ]
+(** Detect tar implementation by running --version *)
+let detect_tar_impl bin =
+  let+ output, _ = Process.run_capture ~display:Quiet Return bin [ "--version" ] in
+  let matches s = Re.execp (Re.compile (Re.str s)) output in
```
Comment (Leonidas-from-XIV) [inline src/dune_pkg/archive_driver.ml]: Maybe pull out the `matches` into the definition of the function like

```ocaml
let detect_tar_impl =
  let matches_bsdtar = .. in
  fun bin ->
    ..
```

That way the `Re.compile` only happens once.

File: src/dune_pkg/archive_driver.ml [hunk 3]
```diff
@@ -16,8 +22,38 @@ type t =
...
+      let archive_str = Path.to_string archive in
+      if
+        Filename.check_suffix archive_str ".tar.gz"
+        || Filename.check_suffix archive_str ".tgz"
+      then [ "-z" ]
+      else if
+        Filename.check_suffix archive_str ".tar.bz2"
+        || Filename.check_suffix archive_str ".tbz"
+      then [ "-j" ]
+      else []
```
Comment (Leonidas-from-XIV) [inline src/dune_pkg/archive_driver.ml:72]: I would suggest adding the other two OPAM-supported formats (LZMA and XZ) and exiting with an error message here. That way we can tell the user to e.g. install `bsdtar` or so.

File: test/blackbox-tests/test-cases/pkg/openbsd-tar.t [hunk 4]
```diff
@@ -59,13 +59,15 @@ Test with a .tar.gz file - fails because dune doesn't pass -z flag:
...
-  Error: failed to extract 'test.tar.gz'
-  Reason: 'tar' failed with non-zero exit code '1' and output:
-  - tar: Cannot open: compressed archive requires -z flag
-  [1]
+  $ PATH=.fakebin build_pkg foo
 
-Test with a .tbz file - fails because dune doesn't pass -j flag:
+Verify that -z flag was passed:
+
+  $ dune trace cat | jq -c 'include "dune"; processes | select(.args.prog | contains("tar")) | .args.process_args | map(if (startswith("/") or startswith("_build")) then "PATH" else . end)'
```
Comment (Leonidas-from-XIV) [inline test/blackbox-tests/test-cases/pkg/openbsd-tar.t]: Very cool trick. I would suggest also matching on `-x` because we only really care about `extract` and having all `tar` calls makes the test more fragile as in the future we might do different detection of `tar` capabilities.

File: test/blackbox-tests/test-cases/pkg/openbsd-tar.t [hunk 5]
```diff
@@ -76,8 +78,10 @@ Test with a .tbz file - fails because dune doesn't pass -j flag:
...
-  $ PATH=.fakebin build_pkg bar 2>&1 | grep -A2 '^Error'
-  Error: failed to extract 'test.tbz'
-  Reason: 'tar' failed with non-zero exit code '1' and output:
-  - tar: Cannot open: compressed archive requires -j flag
-  [1]
+  $ PATH=.fakebin build_pkg bar
+
+Verify that -j flag was passed:
+
+  $ dune trace cat | jq -c 'include "dune"; processes | select(.args.prog | contains("tar")) | .args.process_args | map(if (startswith("/") or startswith("_build")) then "PATH" else . end)'
```
Comment (Leonidas-from-XIV) [inline test/blackbox-tests/test-cases/pkg/openbsd-tar.t]: As above. Maybe the query can be shared?

**Review by Leonidas-from-XIV — CHANGES_REQUESTED** [review]

File: src/dune_pkg/archive_driver.ml (hunk 3 above)
Comment (Alizter) [reply src/dune_pkg/archive_driver.ml:72]: Added a CR for when we tackle those formats

File: test/blackbox-tests/test-cases/pkg/openbsd-tar.t (hunk 5 above)
Comment (Alizter) [reply test/blackbox-tests/test-cases/pkg/openbsd-tar.t]: Done.

File: src/dune_pkg/archive_driver.ml (hunk 2 above)
Comment (Alizter) [reply src/dune_pkg/archive_driver.ml]: Done.

File: src/dune_pkg/archive_driver.ml [hunk 6]
```diff
@@ -16,8 +25,45 @@ type t =
...
+      then [ "-z" ]
+      else if
+        Filename.check_suffix archive_str ".tar.bz2"
+        || Filename.check_suffix archive_str ".tbz"
+      then [ "-j" ]
+      else
+        (* CR-soon alizter: handle .tar.xz (-J) and .tar.lzma (--lzma) which
+           OPAM also supports. Should error with a clear message if the tar
+           implementation doesn't support auto-detection for these formats. *)
+        []
```
Comment (Leonidas-from-XIV) [inline src/dune_pkg/archive_driver.ml]: I still think that throwing an `User_error` here is better since in this code branch we're dealing with e.g. OpenBSD `tar` which just doesn't support `-J` or `--lzma`. Thus returning `[]` will just make it fail later on, when `tar xf archive.tar.xz` happens. Here we can at least error out with a better error message ("Your `tar` does not support XZ decompression" "Hint: Install libarchive bsdtar maybe").

**Review by Leonidas-from-XIV — CHANGES_REQUESTED** [review]

File: src/dune_pkg/archive_driver.ml (hunk 6 above)
Comment (Alizter) [reply src/dune_pkg/archive_driver.ml]: I've added explicit errors here.

**Review by Leonidas-from-XIV — APPROVED** [review]
Maybe worth adding a changelog entry that this was fixed but the code looks good and the tests are very nice.

**Comment by shonfeder** [comment]
Looks like this is fully reviewed and ready to go. Can we merge here?
