### PR TITLE
Resolve symlinks before running git diff

### LINKED ISSUE #3740: Comparison with expected tests using `Git diff` is broken
## Expected Behavior

Diffing expected tests when patdiff is not installed (`git diff` is used) works

## Actual Behavior

Diffing with `git diff` doesn't work because the sandboxing create a symlink and `git diff` is configured to not follow symlink

## Reproduction

1. check that patdiff is not installed
1. make a modification in a test of dune
1. run `make test`

## Specifications

- Version of `dune` (output of `dune --version`): master a6fa0672c96877ddd333185d6d8e0a49c2b92797
- Version of `ocaml` (output of `ocamlc --version`): 4.09
- Operating system (distribution and version): ubuntu 20.03

### PR DESCRIPTION
**Pull request by rgrinberg**
git diff does not like symlink arguments.

Fixes #3740

### CODE REVIEW

File: src/dune_engine/print_diff.ml [hunk 1]
```diff
@@ -22,16 +22,17 @@ let print ?(skip_trailing_cr = Sys.win32) path1 path2 =
...
-    let path, args, skip_trailing_cr_arg =
+    let path, args, skip_trailing_cr_arg, file_arg =
       let which prog = Bin.which ~path:(Env.path Env.initial) prog in
       match which "git" with
       | Some path ->
         ( path
         , [ "diff"; "--no-index"; "--color=always"; "-u" ]
-        , "--ignore-cr-at-eol" )
+        , "--ignore-cr-at-eol"
+        , Unix.readlink )
```
Comment (aalekseyev) [inline src/dune_engine/print_diff.ml:32]: I'm surprised if this works. `readlink` just returns a path stored in the symlink, without combining it with anything if it's relative.
I think the correct way to do it is something like `(fun f -> let l = Unix.readlink f in if Filename.is_relative l then Filename.dirname f ^/ l else l)`, but it needs testing.

Comment (rgrinberg) [reply src/dune_engine/print_diff.ml]: Good catch. I think I was looking for `realpath`. Strangely enough, it doesn't seem to exist in the stdlib and I had to implement something like it.

Comment (aalekseyev) [reply src/dune_engine/print_diff.ml]: Any reason you're converting the paths to absolute?
Don't we prefer relative paths where possible? And here it's clearly possible.

Comment (aalekseyev) [reply src/dune_engine/print_diff.ml]: Sorry, I didn't read the implementation of the function, just the name. I think the name should be changed because it doesn't do what `realpath` command or C function do.

File: src/stdune/path.ml [hunk 2]
```diff
@@ -1335,3 +1335,16 @@ let chmod ~mode ?(stats = None) ?(op = `Set) path =
         stats.st_perm land lnot mode
   in
   Unix.chmod (to_string path) mode
+
+let realpath t =
+  let path_s = to_absolute_filename t in
+  let stat = Unix.lstat path_s in
```
Comment (aalekseyev) [inline src/stdune/path.ml:1341]: Instead of checking the kind, we could catch Unix_error (EINVAL, _, _) and thus eliminate the unnecessary race condition.

Speaking of which, we should handle the other errors too (file or directory not existing etc.).

File: src/stdune/path.ml [hunk 3]
```diff
@@ -1335,3 +1335,16 @@ let chmod ~mode ?(stats = None) ?(op = `Set) path =
...
+  match stat.st_kind with
+  | S_LNK ->
+    Some
+      (let link = Unix.readlink path_s in
+       if Filename.is_relative link then
+         relative (parent_exn t) link
```
Comment (aalekseyev) [inline src/stdune/path.ml:1347]: If symlink points outside of the build directory, then we crash here, which seems undesirable. Maybe the whole function should work with simple unix paths instead of with `Path.t`?

File: src/stdune/path.ml [hunk 4]
```diff
@@ -1335,3 +1335,16 @@ let chmod ~mode ?(stats = None) ?(op = `Set) path =
         stats.st_perm land lnot mode
   in
   Unix.chmod (to_string path) mode
+
+let realpath t =
```
Comment (aalekseyev) [inline src/stdune/path.ml:1339]: Should we call this function `follow_symlink`, to remove the confusion with the real `realpath`?

Comment (aalekseyev) [reply src/stdune/path.ml:1339]: By the way, what should we do with the symlink chains? Should it be the responsibility of the caller to care about those and possibly iterate?

**Review by aalekseyev — CHANGES_REQUESTED** [review]

File: src/stdune/path.ml (hunk 2 above)
Comment (rgrinberg) [reply src/stdune/path.ml:1341]: > Instead of checking the kind, we could catch Unix_error (EINVAL, _, _) and thus eliminate the unnecessary race condition.

Good idea.

> Speaking of which, we should handle the other errors too (file or directory not existing etc.).

How should we handle them?

File: src/stdune/path.ml (hunk 3 above)
Comment (rgrinberg) [reply src/stdune/path.ml:1347]: Good idea. Moved it to Fpath.

File: src/stdune/path.ml (hunk 4 above)
Comment (rgrinberg) [reply src/stdune/path.ml:1339]: Hmm, I guess we should follow the chains ourselves. This function is added to fix a single use case, so we might as well tailor it to this use case.

**Comment by rgrinberg** [comment]
> Any reason you're converting the paths to absolute?
> Don't we prefer relative paths where possible? And here it's clearly possible.

The relative paths were quite ugly when displayed by git’s diff as they’re relative to the sandbox dir. I suppose we should just stay consistent, so I switched back to relative paths.

File: src/stdune/fpath.mli [hunk 5]
```diff
@@ -6,3 +6,10 @@ type mkdir_p =
   | Created  (** The directory was created. *)
 
 val mkdir_p : ?perms:int -> string -> mkdir_p
+
+type follow_symlink_error =
+  | Not_a_symlink
+  | Max_depth_exceeded
+  | Unix_error of exn
```
Comment (aalekseyev) [inline src/stdune/fpath.mli:13]: In other places we use `Unix.error` instead of `exn`, which makes matching on it safer. Should we do the same here?
(I know the exception has a bit extra info, so not sure if you did this deliberately)

File: src/stdune/path.ml [hunk 6]
```diff
@@ -1335,3 +1335,6 @@ let chmod ~mode ?(stats = None) ?(op = `Set) path =
         stats.st_perm land lnot mode
   in
   Unix.chmod (to_string path) mode
+
+let follow_symlink path =
+  Fpath.follow_symlink (to_string path) |> Result.map ~f:of_string
```
Comment (aalekseyev) [inline src/stdune/path.ml:1340]: I guess `of_string` can still raise, so not a fan of `Path.follow_symlink`. I guess this won't be a problem for the diffing though.

**Review by aalekseyev — APPROVED** [review]

File: src/stdune/fpath.mli (hunk 5 above)
Comment (rgrinberg) [reply src/stdune/fpath.mli:13]: Changed it to `Unix.error`. I forgot we used this elsewhere.
