### PR TITLE
pkg: Show git error output when Rev_store's fetch fails

### LINKED ISSUE #12610: dune pkg lock error message not verbose enough to debug issue
On dune 3.20.2, I tried to `dune pkg lock` a fresh eio checkout.

```
# dune pkg lock
Error: unable to fetch "02037130881a6b5f31cd6c68a8081b4c42b023ee" from
"https://github.com/ocaml/opam-repository.git"
```

Retrying this worked:
```
# dune pkg lock --verbose
Shared cache: enabled-except-user-rules
Shared cache location: /root/.cache/dune/db
Workspace root: /root/eio
Auto-detected concurrency: 4
Running[3]: (cd /root/.cache/dune/git-repo && /usr/bin/git ls-remote https://github.com/ocaml-dune/opam-overlays.git) > /tmp/dune_87af00_output
Running[4]: (cd /root/.cache/dune/git-repo && /usr/bin/git ls-remote https://github.com/ocaml/opam-repository.git) > /tmp/dune_ca41d4_output
Running[9]: (cd /root/.cache/dune/git-repo && /usr/bin/git fetch --no-write-fetch-head https://github.com/ocaml/opam-repository.git 02037130881a6b5f31cd6c68a8081b4c42b023ee) 2> /tmp/dune_a24205_run_with_exit_code
Locking dune.lock: Updating package repos "overlay" and "upstream"
```

However, it would be nice to have the process error message from the git propagated in the error that dune displays, or its not possible to figure out why that git fetch failed (was it a transient network error, or something else?)

### PR DESCRIPTION
**Pull request by punchagan**
Closes #12610

### CODE REVIEW

**Review by shonfeder — APPROVED** [review]

File: src/dune_pkg/rev_store.ml [hunk 1]
```diff
@@ -1156,7 +1163,7 @@ let resolve_revision t (remote : Remote.t) ~revision =
 let fetch_object t (remote : Remote.t) revision =
   fetch_allow_failure t ~url:remote.url revision
   >>= function
-  | `Not_found -> Fiber.return None
+  | `Not_found _ -> Fiber.return None
```
Comment (rgrinberg) [inline src/dune_pkg/rev_store.ml]: I don't think you want to throw away the error here.

Comment (punchagan) [reply src/dune_pkg/rev_store.ml]: Yes, makes sense. I pushed a commit to handle the error in fetch_object too. Thanks!

File: src/dune_pkg/rev_store.mli [hunk 2]
```diff
@@ -107,7 +107,7 @@ val resolve_revision : t -> Remote.t -> revision:string -> Object.resolved optio
     is present in the revision store [t]. If the reviison is already present,
     no network I/O is performed. Returns [None] if the remote reports "not
     found". *)
-val fetch_object : t -> Remote.t -> Object.t -> At_rev.t option Fiber.t
+val fetch_object : t -> Remote.t -> Object.t -> (At_rev.t, string list) result Fiber.t
```
Comment (Alizter) [inline src/dune_pkg/rev_store.mli:110]: Comment needs to be updated.

File: src/dune_pkg/opamUrl0.ml [hunk 3]
```diff
@@ -52,12 +52,14 @@ type resolve =
   | Resolved of Rev_store.Object.resolved
   | Unresolved of Rev_store.Object.t
 
-let not_found t =
+let not_found ?(git_output = []) t =
```
Comment (rgrinberg) [inline src/dune_pkg/opamUrl0.ml]: You can just always pass this argument

**Review by rgrinberg — CHANGES_REQUESTED** [review]

**Comment by punchagan** [comment]
Using the following `dune-workspace` file, 

```
(repository
 (name pinned)
 (url
  git+https://github.com/ocaml/opam-repository.git#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa))

(lock_dir
 (repositories pinned overlay))
```

`dune pkg lock` generates the error shown below:

```
fatal: remote error: upload-pack: not our ref aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

revision "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" not found in               
https://github.com/ocaml/opam-repository.git
```

----

I'm not sure how to trigger the other fetch repo error. There are other errors triggered with my internet turned off.

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
@rgrinberg ping

File: src/dune_pkg/opamUrl0.ml [hunk 4]
```diff
@@ -101,8 +103,8 @@ let fetch_revision t ~loc resolve rev_store =
   | Unresolved o ->
     Rev_store.fetch_object rev_store remote o
     >>| (function
-     | None -> not_found t
-     | Some rev -> Ok rev)
+     | Error git_output -> not_found ~git_output t
```
Comment (rgrinberg) [inline src/dune_pkg/opamUrl0.ml]: Maybe you can also pass this `loc` to `not_found` and then we'll have a decent location in the error as well?

**Review by rgrinberg — APPROVED** [review]

File: src/dune_pkg/opamUrl0.ml (hunk 4 above)
Comment (Alizter) [reply src/dune_pkg/opamUrl0.ml]: I'll do it in a follow up.

**Comment by Alizter** [comment]
Error message from above now looks like:
```
  $ dune pkg lock
  fatal: remote error: upload-pack: not our ref aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  
  File "dune-workspace", line 6, characters 2-91:
  6 |   git+https://github.com/ocaml/opam-repository.git#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  revision "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" not found in
  https://github.com/ocaml/opam-repository.git
  [1]
```

**Comment by Alizter** [comment]
The error above is not great because we are dumping the stderr output from git *before* we are reporting the error. This is because rev_store is printing it directly. I've removed that nonsense and now the error looks like:
```
  File "dune-workspace", line 6, characters 2-91:
  6 |   git+https://github.com/ocaml/opam-repository.git#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  fatal: remote error: upload-pack: not our ref aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  
  revision "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" not found in
  https://github.com/ocaml/opam-repository.git
  [1]
```

**Comment by Alizter** [comment]
(Rudi ok'd async)
