### PR TITLE
Never raise when printing errors

### LINKED ISSUE #1736: ocaml 4.02.3: internal error raised from Exn.Code_error
In the ctypes build of the dune port, 4.02.3 is specifically raising some internal errors in dune that aren't happening on later versions of the compiler. Sadly, 4.02.3 is still one of the support compiler versions so we need to worry about it :-)

See https://travis-ci.com/avsm/ocaml-ctypes/jobs/168302505 for a full run.  The tree that is exhibiting the problem is in https://github.com/avsm/ocaml-ctypes/tree/dune-port and tracked as a PR in ocamllabs/ocaml-ctypes#588

```
- /-----------------------------------------------------------------------
- | Internal error: Fiber.Execution_context.forward_error: error handler raised.
- | Stdune__Exn.Code_error(_)
- | Called from file "camlinternalLazy.ml", line 25, characters 17-27
- | Re-raised at file "camlinternalLazy.ml", line 32, characters 10-11
- | Called from file "src/errors.ml", line 77, characters 17-47
- | Called from file "format.ml", line 1175, characters 28-44
- | Called from file "src/stdune/option.ml", line 23, characters 14-17
- | Called from file "src/fiber/fiber.ml", line 243, characters 6-18
- | Called from file "src/fiber/fiber.ml", line 56, characters 6-20
- | 
- | Original exception was: Stdune__Exn.Code_error(_)
- | Called from file "camlinternalLazy.ml", line 25, characters 17-27
- | Re-raised at file "camlinternalLazy.ml", line 32, characters 10-11
- | Called from file "src/errors.ml", line 77, characters 17-47
- | Called from file "format.ml", line 1175, characters 28-44
- | Called from file "src/stdune/option.ml", line 23, characters 14-17
- | Called from file "src/fiber/fiber.ml", line 243, characters 6-18
- \-----------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by rgrinberg**
We shouldn't raise in exception handling code. We avoid raising exceptions
by wrapping calls with Result.try_with and avoiding the Path module.

Apologies for the annoying contortions required to factor out the uncaught exception printing code.

Fix #1736 (@avsm could you give this one a test run?)

### CODE REVIEW

File: src/stdune/loc.ml [hunk 1]
```diff
@@ -94,48 +94,65 @@ let pp_file_excerpt ~context_lines ~max_lines_to_print_in_full
...
-          (stop_c + padding_width + 3)
-          (String.make len '^')
+    let file = start.pos_fname in
+    let res =
+      let open Result.O in
+      Result.try_with (fun () -> Sys.file_exists start.pos_fname)
+      >>= fun exists ->
+      if not exists then
+        Result.Ok ()
       else
```
Comment (avsm) [inline src/stdune/loc.ml]: such a huge unguarded `else` makes me nervous :-) Would it be safer to wrap this clause in a `begin/end`?

Comment (rgrinberg) [reply src/stdune/loc.ml]: I'm actually of a fan of never allowing the ungarded if's (always using parens or begin/end) but I know some of the other maintainers aren't so keen on this style as they keep removing my parens.

In any case, there's actually a couple of these dangling elses. I added begin/end to both of them.

Comment (emillon) [reply src/stdune/loc.ml]: I agree with avoiding unguarded ifs. Or better yet you can try to extract a local function for the `else` part, sometimes that works well. As an extra benefit that's an opportunity to invert the conditional :)

Comment (rgrinberg) [reply src/stdune/loc.ml]: Okay, done. I created a helper function (that's still inside the main function)

**Review by emillon — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by rgrinberg** [comment]
I checked the CI and indeed the error is absent. Merging.
