### PR TITLE
fix(pkg): do not redownload the same url's

### LINKED ISSUE #9701: Re-downloading the same sources when building packages
Our source fetching rules do a bunch of redundant work. For example:

* Fetching the same package sources in different contexts
* Fetching package sources for packages that live in the same repository

We should adjust the rules to deduplicate this work.

This will also make the source fetching rules work much better with the dune cache

### PR DESCRIPTION
**Pull request by rgrinberg**
Download them all to _build/_fetch/$checksum

Signed-off-by: Rudi Grinberg <me@rgrinberg.com>

### CODE REVIEW

File: src/dune_rules/fetch_rules.ml [hunk 1]
```diff
@@ -0,0 +1,275 @@
+open Import
+open Memo.O
+module Gen_rules = Build_config.Gen_rules
+
+include struct
```
Comment (Leonidas-from-XIV) [inline src/dune_rules/fetch_rules.ml:5]: What is the purpose of including it instead of writing this on the top-level?

File: src/dune_rules/fetch_rules.ml [hunk 2]
```diff
@@ -0,0 +1,275 @@
...
+      Rules.collect_unit (fun () ->
+        url_of_checksum ctx checksum
+        >>= function
+        | None ->
+          User_error.raise
+            [ Pp.textf "unknown checksum %s" (Checksum.to_string checksum) ]
+        | Some (url, checksum) -> gen_rules_checksum url checksum)
+    in
+    Gen_rules.make rules ~directory_targets |> Memo.return
+  | _ -> Memo.return Gen_rules.no_rules
```
Comment (Leonidas-from-XIV) [inline src/dune_rules/fetch_rules.ml:192]: What is `compontents` here? Is silently no-oping in that case the right thing to do?

File: src/dune_rules/fetch_rules.ml [hunk 3]
```diff
@@ -0,0 +1,275 @@
...
+  | `Directory ->
+    Copy.action ~src_dir:src ~dst_dir:target
+    |> Action.Full.make
+    |> Action_builder.With_targets.return
+    |> Action_builder.With_targets.add_directories ~directory_targets:[ target ]
+;;
+
+let fetch ~target kind url checksum =
+  match checksum with
+  | Some (_, checksum) -> copy ~target kind checksum
```
Comment (Leonidas-from-XIV) [inline src/dune_rules/fetch_rules.ml:264]: Will this not fail when a checksum is specified but not present in the cache?

File: src/dune_rules/fetch_rules.ml (hunk 1 above)
Comment (rgrinberg) [reply src/dune_rules/fetch_rules.ml:5]: You get to avoid the `Dune_pkg` prefix. E.g. in

```
module Checksum = Dune_pkg.Checksum
module Pkg = Dune_pkg.Lock_dir.Pkg
```

the `Dune_pkg` is repeated.

File: src/dune_rules/fetch_rules.ml (hunk 2 above)
Comment (rgrinberg) [reply src/dune_rules/fetch_rules.ml:192]: components would be any other build path `_build/_fetch/` that doesn't match the pattern above. So it's correct to return no rules for these unknown paths. There's not much of a real difference though. We load the rules in a directory to build a particular target in it, so we could either:

1. Get an error loading some directory rules
2. Depending on that target and then dune telling us the target doesn't exist.

File: src/dune_rules/fetch_rules.ml [hunk 4]
```diff
@@ -0,0 +1,275 @@
...
+let context_name = Context_name.of_string "_fetch"
+let context = Build_context.create ~name:context_name
+
+let make_target ~kind checksum =
+  let basename =
+    match kind with
+    | `File -> "file"
+    | `Directory -> "dir"
+  in
+  Path.Build.L.relative context.build_dir [ Checksum.to_string checksum; basename ]
```
[the remark this answers is not in the document]
Comment (rgrinberg) [reply src/dune_rules/fetch_rules.ml:20]: Yes, we could do that. I'll leave a TODO

[the remark this answers is not in the document]
Comment (rgrinberg) [reply src/dune_rules/fetch_rules.ml:20]: Actually, if we need to do this for the source fetching, we'd also need to do this for the package rules themselves. Those are going to have at least as many directories in `.pkg/$pkg_name`

File: src/dune_rules/fetch_rules.ml (hunk 3 above)
Comment (rgrinberg) [reply src/dune_rules/fetch_rules.ml:264]: It will not. It will introduce a dependency on `_fetch/$checksum/<file|dir>` which will load the rules in that directory and generate the rule for this checksum (if it's a valid checksum).

**Review by gridbugs — APPROVED** [review]

**Review by Leonidas-from-XIV — APPROVED** [review]
