### PR TITLE
time_stubs.c: add fallback for Windows 7

### LINKED ISSUE #13871: dune 3.22.0 bootstrap fails on Windows < 8 — GetSystemTimePreciseAsFileTime not found in KERNEL32.dll
## Environment
- OS: Windows 7
- OCaml: 4.14.2+mingw64
- opam: 2.0.8
- dune: 3.22.0 (regression from 3.21)

## Error
Running `opam install dune` fails at bootstrap:

  dune.exe - entry point not found
  The procedure entry point GetSystemTimePreciseAsFileTime could not be
  located in the dynamic link library KERNEL32.dll

exit-code: -1073741511 (0xC0000139 STATUS_ENTRYPOINT_NOT_FOUND)

## ldd output
  ntdll.dll    => C:\Windows\SYSTEM32\ntdll.dll
  kernel32.dll => C:\Windows\system32\kernel32.dll
  KERNELBASE.dll => C:\Windows\system32\KERNELBASE.dll

## Notes
- dune 3.21 installs and works correctly on this system
- GetSystemTimePreciseAsFileTime was introduced in Windows 8

### PR DESCRIPTION
**Pull request by nojb**
Adds a fallback for `GetSystemTimePreciseAsFileTime` for old versions of Windows (< 8).

Fixes #13871

### CODE REVIEW

File: otherlibs/stdune/src/time_stubs.c [hunk 1]
```diff
@@ -12,8 +12,18 @@
...
-
+  static VOID (WINAPI *GetSystemTime)(LPFILETIME) = NULL;
+  if (GetSystemTime == NULL) {
+    HMODULE h = GetModuleHandleA("kernel32.dll");
+    if (h) {
+      GetSystemTime = GetProcAddress(h, "GetSystemTimePreciseAsFileTime");
+    }
+    if (GetSystemTime == NULL) { /* < Windows 8 */
+      GetSystemTime = GetSystemTimeAsFileTime;
+    }
```
Comment (Alizter) [inline otherlibs/stdune/src/time_stubs.c:23]: I added an else and a printf here, however I am seeing that this is getting called quite a few times. Shouldn't this only be happening once? (On Win 11)

Comment (nojb) [reply otherlibs/stdune/src/time_stubs.c:23]: Yes, it should be called only once per process. Could there be more than one Dune process active?

Comment (Alizter) [reply otherlibs/stdune/src/time_stubs.c:23]: I think I've solved the mystery. We have rules that generate the help pages so there were multiple dune processes happening when I did `dune build dune.install`. :-)

**Review by Alizter — APPROVED** [review]

**Comment by nojb** [comment]
CI failure is unrelated.

**Comment by Alizter** [comment]
We get this new warning on mingw:
```
time_stubs.c: In function 'dune_clock_gettime_realtime':
time_stubs.c:19:21: warning: assignment to 'void (*)(struct _FILETIME *)' from incompatible pointer type 'FARPROC' {aka 'long long int (*)()'} [-Wincompatible-pointer-types]
   19 |       GetSystemTime = GetProcAddress(h, "GetSystemTimePreciseAsFileTime");
      |                     ^
```

**Comment by Alizter** [comment]
I've made #13914 to fix the warning.

**Comment by rgrinberg** [comment]
Does OCaml 4.14 even support windows 7? If not, then this change is kind of pointless as it will be broken by the next release anyway.

**Comment by Alizter** [comment]
@rgrinberg I was able to test the patch in a Windows 7 VM so that's a yes.
