### PR TITLE
Fix some issues with extra-sources

### LINKED ISSUE #10788: Error building the package "seq" as a dependency with dune package management
To reproduce this, clone https://github.com/ocaml-ppx/ocamlformat.git (which depends on seq - other packages depending on seq may also have this problem).

The run:
```
$ dune pkg lock
$ dune build
```

The error will be:
```
Error:                              
open(_build/_private/default/.pkg/seq/source/META.seq): No such file or directory
-> required by _build/_private/default/.pkg/seq/target/cookie
-> required by - package re
-> required by - package alcotest
```

Inspecting the contents of _build/_private/default/.pkg/seq/source/META.seq:
```
$ ls _build/_private/default/.pkg/seq/
extra_source
```

The lockfile for seq hints at the issue:
```
 $ cat dune.lock/seq.pkg 
(version base)

(depends ocaml)

(extra_sources
 (META.seq
  (fetch
   (url
    https://raw.githubusercontent.com/ocaml/opam-source-archives/main/patches/seq/META.seq)
   (checksum
    sha256=e95062b4d0519ef8335c02f7d0f1952d11b814c7ab7e6d566a206116162fa2be)))
 (seq.install
  (fetch
   (url
    https://raw.githubusercontent.com/ocaml/opam-source-archives/main/patches/seq/seq.install)
   (checksum
    sha256=fff926c2c4d5a82b6c94c60c4c35eb06e3d39975893ebe6b1f0e6557cbe34904))))
```

This corresponds with the opam file:
```
$ opam show seq.base --raw
opam-version: "2.0"
name: "seq"
version: "base"
synopsis:
  "Compatibility package for OCaml's standard iterator type starting from 4.07."
maintainer: " "
authors: " "
homepage: " "
bug-reports: "https://caml.inria.fr/mantis/main_page.php"
depends: [
  "ocaml" {>= "4.07.0"}
]
dev-repo: "git+https://github.com/ocaml/ocaml.git"
extra-source "META.seq" {
  src:
    "https://raw.githubusercontent.com/ocaml/opam-source-archives/main/patches/seq/META.seq"
  checksum: [
    "sha256=e95062b4d0519ef8335c02f7d0f1952d11b814c7ab7e6d566a206116162fa2be"
    "md5=b33c8a1a6c7ed797816ce27df4855107"
  ]
}
extra-source "seq.install" {
  src:
    "https://raw.githubusercontent.com/ocaml/opam-source-archives/main/patches/seq/seq.install"
  checksum: [
    "sha256=fff926c2c4d5a82b6c94c60c4c35eb06e3d39975893ebe6b1f0e6557cbe34904"
    "md5=026b31e1df290373198373d5aaa26e42"
  ]
}
```

This package is unusual in that it has no sources, only extra-sources. This is a case that we're probably not handling yet in dune.

### PR DESCRIPTION
**Pull request by gridbugs**
Before copying a file from a package's "extra_sources" directory to the "source" directory, make sure that:
 - the package's "source" directory exists
 - the destination file doesn't already exist

Fixes https://github.com/ocaml/dune/issues/10788

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
I don't think this is the right solution. The issue is that if there is no `build` field, it doesn't add the `Action.chdir` thus no dependency on the `source_dir` is recorded, thus the copy rules are not executed by the engine. If they are executed, they work fine, the directory is created.

You can see that `seq` works if you add a

```
(build (run true))
```
into the lock file.

**Comment by gridbugs** [comment]
Interesting! I'll dig deeper into this tomorrow.

**Comment by Leonidas-from-XIV** [comment]
I've been discussing this with help from @emillon but just recording a dependency is not enough, as then it fails because there's no target that generates `source_dir`. I'll also be looking at this because this is what at every single package that (transitively) depends on `seq` fails on when building.

**Comment by emillon** [comment]
do we have a test for that?
also, if setting `(build (run true))` works we can use that in the meantime.

**Review by Leonidas-from-XIV — APPROVED** [review]
After spending entirely too much of both my and @emillon's time trying to understand what is happening and why `(build (run true))` or even just `(build (progn))` is fixing it:

If there is a build action, the expander will add a `Action.chdir <source-dir>` to the build. This will implicitly `mkdir` `<source-dir>` if if doesn't exist thus when the copy rules are executed they succeed because `<source-dir>` exists at that point. So the `(build (progn))` is actually a `(build (chdir <source-dir> (progn))`.

If there are no build instructions in the lock file, this `chdir` doesn't happen and thus no `<source-dir>` folder will be created, at which case the copy rules will fail (I guess silently) and the next thing expecting the copy rules to have succeeded will fail because the files didn't appear where they were supposed to be.

Thus creating the `<source-dir>` explicitly is the right solution here, however maybe it would make sense to do that conditionally if it doesn't exist, like above with `Fs_memo.dir_exists`. Then again, if the `mkdir` action is idempotent, it might be faster to attempt to create it than issuing a `stat()`.

Anyway I am now confident that this is the right solution and explains the rather unexpected behavior that I've observed.

File: src/dune_rules/pkg_rules.ml [hunk 1]
```diff
@@ -1757,9 +1757,27 @@ let build_rule context_name ~source_deps (pkg : Pkg.t) =
...
+          Action.progn
+            [ (* If the package has no source directory (some
+                 low-level packages are exclusively made up of extra
+                 sources), the source directory is first created. *)
+              Action.mkdir pkg.write_paths.source_dir
+            ; (* It's possible for some extra sources to already be at
+                 the destination. If these files are write-protected
+                 then the copy action will fail if we don't first remove
+                 them. *)
+              Action.remove_tree dst
```
Comment (rgrinberg) [inline src/dune_rules/pkg_rules.ml:1776]: Why are removing existing sources though? Shouldn't we merge all the sources?

**Comment by Leonidas-from-XIV** [comment]
Given `Copy` just maps to `cp` https://github.com/ocaml/dune/blob/0a8af6e1c8eb701e43cefa92bcfd131ec89ed6d7/src/dune_engine/action_to_sh.ml#L62

I guess you're right, it's `cp` being cryptic what exactly is missing:

```sh
$ cp exists.ml missing/new.ml
cp: cannot create regular file 'missing/new.ml': No such file or directory
```

File: src/dune_rules/pkg_rules.ml (hunk 1 above)
Comment (emillon) [reply src/dune_rules/pkg_rules.ml:1776]: that confused me as well, apparently this is to encode the semantics that extra-sources override the contents of the tarball.
I think a dedicated test for this would be useful.
In addition, maybe we can skip unpacking files present in `extra_sources` and skip this `remove_tree`, or something like that?

**Comment by emillon** [comment]
Copy is not executed by shelling out to `cp`, it's just how we represent that in `dune rules -m`. It's implemented by `Io.copy_file` (see the `Action_exec` module).

File: src/dune_rules/pkg_rules.ml (hunk 1 above)
Comment (Leonidas-from-XIV) [reply src/dune_rules/pkg_rules.ml:1776]: If the source tarball has a file (or directory) and the extra-source has the same path I would expect that the extra-source would replace the original file as it is meant to patch the source tarball.

Comment (rgrinberg) [reply src/dune_rules/pkg_rules.ml:1776]: Ok let's just make sure we have a test for this and we are matching opam's behavior.

Comment (gridbugs) [reply src/dune_rules/pkg_rules.ml:1776]: Tests are added in https://github.com/ocaml/dune/pull/10790. I updated that PR with a test for the scenario where an extra-source file replaces a file in the source dir and did a manual experiment to confirm that this is also how opam behaves.
