### PR TITLE
pkg: fall back to copy when renaming lock dir

### LINKED ISSUE #11644: dune pkg lock: cross device link error when refreshing package locks
I'm trying dune package management again and just ran into this error when refreshing a pkg lock in a Dockerfile.

```
#18 1.525 - zarith.1.14
#18 1.531 Error: rename(dune.lock): Cross-device link
#18 ERROR: process "/bin/sh -c dune pkg lock" did not complete successfully: exit code: 1
------
 > [12/13] RUN dune pkg lock:
```

This only happens when the lock file already exists, and is presumably because it's trying to rename across a bindmount. The tempfile should probably be in the same directory as the lockfile itself.

The Dockerfile is something like:

```
# syntax=docker/dockerfile:1.2
FROM ocaml/opam:alpine AS build
RUN curl -fsSL https://get.dune.build/install | sh
WORKDIR /home/ocaml/src
RUN --mount=type=secret,id=GIT_TOKEN git clone <snip...>
ENV PATH=/home/opam/.local/bin:$PATH
RUN sudo apk add libev-dev gmp-dev openssl-dev
RUN ~/.local/bin/dune pkg lock
RUN ~/.local/bin/dune build @pkg-install
RUN git pull
RUN dune pkg lock
RUN dune build
```

The failure happens on the second lock.

### PR DESCRIPTION
**Pull request by punchagan**
Previously, we renamed existing lock dirs to a hidden lock dir before creating a new one in a temporary directory and moving it to the correct location. This was done to keep the lock dir generation atomic as part of #10852 for apparently better behaved `dune pkg lock` when run alongside another `dune build --watch`. But, it caused problems when running inside a docker container (as reported in #11644). This code removes the dance of using a hidden lock dir and fixes #11644. The problem for which #10852 was required couldn't be reproduced by me or Steve (as per [the comment here])

[the comment here]: https://github.com/ocaml/dune/issues/11644#issuecomment-3243989375

### CODE REVIEW

**Comment by punchagan** [comment]
I modified the reproducer shared by Mark [here](https://github.com/ocaml/dune/issues/11644#issuecomment-3115101688) to verify that the fix works. 

```dockerfile
FROM ocaml/opam:alpine AS build
RUN sudo ln -f /usr/bin/opam-2.4 /usr/bin/opam
RUN uname -rs && opam exec -- ocaml -version && opam --version
RUN opam init --reinit -ni
RUN sudo apk add linux-headers
COPY --chown=1000:1000 . /home/opam/dune/
WORKDIR /home/opam/dune
RUN opam exec -- opam install --deps-only -y ./dune.opam
RUN opam exec -- make bootstrap
RUN mkdir -p /home/opam/.local/bin
RUN sudo cp /home/opam/dune/_boot/dune.exe /home/opam/.local/bin/dune
# RUN curl -fsSL https://get.dune.build/install | sh
WORKDIR /home/opam
RUN git clone https://github.com/ocurrent/ocaml-dockerfile
ENV PATH=/home/opam/.local/bin:$PATH
RUN sudo apk add libev-dev gmp-dev openssl-dev
WORKDIR /home/opam/ocaml-dockerfile
RUN dune pkg lock
RUN dune build @pkg-install
RUN git pull
RUN dune pkg lock
RUN dune build
```

**Comment by rgrinberg** [comment]
Can we keep the old code path for atomic updates? There's a Unix error code we can use to detect a cross device link. Then  we can fallback to copying.

File: src/dune_pkg/lock_dir.ml [hunk 1]
```diff
@@ -1389,11 +1389,44 @@ module Write_disk = struct
...
+  ;;
+
   (* Does the same checks as [safely_remove_lock_dir_if_exists_thunk] but it raises an
      error if the lock dir already exists. [dst] is the new file name *)
   let safely_rename_lock_dir_thunk ~dst src =
     match check_existing_lock_dir src, check_existing_lock_dir dst with
-    | Ok `Is_existing_lock_dir, Ok `Non_existant -> fun () -> Path.rename src dst
+    | Ok `Is_existing_lock_dir, Ok `Non_existant ->
+      fun () ->
+        (try Path.rename src dst with
```
Comment (Alizter) [inline src/dune_pkg/lock_dir.ml]: Can you switch this to `match .. with | exception ...`?

Comment (shonfeder) [reply src/dune_pkg/lock_dir.ml]: Not meaning to block your review request, but why is that better *in this case*?

Comment (Alizter) [reply src/dune_pkg/lock_dir.ml]: This is my preference and a general style we have in the code base. Here is some information on why it might be considered better in other cases https://blog.janestreet.com/pattern-matching-and-exception-handling-unite/

It's not blocking here however.

Comment (shonfeder) [reply src/dune_pkg/lock_dir.ml]: Thanks :) 

If we want to enforce this style in the codebase, I suggest adding it to https://dune.readthedocs.io/en/latest/hacking.html#general-guidelines, just to streamline style nits. I don't care personally one way or the other in cases like this.

File: src/dune_pkg/lock_dir.ml [hunk 2]
```diff
@@ -1389,11 +1389,44 @@ module Write_disk = struct
...
+             match kind with
+             | Unix.S_DIR ->
+               Path.mkdir_p child_dst;
+               safely_copy_lock_dir_when_dst_non_existant ~dst:child_dst child_src
+             | _ ->
+               Path.mkdir_p dst;
+               Io.copy_file ~src:child_src ~dst:child_dst ())
+           children)
+    | Ok `Non_existant -> ()
+    | Error e -> raise_user_error_on_check_existance src e
```
Comment (rgrinberg) [inline src/dune_pkg/lock_dir.ml]: I'd move the shorter clauses to the top.

File: src/dune_pkg/lock_dir.ml [hunk 3]
```diff
@@ -1389,11 +1389,44 @@ module Write_disk = struct
...
+       | Ok children ->
+         List.iter
+           ~f:(fun (name, kind) ->
+             let child_src = Path.relative src name in
+             let child_dst = Path.relative dst name in
+             match kind with
+             | Unix.S_DIR ->
+               Path.mkdir_p child_dst;
+               safely_copy_lock_dir_when_dst_non_existant ~dst:child_dst child_src
+             | _ ->
```
Comment (rgrinberg) [inline src/dune_pkg/lock_dir.ml]: How about tightening this to S_REG and doing `assert false` on the other kinds?

File: src/dune_pkg/lock_dir.ml [hunk 4]
```diff
@@ -1389,11 +1389,44 @@ module Write_disk = struct
...
+               Path.mkdir_p dst;
+               Io.copy_file ~src:child_src ~dst:child_dst ())
+           children)
```
Comment (rgrinberg) [inline src/dune_pkg/lock_dir.ml]: If you move `children` to be the first argument, the code will be more readable and shorter.

**Review by rgrinberg — APPROVED** [review]

**Review by gridbugs — APPROVED** [review]

File: src/dune_pkg/lock_dir.ml (hunk 1 above)
Comment (punchagan) [reply src/dune_pkg/lock_dir.ml]: Thanks! I've switched this

**Comment by punchagan** [comment]
Thanks for your reviews and inputs. I've addressed all the PR review suggestions here!

File: src/dune_pkg/lock_dir.ml [hunk 5]
```diff
@@ -1389,11 +1389,44 @@ module Write_disk = struct
...
+    | Ok `Non_existant -> ()
+    | Ok `Is_existing_lock_dir ->
+      (match Path.readdir_unsorted_with_kinds src with
+       | Error (e, _, _) ->
+         User_error.raise
+           [ Pp.textf
+               "Failed to list %s with error %s"
+               (Path.to_string_maybe_quoted src)
+               (Unix.error_message e)
+           ]
```
Comment (Alizter) [inline src/dune_pkg/lock_dir.ml]:
```suggestion
               "Failed to list %s with error:"
               (Path.to_string_maybe_quoted src)
           ; Unix_error.Detailed.pp e
           ]
```
Or something like that.

**Review by Alizter — APPROVED** [review]
LGTM after my comment is addressed.
