### PR TITLE
fix: auto-inject menhir lower bound in generated opam files

### LINKED ISSUE #10707: Add correct lower bound to menhir
## Desired Behavior

`dune` assumes that `menhir` supports the `--infer-write-query` flag (https://github.com/ocaml/dune/blob/30add837eca7ba1d27a5d7955777f4b96cbbb1b7/src/dune_rules/menhir/menhir_rules.ml#L7).
In the `opam-repository` we often get packages using the feature and whose opam files are autogenerated with `dune`. These usually depend on `menhir` without any version bound, and in almost all cases we need to manually modify this to `"menhir" {>= "20180528"}`.

Would it be possible to make dune automatically generate an opam file with this lower bound already added in, like it does with its own version?

### PR DESCRIPTION
**Pull request by robinbb**
## Summary

Fixes #10707.

When a project uses `(using menhir ...)`, dune assumes menhir supports `--infer-write-query` and `--infer-read-reply` (available since menhir 20180523), but the generated opam file includes no version constraint on menhir. This causes packages in opam-repository to frequently need manual lower-bound fixes.

This PR auto-injects `"menhir" {>= "20180523"}` into generated opam files when the menhir extension is active, following the same pattern as the existing dune and odoc auto-injected dependencies. If the user already declares a menhir dependency with a version constraint, it is preserved.

### CODE REVIEW

File: src/dune_rules/opam_create.ml [hunk 1]
```diff
@@ -275,6 +276,32 @@ let insert_odoc_dep depends =
   loop [] depends
 ;;
 
+let menhir_constraint : Package_constraint.t = Uop (Gte, String_literal "20180523")
```
Comment (Leonidas-from-XIV) [inline src/dune_rules/opam_create.ml:281]: Worth commenting why exactly this constraint.

File: src/dune_rules/opam_create.ml [hunk 2]
```diff
@@ -275,6 +276,32 @@ let insert_odoc_dep depends =
...
+
+let insert_menhir_dep depends =
+  let menhir_dep =
+    { Package_dependency.name = menhir_name; constraint_ = Some menhir_constraint }
+  in
+  let rec loop acc = function
```
Comment (Leonidas-from-XIV) [inline src/dune_rules/opam_create.ml]: Why is this a recursive function? Looks more like a case for `List.map` to me?

File: test/blackbox-tests/test-cases/menhir/opam-menhir-dep.t [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+
+  $ cat > dune-project << EOF
+  > (lang dune 3.23)
+  > (using menhir 2.1)
+  > (generate_opam_files true)
+  > (package (name foo) (allow_empty))
+  > EOF
+
+  $ dune build foo.opam
+  $ cat foo.opam | grep menhir
```
Comment (Leonidas-from-XIV) [inline test/blackbox-tests/test-cases/menhir/opam-menhir-dep.t]: This is just `grep menhir < foo.opam`

File: test/blackbox-tests/test-cases/menhir/opam-menhir-dep.t [hunk 4]
```diff
@@ -0,0 +1,53 @@
...
+  > (using menhir 2.1)
+  > (generate_opam_files true)
+  > (package
+  >  (name foo)
+  >  (allow_empty)
+  >  (depends (menhir (>= 20211128))))
+  > EOF
+
+  $ dune build foo.opam
+  $ cat foo.opam | grep menhir
```
Comment (Leonidas-from-XIV) [inline test/blackbox-tests/test-cases/menhir/opam-menhir-dep.t]: As above.

File: test/blackbox-tests/test-cases/menhir/opam-menhir-dep.t [hunk 5]
```diff
@@ -0,0 +1,53 @@
...
+  > (using menhir 2.1)
+  > (generate_opam_files true)
+  > (package
+  >  (name foo)
+  >  (allow_empty)
+  >  (depends menhir))
+  > EOF
+
+  $ dune build foo.opam
+  $ cat foo.opam | grep menhir
```
Comment (Leonidas-from-XIV) [inline test/blackbox-tests/test-cases/menhir/opam-menhir-dep.t]: As above.

File: doc/changes/fixed/10707.md [hunk 6]
```diff
@@ -0,0 +1,2 @@
+- Auto-inject `"menhir" {>= "20180523"}` into generated opam files when the
+  menhir extension is used. (#10707, @robinbb)
```
Comment (Leonidas-from-XIV) [inline doc/changes/fixed/10707.md]: Worth writing here why this is being done.

**Review by Leonidas-from-XIV — CHANGES_REQUESTED** [review]
It's a good improvement, I was frustrated by this myself a number of times.

File: src/dune_rules/opam_create.ml (hunk 1 above)
Comment (robinbb) [reply src/dune_rules/opam_create.ml:281]: Done.

File: src/dune_rules/opam_create.ml (hunk 2 above)
Comment (robinbb) [reply src/dune_rules/opam_create.ml]: Rewritten.

File: doc/changes/fixed/10707.md (hunk 6 above)
Comment (robinbb) [reply doc/changes/fixed/10707.md]: Agreed. Done.

File: src/dune_rules/opam_create.ml [hunk 7]
```diff
@@ -275,6 +276,28 @@ let insert_odoc_dep depends =
...
+      Package.Name.equal dep.name menhir_name)
+  then
+    List.map depends ~f:(fun (dep : Package_dependency.t) ->
+      if Package.Name.equal dep.name menhir_name
+      then
+        { dep with
+          constraint_ = Some (Option.value dep.constraint_ ~default:menhir_constraint)
+        }
+      else dep)
+  else List.rev (menhir_dep :: List.rev depends)
```
Comment (Leonidas-from-XIV) [inline src/dune_rules/opam_create.ml]: Why are there these two `List.rev`? Is it to append it to the end? In such case I think `depends @ [menhir_dep]` might be a better option that doesn't build the list twice.

**Review by Leonidas-from-XIV — CHANGES_REQUESTED** [review]
Unless I am missing something, the two `List.rev` are probably unnecessary.

File: src/dune_rules/opam_create.ml (hunk 7 above)
Comment (robinbb) [reply src/dune_rules/opam_create.ml]: Thank you!

**Review by Leonidas-from-XIV — APPROVED** [review]
LGTM

**Comment by toots** [comment]
This PR adds menhir dependency to all packages! It should only be for the packages that need it.

**Comment by Alizter** [comment]
@toots Indeed. This has been fixed here https://github.com/ocaml/dune/pull/14434 and will appear in 3.23.1.

**Comment by toots** [comment]
> @toots Indeed. This has been fixed here #14434 and will appear in 3.23.1.

Awesome thanks!
