### PR TITLE
Fix gh10408

### LINKED ISSUE #10408: pkg: adding a path to the `PATH` variable with the `withenv` action overwrites the existing `PATH` value rather than prepending to it
Not sure if this behaviour is intentional or not. I expected that adding a value to `PATH` would result in the existing `PATH` being prepended to rather than clobbered.

Repro here: https://github.com/ocaml/dune/pull/10407

### PR DESCRIPTION
**Pull request by gridbugs**
When updating the PATH variable with the `withenv` action, dune would previously clobber the existing PATH from the environment rather than updating it. Withenv applies environment updates iteratively starting from some base environment. Prior to this change, the base environment did not include the global environment, so as far as withenv knew the PATH was originally empty. The fix is to start withenv with an environment which includes the global environment.

Fixes https://github.com/ocaml/dune/issues/10408

### CODE REVIEW

File: src/dune_rules/pkg_rules.ml [hunk 1]
```diff
@@ -144,6 +144,40 @@ module Install_cookie = struct
...
+  let get_path t = Env.Map.find t Env_path.var
+
+  (* [extend_concat_path a b] adds all variables from [b] to [a]
+     overwriting any existing values of those variables in [a] except for PATH
+     which is set to the concatenation of the PATH variables from [a] and [b]
+     with the PATH entries from [b] preceding the PATH entries from [a] *)
+  let extend_concat_path a b =
+    let path =
+      match get_path a, get_path b with
+      | None, None -> []
```
Comment (rgrinberg) [inline src/dune_rules/pkg_rules.ml:173]: Does this mean if neither side has `PATH` set, you will set it to the empty path?

Comment (gridbugs) [reply src/dune_rules/pkg_rules.ml:173]: That's correct, though thinking more about this I think what it should be doing instead is not setting `PATH` at all in such a case. Will update.

Comment (gridbugs) [reply src/dune_rules/pkg_rules.ml]: Updated

File: src/dune_rules/pkg_rules.ml [hunk 2]
```diff
@@ -144,6 +144,47 @@ module Install_cookie = struct
...
+
+  (* [extend_concat_path a b] adds all variables from [b] to [a]
+     overwriting any existing values of those variables in [a] except for PATH
+     which is set to the concatenation of the PATH variables from [a] and [b]
+     with the PATH entries from [b] preceding the PATH entries from
+     [a]. If only one of the arguments contains a PATH variable then
+     its value will be the value of PATH in the result, however if
+     neither argument contains a PATH variable then PATH will be unset
+     in the result. *)
+  let extend_concat_path a b =
```
Comment (rgrinberg) [inline src/dune_rules/pkg_rules.ml:174]: There's a few other variables where we need this treatment - basically any variable that we expand automatically by adding a package dep. This is a good start though.

**Review by rgrinberg — APPROVED** [review]

File: src/dune_rules/pkg_rules.ml (hunk 2 above)
Comment (gridbugs) [reply src/dune_rules/pkg_rules.ml:174]: Ah that makes sense. I'll make an issue for generalizing this to other variables. Any idea what variables might be affected or under what conditions this might fail?

Comment (gridbugs) [reply src/dune_rules/pkg_rules.ml:174]: Actually @rgrinberg would you mind making an issue for this. Can you think of a problem that could be caused by dune clobering environment variables containing lists other than PATH? Possibly systems where libraries are stored in an unusual place dictated by an environment variable? I guess dune needs to establish a convention for which variables get passed through and which ones are sandboxed.

Relevant: https://github.com/ocaml/dune/pull/8237

Comment (rgrinberg) [reply src/dune_rules/pkg_rules.ml:174]: Isn't this the same as https://github.com/ocaml/dune/issues/10294? I've expanded the list of variables we need to relocate there.
