### PR TITLE
Fix/good error msg pkg enabled

### LINKED ISSUE #12801: Good error when `(pkg enabled)` is put in dune-project
We should provide a more informative error when `(pkg enabled)` is put inside the `dune-project` file rather than the `dune-workspace` file.

https://github.com/ocaml/dune/pull/12761#issuecomment-3585644753

### PR DESCRIPTION
**Pull request by benodiwal**
Closes #12801

### CODE REVIEW

File: src/dune_lang/dune_project.ml [hunk 1]
```diff
@@ -953,7 +953,21 @@ let parse ~dir ~(lang : Lang.Instance.t) ~file =
...
+     and+ pkg_field =
+       field_o
+         "pkg"
+         (let+ loc = loc
+          and+ () = junk_everything in
+          loc)
      in
+     (match pkg_field with
+      | Some loc ->
+        User_error.raise
```
Comment (Leonidas-from-XIV) [inline src/dune_lang/dune_project.ml]: `User_error.raise` has a `hints` parameter, this is a better way to provide the hints.

File: src/dune_lang/dune_project.ml [hunk 2]
```diff
@@ -953,7 +953,21 @@ let parse ~dir ~(lang : Lang.Instance.t) ~file =
...
+          ~loc
+          [ Pp.text "(pkg ...) belongs in dune-workspace, not dune-project"
+          ; Pp.text "Hint: move this stanza to your dune-workspace file"
```
Comment (Alizter) [inline src/dune_lang/dune_project.ml]: We have a `~hints` argument you can use for this instead.

File: test/blackbox-tests/test-cases/workspaces/pkg-in-dune-project.t/dune-project [hunk 3]
```diff
@@ -0,0 +1,2 @@
+(lang dune 3.20)
```
Comment (Leonidas-from-XIV) [inline test/blackbox-tests/test-cases/workspaces/pkg-in-dune-project.t/dune-project]: This should be `3.21`

File: test/blackbox-tests/test-cases/pkg/pkg-in-dune-project-error.t [hunk 4]
```diff
@@ -0,0 +1,10 @@
+Test that putting (pkg enabled) in dune-project instead of dune-workspace
```
Comment (Leonidas-from-XIV) [inline test/blackbox-tests/test-cases/pkg/pkg-in-dune-project-error.t:1]: Can you make it a single-file test in `test/blackbox-tests/test-cases/pkg`? That would make it a bit easier to grasp.

File: src/dune_lang/dune_project.ml [hunk 5]
```diff
@@ -953,7 +953,21 @@ let parse ~dir ~(lang : Lang.Instance.t) ~file =
          "warnings"
          ~default:Warning.Settings.empty
          (Syntax.since Stanza.syntax (3, 11) >>> Warning.Settings.decode)
+     and+ pkg_field =
```
Comment (Leonidas-from-XIV) [inline src/dune_lang/dune_project.ml]: I believe this would need to be gated on `3.21`.

File: src/dune_lang/dune_project.ml (hunk 2 above)
Comment (benodiwal) [reply src/dune_lang/dune_project.ml]: Sure

**Review by Leonidas-from-XIV — DISMISSED** [review]
Thanks for the PR. I have made some comments on how to improve the code.

However I think I would ask the opinion of other Dune maintainers to ask whether adding support for `pkg` in `dune-project` only to state that you don't support is is a good idea. It feels a bit.. odd. Likewise, should we add stanzas for other error cases too (`lock_dir` etc)?

**Comment by benodiwal** [comment]
> Thanks for the PR. I have made some comments on how to improve the code.
> 
> However I think I would ask the opinion of other Dune maintainers to ask whether adding support for `pkg` in `dune-project` only to state that you don't support is is a good idea. It feels a bit.. odd. Likewise, should we add stanzas for other error cases too (`lock_dir` etc)?

Thanks for the feedback @Leonidas-from-XIV ! I've implemented all your suggestions ! You raise a good point about whether this approach feels odd. I can see the concern, we're essentially adding a field just to reject it with a better error message.

**Comment by Alizter** [comment]
@Leonidas-from-XIV Given that we are/will be pushing people to use package management it would be good to handle this particular case since it does occur if users are new to the dune-workspace file. It's better than the confusing message we get otherwise. https://github.com/ocaml/dune/pull/12761#issuecomment-3585644753

**Comment by Leonidas-from-XIV** [comment]
Thanks for addressing the issues, quite nice.

I've been looking at this a little and if we decide that we want to support a feature like this maybe we should extend `Syntax.check_supported` with an additional case for something like `` `Unsupported_in_dune_project``. That way it would be easier to add stanzas that are unsupported without having to write an ad-hoc error message for every single of them.

File: src/dune_lang/dune_project.ml [hunk 6]
```diff
@@ -953,7 +953,21 @@ let parse ~dir ~(lang : Lang.Instance.t) ~file =
...
+          >>> let+ loc = loc
+              and+ () = junk_everything in
+              loc)
      in
+     (match pkg_field with
+      | Some loc ->
+        User_error.raise
+          ~loc
+          ~hints:[ Pp.text "move this stanza to your dune-workspace file" ]
+          [ Pp.text "(pkg ...) belongs in dune-workspace, not dune-project" ]
```
Comment (Alizter) [inline src/dune_lang/dune_project.ml]:
```
Error: The (pkg ...) configuration is only valid in dune-workspace, not a dune-project.
Hint: Add this configuration to your dune-workspace file (create one in your workspace root if you don't have one).
```
Here is a slightly more helpful message

Comment (benodiwal) [reply src/dune_lang/dune_project.ml]: Hey @Alizter, I have made the changes you asked.

**Review by Alizter — DISMISSED** [review]

File: src/dune_lang/dune_project.ml [hunk 7]
```diff
@@ -953,7 +953,28 @@ let parse ~dir ~(lang : Lang.Instance.t) ~file =
...
          ~default:Warning.Settings.empty
          (Syntax.since Stanza.syntax (3, 11) >>> Warning.Settings.decode)
+     and+ pkg_field =
+       field_o
+         "pkg"
+         (Syntax.since Stanza.syntax (3, 21)
+          >>> let+ loc = loc
+              and+ () = junk_everything in
+              loc)
      in
```
Comment (Alizter) [inline src/dune_lang/dune_project.ml:971]: No point putting a since here since it was never possible before. Instead I would just `>>|` the `field_o` above into `Option.iter` which raises the user error below. Then you don't need `pkg_field`, it would just become `()`.

Comment (Alizter) [reply src/dune_lang/dune_project.ml:971]:
```ocaml
 and+ () =
       field_o
         "pkg"
         (let+ loc = loc
              and+ () = junk_everything in
              loc)
       >>| Option.iter ~f:(fun loc ->
        User_error.raise
          ~loc
          ~hints:
            [ Pp.text
                "Add this configuration to your dune-workspace file (create one in your \
                 workspace root if you don't have one)."
            ]
          [ Pp.text
              "The (pkg ...) configuration is only valid in dune-workspace, not a \
               dune-project."
          ])
     in
```
something like this

Comment (benodiwal) [reply src/dune_lang/dune_project.ml:971]: Got your point, but in the above comments, Leonidas-from-XIV suggested about this change so that we get this type of message for earlier versions if user tries to put it in `dune-project`. 

```bash
Error: 'pkg' is only available since version 3.21 of the dune language.
Please update your dune-project file to have (lang dune 3.21).
```

Comment (Alizter) [reply src/dune_lang/dune_project.ml:971]: If a user is in a situation where they have put `pkg` in their `dune-project` file, then the version that they are on shouldn't really matter. This may prompt them to upgrade their `dune lang` version first and then mention that it should be in `dune-workspace`. I would rather we first mention that we are in `dune-workspace` and then the correct stanza would be arguing about the version constraint.

Comment (Alizter) [reply src/dune_lang/dune_project.ml:971]: The `pkg` stanza doesn't exist in `dune-project`, we are simply giving a helpful error message for a (possibly) common mistake.

Comment (benodiwal) [reply src/dune_lang/dune_project.ml:971]: makes sense, I just made the change

File: test/blackbox-tests/test-cases/pkg/pkg-in-dune-project-error.t [hunk 8]
```diff
@@ -0,0 +1,17 @@
...
+
+  $ dune build
+  File "dune-project", line 2, characters 0-13:
+  2 | (pkg enabled)
+      ^^^^^^^^^^^^^
+  Error: The (pkg ...) configuration is only valid in dune-workspace, not a
+  dune-project.
+  Hint: Add this configuration to your dune-workspace file (create one in your
+  workspace root if you don't have one).
+  [1]
```
Comment (Alizter) [inline test/blackbox-tests/test-cases/pkg/pkg-in-dune-project-error.t:16]: cc @avsm, since you encountered this situation before, could you give this a read and see if you would have found it useful with your issue before?

**Review by Alizter — APPROVED** [review]

**Review by Alizter — CHANGES_REQUESTED** [review]
Sorry to keep iterating on the wording but I am still not happy. Let me block this to avoid others merging.

**Comment by Alizter** [comment]
```
File "dune-project", line 2, characters 0-13:
2 | (pkg enabled)
    ^^^^^^^^^^^^^
Error: The (pkg ...) stanza is only valid in dune-workspace files.
Hint: Move this stanza to your dune-workspace file. If you don't have one,
create one in your workspace root.
```
This should be better I think.

**Comment by benodiwal** [comment]
> Sorry to keep iterating on the wording but I am still not happy. Let me block this to avoid others merging.

Sure @Alizter

**Comment by benodiwal** [comment]
Hey @Alizter, is there any update on the new message text

**Comment by Alizter** [comment]
@benodiwal Did you see my proposed wording above? https://github.com/ocaml/dune/pull/12802#issuecomment-3589132271

**Comment by benodiwal** [comment]
> @benodiwal Did you see my proposed wording above? [#12802 (comment)](https://github.com/ocaml/dune/pull/12802#issuecomment-3589132271)

Ohh shoot, missed it. Making the change now

File: src/dune_lang/dune_project.ml [hunk 9]
```diff
@@ -953,6 +953,21 @@ let parse ~dir ~(lang : Lang.Instance.t) ~file =
...
+         (let+ loc = loc
+          and+ () = junk_everything in
+          loc)
+       >>| Option.iter ~f:(fun loc ->
+         User_error.raise
+           ~loc
+           ~hints:
+             [ Pp.text
+                 "Move this stanza to your dune-workspace file. If you don't have one,\n\
+                 \                 create one in your workspace root."
```
Comment (Alizter) [inline src/dune_lang/dune_project.ml]: You don't need to put new lines in the text. `Pp` will break it appropriately for you.

Comment (benodiwal) [reply src/dune_lang/dune_project.ml]: I have fixed it

**Review by Alizter — APPROVED** [review]
Looks great. Thanks!

**Comment by Alizter** [comment]
@shonfeder This will be in 3.21, but I don't know if you want to keep the changelog entry since it is package management related. I think its fine to keep in this case but I defer judgement to you.
