### PR TITLE
Fix dune subst trying to substitute on directories

### LINKED ISSUE #1997: dune subst: internal Sys_error raised
```
$ dune subst
Error: exception Sys_error("Is a directory")
Backtrace:
Raised by primitive operation at file "stdlib.ml", line 412, characters 12-37
Called from file "stdlib.ml", line 425, characters 2-25
Called from file "src/stdune/exn.ml", line 27, characters 8-11
Re-raised at file "src/stdune/exn.ml", line 29, characters 30-37
Called from file "src/stdune/io.ml" (inlined), line 94, characters 29-64
Called from file "src/watermarks.ml", line 153, characters 10-27
Called from file "list.ml", line 106, characters 12-15
Called from file "src/watermarks.ml", line 261, characters 2-117
Called from file "src/fiber/fiber.ml", line 95, characters 6-13

I must not segfault.  Uncertainty is the mind-killer.  Exceptions are
the little-death that brings total obliteration.  I will fully express
my cases.  Execution will pass over me and through me.  And when it
has gone past, I will unwind the stack along its path.  Where the
cases are handled there will be nothing.  Only I will remain.
yak:opam2web avsm$ dune --version
1.8.2
```

### PR DESCRIPTION
**Pull request by rgrinberg**
@avsm does it fix #1997 for you?

### CODE REVIEW

File: src/stdune/path.ml [hunk 1]
```diff
@@ -866,6 +866,7 @@ let readdir_unsorted t = Sys.readdir (to_string t) |> Array.to_list
 let is_directory t =
   try Sys.is_directory (to_string t)
   with Sys_error _ -> false
+let is_file t = not (is_directory t)
```
Comment (emillon) [inline src/stdune/path.ml]: does it work for things like named pipes and sockets?

Comment (rgrinberg) [reply src/stdune/path.ml]: Probably not, but this is why I'm introducing this function here. So that we can improve it to take care of these corner cases.

**Comment by rgrinberg** [comment]
I'm merging this meanwhile. Improvements to `Path.is_file` are more than welcome.
