### PR TITLE
Fix inline_tests action when partition list is empty

### LINKED ISSUE #8848: Inline_tests with empty partition
When no inline test is declared (aka empty partition list) in a library using (inline_tests), dune complains with
```
- Error: Rule dependencies are configured to require sandboxing, but the rule
- has no actions that could potentially require sandboxing.
```

### PR DESCRIPTION
**Pull request by hhugo**
fix #8848 

This is a 3 lines fix if your ignore white space

### CODE REVIEW

File: src/dune_rules/inline_tests.ml [hunk 1]
```diff
@@ -347,15 +347,18 @@ include Sub_system.Register_end_point (struct
...
+             | _ :: _ ->
+               let run_tests = Action.concurrent actions in
+               let diffs =
+                 List.map source_files ~f:(fun fn ->
+                   Path.as_in_build_dir_exn fn
+                   |> Path.Build.extend_basename ~suffix:".corrected"
+                   |> Action.diff ~optional:true fn)
+                 |> Action.concurrent
+               in
+               Action.Full.make ~sandbox @@ Action.progn [ run_tests; diffs ]))
```
Comment (Alizter) [inline src/dune_rules/inline_tests.ml:361]: Doesn't have to be in this PR, but wouldn't it make more sense to concurrently run and diff rather than concurrently run and then concurrently diff? At the moment, all the diffs have to wait for all the tests to run.

Comment (hhugo) [reply src/dune_rules/inline_tests.ml:361]: There is nothing allowing us to know what diff to perform after a given run

Comment (Alizter) [reply src/dune_rules/inline_tests.ml:361]: Oh yes of course.

**Review by Alizter — APPROVED** [review]
Fix looks good to me. Of course, we wouldn't need it if `Action.Full.make` was smart enough to avoid sandboxing if an action doesn't need it rather than complaining.

**Comment by rgrinberg** [comment]
Thanks. a CHANGES entry would be appropriate

**Comment by hhugo** [comment]
> a CHANGES entry would be appropriate

done

**Comment by rgrinberg** [comment]
DCO please :)
