### PR TITLE
fix(sendfile): reuse fd before fallback

### LINKED ISSUE #8210: _build/default/bin/dune.exe: Permission denied (ecryptfs, Mint)
## Expected Behavior

I can upgrade Dune.

## Actual Behavior

I get a permission denied error.

## Reproduction

I currently have Dune 3.7.1 installed. When I ran `opam upgrade`, Dune 3.9.1 cannot build due to a permission error.

```
[ERROR] The compilation of dune.3.9.1 failed at "./_boot/dune.exe build dune.install --release --profile dune-bootstrap -j 15".

#=== ERROR while compiling dune.3.9.1 =========================================#
# context     2.1.4 | linux/x86_64 | ocaml-base-compiler.5.0.0 | https://opam.ocaml.org#7109cb08
# path        ~/.opam/5.0.0/.opam-switch/build/dune.3.9.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build ./_boot/dune.exe build dune.install --release --profile dune-bootstrap -j 15
# exit-code   1
# env-file    ~/.opam/log/dune-208893-44c9eb.env
# output-file ~/.opam/log/dune-208893-44c9eb.out
### output ###
# Error: _build/default/bin/dune.exe: Permission denied
# -> required by _build/default/bin/dune.exe
# -> required by _build/install/default/bin/dune
# -> required by _build/default/dune.install
```

When I try to upgrade to 3.8.0, 3.8.1, or 3.8.2, I get the error https://github.com/ocaml/dune/issues/8041. When I try to upgrade to 3.8.3, 3.9.0, or 3.9.1, I get this current error. https://github.com/ocaml/dune/pull/8049, which fixes the sendfile error and was included in 3.8.3, is probably the cause of the current error.

My Linux kernel version is `5.15.0-76-generic`, I am running Linux Mint 21.1.

### PR DESCRIPTION
**Pull request by emillon**
Fixes #8210

If the `sendfile` branch failed, it left an empty target file.
This file needs to be removed, otherwise the next `open` call can fail if the file is not writeable.

### CODE REVIEW

File: otherlibs/stdune/src/io.ml [hunk 1]
```diff
@@ -179,6 +179,7 @@ module Copyfile = struct
   let sendfile_with_fallback ?chmod ~src ~dst () =
     try sendfile ?chmod ~src ~dst ()
     with Unix.Unix_error (EINVAL, "sendfile", _) ->
+      Unix.unlink dst;
```
Comment (Alizter) [inline otherlibs/stdune/src/io.ml:182]: Is this the correct place to do this, or can it be done inside `sendfile` when it aborts?

Comment (Alizter) [reply otherlibs/stdune/src/io.ml:182]: I think there is some similar cleanup for src there too.

Comment (emillon) [reply otherlibs/stdune/src/io.ml:182]: I thought as well, but this happens in the prepare phase, not when `sendfile` itself fails.

Comment (rgrinberg) [inline otherlibs/stdune/src/io.ml:182]: What if this call fails?

The way we handle the sendfile fallback seems error prone in general. We should should move the fallback code directly into `Copyfile.sendfile` and only catch errors from the surrounding `sendfile` syscall.

This way we can resume the fallback with the existing open fd rather than deleting and re-opening.

Comment (emillon) [reply otherlibs/stdune/src/io.ml]: I just did that, let me know what you think.

**Review by rgrinberg — APPROVED** [review]
Thanks. This is indeed simpler.

**Review by Alizter — APPROVED** [review]
