### PR TITLE
fix: revert --diff-command behavior

### LINKED ISSUE #13891: Revert the behavior of --diff-command wrt to non-existent files
Do I understand correctly and this now means that the documentation in `doc/concepts/promotion.rst` doesn’t apply any more:

> - If ``<file1>`` doesn't exist, it will compare with the empty file.

(I had been using that behaviour in some places to make sure some expected output is indeed empty; that’s easy to fix but the documentation should be fixed if that changed on purpose)

_Originally posted by @shym in https://github.com/ocaml/dune/issues/13696#issuecomment-4088981261_

### PR DESCRIPTION
**Pull request by rgrinberg**
Pass non-existent files and directories to the --diff-command

### CODE REVIEW

File: src/dune_engine/print_diff.ml [hunk 1]
```diff
@@ -177,8 +177,8 @@ let prepare_with_labels
              (Path.to_string_maybe_quoted (Path.drop_optional_sandbox_root path2))
          ])
   in
-  let path1 = noent_to_dev_null path1 in
-  let path2 = noent_to_dev_null path2 in
+  let builtin_path1 = noent_to_dev_null path1 in
+  let builtin_path2 = noent_to_dev_null path2 in
```
Comment (shonfeder) [inline src/dune_engine/print_diff.ml]: Maybe these should be moved to line 215 so they are nearer to the scope where they are actually used?

**Review by shonfeder — APPROVED** [review]

**Comment by shonfeder** [comment]
This looks quite straight forward, and my superficial improvement needn't be addressed here.

But, @shym, would you like to try this to see if recovers the behavior you rely on, to ensure the patch release will restore the functionality?

You should be able to pin this change to give it a shot in your project with

```
opam pin dune.dev git@github.com:rgrinberg/jbuilder.git#push-qntvoltulvsp
```
