### PR TITLE
Tweak mkdir_p uses

### LINKED ISSUE #2158: Mkdir_p.exec: attempted to create unmanaged dir in Dune 1.9
This used to work fine in Dune 1.8.2 at least. I'm asking to run some programs from outside directories, but that shouldn't be a problem right? I'm passing in that outside directory here as the cmdstan env variable (I should probably capitalize it). Here's the dune file: https://github.com/stan-dev/stanc3/blob/e1f2c7359eca43c478cfba07bcdb7dab64c622e4/test/integration/good/code-gen/dune#L45 
```
halair ~/scm/stanc3 (jenkins/end-to-end) $ cmdstan=~/scm/clean/cmdstan dune runtest test/integration/good/code-gen/
Internal error, please report upstream including the contents of _build/log.
Description:
("Mkdir_p.exec: attempted to create unmanaged dir"
 (p (External /Users/xitrium/scm/clean/cmdstan)))
Backtrace:
Raised at file "src/stdune/exn.ml", line 40, characters 5-10
Called from file "set.ml", line 343, characters 35-38
Called from file "set.ml", line 343, characters 25-33
Called from file "src/stdune/set.ml" (inlined), line 36, characters 18-27
Called from file "src/build_system.ml", line 1451, characters 8-60
Called from file "src/fiber/fiber.ml", line 176, characters 6-11
Re-raised at file "src/stdune/exn.ml" (inlined), line 65, characters 38-65
Called from file "src/stdune/exn_with_backtrace.ml", line 17, characters 2-40
Called from file "src/fiber/fiber.ml", line 82, characters 8-15
Re-raised at file "src/stdune/exn.ml" (inlined), line 65, characters 38-65
Called from file "src/stdune/exn_with_backtrace.ml", line 17, characters 2-40
Called from file "src/fiber/fiber.ml", line 82, characters 8-15
Re-raised at file "src/stdune/exn.ml" (inlined), line 65, characters 38-65
Called from file "src/stdune/exn_with_backtrace.ml", line 17, characters 2-40
Called from file "src/fiber/fiber.ml", line 82, characters 8-15
Re-raised at file "src/stdune/exn.ml" (inlined), line 65, characters 38-65
Called from file "src/stdune/exn_with_backtrace.ml", line 17, characters 2-40
Called from file "src/fiber/fiber.ml", line 82, characters 8-15
Re-raised at file "src/stdune/exn.ml" (inlined), line 65, characters 38-65
Called from file "src/stdune/exn_with_backtrace.ml", line 17, characters 2-40
Called from file "src/fiber/fiber.ml", line 82, characters 8-15
                       
I must not segfault.  Uncertainty is the mind-killer.  Exceptions are
the little-death that brings total obliteration.  I will fully express
my cases.  Execution will pass over me and through me.  And when it
has gone past, I will unwind the stack along its path.  Where the
cases are handled there will be nothing.  Only I will remain.
```

### PR DESCRIPTION
**Pull request by rgrinberg**
If the directory that we're trying to create exists, then this is never an error.

We now forbid actions to create external or source dirs.

This should fix #2158

### CODE REVIEW

File: src/action_exec.ml [hunk 1]
```diff
@@ -108,7 +108,14 @@ let rec exec t ~ectx ~dir ~env ~stdout_to ~stderr_to =
...
     Fiber.return ()
   | Mkdir path ->
-    Path.mkdir_p path;
+    begin
+      if Path.is_in_build_dir path then
+        Path.mkdir_p path
+      else if Path.exists path then
+        ()
+      else
+        die "action attempted to create %a outside the build dir" Path.pp path
```
Comment (rgrinberg) [inline src/action_exec.ml]: It's a bit unfortunate that we can't give the user a proper location here, but passing the location along would be quite painful

**Comment by diml** [comment]
One sec, where does such an action come from? The `mkdir` action is not exposed in the action DSL.

**Comment by diml** [comment]
Additionally, the `check_mkdir` in `action_unexpanded.ml` should catch this

**Comment by rgrinberg** [comment]
> Additionally, the check_mkdir in action_unexpanded.ml should catch this

Ah yes, then we can just turn this check into an assert I think.

> One sec, where does such an action come from? The mkdir action is not exposed in the action DSL.

From the `chdir` I believe.

**Comment by aalekseyev** [comment]
Do you have a motivating example? At a first glance, it seems to me that it makes the logic more complicated for no obvious gain.

**Comment by rgrinberg** [comment]
> 

The error from the bug report indeed comes from `build_syste.ml`. In particular, `Mkdir_p.exec`:

```ocaml
  let exec p =
    if Path.is_managed p then
      Memo.exec def p
    else
      Exn.code_error "Mkdir_p.exec: attempted to create unmanaged dir"
        [ "p", Path.to_sexp p
        ]
```

So the first commit will fix the bug for sure.

The second commit was a preventative measure after reviewing more uses of `mkdir`. It's not necessary to fix the bug.

**Comment by rgrinberg** [comment]
> Do you have a motivating example? At a first glance, it seems to me that it makes the logic more complicated for no obvious gain.

The first commit fixes a bug reported in #2158 

The second commit can be omitted, but I think it would be useful to turn it into `Exn.code_error`

**Comment by aalekseyev** [comment]
It would be nice to have a test for this because I imagine that use case is very easy to forget about and break in the future.

**Comment by rgrinberg** [comment]
I'll add a test case.

**Comment by diml** [comment]
Turning it into a code error seems good. However, Dune should never try to create directories outside of the workspace. So I feel like we are hiding a real problem by silently ignoring external mkdirs when the external path exists.

**Comment by diml** [comment]
>> From the chdir I believe.

> These are handled in build_system.ml. It must be from somewhere else

Sorry, I read the code wrong, I thought this was touching action_exec.ml. However, looking at the stacktrace, you are right that this come from a chdir. What we should do is not call Mkdir_p for external chdirs. For instance, we could replace `Action.chdirs` by `Action.managed_chdirs` that would only return managed paths.

**Comment by rgrinberg** [comment]
>  What we should do is not call Mkdir_p for external chdirs. For instance, we could replace Action.chdirs by Action.managed_chdirs that would only return managed paths.

Managed? If we're restricting this, I think we should go all the way and only allow build dirs. Chdir'ing into the source dir seems dangerous to me.

Just to confirm: #2158 is not considered to be a regression, and that we indeed don't allow to chdir into external paths.

**Comment by rgrinberg** [comment]
I removed the "fix" which ignored the `mkdir_p` on external dirs when the dir already existed. All that remains is the assertion that we're only creating a build dir in the action. I think we can safely merge that.

**Comment by diml** [comment]
Seems good to me
