### PR TITLE
Don't crash when trimming while the cache directory does not exist.

### LINKED ISSUE #3204: dune cache trim crashes when the cache directory does not exists
Given an empty dune cache directory, dune cache trim crashes with the following error message:
```
$ mkdir -p ~/.cache/dune
$ ls ~/.cache/dune
$ dune --version
2.3.1
$ dune cache trim --size=100GB
Error: exception Sys_error("/home/opam/.cache/dune/db/v2/files: No such file or directory")
Backtrace:
Raised by primitive operation at file "src/dune_cache/dune_cache.ml", line 111, characters 38-73
Called from file "src/dune_cache/dune_cache.ml", line 452, characters 14-36
Called from file "bin/cache_daemon.ml", line 70, characters 38-59
Called from file "src/stdune/result.ml" (inlined), line 26, characters 12-15
Called from file "src/stdune/result.ml" (inlined), line 59, characters 20-29
Called from file "bin/cache_daemon.ml", line 63, characters 4-434
Called from file "bin/cache_daemon.ml", line 142, characters 24-50
Called from file "vendor/cmdliner/src/cmdliner_term.ml", line 25, characters 19-24
Called from file "vendor/cmdliner/src/cmdliner.ml", line 30, characters 14-21
Called from file "vendor/cmdliner/src/cmdliner.ml", line 146, characters 9-16
Called from file "vendor/cmdliner/src/cmdliner.ml", line 176, characters 18-36
Called from file "vendor/cmdliner/src/cmdliner.ml", line 312, characters 20-46
Called from file "bin/main.ml", line 240, characters 10-51
I must not segfault.  Uncertainty is the mind-killer.  Exceptions are
the little-death that brings total obliteration.  I will fully express
my cases.  Execution will pass over me and through me.  And when it
has gone past, I will unwind the stack along its path.  Where the
cases are handled there will be nothing.  Only I will remain.
```
cc @mefyl

### PR DESCRIPTION
**Pull request by mefyl**
Fix #3204.

### CODE REVIEW

File: src/cache/local.ml [hunk 1]
```diff
@@ -140,9 +140,14 @@ module Metadata_file = struct
...
 end
 
-let path_files cache = Path.relative cache.root "files"
+let path_ cache d =
+  let res = Path.relative cache.root d in
+  Path.mkdir_p res;
+  res
 
-let path_meta cache = Path.relative cache.root "meta"
+let path_files cache = path_ cache "files"
```
Comment (diml) [inline src/cache/local.ml]: Doing a system call every-time in such a function seems not very efficient. Could it be done at some initialisation stage?
