### PR TITLE
fix(rev_store): only negotiate with relevant tips

### LINKED ISSUE #13671: rev_store: negotiate only with relevant tips
Following up from #13323 and #13659, we should modify the rev_store so that it only negotiates using relevant tips from the remote in question. Currently we send all references, even unrelated ones, which is wasteful. There is also a privacy angle, but I find this less convincing as we are only sharing hashes.

### PR DESCRIPTION
**Pull request by Alizter**
As discussed in #13671, we restrict how we negotiate from the rev_store to a server to use only the relevant tips.

- Fixes #13671

This is done by name spacing the recorded references by (the hash of) their URL. This way we can provide only the relevant references during negotiation.

This should both speed up negotiation (and hence downloads) and avoid unnecessary communication of rev_store contents.

`--negotiation-tip` is an argument that was introduced in the minimum supported Git version that we currently have.

I've updated the doc/dev/rev_store.md about this new behaviour.

### CODE REVIEW

File: src/dune_pkg/rev_store.ml [hunk 1]
```diff
@@ -763,17 +765,25 @@ let fetch_allow_failure ~env repo ~url obj =
     >>= function
     | true -> Fiber.return `Fetched
     | false ->
+      let negotiation_ref_prefix =
+        Dune_digest.string url |> Dune_digest.to_string |> sprintf "refs/dune-pkg/%s"
```
Comment (rgrinberg) [inline src/dune_pkg/rev_store.ml]: I don't get the point of using cryptographic hashing here. Don't you just need to escape some characters?

Comment (Alizter) [reply src/dune_pkg/rev_store.ml]: This seemed easier than escaping. What do you suggest should happen to `git+https://github.com/ocaml/foo.git`?

Comment (rgrinberg) [reply src/dune_pkg/rev_store.ml]: I don't really care. Any reversible escaping scheme sounds fine to me. At first glance, I would just map all invalid chars to underscores. Cryptographic hashing might be easier, but it also makes things much harder to debug than is necessary. So let's use a reversible, and preferably readable scheme.

**Review by shym — APPROVED** [review]
This looks good to me, thank you!

**Review by rgrinberg — APPROVED** [review]
