### PR TITLE
[stdune] Support for OCaml 4.08 `List.t` type.

### LINKED ISSUE #1559: [compat] Fix build with OCaml 4.08 `trunk`
As of today, Dune build is broken with OCaml `trunk` "4.08" as the upstream `List` module declares a `List.t` type, conflicting with the one in Dune.

It would be great if a compat fix could be implemented so we could use Dune with `trunk`. Note that I am not familiar with the current schedule of OCaml so requesting this fix may be premature [imagine the `List.t` addition gets reverted upstream].

### PR DESCRIPTION
**Pull request by ejgallego**
We piggyback on ocaml/ocaml#1892 "Allow shadowing of items coming from
an include" to support OCaml 4.08 and avoid a conflict with OCaml's
new `List.t`.

Thanks to @diml for pointing this out.

Note the comment from @diml regarding `Stdune.List`:

> Ideally, we shouldn't use include and manually import the function we use in dune. That would make the code more robust against upstream changes.

This is left to future work.

### CODE REVIEW

File: src/stdune/list.ml [hunk 1]
```diff
@@ -1,7 +1,7 @@
-type 'a t = 'a list
-
+open ListType
 include ListLabels
 
+type nonrec 'a t = 'a t
```
Comment (diml) [inline src/stdune/list.ml]: I was surprised that this works, given that the type is still defined twice in this module (once through the include and once here). Then I remembered that this is a new feature in 4.08, so simply switching the order of the `include` and `type 'a t = 'a list` should be enough.

**Review by ghost — CHANGES_REQUESTED** [review]

**Review by ghost — APPROVED** [review]

**Comment by ejgallego** [comment]
> Looks good, feel free to merge :)

Thanks :D ! Do you use the github interface for merging?

**Comment by diml** [comment]
Yep, except when we need to amend something before merging

**Comment by ejgallego** [comment]
Merged! Thanks for all the help!
