### PR TITLE
fix: Downloading local repo doesn't work

### LINKED ISSUE #7952: Fetching local repositories doesn't work
It seems this is triggering an error in `OpamRepository.pull_file` where it fails to check out a git repo. Will need to investigate the failure.

_Originally posted by @Leonidas-from-XIV in https://github.com/ocaml/dune/pull/7802#discussion_r1210339089_

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
The OPAM API acts differently between `pull_file` (downloads a file and puts it in the desired location) and `pull_tree` (downloads a file or VCS repo, checks it out and unpacks it), so it needs to use the right function call depending on what we want to do.

Closes #7952.

### CODE REVIEW

File: src/dune_pkg/fetch.ml [hunk 1]
```diff
@@ -90,13 +105,10 @@ let fetch ~checksum ~target url =
                    ("checksum", `String (Checksum.to_string checksum)) :: args))
           }))
   in
-  (* hashes have to be empty otherwise OPAM deletes the file after
```
Comment (rgrinberg) [inline src/dune_pkg/fetch.ml:93]: Where did this comment go?

Comment (Leonidas-from-XIV) [reply src/dune_pkg/fetch.ml:93]: Upward into where it constructs the `pull` closure. It actually applies to both branches so I pulled it into a single identifier with the comment in 52548b92e.

**Review by gridbugs — APPROVED** [review]
