### PR TITLE
fix(init): parse --public as a public name

### LINKED ISSUE #7108: Dune init's `--public` doesn't allow dashes
## Expected Behavior
Dune init's `--public` can take names with dashes in them.

## Actual Behavior
An error explaining only characters `[a-zA-Z0-9_]` are allowed.

## Reproduction

```shell
$ dune init lib mirage_pair --public mirage-pair
dune: option '--public': invalid component name `mirage-pair'
      Library names must be non-empty and composed only of the
      following
      characters: 'A'..'Z', 'a'..'z', '_' or '0'..'9'.
Usage: dune init library [OPTION]… NAME [PATH]
Try 'dune init library --help' or 'dune --help' for more information.
```

## Specifications

- Version of `dune` (output of `dune --version`): 3.6.1
- Version of `ocaml` (output of `ocamlc --version`) 4.14.0
- Operating system (distribution and version): debian 11.6

### PR DESCRIPTION
**Pull request by emillon**
Fixes #7108

### CODE REVIEW

File: bin/dune_init.ml [hunk 1]
```diff
@@ -195,6 +195,64 @@ module Init_context = struct
   ;;
 end
 
+module Public_name = struct
```
Comment (rgrinberg) [inline bin/dune_init.ml:198]: Is this not the same as `Lib_name`?

Comment (emillon) [reply bin/dune_init.ml:198]: not quite since it's using `Opam_compatible` and there's no `Private` version. but I'd like to make that a bit closer. maybe I can use the Lib_name parser and validate after the fact.

Comment (emillon) [reply bin/dune_init.ml:198]: I did that, I think it looks better indeed.

**Review by rgrinberg — APPROVED** [review]
