### PR TITLE
Attempt to fix #4097

### LINKED ISSUE #4097: Fix exponential blow up in Memo
Memoized fiber functions exhibit an exponential blow up in exceptions if they raise. The test case in https://github.com/ocaml/dune/pull/4036 demonstrates this. There were a couple of suggestions on how to fix this, but I'm having trouble finding them in the bug tracker. In any case, we must fix this before releasing 2.8

### PR DESCRIPTION
**Pull request by rgrinberg**
This tries to implement @snowleopard's idea of saving the exceptions in a set

### CODE REVIEW

**Review by aalekseyev — APPROVED** [review]
Looks good.

File: test/expect-tests/memo/memoize_tests.ml [hunk 1]
```diff
@@ -622,21 +621,13 @@ let%expect_test "error handling and async diamond" =
...
-    f 2 = Error
-            [ { exn = "(Failure \"reached 0\")"; backtrace = "" }
-            ; { exn = "(Failure \"reached 0\")"; backtrace = "" }
-            ; { exn = "(Failure \"reached 0\")"; backtrace = "" }
-            ; { exn = "(Failure \"reached 0\")"; backtrace = "" }
-            ]
+    f 2 = Error [ { exn = "(Failure \"reached 0\")"; backtrace = "" } ]
     |}]
 
 (* XXX aalekseyev: The exceptions get duplicated here, so the total number of
```
Comment (snowleopard) [inline test/expect-tests/memo/memoize_tests.ml:633]: An outdated comment.

File: src/memo/memo.ml [hunk 2]
```diff
@@ -793,6 +797,11 @@ end = struct
     in
     (* update the output cache with the correct value *)
     let deps = List.rev running_state.deps_so_far.deps_reversed in
+    let res =
+      match res with
+      | Ok a -> Ok a
+      | Error exns -> Error (Value.Async (Exn_with_backtrace.Set.of_list exns))
```
Comment (snowleopard) [inline src/memo/memo.ml:803]: For a moment I got confused because I didn't understand where we filter out duplicate errors. I guess this happens here, when we turn the list that has duplicates into a set. Perhaps, it's worth adding a comment here that this is what happens here.

**Review by snowleopard — APPROVED** [review]
Looks good to me too, but see a couple of comments about comments.
