### PR TITLE
Drastically simplify output when packages are missing in solve

### LINKED ISSUE #10987: pkg: inscrutable error when depending on a non-existent package
## Expected Behavior

If the dune-project file mentions a package that doesn't exist in the `depends` field, I'd expect an error saying so when calling `dune pkg lock`.

## Actual Behavior

Instead, dune prints screenfuls of confusing information that mention various problems, almost all of which is irrelevant to the problem (but seems like it could be relevant).

## Reproduction

Given a dune-project with:

```
(lang dune 3.15)
(name abc)
(package
 (name abc)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends
   ocaml
   dune
   base
   re
   unix
   core
   core_unix
   ocamlformat
   ocamlformat-lib
 )
 (tags
  (topics "to describe" your project)))
```

I get this error when running `dune pkg lock`:

```sh
$ dune --version
"Dune Developer Preview: build 2024-09-28T01:30:13+00:00, git revision
17071ec30d10390badcb6cb1f6a43984b1be54a6"
$ dune pkg lock
Error: Unable to solve dependencies for the following lock directories:
Lock directory dune.lock:
Can't find all required versions.
Selected: base.v0.17.1 base-threads.base base-unix.base
          base_bigstring.v0.17.0 base_quickcheck.v0.17.0 bin_prot.v0.17.0
          capitalization.v0.17.0 cmdliner.1.3.0 core.v0.17.1
          core_kernel.v0.17.0 core_unix.v0.17.0 csexp.1.5.2
          dune-configurator.3.16.0 expect_test_helpers_core.v0.17.0
          fieldslib.v0.17.0 gel.v0.17.0 int_repr.v0.17.0
          jane-street-headers.v0.17.0 jst-config.v0.17.0 migration.dev
          num.1.5-1 ocaml.5.4.0 ocaml-config.3
          ocaml_intrinsics_kernel.v0.17.1 ocamlformat.0.26.2 parsexp.v0.17.0
          ppx_assert.v0.17.0 ppx_base.v0.17.0 ppx_bench.v0.17.0
          ppx_bin_prot.v0.17.0 ppx_cold.v0.17.0 ppx_compare.v0.17.0
          ppx_custom_printf.v0.17.0 ppx_diff.v0.17.0
          ppx_disable_unused_warnings.v0.17.0 ppx_enumerate.v0.17.0
          ppx_expect.v0.17.0 ppx_fields_conv.v0.17.0
          ppx_fixed_literal.v0.17.0 ppx_globalize.v0.17.0 ppx_hash.v0.17.0
          ppx_here.v0.17.0 ppx_ignore_instrumentation.v0.17.0
          ppx_inline_test.v0.17.0 ppx_jane.v0.17.0 ppx_let.v0.17.0
          ppx_log.v0.17.0 ppx_module_timer.v0.17.0 ppx_optcomp.v0.17.0
          ppx_optional.v0.17.0 ppx_pipebang.v0.17.0 ppx_sexp_conv.v0.17.0
          ppx_sexp_message.v0.17.0 ppx_sexp_value.v0.17.0 ppx_stable.v0.17.0
          ppx_stable_witness.v0.17.0 ppx_string.v0.17.0
          ppx_string_conv.v0.17.0 ppx_tydi.v0.17.0 ppx_typerep_conv.v0.17.0
          ppx_variants_conv.v0.17.0 ppxlib_jane.v0.17.1 re.1.12.0 seq.base
          sexp_pretty.v0.17.0 sexplib.v0.17.0 sexplib0.v0.17.0 spawn.v0.15.1
          splittable_random.v0.17.0 stdio.v0.17.0 time_now.v0.17.0
          timezone.v0.17.0 uopt.v0.17.0 variantslib.v0.17.0
          ocaml-base-compiler ocaml-base-compiler ocaml
- dune -> dune.3.16.0
    User requested = 3.17
- ocaml-base-compiler -> (problem)
    Rejected candidates:
      ocaml-base-compiler.5.2.0: Requires ocaml = 5.2.0
      ocaml-base-compiler.5.1.1: Requires ocaml = 5.1.1
      ocaml-base-compiler.5.1.0: Requires ocaml = 5.1.0
      ocaml-base-compiler.5.0.0: Requires ocaml = 5.0.0
      ocaml-base-compiler.4.14.2: Requires ocaml = 4.14.2
      ...
- ocamlformat-lib -> (problem)
    ocamlformat 0.26.2 requires = 0.26.2
    Rejected candidates:
      ocamlformat-lib.0.26.2: Requires ocaml >= 4.08 & < 5.3
      ocamlformat-lib.0.26.1: Incompatible with restriction: = 0.26.2
      ocamlformat-lib.0.26.0: Incompatible with restriction: = 0.26.2
      ocamlformat-lib.0.25.1: Incompatible with restriction: = 0.26.2
- ppxlib -> (problem)
    base_quickcheck v0.17.0 requires >= 0.28.0
    Rejected candidates:
      ppxlib.0.33.0: Requires ocaml >= 4.04.1 & < 5.3.0
      ppxlib.0.32.1: Requires ocaml >= 4.04.1 & < 5.3.0
      ppxlib.0.32.0: Requires ocaml >= 4.04.1 & < 5.2.0 & <> 5.1.0~alpha1
      ppxlib.0.31.0: Requires ocaml >= 4.04.1 & < 5.2.0 & <> 5.1.0~alpha1
      ppxlib.0.30.0: Requires ocaml >= 4.04.1 & < 5.2.0 & <> 5.1.0~alpha1
      ...
- typerep -> (problem)
    core v0.17.1 requires >= v0.17 & < v0.18
    Rejected candidates:
      typerep.v0.17.0: Requires ocaml >= 5.1.0 & < 5.3
      typerep.v0.16.0: Incompatible with restriction: >= v0.17 & < v0.18
      typerep.v0.15.0: Incompatible with restriction: >= v0.17 & < v0.18
      typerep.v0.14.0: Incompatible with restriction: >= v0.17 & < v0.18
      typerep.v0.13.0: Incompatible with restriction: >= v0.17 & < v0.18
      ...
- unix -> (problem)
    No known implementations at all
```

The real problem here is 

```
- unix -> (problem)
    No known implementations at all
```

but that's just one of many `problem` listed above. If `unix` is removed from the `depends` list, the command succeeds (because unix is in fact not a package, it's just a library in the ocaml package or something. Also if dune generated the depends list from the dune files, this confusion wouldn't need to exist in the first place).

### PR DESCRIPTION
**Pull request by ElectreAAS**
Fixes #10987.
When some packages are missing entirely, we only report that as that seems way more pressing than the wall of info about the state of the solver seen in the issue.

The fix was found while working on #11015, but is independent from it.

### CODE REVIEW

**Comment by v-gb** [comment]
Thanks, that'd be much more understandable.
The format of the list of missing packages seems a bit weird though. To me, one of these formats would make sense

```
  The following packages couldn't be found:
  - ocamlformat
  - whatever

  The following packages couldn't be found: ocamlformat, whatever

  The following packages couldn't be found: ocamlformat whatever
```

but it seems to be (from reading the code, I could be mistaken):

```
The following packages couldn't be found: - ocamlformat - whatever
```

**Comment by ElectreAAS** [comment]
You're right. Should be fixed now.

**Comment by Alizter** [comment]
If we are moving 0install to be our own library, we might as well just drop the messages being created in 0install and only have the data. We can then use our own Pp library to render the messages nicely.

**Comment by rgrinberg** [comment]
It might be independent from forking the solver, but I think we should finish forking the solver first. In general, we don't make changes in vendored repos without a lot of extra overhead (update scripts, maintaining commits in separate repos). If you fork the solver, you will avoid doing all that work in this PR.

**Comment by Leonidas-from-XIV** [comment]
Now that #11015 is merged this needs to be rebased and then we can proceed.

**Comment by ElectreAAS** [comment]
Rebased on main!

File: src/opam-0install/lib/solver.ml [hunk 1]
```diff
@@ -38,32 +38,48 @@ struct
...
     let pp_item f c = Fmt.pf f "- @[%a@]" (Diagnostics.Component.pp ~verbose) c in
-    Fmt.pf
-      f
-      "Selected: @[<hov>%a@]@,%a"
-      (Fmt.(list ~sep:sp) pp_short)
-      short
-      (Fmt.(list ~sep:cut) pp_item)
-      long
+    let pp_unknown f (role, _) = Fmt.pf f "@[%a@]" Solver.Output.Role.pp role in
+    let pp_normals f short long =
```
Comment (Leonidas-from-XIV) [inline src/opam-0install/lib/solver.ml:66]: What are "normals"? I think this would benefit from a better name.

**Review by Leonidas-from-XIV — COMMENTED** [review]
Thanks for taking care of this. Here some comments on the code.

File: src/opam-0install/lib/solver.ml [hunk 2]
```diff
@@ -38,32 +38,48 @@ struct
...
+        long
+    in
+    if unknowns = []
+    then pp_normals f short long
+    else
+      Fmt.pf
+        f
+        "The following packages couldn't be found: @[<h>%a@]"
+        Fmt.(list ~sep:sp pp_unknown)
+        unknowns
```
[the remark this answers is not in the document]
Comment (rgrinberg) [reply src/opam-0install/lib/solver.ml:82]: To make it work well with the rest of dune, we should get rid of `Fmt` in favor of `Pp`. So maybe it's not worth dwelling on this for now?

[the remark this answers is not in the document]
Comment (Leonidas-from-XIV) [reply src/opam-0install/lib/solver.ml:82]: Yes, I agree, but I didn't want to add unrelated stuff to the PR by asking for `Fmt` to be removed.

[the remark this answers is not in the document]
Comment (ElectreAAS) [reply src/opam-0install/lib/solver.ml]: I ended up removing `Fmt` in favor of good old `Format`. I briefly tried converting to `Pp`, but felt this was simpler.

[the remark this answers is not in the document]
Comment (rgrinberg) [reply src/opam-0install/lib/solver.ml]: Note that both `Fmt` and `Format` suffer from the same problem: they don't allow the errors to be serialized. That is why we're using Pp.

[the remark this answers is not in the document]
Comment (ElectreAAS) [reply src/opam-0install/lib/solver.ml]: Oooooooh _that's_ why `Pp` is used!
It wasn't painless, but I finally moved everything to `Pp`, so we can enjoy better errors :)

**Comment by ElectreAAS** [comment]
Moving to `Pp` introduces a fair amount of noise in the form of `type t -> type 'tag t` to accommodate for [`Pp`'s notion of tags](https://ocaml.org/p/pp/latest/doc/Pp/index.html#tags) that are not used at the moment. We could stylize solver failures further with them. What do you think?

File: src/0install-solver/diagnostics.ml [hunk 3]
```diff
@@ -27,53 +26,50 @@ struct
       | Restricts of Model.Role.t * Model.impl * Model.restriction list
       | Feed_problem of string
 
-    let pp f = function
-      | UserRequested r -> pf f "User requested %s" (format_restrictions [ r ])
+    let pp = function
+      | UserRequested r -> Pp.verbatimf "User requested %s" (format_restrictions [ r ])
```
[the remark this answers is not in the document]
Comment (Alizter) [reply src/0install-solver/diagnostics.ml:30]: Basically, anywhere you have `verbatim` replace it with `text`.

[the remark this answers is not in the document]
Comment (ElectreAAS) [reply src/0install-solver/diagnostics.ml:30]: That's what I did initially, but I ended up with this kind of formatting:
```
Rejected
  candidates:
  bar.0.0.1:
  In
  same
  conflict
  class
  (ccc)
  as
  foo
```

I expect a fair amount of these messages are wrapped in a `vbox` at some point, which means that basically all spaces in `text` are used as line breaks

File: src/0install-solver/diagnostics.ml [hunk 4]
```diff
@@ -27,53 +26,50 @@ struct
...
+      | Feed_problem msg -> Pp.verbatim msg
     ;;
   end
 
   (** Represents a single interface in the example (failed) selections produced by the solver.
       It partitions the implementations into good and bad based (initially) on the split from the
       impl_provider. As we explore the example selections, we further filter the candidates. *)
   module Component = struct
-    type rejection_reason =
+    type 'tag rejection_reason =
```
Comment (Alizter) [inline src/0install-solver/diagnostics.ml:49]:
```suggestion
    type 'tag rejection_reason =
```
No need to do this, the tag will always be `Stdune.User_message.Style.t`.

Comment (Alizter) [reply src/0install-solver/diagnostics.ml:49]: It's a bit tricky to do, but replace everything with 'tag that you introduced with `Stdune.User_message.Style.t`. We can look at cleaning up that name at another time using our `Import` module, but there will be too many conflicts for now. Sometimes there is a `_` instead of a `'tag` in the interface just so that you are aware. Also any `unit Pp.t` can be taken as `Stdune.User_message.Style.t Pp.t` but that seems to only be for debug stuff.

File: src/0install-solver/diagnostics.ml (hunk 3 above)
[the remark this answers is not in the document]
Comment (Alizter) [reply src/0install-solver/diagnostics.ml:30]: That indicates that you have too few boxes around and you have some `vbox`es that need some more thought. I will give you some help once I've read some of the messages.

File: src/0install-solver/diagnostics.ml (hunk 4 above)
Comment (ElectreAAS) [reply src/0install-solver/diagnostics.ml:49]: If `'tag` is always `Stdune.User_message.Style.t`, why is it parameterized? We could have a type alias in stdune if it's always the same

File: src/0install-solver/diagnostics.ml [hunk 5]
```diff
@@ -424,17 +427,16 @@ struct
...
 
   (** Return a message explaining why the solve failed. *)
   let get_failure_reason ?(verbose = false) result =
     let+ reasons = of_result result in
-    Format.asprintf
-      "Can't find all required implementations:@\n@[<v0>%a@]"
-      (pp_rolemap ~verbose)
-      reasons
+    Pp.verbatim "Can't find all required implementations:"
+    ++ Pp.newline
```
Comment (Alizter) [inline src/0install-solver/diagnostics.ml:439]: This should be a break with a vbox surrounding the Pp so that it is formatted the correct way. You might need a `hovbox` on the sentence above.

File: src/0install-solver/sat.ml [hunk 6]
```diff
@@ -200,17 +199,13 @@ module Make (User : USER) = struct
   ;;
 
   (* For nicer log_debug messages *)
-  let name_lit f (sign, var) =
+  let name_lit (sign, var) =
     match sign with
-    | Pos -> User.pp f var.obj
-    | Neg -> Format.fprintf f "not(%a)" User.pp var.obj
+    | Pos -> User.pp var.obj
+    | Neg -> Pp.text "not(" ++ User.pp var.obj ++ Pp.char ')'
```
Comment (Alizter) [inline src/0install-solver/sat.ml:205]: textf

File: src/0install-solver/diagnostics.ml (hunk 4 above)
Comment (Alizter) [reply src/0install-solver/diagnostics.ml:49]: It's not always the same, sometimes it carries style information like color and italics etc. For the output of the solver none of this is relevant and we should try to keep types simple rather than making them needlessly polymorphic.

**Comment by Alizter** [comment]
Try something like this:

```
Pp.vbox (Pp.concat [ Pp.paragraph "Sentece describing something, but not breaking:"; Pp.enumerate ~f candidates])
```
The vbox will mean each entry is formatted vertically, and the Pp.paragraph will take care of wrapping text more generally.

File: src/0install-solver/sat.ml (hunk 6 above)
Comment (ElectreAAS) [reply src/0install-solver/sat.ml:205]: I don't see how one would use `Pp.textf` here. If we keep `User.pp` as `User.t -> _ Pp.t`, then the `%a` conversion does not work.
If we wish to use it as a string that's possible, but we loop back to removing a lot of Pp.t everywhere

Comment (ElectreAAS) [reply src/0install-solver/sat.ml:205]: Maybe my regexp game isn't strong enough, but I can't find a single use of `Pp.textf "...%a"` in the entire dune codebase or [anywhere else in the OCaml world](https://sherlocode.com/?q=Pp.textf%20%22%5C.%5C*%25a), even though it is technically possible, it just requires a very weirdly typed conversion function (`unit -> <your type, here User.t> -> string`)

Comment (Alizter) [reply src/0install-solver/sat.ml:205]: OK never mind about this then, there are better things to focus on.

File: src/0install-solver/diagnostics.ml (hunk 4 above)
Comment (ElectreAAS) [reply src/0install-solver/diagnostics.ml]: Should be better now.
I couldn't shadow the long `Stdune.User_message.Style.t` everywhere, so it spills out a little in `dune_pkg`, but that seems fine to me

**Review by Leonidas-from-XIV — COMMENTED** [review]
With all the `Pp` changes I feel like it would be a better solution to split this into a PR that migrates to `Pp` and a PR that implements the output improvement. At the moment the latter is completely dominated by a lot of changes due to migrating to `Pp`.

File: src/0install-solver/diagnostics.ml [hunk 7]
```diff
@@ -282,7 +288,9 @@ struct
   let find_component_ex role report =
     match RoleMap.find_opt role report with
     | Some c -> c
-    | None -> failwith (Format.asprintf "Can't find component %a!" format_role role)
+    | None ->
+      Stdune.User_error.raise
```
[the remark this answers is not in the document]
Comment (Alizter) [reply src/0install-solver/diagnostics.ml:292]: I also thought the same, but there is more work to be done since it uses stdlib `List` functions.

[the remark this answers is not in the document]
Comment (ElectreAAS) [reply src/0install-solver/diagnostics.ml:292]: I already started working on something like this in #11121

**Comment by ElectreAAS** [comment]
> With all the `Pp` changes I feel like it would be a better solution to split this into a PR that migrates to `Pp` and a PR that implements the output improvement. At the moment the latter is completely dominated by a lot of changes due to migrating to `Pp`.

You are right, as always :) See #11126 for that new PR

**Review by Leonidas-from-XIV — APPROVED** [review]
