### PR TITLE
uninstall: do not fail if directories are non-empty

### LINKED ISSUE #5542: Dune errors when trying to remove non-empty man directory
## Expected Behavior

When uninstalling a package containing man pages, dune should accept that the manpage directories can be non-empty after removing the manpages from the project being uninstalled.

## Actual Behavior

When uninstalling a package containing man pages, dune sometimes errors out, with a message stating that some directories, such as `<prefix>/man/man1`, are non-empty and that the user should manually delete it. This is a problem since such directories are shared by all tools being installed in a prefix, and thus there are perfectly good reasons for such directories to not be empty (even if during installation dune had to create some of these directories).

## Reproduction

- PR with a reproducing test: #5541 

## Specifications

- Version of `dune` (output of `dune --version`): 3.0.3
- Version of `ocaml` (output of `ocamlc --version`): 4.13.1
- Operating system (distribution and version): Archlinux

## Additional information 

This issue makes the CI of alt-ergo fail (see e.g. https://github.com/OCamlPro/alt-ergo/runs/5816456115?check_suite_focus=true ).

### PR DESCRIPTION
**Pull request by nojb**
Fixes #5542

### CODE REVIEW

File: bin/install_uninstall.ml [hunk 1]
```diff
@@ -295,10 +301,20 @@ module File_ops_real (W : Workspace) : File_operations = struct
...
+               [ Pp.textf "Directory %s is not empty, cannot delete (ignoring)."
+                   dir
+               ])
+        else
+          User_error.raise
+            [ Pp.textf "Please delete non-empty directory %s manually." dir ]
+
+  let try_remove_dir_if_empty dir = remove_dir_if_empty ~try_:true dir
+
+  let remove_dir_if_empty dir = remove_dir_if_empty ~try_:false dir
```
Comment (rgrinberg) [inline bin/install_uninstall.ml:317]: I wonder if these aliases that just partially apply `try_` are useful for readability. A flag like `on_non_empty:[Fail | Warn]` instead of `try_` and without the aliases would be shorter and just as readable.

**Review by rgrinberg — APPROVED** [review]

File: bin/install_uninstall.ml (hunk 1 above)
Comment (nojb) [reply bin/install_uninstall.ml]: Good idea. I pushed a commit in this direction. Do you mind taking another look? Thanks!

**Review by rgrinberg — APPROVED** [review]
Looks good. Could you rebase and re-run the tests. I merged Gbury's test case.

**Comment by nojb** [comment]
> Looks good. Could you rebase and re-run the tests. I merged Gbury's test case.

Done, thanks!
