### PR TITLE
fix: `(select ..)` field + `(include_subdirs ..)`

### LINKED ISSUE #4383: Alternative dependencies do not work with `include_subdirs unqualified`
This is a similar issue to https://github.com/ocaml/dune/issues/4381. It looks like any file used for alternative dependency need to be at the root even when using `include_subdirs unqualified`

### LINKED ISSUE #12450: Can `include_subdirs qualified` and `select` work together?
I'm trying to use dune's `include_subdirs qualified` and the `select` target to define [alternative dependencies/optional modules](https://dune.readthedocs.io/en/latest/reference/library-dependencies.html#alternative-dependencies).

I have tried creating `lib/foo/file.enabled.ml`, `lib/foo/file.disabled.ml`, and using a dune file like 
```
(library
 (public_name dune_qualified_select)
 (name main)
 (libraries
   (select foo.file.ml from
    (utop -> foo.file.enabled.ml)
    ( -> foo.file.disabled.ml )
   )
 )
)

(include_subdirs qualified)
(dirs :standard)
```

I keep hitting errors like `Error: No rule found for bin/foo.file.enabled.ml`. I also tried creating `lib/foo/file/disabled.ml` for example, but the issue is the same. How are those two options supposed to work together?

Wondering if this is somehow related to #11119? I know there are reported issue for the unqualified mode too (#4383).

### PR DESCRIPTION
**Pull request by anmonteiro**
fixes #12450
fixes #4383

- Moves inference of modules generated by `(select ..)` rules to `Ml_sources`, which takes include_subdirs into account

### CODE REVIEW

File: src/dune_rules/ml_sources.ml [hunk 1]
```diff
@@ -590,6 +591,182 @@ let make_lib_modules
...
+                 Path.Local.parent_exn descendant
+                 |> Path.Local.explode
+                 |> List.map ~f:Module_name.of_string
+             in
+             let basename, ext = Path.Build.basename dst |> Filename.split_extension in
+             let module_name = Module_name.parse_string_exn (loc, basename) in
+             let m =
+               let dialect, ml_kind =
+                 (* TODO(anmonteiro): validate *)
+                 Dialect.DB.find_by_extension dialects ext |> Option.value_exn
```
Comment (Alizter) [inline src/dune_rules/ml_sources.ml]: Can we add a test for this? This just raises a code error atm I believe.

**Comment by Alizter** [comment]
Is this also fixing the `qualified` case?

**Comment by Alizter** [comment]
The issue for the unqualified case is here
- https://github.com/ocaml/dune/issues/4383

**Comment by anmonteiro** [comment]
Thank you. This will also fix https://github.com/ocaml/dune/pull/13174, which will show in the diff once rebased.

File: test/blackbox-tests/test-cases/select-field/select-unqualified.t [hunk 2]
```diff
@@ -36,16 +36,43 @@ correctly. This is a bug.
   > (library
   >  (name foo)
   >  (libraries
-  >   (select bar.ml from
+  >   (select sub/bar.ml from
```
Comment (Alizter) [inline test/blackbox-tests/test-cases/select-field/select-unqualified.t:43]: Can we also add a select for an interface file and test that is working?

File: src/dune_rules/ml_sources.ml [hunk 3]
```diff
@@ -590,6 +591,182 @@ let make_lib_modules
...
+              match include_subdirs with
+              | Include_subdirs.No | Include Unqualified -> []
+              | Include Qualified ->
+                let loc =
+                  Path.build dir |> Path.drop_optional_build_context |> Loc.in_dir
+                in
+                List.map path_to_root ~f:(fun m -> Module_name.parse_string_exn (loc, m))
+            in
+            Memo.parallel_map stanzas ~f:(fun stanza ->
+              let enabled_if =
```
Comment (Alizter) [inline src/dune_rules/ml_sources.ml]: This is also done in 872. Can we keep these in sync?

File: test/blackbox-tests/test-cases/select-field/select-relative-parent.t [hunk 4]
```diff
@@ -22,5 +22,6 @@ paths
   > let () = print_endline "Test: Unix was not found!"
   > EOF
 
-  $ dune build foo.cma 2>&1 | grep "must not crash"
-  I must not crash.  Uncertainty is the mind-killer. Exceptions are the
+  $ dune build foo.cma
+  Error: path outside the workspace: ../bar.unix.ml from .
```
Comment (Alizter) [inline test/blackbox-tests/test-cases/select-field/select-relative-parent.t:29]: Maybe add a location for this error otherwise its not clear.

File: src/dune_rules/ml_sources.ml [hunk 5]
```diff
@@ -590,6 +591,182 @@ let make_lib_modules
         ~wrapped )
 ;;
 
+module Generated_modules = struct
+  let merge_two a b =
```
Comment (Alizter) [inline src/dune_rules/ml_sources.ml:784]: Maybe worth adding a comment that the conflicts are caught earlier on. I tried to get this to silently replace a module coming from ocamllex but it seems to be validated elsewhere. In that case, maybe this should even be a code error?

File: test/blackbox-tests/test-cases/select-field/select-relative-parent.t (hunk 4 above)
Comment (Alizter) [inline test/blackbox-tests/test-cases/select-field/select-relative-parent.t:29]: Also, will this work for a path inside the workspace but outside of the dir? Doesn't seem so:
```
  $ dune build lib/foo.cma
  File "dune", line 5, characters 12-36:
  5 |    (unix -> alternatives/bar.unix.ml)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  Error: The format for files in this select branch must be bar.{name}.ml
  File "lib/dune", line 5, characters 12-36:
  5 |    (unix -> alternatives/bar.unix.ml)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  Error: The format for files in this select branch must be bar.{name}.ml
  [1]
```
this error message is a bit confusing in this case.

**Review by Alizter — DISMISSED** [review]

File: src/dune_rules/ml_sources.ml (hunk 1 above)
Comment (anmonteiro) [reply src/dune_rules/ml_sources.ml]: [lib-errors.t](https://github.com/ocaml/dune/tree/main/test/blackbox-tests/test-cases/lib-errors.t) tests this case.

File: test/blackbox-tests/test-cases/select-field/select-relative-parent.t (hunk 4 above)
Comment (anmonteiro) [reply test/blackbox-tests/test-cases/select-field/select-relative-parent.t:29]: That's correct. The path will follow the module group rules for consistency: I agree there's room to make this error better, will add in a follow-up PR.

Comment (anmonteiro) [reply test/blackbox-tests/test-cases/select-field/select-relative-parent.t:29]: I added better validation and left room to make the error message a bit better when I've worked more with this.

File: src/dune_rules/ml_sources.ml (hunk 5 above)
Comment (anmonteiro) [reply src/dune_rules/ml_sources.ml:784]: I added a comment explaining what `merge_two` is doing: sometimes we need to merge 2 distinct modules, e.g. one `.ml`-generated file and a user-written `.mli`: [this test](https://github.com/ocaml/dune/blob/main/test/blackbox-tests/test-cases/ocamllex/ocamllex-intf.t) exercises it.

File: src/dune_rules/ml_sources.ml [hunk 6]
```diff
@@ -758,173 +1027,86 @@ let modules_of_stanzas =
...
-    let modules = merge_parser_targets ~ocamllexes ~ocamlyaccs ~menhirs modules in
-    Memo.parallel_map dirs ~f:(fun (_, stanzas, _) ->
-      Memo.parallel_map stanzas ~f:(fun stanza ->
-        let enabled_if =
-          match Stanza.repr stanza with
-          | Library.T lib -> lib.enabled_if
-          | Tests.T tests -> tests.exes.enabled_if
-          | Executables.T exes -> exes.enabled_if
-          | Melange_stanzas.Emit.T mel -> mel.enabled_if
-          | _ -> Blang.true_
```
Comment (Alizter) [inline src/dune_rules/ml_sources.ml:876]: hmm this case used to be true_ but I'm trying to understand if that makes a difference here.

Comment (anmonteiro) [reply src/dune_rules/ml_sources.ml:876]: I don't think there's a difference. It's just an earlier return.

File: src/dune_rules/ml_sources.ml [hunk 7]
```diff
@@ -672,6 +673,274 @@ let make_lib_modules
...
+                  | Some (dialect, ml_kind) ->
+                    let file = Module.File.make dialect (Path.build dst) in
+                    let module_path = Nonempty_list.(base_path @ [ module_name ]) in
+                    (match ml_kind with
+                     | Ml_kind.Impl -> Left (module_path, (loc, file))
+                     | Intf -> Right (module_path, (loc, file)))
+                  | None ->
+                    User_error.raise
+                      ~loc
+                      [ Pp.text "No solution found for this select form." ])))
```
Comment (Alizter) [inline src/dune_rules/ml_sources.ml:754]: What about "Unrecognised file extension in select form."? I am not sure what solution means in this context.

**Comment by Alizter** [comment]
```

  $ cat > dune-project <<EOF
  > (lang dune 3.22)
  > EOF

  $ cat > dune <<EOF
  > (include_subdirs qualified)
  > (library
  >  (name foo)
  >  (libraries
  >   (select foo-bar/baz.ml from
  >    (unix -> foo-bar/baz.unix.ml)
  >    (!unix -> foo-bar/baz.nounix.ml))))
  > EOF

  $ mkdir -p foo-bar
  $ cat > foo-bar/baz.unix.ml <<EOF
  > let msg = "unix"
  > EOF
  $ cat > foo-bar/baz.nounix.ml <<EOF
  > let msg = "no unix"
  > EOF

  $ cat > foo.ml <<EOF
  > let () = print_endline Foo_bar.Baz.msg
  > EOF
```
should exercise the module validation in the select form directories.

**Review by Alizter — APPROVED** [review]

**Comment by anmonteiro** [comment]
thank you. I added an extended version of that test in #13187, and will show in this diff how the validation errors improve.
