### PR TITLE
Fix `dune install --create-install-files` not being able to overwrite opam files

### LINKED ISSUE #12540: [pkg] Read-only files cause `caqti` build to fail
## Expected Behavior

Since #12519, Dune can't build `caqti` with Package management anymore. Previously, the code was building correctly. My bet is that the `caqti` build plan tries to override a file that already exists. However, as it is read-only, it doesn't work anymore.

## Actual Behavior

It fails with the error:

```
File "dune.lock/caqti.pkg", line 7, characters 3-7:
7 |    dune
       ^^^^
Error: Logs for package caqti
Error: open(caqti.install): Permission denied
```

## Reproduction

1. Create the dune-project:
```sh
cat > dune-project <<EOF
(lang dune 3.20)
(package
  (name reproduce)
  (allow_empty)
  (depends ocaml caqti))
EOF
```
2. Lock the package
```sh
dune pkg lock
```
3. Build the dependencies to get the error:
```sh
DUNE_CONFIG__PKG_BUILD_PROGRESS=enabled dune build  @pkg-install
```

## Specifications

- Version of `dune` (output of `dune --version`): `main`
- Version of `ocaml` (output of `ocamlc --version`): `5.3.0`
- Operating system (distribution and version): Arch Linux

### PR DESCRIPTION
**Pull request by MisterDA**
See #12519 and #12465.
Fixes #12540.

### CODE REVIEW

File: bin/install_uninstall.ml [hunk 1]
```diff
@@ -680,7 +680,14 @@ let run
                 ~findlib_toolchain:(Context.findlib_toolchain context)
                 package
             in
-            Install.Entry.gen_install_file entries |> Io.write_file (Path.source fn))))
+            let contents = Install.Entry.gen_install_file entries in
+            let path = Path.source fn in
+            try Io.write_file path contents with
```
Comment (rgrinberg) [inline bin/install_uninstall.ml]: Could you try sharing this with the promotion code? You could perhaps add a helper to stdune.

Comment (MisterDA) [reply bin/install_uninstall.ml]: I've added `Io.overwrite_file`.

File: otherlibs/stdune/src/io.ml [hunk 2]
```diff
@@ -282,6 +282,18 @@ struct
     else with_file_out ~binary ?perm fn ~f:(fun oc -> output_string oc data)
   ;;
 
+  let overwrite_file ?binary fn data =
```
Comment (rgrinberg) [inline otherlibs/stdune/src/io.ml:285]: Thinking about this again, maybe you could just update the file atomically by creating a temp file and then renaming on top of this? That would allow us to avoid this changing the permissions of this file.

Comment (MisterDA) [reply otherlibs/stdune/src/io.ml:285]: Well I'm not so sure. [`Sys.rename`](https://ocaml.org/manual/5.4/api/Sys.html#VALrename) and [`Unix.rename`](https://ocaml.org/manual/5.4/api/Unix.html#VALrename) both note:

> Depending on the operating system, the metadata (permissions, owner, etc) of `dst` can either be preserved or be replaced by those of `src`.

In general it seems that `dst` gets the (data and) metadata from `src`.

There's also the `EXDEV` error to handle if the files are not on the same mounted filesystem.

Am I misunderstanding what you meant?

Comment (rgrinberg) [reply otherlibs/stdune/src/io.ml:285]: Hmm, on POSIX I'm pretty sure the metadata is replaced. I guess on Windows, it's not safe to rely on that.

> There's also the EXDEV error to handle if the files are not on the same mounted filesystem.

Yes, that would need a fallback.

In general though, I think complicating the code for atomic updates is well worth it.
