### PR TITLE
Scan the file-system lazily

### LINKED ISSUE #228: jbuild-ignore not respected when there's a nested symlink
Directory structure
```
jbuild (empty)
jbuild-ignore (contents: node_modules)
node_modules/
  bs-platform (is a symlink to ~/.nvm/versions/node/v7.6.0/lib/node_modules/bs-platform
```
in this case, jbuilder clearly does a ton of traversing, because it takes 15s to complete
```
$ time jbuilder build                                                                                                                                                                                                                                  Error: exception Stack overflow
Backtrace:
Raised at file "src/import.ml", line 414, characters 36-37
Called from file "src/future.ml", line 657, characters 6-29
Called from file "vendor/cmdliner/src/cmdliner_term.ml", line 27, characters 19-24
Called from file "vendor/cmdliner/src/cmdliner.ml", line 106, characters 32-39
Called from file "vendor/cmdliner/src/cmdliner.ml", line 136, characters 18-36
Called from file "vendor/cmdliner/src/cmdliner.ml", line 251, characters 22-48
Called from file "bin/main.ml", line 909, characters 10-51
jbuilder build  1.37s user 13.44s system 98% cpu 15.095 tota
```

If instead of a symlink, `bs-plaftorm` is copied into the `node_modules` directory, then there's no problem.
```
$ time jbuilder build
jbuilder build  0.02s user 0.03s system 20% cpu 0.267 total
```

It's weird to me that jbuilder would be looking inside of an ignored folder, and behavior would differ based on the contents

### LINKED ISSUE #718: Unscannable directory stopping the build
I encountered this when building using jbuilder and having some weird permissions on unrelated files/directories in the same directory as my sources.
```
$ jbuilder build test_server.exe
Error: exception Sys_error("output/queue: Permission denied")
Backtrace:
Raised by primitive operation at file "src/path.ml", line 431, characters 16-41
Called from file "src/file_tree.ml", line 51, characters 6-23
Called from file "src/file_tree.ml", line 89, characters 13-31
Called from file "list.ml", line 67, characters 20-23
Called from file "src/file_tree.ml", line 83, characters 6-232
Called from file "src/file_tree.ml", line 89, characters 13-31
Called from file "list.ml", line 67, characters 20-23
Called from file "list.ml", line 67, characters 32-39
Called from file "src/file_tree.ml", line 83, characters 6-232
Called from file "src/file_tree.ml", line 98, characters 13-37
Called from file "src/jbuild_load.ml", line 185, characters 14-62
Called from file "src/main.ml", line 42, characters 4-70
Called from file "bin/main.ml", line 674, characters 7-29
Called from file "vendor/cmdliner/src/cmdliner_term.ml", line 27, characters 19-24
Called from file "vendor/cmdliner/src/cmdliner.ml", line 106, characters 32-39
Called from file "vendor/cmdliner/src/cmdliner.ml", line 136, characters 18-36
Called from file "vendor/cmdliner/src/cmdliner.ml", line 251, characters 22-48
Called from file "bin/main.ml", line 1420, characters 10-51
```
Those files/directories were owned by root and jbuilder stopped scanning the files when encountering them.
```
$ ls -l output/
drwx------. 2 root root  4096 19 avril 13:04 crashes/
-rw-------. 1 root root 65536 19 avril 13:13 fuzz_bitmap
-rw-------. 1 root root   762 19 avril 13:13 fuzzer_stats
drwx------. 2 root root  4096 19 avril 13:12 hangs/
-rw-------. 1 root root  4062 19 avril 13:13 plot_data
drwx------. 3 root root  4096 19 avril 13:13 queue/
```
Even though those this problem has a good work-around with jbuild-ignore, it would probably be better to just issue a warning for unscannable directories and not completly crash the build.

### PR DESCRIPTION
**Pull request by diml**
This way ignored sub-directories are only traversed if the user explicitly references them in a jbuild file or on the command line.

Fix #228
Fix #718

### CODE REVIEW

File: src/file_tree.ml [hunk 1]
```diff
@@ -47,69 +54,86 @@ let ignore_file fn ~is_directory =
...
+        >>= fun parent ->
+        String.Map.find (Dir.sub_dirs parent) (Path.basename path)
+      with
+      | Some dir as res ->
+        Hashtbl.add t.dirs path dir;
+        res
+      | None ->
+        (* We don't cache failures in [t.dirs]. The expectation is
+           that these only happen when the user writes an invalid path
+           in a jbuild file, so there is no need to chache them. *)
```
Comment (rgrinberg) [inline src/file_tree.ml]: *cache
