### PR TITLE
fix(pkg): fallback to gpatch when patch isn't available

### LINKED ISSUE #12232: [pkg] gpatch vs patch in package management
Hello,

While trying to move build my project using the dune developer preview, I hit [this issue](https://discuss.ocaml.org/t/issue-with-gel-prevents-install-of-jane-street-core-under-5-3-0/16909/9).

Interestingly, this is not an issue with opam, so I guess opam knows to inject `gpatch` in the path somehow instead of `patch`, and dune isn't doing that?

### PR DESCRIPTION
**Pull request by Alizter**
We add a fallback to gpatch when searching for patch. This won't be necessary when we have an OCaml implementation of dune_patch, but that is still some time away.

- fix https://github.com/ocaml/dune/issues/12232

### CODE REVIEW

File: src/dune_patch/dune_patch.ml [hunk 1]
```diff
@@ -90,7 +90,8 @@ let patches_of_string patch_string =
 
 let prog =
   lazy
-    (match Bin.which ~path:(Env_path.path Env.initial) "patch" with
+    (let path = Env_path.path Env.initial in
+     match List.find_map [ "patch"; "gpatch" ] ~f:(Bin.which ~path) with
      | Some p -> p
      | None -> User_error.raise [ Pp.text "patch not found" ])
```
Comment (rgrinberg) [inline src/dune_patch/dune_patch.ml]: "patch and gpatch not found"

**Review by rgrinberg — APPROVED** [review]
Thanks for the quick fix

File: src/dune_patch/dune_patch.ml [hunk 2]
```diff
@@ -90,9 +90,11 @@ let patches_of_string patch_string =
 
 let prog =
   lazy
-    (match Bin.which ~path:(Env_path.path Env.initial) "patch" with
+    (let path = Env_path.path Env.initial in
+     let bins = [ "patch"; "gpatch" ] in
```
Comment (rgrinberg) [inline src/dune_patch/dune_patch.ml]: Actually, shouldn't you lookup gpatch first?

Comment (Alizter) [reply src/dune_patch/dune_patch.ml]: I'm not sure I follow. I would imagine `patch` to be more available than `gpatch`. For instance, I don't have `gpatch`.

Comment (rgrinberg) [reply src/dune_patch/dune_patch.ml]: Yes, `patch` is more common. But the set of people that have both utilities would almost certainly prefer `gpatch`. Otherwise, why did they install it explicitly?

Comment (Alizter) [reply src/dune_patch/dune_patch.ml]: Fair enough. Done that.
