### PR TITLE
fix: run inline tests for byte-only libraries

### LINKED ISSUE #9757: `dune runtest` compiles but does not execute `(inline_tests) (modes byte)`
## Expected Behavior

`dune`:

```
(library
 (name test_bytecode_repro)
 (inline_tests)
 (preprocess (pps ppx_inline_test))
 (modes byte))
```

`test_bytecode_repro.ml`:

```ocaml
let rec fact n = if n = 1 then 1 else n * fact (n - 1)

let%test _ = fact 5 = 121
```

Behavior:

```sh
$ dune runtest
File "test/test_bytecode_repro.ml", line 3, characters 0-25: <<(fact 5) = 121>> is false.

FAILED 1 / 1 tests
$ _
```

## Actual Behavior

```sh
$ dune runtest
$ _
```

Invoking `dune runtest` compiles AFAICT but does not execute the test.

## Reproduction

- PR with a reproducing test: 

https://github.com/ocaml/dune/pull/9756

## Specifications

- Version of `dune` (output of `dune --version`): 3.12.1 and 3.12.2
- Version of `ocaml` (output of `ocamlc --version`): 4.14.1 and 5.1.1
- Operating system (distribution and version): WSL, Ubuntu 23.10

### PR DESCRIPTION
**Pull request by robinbb**
## Summary

Fixes #9757.

When a library has `(modes byte)` and `(inline_tests)`, the default inline test mode `Best` resolves to native linkage. But the byte-only library has no `.cmxa` archive, so its test registration code is never linked into the native runner. The runner starts with zero tests and exits 0 — silently skipping all tests.

The fix consults the library's available modes when resolving `Best`: if the library doesn't support native, `Best` falls back to `Byte`, so the test runner is linked in byte mode where the library's `.cma` is available.

Supersedes the test-only PR #13199 by @Alizter, which documented the broken behavior.

### CODE REVIEW

File: src/dune_rules/inline_tests.ml [hunk 1]
```diff
@@ -311,11 +311,21 @@ include Sub_system.Register_end_point (struct
...
-        |> List.filter ~f:(fun (mode : Mode_conf.t) ->
+        |> List.filter_map ~f:(fun (mode : Mode_conf.t) ->
           match mode with
-          | Native | Best | Byte -> true
-          | Jsoo mode -> Js_of_ocaml.Mode.Pair.select ~mode jsoo_enabled_modes)
+          | Best -> Some (if lib_has_native then mode else Mode_conf.Byte)
+          | Native | Byte -> Some mode
+          | Jsoo mode ->
+            if Js_of_ocaml.Mode.Pair.select ~mode jsoo_enabled_modes
+            then Some (Jsoo mode)
```
Comment (Leonidas-from-XIV) [inline src/dune_rules/inline_tests.ml]: You can bind `(Jsoo mode) as v` and then return `Some v` to avoid reconstructing the exact same value that you deconstructed before but it's fine either way.

**Review by Leonidas-from-XIV — APPROVED** [review]
LGTM and the tests seem to do exactly what was requested.

**Comment by rgrinberg** [comment]
@hhugo could you take a look at this?

File: src/dune_rules/inline_tests.ml (hunk 1 above)
Comment (robinbb) [reply src/dune_rules/inline_tests.ml]: Agreed - that would be better. Done.

**Comment by robinbb** [comment]
@rgrinberg Do you want me to block the merge on @hhugo 's approval?

**Comment by rgrinberg** [comment]
No, it's not blocking, but let's give him a couple of days to respond. This is a hairy part of the code base where not many have familiarity and we've seen plenty of bugs. Also, inline tests affect many people while this bug is comparatively niche.

Do you have some work that depends on this fix? That could be a reason to speed things up.
