### PR TITLE
[coq] Fix coqlib file scanning.

### LINKED ISSUE #7893: Can't find Coq plugin cmxs on loadpath error
## Expected Behavior

When I create a `dune-project` and `dune` file for a Coq project with Dune 3.8 and depend on a Coq plugin installed via coq_makefile like [Equations](https://github.com/mattam82/Coq-Equations), it should suffice to add `(theories Equations)` into `(coq.theory ...)` to enable compilation of the project.

## Actual Behavior

When I run `dune build`, I get the following error:
```
Error: Can't find file equations_plugin.cmxs on loadpath.
```

## Reproduction

1. Create a `dune-project` file like the following:
```
(lang dune 3.8)
(using coq 0.8)
(name TestEquations)
```
2. Create a `dune` file like the following:
```
(coq.theory
 (name TestEquations)
 (synopsis "Test Equations")
 (theories Equations)
 ;(plugins coq-equations)
)
```
3. Create `Eqn.v` or other `.v` file like the following:
```coq
From Equations Require Import Equations.
```
4. Run `dune build`, get the following error:
```
File "./Eqn.v", line 1, characters 0-40:
Error: Can't find file equations_plugin.cmxs on loadpath.
```

Note that the error disappears if `;(plugins coq-equations)` in `dune` is uncommented.

## Specifications

- Version of `dune` (output of `dune --version`): 3.8.0
- Version of `ocaml` (output of `ocamlc --version`): 4.14.1
- Operating system (distribution and version): Ubuntu LTS 22.04

## Additional information 

This bug report was submitted at the suggestion of @ejgallego.

- Coq version: 8.16.0
- Equations version: 1.3+8.16

### PR DESCRIPTION
**Pull request by ejgallego**
The old code did indeed was nonsense, and among others was filtering all the files due to the `String.contains d '.'` condition.

I wonder how the test for updating a file in user-contrib did pass tho, that seems pretty strange, as indeed we were not adding any .vo file to the .vo file list on the user-contrib deps, so this deserves more investigation.

Fixes #7893 , thanks to Karl Palmskog for testing and detailed report.

TODO:
  - some code bits can be improved
  - new test cases [installed plugin]
  - figure out why old test-cases were not catching `Coq_lib.Legacy.vo` always returning the empty list.

### CODE REVIEW

File: src/dune_rules/coq/coq_lib.ml [hunk 1]
```diff
@@ -504,16 +505,30 @@ module DB = struct
     let create_from_stanza coq_db db dir stanza =
       Memo.exec memo (coq_db, db, dir, stanza)
 
-    (* XXX: Memoize? This is pretty cheap so not sure worth the cost *)
+    let directory_of_file p =
+      Path.of_string (Path.to_string p |> Filename.dirname)
+
+    (* XXX: Memoize? This is pretty cheap so not sure worth the cost,
+       still called too much I have observed, suspicious! *)
```
Comment (ejgallego) [inline src/dune_rules/coq/coq_lib.ml:512]: This is called 3 times on a single .vo build, so that seems quite suspicious.

File: src/dune_rules/coq/coq_lib.ml [hunk 2]
```diff
@@ -504,16 +505,30 @@ module DB = struct
...
     let create_from_coqpath ~boot_id cp =
       let name = Coq_path.name cp in
       let installed_root = Coq_path.path cp in
       let implicit = Coq_path.stdlib cp in
       let cmxs = Coq_path.cmxs cp in
+      let cmxs_directories =
+        Path.Set.of_list_map ~f:directory_of_file cmxs |> Path.Set.to_list
```
Comment (ejgallego) [inline src/dune_rules/coq/coq_lib.ml:519]: Better way to do this?

File: test/blackbox-tests/test-cases/coq/coqtop/coqtop-flags.t/run.t [hunk 3]
```diff
@@ -26,7 +26,10 @@ The flags passed to coqc:
   -I lib/coq/../coq-core/plugins/ssreflect
   -I lib/coq/../coq-core/plugins/ssrmatching
   -I lib/coq/../coq-core/plugins/tauto
-  -I lib/coq/../coq-core/plugins/tutorial
+  -I lib/coq/../coq-core/plugins/tutorial/p0
+  -I lib/coq/../coq-core/plugins/tutorial/p1
+  -I lib/coq/../coq-core/plugins/tutorial/p2
+  -I lib/coq/../coq-core/plugins/tutorial/p3
```
Comment (ejgallego) [inline test/blackbox-tests/test-cases/coq/coqtop/coqtop-flags.t/run.t:32]: I've added this for consistency with what Coq does.

Coq also adds `$opam_root/lib` but I'd rather avoid this for now.

File: src/dune_rules/coq/coq_path.ml [hunk 4]
```diff
@@ -99,41 +108,44 @@ let rec scan_path ~f ~acc ~prefix path : 'a list Memo.t =
...
+  let f ~path ~prefix:() ~subresults dir_contents =
+    let cmxs, _ = scan_vo_cmxs ~path dir_contents in
+    Memo.return (cmxs @ subresults)
+  in
+  let pluginsdir = Path.relative coqcorelib "plugins" in
+  let acc _ _ = () in
+  scan_path ~f ~acc ~prefix:() pluginsdir
+
+(** [scan_user_path path] Note that we already have very similar functionality
+    in [Dir_status] *)
```
Comment (ejgallego) [inline src/dune_rules/coq/coq_path.ml:124]: Would be good to consolidate all the scanning code indeed.

File: src/dune_rules/coq/coq_lib.ml [hunk 5]
```diff
@@ -504,16 +505,30 @@ module DB = struct
     let create_from_stanza coq_db db dir stanza =
       Memo.exec memo (coq_db, db, dir, stanza)
 
-    (* XXX: Memoize? This is pretty cheap so not sure worth the cost *)
+    let directory_of_file p =
```
[the remark this answers is not in the document]
Comment (ejgallego) [reply src/dune_rules/coq/coq_lib.ml:508]: Otherwise we can tweak the scanning to accumulate the plugins dir too.

[the remark this answers is not in the document]
Comment (ejgallego) [reply src/dune_rules/coq/coq_lib.ml:508]: I will add a comment actually to coq_path

[the remark this answers is not in the document]
Comment (ejgallego) [reply src/dune_rules/coq/coq_lib.ml:508]: Almost fixed in my tree by indeed accumulating the directories with cmxs too.

File: src/dune_rules/coq/coq_lib.ml (hunk 2 above)
Comment (ejgallego) [reply src/dune_rules/coq/coq_lib.ml:519]: Almost done in my tree.

File: src/dune_rules/coq/coq_lib.ml [hunk 6]
```diff
@@ -153,6 +153,7 @@ and Legacy : sig
     ; installed_root : Path.t (* ; libraries : (Loc.t * Lib.t) list Resolve.t *)
     ; vo : Path.t list
     ; cmxs : Path.t list
+    ; cmxs_directories : Path.t list
```
Comment (Alizter) [inline src/dune_rules/coq/coq_lib.ml:156]: can you add a comment distinguishing this from the field above. It seems strange that we have both the cmxs files themselves and the directories we find them in.

File: src/dune_rules/coq/coq_lib.ml (hunk 2 above)
Comment (Alizter) [reply src/dune_rules/coq/coq_lib.ml:519]: If the goal is to remove duplicates, this is the way I have seen it being done elsewhere. Alreternatively we could just always use a map rather than a list.

File: src/dune_rules/coq/coq_lib.ml (hunk 5 above)
[the remark this answers is not in the document]
Comment (Alizter) [reply src/dune_rules/coq/coq_lib.ml:508]: You want `Path.parent` or `Path.parent_exn` if you are brave.

File: src/dune_rules/coq/coq_lib.ml (hunk 1 above)
Comment (Alizter) [reply src/dune_rules/coq/coq_lib.ml:512]: Could it be that the ~boot_id is changing each time?

File: src/dune_rules/coq/coq_path.ml [hunk 7]
```diff
@@ -48,34 +48,15 @@ let config_path ~default coq_config key =
...
+let build_user_contrib ~cmxs ~vo ~path ~name =
   { name; path; cmxs; vo; stdlib = false }
 
 (* Scanning todos: blacklist? *)
 let scan_vo_cmxs ~path dir_contents =
   let f (d, kind) =
     match kind with
-    (* Skip some directories as Coq does, for now '-' and '.' *)
+    (* Skip some files as Coq does, for now files with '-' *)
     | _ when String.contains d '-' -> List.Skip
```
Comment (Alizter) [inline src/dune_rules/coq/coq_path.ml:59]: Wasn't the code before skipping only directories containing a `.`?

File: src/dune_rules/coq/coq_path.ml [hunk 8]
```diff
@@ -99,41 +108,44 @@ let rec scan_path ~f ~acc ~prefix path : 'a list Memo.t =
...
-        f ~path ~prefix ~subpath ~subpaths dir_contents
-      | _ -> Memo.return []
-    in
-    Memo.List.concat_map ~f dir_contents
-
-let scan_user_path path =
-  let f ~path ~prefix ~subpath ~subpaths dir_contents =
+    scan_path ~f ~acc ~prefix ~path dir_contents
+
+(**  *)
```
Comment (Alizter) [inline src/dune_rules/coq/coq_path.ml:113]: comment?

**Review by Alizter — COMMENTED** [review]
The scanning code was a little hard to read but I think I got the gist of it. We definitely need more tests, especially those with plugins.

**Comment by emillon** [comment]
3.8.1 has been released, I'm removing it from the milestone.

File: src/dune_rules/coq/coq_lib.ml (hunk 1 above)
Comment (ejgallego) [reply src/dune_rules/coq/coq_lib.ml:512]: Good idea, I will try.

File: src/dune_rules/coq/coq_lib.ml (hunk 2 above)
Comment (ejgallego) [reply src/dune_rules/coq/coq_lib.ml:519]: Actually accumulating the dirs directly makes the paths unique (and removes the need for parent, so I will push that trivial change)

File: src/dune_rules/coq/coq_lib.ml (hunk 6 above)
Comment (ejgallego) [reply src/dune_rules/coq/coq_lib.ml:156]: In fact `cmxs` files are not used anywhere, oh, actually I think they should be in as coqdep requires re-run when the list of cmxs files change! (Not the contents) Yuck!

File: src/dune_rules/coq/coq_path.ml (hunk 7 above)
Comment (ejgallego) [reply src/dune_rules/coq/coq_path.ml:59]: Before the PR the code was not skipping anything, I don't know what happened with older versions as git blame is not useful due to squashes.

**Comment by ejgallego** [comment]
Ok this should be ready.

Can we add this to the 3.8.2 milestone ?

File: src/dune_rules/coq/coq_lib.ml (hunk 6 above)
Comment (ejgallego) [reply src/dune_rules/coq/coq_lib.ml:155]: I removed the cmxs field from coq_lib as it is not used, still we keep it in the scanning code for debug purposes.

**Comment by Alizter** [comment]
@ejgallego Yes, it is already in the list of backports. The milestone won't make sense for PRs targeting the main branch.

File: src/dune_rules/coq/coq_lib.ml (hunk 1 above)
Comment (ejgallego) [reply src/dune_rules/coq/coq_lib.ml:505]: Now it is cheap again so not a big deal.

File: test/blackbox-tests/test-cases/coq/compose-installed-rebuild.t/run.t [hunk 9]
```diff
@@ -80,3 +80,36 @@ Now we should see that A is rebuilt
...
+  Installing $TESTCASE_ROOT/lib/coq/user-contrib/B/.coq-native/NB_c.cmi
+  Installing $TESTCASE_ROOT/lib/coq/user-contrib/B/.coq-native/NB_c.cmxs
+  Deleting $TESTCASE_ROOT/lib/coq/user-contrib/B/b.v
+  Installing $TESTCASE_ROOT/lib/coq/user-contrib/B/b.v
+  Deleting $TESTCASE_ROOT/lib/coq/user-contrib/B/b.vo
+  Installing $TESTCASE_ROOT/lib/coq/user-contrib/B/b.vo
+  Installing $TESTCASE_ROOT/lib/coq/user-contrib/B/c.v
+  Installing $TESTCASE_ROOT/lib/coq/user-contrib/B/c.vo
+
+Now we should see that A is not rebuilt, however coqdep is called, this seems to fail
```
Comment (ejgallego) [inline test/blackbox-tests/test-cases/coq/compose-installed-rebuild.t/run.t:111]: It is strange this is not working, we now correctly add the full list of .vo files to the deps for the `A.v.d` file.

File: CHANGES.md [hunk 10]
```diff
@@ -30,6 +30,13 @@ Unreleased
 - Switch back to threaded console for all systems; fix unresponsive console on
   Windows (#7906, @nojb)
 
+3.8.2 (unreleased)
```
Comment (Alizter) [inline CHANGES.md:33]: Add this to the unreleased changelog, @emillon will clean up the changelog later.

File: test/blackbox-tests/test-cases/coq/coqtop/coqtop-flags.t/run.t (hunk 3 above)
Comment (ejgallego) [reply test/blackbox-tests/test-cases/coq/coqtop/coqtop-flags.t/run.t:32]: We should make a bug upstream about this. For now it makes sense to keep the scanning behavior close.

File: src/dune_rules/coq/coq_path.mli [hunk 11]
```diff
@@ -20,11 +20,16 @@ val path : t -> Path.t
 
 val vo : t -> Path.t list
 
+(** Unused for now *)
 val cmxs : t -> Path.t list
```
Comment (Alizter) [inline src/dune_rules/coq/coq_path.mli:24]: If it is completely unused why not get rid of it?

File: src/dune_rules/coq/coq_path.mli [hunk 12]
```diff
@@ -20,11 +20,16 @@ val path : t -> Path.t
...
 
+val cmxs_directories : t -> Path.t list
+
 val stdlib : t -> bool
 
 val of_coq_install : Context.t -> t list Memo.t
 
 (**  *)
```
Comment (Alizter) [inline src/dune_rules/coq/coq_path.mli:32]: Could you update this comment btw?

**Review by Alizter — APPROVED** [review]

File: src/dune_rules/coq/coq_path.mli (hunk 12 above)
Comment (Alizter) [reply src/dune_rules/coq/coq_path.mli:32]: (the empty one)

File: CHANGES.md (hunk 10 above)
Comment (ejgallego) [reply CHANGES.md:33]: Ok, but that seems more work @emillon no? As things are now you have to do nothing, right? If I put this in `unreleased` you need to amend both the backport and `main` which seems a huge pain.

File: src/dune_rules/coq/coq_path.mli (hunk 11 above)
Comment (ejgallego) [reply src/dune_rules/coq/coq_path.mli:24]: It could be useful in the future, for example for coqdep -modules

File: CHANGES.md (hunk 10 above)
Comment (emillon) [reply CHANGES.md:33]: no, please keep it to the unreleased changelog with no mention of 3.8.2, it's simpler like that. I'll expand on that later.

Comment (ejgallego) [reply CHANGES.md:33]: Changelog updated!
