### PR TITLE
fix: Better error for unzip failure

### LINKED ISSUE #11548: dune-pkg: Print an error when a tool required to extract an archive is missing
When dune downloads a package source archive but is unable to extract it because the necessary tool is missing, dune should print an error explaining the situation.

The current error message in this situation is:
```
File "dune.lock/tsort.pkg", line 10, characters 7-65:
10 |   (url https://github.com/dmbaturin/ocaml-tsort/archive/2.0.0.zip)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error:
failed to unpack archive downloaded from
https://github.com/dmbaturin/ocaml-tsort/archive/2.0.0.zip
reason:
unable to extract "_build/.temp/dune_d7c5e3_2.0.0.zip/download"
```

It would be more helpful if the message referenced the fact that the required tool (`unzip` in the case of this example) was not in the user's PATH.

### PR DESCRIPTION
**Pull request by Sudha247**
Fixes #11548

Currently the archive driver tries to use `bsdtar` and `tar` to unzip a zip file if `unzip` is not present in the system. This may or may not work depending on the specific implementation. Concretely, if the `tar` is a variant of `bsdtar` it can unpack zip files whearas `tar` cannot. We check that and return an error message that `unzip` is expected and not present.

### CODE REVIEW

File: src/dune_pkg/archive_driver.ml [hunk 1]
```diff
@@ -32,32 +32,56 @@ let tar =
...
+  in
+  let bin_path =
+    match which bin_name with
+    | Some bin -> bin
+    | None -> Dune_engine.Utils.program_not_found "unzip" ~loc:None
+  in
+  let+ output, _error =
+    Process.run_capture_lines ~display:Quiet Return bin_path [ "--version" ]
+  in
+  let output_str = String.concat ~sep:"\n" output in
```
Comment (Alizter) [inline src/dune_pkg/archive_driver.ml]: Just use Process.run in this case, capture_lines will split the output of that but since you recombine there is no point. Check process.mli for the variants.

File: src/dune_pkg/archive_driver.ml [hunk 2]
```diff
@@ -32,32 +32,56 @@ let tar =
...
        with
-       | Some bin -> { Command.bin; make_args = make_tar_args }
+       | Some bin -> Fiber.return { Command.bin; make_args = make_tar_args }
        | None -> Dune_engine.Utils.program_not_found "tar" ~loc:None)
   in
   { command; suffixes = [ ".tar"; ".tar.gz"; ".tgz"; ".tar.bz2"; ".tbz" ] }
 ;;
 
+let which_bsdtar (bin_name : string) =
+  let contains s sub =
```
Comment (rgrinberg) [inline src/dune_pkg/archive_driver.ml]: Could you just write a regex? This is a bit too low level for `dune_pkg`. Given the implementation here, the regex should perform adequately anyway.

File: src/dune_pkg/archive_driver.ml [hunk 3]
```diff
@@ -10,7 +10,7 @@ module Command = struct
 end
 
 type t =
-  { command : Command.t Lazy.t
+  { command : Command.t Fiber.t Lazy.t
```
Comment (rgrinberg) [inline src/dune_pkg/archive_driver.ml]: This should be `Fiber.Lazy.t` otherwise the laziness is useless here

**Review by rgrinberg — DISMISSED** [review]

File: src/dune_pkg/archive_driver.ml [hunk 4]
```diff
@@ -26,38 +26,50 @@ let make_zip_args ~archive ~target_in_temp =
...
        | None -> Dune_engine.Utils.program_not_found "tar" ~loc:None)
   in
   { command; suffixes = [ ".tar"; ".tar.gz"; ".tgz"; ".tar.bz2"; ".tbz" ] }
 ;;
 
+let which_bsdtar (bin_name : string) =
+  let bin_path =
+    match which bin_name with
+    | Some bin -> bin
+    | None -> Dune_engine.Utils.program_not_found "unzip" ~loc:None
```
Comment (Leonidas-from-XIV) [inline src/dune_pkg/archive_driver.ml]: This is probably wrong, if it searches for `tar` or `bsdtar` it shouldn't fail with an error that `unzip` can't be found.

```suggestion
    | None -> Dune_engine.Utils.program_not_found bin_name ~loc:None
```

File: src/dune_pkg/archive_driver.ml [hunk 5]
```diff
@@ -26,38 +26,50 @@ let make_zip_args ~archive ~target_in_temp =
...
+  in
+  let+ output, _error =
+    Process.run_capture ~display:Quiet Return bin_path [ "--version" ]
+  in
+  let re = Re.compile (Re.str "bsdtar") in
```
Comment (Leonidas-from-XIV) [inline src/dune_pkg/archive_driver.ml]: You can curry this in the definition of `which_bsdtar`, then it won't need to be compiled on every call. But it only happens twice if unzip is not found, so your call :)

**Review by Leonidas-from-XIV — CHANGES_REQUESTED** [review]
Looks pretty sensible! I found one thing that's probably an actual issue.

File: src/dune_pkg/archive_driver.ml (hunk 4 above)
Comment (Sudha247) [reply src/dune_pkg/archive_driver.ml]: Hm, I'm not so sure about this. The reason we're looking for `bsdtar` or `tar` is because `unzip` doesn't exist, and `unzip` is the definitive program to extract zip files, while `tar` may or may not extract zip files. I think the error message should be clear here that the failure is because a zip file is not being extracted. Should we write a custom error message here?

File: src/dune_pkg/archive_driver.ml (hunk 5 above)
Comment (Sudha247) [reply src/dune_pkg/archive_driver.ml]: Good point! Will modify.

File: src/dune_pkg/archive_driver.ml (hunk 4 above)
Comment (Alizter) [reply src/dune_pkg/archive_driver.ml]: A custom error message would be fine. Something like
```
Couldn't find a program to extra .zip. Tried:
- unzip
- tar
- bsdtar
```

Comment (Sudha247) [reply src/dune_pkg/archive_driver.ml]: I just realised we don't need to error out here. My bad!

**Review by Leonidas-from-XIV — APPROVED** [review]
Looks good to me. It would be nice to add a cram test, however removing tools from the `PATH` on Unix is rather tedious (as one would need to iterate over the whole `PATH`, symlink those that should stay in the path and skip those that should be excluded).

**Comment by Alizter** [comment]
We have such a test for `curl`, we could reuse that setup.

**Comment by Leonidas-from-XIV** [comment]
Hmm, yes, looks like we don't actually need many binaries to exist in the `PATH`. So a fake `PATH` folder is fairly easy to create, only needs `g(un)zip`, `tar` `unzip` etc.

**Comment by Sudha247** [comment]
Good idea, I'll try to add a cram test.

**Comment by Leonidas-from-XIV** [comment]
@Sudha247 Can you rebase? It seems like the PR has now a number of unrelated commits.

**Comment by Sudha247** [comment]
Rebased! Thanks for the heads up.

File: test/blackbox-tests/test-cases/pkg/zip-extract-fail.t [hunk 6]
```diff
@@ -0,0 +1,23 @@
+Test the error message when curl is needed but not installed.
```
Comment (Leonidas-from-XIV) [inline test/blackbox-tests/test-cases/pkg/zip-extract-fail.t]: I think this should test in an environment without `unzip` no?

File: test/blackbox-tests/test-cases/pkg/zip-extract-fail.t [hunk 7]
```diff
@@ -0,0 +1,23 @@
...
+  > (source
+  >  (fetch
+  >   (url "file://$(pwd)/bar.zip")))
+  > (version dev)
+  > EOF
+  > }
+
+  $ makepkg foo
+
+Build the package in an environment without curl.
```
Comment (Leonidas-from-XIV) [inline test/blackbox-tests/test-cases/pkg/zip-extract-fail.t]: Likewise here.

File: test/blackbox-tests/test-cases/pkg/zip-extract-fail.t [hunk 8]
```diff
@@ -0,0 +1,23 @@
...
+  $ PATH=$(dirname $(which dune)) build_pkg foo &> error.txt
+  $ cat error.txt | grep "^Error: Program unzip not found in the tree or in PATH"
+  [1]
+
```
Comment (Leonidas-from-XIV) [inline test/blackbox-tests/test-cases/pkg/zip-extract-fail.t:86]: I think it would be nice to test that it uses `unzip` and if not then `bsdtar` and if that doesn't exist then `tar`.

File: test/blackbox-tests/test-cases/pkg/zip-extract-fail.t [hunk 9]
```diff
@@ -0,0 +1,23 @@
+Test the error message when curl is needed but not installed.
+
+  $ . ./helpers.sh
+  $ make_lockdir
+  $ echo "random" >> test.txt
+  $ zip bar.zip test.txt >> /dev/null
```
Comment (Leonidas-from-XIV) [inline test/blackbox-tests/test-cases/pkg/zip-extract-fail.t]: I'd suggest making `zip` and `unzip` just aliases to `cp`, thus faking it. That way this test does not need to rely on `zip` existing on the test system. As we don't really need to test that it can unpack ZIP archives, just that it uses the right commands.

(You can see that one of the CI machines does not have `zip` installed, thus the test fails to create the archive)

**Review by Leonidas-from-XIV — CHANGES_REQUESTED** [review]
I think there's some issues in the cram test that would be nice to fix to have a more comprehensive (and faster) coverage of decompression tool testing.

File: test/blackbox-tests/test-cases/pkg/zip-extract-fail.t (hunk 8 above)
Comment (Sudha247) [reply test/blackbox-tests/test-cases/pkg/zip-extract-fail.t:86]: That's how the sequence goes, but we don't print error messages if `bsdtar` isn't present and `tar` doesn't support zip, as `unzip` is the definitive binary for zip files. Should the error message be changed to indicate this sequence has been tried?

Comment (Leonidas-from-XIV) [reply test/blackbox-tests/test-cases/pkg/zip-extract-fail.t:86]: Not necessarily, it's ok to print that we found no tool to decompress the files (and mention we tried `unzip`, `bsdtar` and `tar` so people know they can install either), it's already better than the status quo.

File: src/dune_pkg/archive_driver.ml [hunk 10]
```diff
@@ -69,7 +65,14 @@ let zip =
         let* program = find_tar [ "bsdtar"; "tar" ] in
         (match program with
          | Some bin -> Fiber.return { Command.bin; make_args = make_tar_args }
-         | None -> Fiber.return @@ Dune_engine.Utils.program_not_found "unzip" ~loc:None))
+         | None ->
+           Fiber.return
+           @@ User_error.raise
+                [ Pp.textf "No program found to extract zip file. Tried"
```
Comment (Leonidas-from-XIV) [inline src/dune_pkg/archive_driver.ml]: I believe this can be done nicer with `Pp.enumerate`.

File: src/dune_pkg/archive_driver.ml [hunk 11]
```diff
@@ -26,38 +26,56 @@ let make_zip_args ~archive ~target_in_temp =
...
+             | None -> find_tar xs)
+        in
+        let* program = find_tar [ "bsdtar"; "tar" ] in
+        (match program with
+         | Some bin -> Fiber.return { Command.bin; make_args = make_tar_args }
+         | None ->
+           Fiber.return
+           @@ User_error.raise
+                [ Pp.enumerate
+                    [ "No program found to extract zip file. Tried"
```
Comment (Alizter) [inline src/dune_pkg/archive_driver.ml]:
```suggestion
                [ "No program found to extract zip file. Tried:"
                ; Pp.enumerate
                  [
```

Comment (Alizter) [reply src/dune_pkg/archive_driver.ml]: You want to state something and then enumerate all the options.

File: test/blackbox-tests/test-cases/pkg/zip-extract-fail.t [hunk 12]
```diff
@@ -0,0 +1,74 @@
...
+  $ cat > fakebin/tar << 'EOF'
+  > #!/usr/bin/env sh
+  > cp "$@"
+  > EOF
+  $ chmod +x fakebin/tar
+  $ PATH=fakebin:$(dirname $(which dune)) build_pkg foo 2>&1 | grep '^Error:' -A 3
+  Error: - No program found to extract zip file. Tried:
+         - unzip
+         - bsdtar
+         - tar
```
Comment (Leonidas-from-XIV) [inline test/blackbox-tests/test-cases/pkg/zip-extract-fail.t]: Can you add a test with a fake tar that can unzip? Because now we're missing the case where `tar` is `bsdtar` and unpacking works (e.g. default on FreeBSD and presumably macOS systems).

File: test/blackbox-tests/test-cases/pkg/zip-extract-fail.t [hunk 13]
```diff
@@ -0,0 +1,74 @@
...
+
+Build the package with bsdtar and tar, tar doesn't help but bsdtar should. Note
+that however since we're aliasing bsdtar to cp, it will fail. This is because it
+checks if `bsdtar --version` returns the string bsdtar and in this case it
+doesn't. But that's ok because we just want to check if it's using the correct
+binary.
+
+  $ cat > fakebin/bsdtar << 'EOF'
```
Comment (Leonidas-from-XIV) [inline test/blackbox-tests/test-cases/pkg/zip-extract-fail.t]: You can make your fake `bsdtar` support `--version` and call `cp` if no `--version` is specified. That way you exercise the code paths and don't need to explain why this failure is correct, because the failure should go away.

File: test/blackbox-tests/test-cases/pkg/zip-extract-fail.t [hunk 14]
```diff
@@ -0,0 +1,74 @@
...
+
+Build with unzip. Same failure expected as above.
+
+  $ cat > fakebin/unzip << 'EOF'
+  > #!/usr/bin/env sh
+  > cp "$@"
+  > EOF
+  $ chmod +x fakebin/unzip
+  $ PATH=fakebin:$(dirname $(which dune)) build_pkg foo 2>&1 | grep '^Error:'
+  Error: failed to extract 'bar.zip'
```
Comment (Leonidas-from-XIV) [inline test/blackbox-tests/test-cases/pkg/zip-extract-fail.t]: Shouldn't this work now?

I believe this fails because your `fakebin/unzip` calls `cp` without a target argument.

File: test/blackbox-tests/test-cases/pkg/zip-extract-fail.t [hunk 15]
```diff
@@ -0,0 +1,74 @@
...
+
+  $ mkdir -p fakebin
+  $ cat > fakebin/zip << 'EOF'
+  > #!/usr/bin/env sh
+  > cp "$@"
+  > EOF
+  $ chmod +x fakebin/zip
+
+  $ echo "random" >> test.txt
+  $ PATH=fakebin:$PATH zip test.txt bar.zip >> /dev/null
```
Comment (Leonidas-from-XIV) [inline test/blackbox-tests/test-cases/pkg/zip-extract-fail.t]: No need for `fakebin/zip` if our fake compression is just `cp`:

```suggestion
  $ echo "random" > bar.zip
```

**Review by Leonidas-from-XIV — CHANGES_REQUESTED** [review]

**Comment by Alizter** [comment]
This issue is relevant:
- https://github.com/ocaml/dune/issues/10123

This issue also makes all the work being done here pointless if we ever go down that route:
- https://github.com/ocaml/dune/issues/10127

I don't think this PR and it's coverage need to be perfect.

**Comment by Leonidas-from-XIV** [comment]
Fair, however pure-OCaml `tar` is not enough, we'd need the same also for `bz2`, `gzip` and potentially `xz`. I don't think that is realistic in the medium-term.

File: test/blackbox-tests/test-cases/pkg/zip-extract-fail.t [hunk 16]
```diff
@@ -0,0 +1,97 @@
...
+and built.
+
+  $ cat > .fakebin/bsdtar << 'EOF'
+  > #!/usr/bin/env sh
+  > case $1 in
+  >  --version)
+  >    echo "bsdtar"
+  >  ;;
+  >  *)
+  >    echo "I am faketar"
```
Comment (Leonidas-from-XIV) [inline test/blackbox-tests/test-cases/pkg/zip-extract-fail.t]: I think this is a leftover from testing.

File: test/blackbox-tests/test-cases/pkg/zip-extract-fail.t [hunk 17]
```diff
@@ -0,0 +1,97 @@
...
+Build with unzip
+
+  $ cat > .fakebin/unzip << 'EOF'
+  > #!/usr/bin/env sh
+  > case $1 in
+  >  --version)
+  >    echo "bsdtar"
+  >  ;;
+  >  *)
+  >    echo "I am faketar"
```
Comment (Leonidas-from-XIV) [inline test/blackbox-tests/test-cases/pkg/zip-extract-fail.t]: Same as above.

**Review by Leonidas-from-XIV — APPROVED** [review]
Pretty nice. I think some debug prints can be removed but otherwise its good to go.

**Comment by Leonidas-from-XIV** [comment]
@Sudha247 I think the only thing blocking is the DCO check.

**Comment by Sudha247** [comment]
Thanks for the heads up! Fixed DCO and rebased.

**Comment by Alizter** [comment]
@shonfeder I would like to give this another pass tomorrow if you don't mind.

File: src/dune_pkg/archive_driver.ml [hunk 18]
```diff
@@ -26,38 +26,51 @@ let make_zip_args ~archive ~target_in_temp =
...
   { command; suffixes = [ ".tar"; ".tar.gz"; ".tgz"; ".tar.bz2"; ".tbz" ] }
 ;;
 
+let which_bsdtar (bin_name : string) =
+  match which bin_name with
+  | Some bin ->
+    let+ output, _error = Process.run_capture ~display:Quiet Return bin [ "--version" ] in
+    let re = Re.compile (Re.str "bsdtar") in
+    if Re.execp re output then Some bin else None
+  | None -> Fiber.return None
```
Comment (rgrinberg) [inline src/dune_pkg/archive_driver.ml]: Do you mind putting this clause the `Some`?

File: src/dune_pkg/archive_driver.ml [hunk 19]
```diff
@@ -26,38 +26,51 @@ let make_zip_args ~archive ~target_in_temp =
...
+        (* Test for tar before bsdtar as tar is more likely to be installed
             and both work equally well for tarballs. *)
-         List.find_map [ "tar"; "bsdtar" ] ~f:which
-       with
-       | Some bin -> { Command.bin; make_args = make_tar_args }
-       | None -> Dune_engine.Utils.program_not_found "tar" ~loc:None)
+        List.find_map [ "tar"; "bsdtar" ] ~f:which
+      with
+      | Some bin -> Fiber.return { Command.bin; make_args = make_tar_args }
+      | None -> Dune_engine.Utils.program_not_found "tar" ~loc:None)
```
Comment (rgrinberg) [inline src/dune_pkg/archive_driver.ml]: Why don't you use the same error style as you did for unzip? You're trying more than `tar` here.

**Review by rgrinberg — CHANGES_REQUESTED** [review]

**Review by rgrinberg — APPROVED** [review]

**Review by Alizter — APPROVED** [review]
