### PR TITLE
Fix interpretation of / in META files

### LINKED ISSUE #1885: Regression from 1.6 to 1.7 for libraries with archives in subdirectories
I'm seeing build failures with 1.7.* that work well with 1.6.3, in particular due to bec9fbb95c79dd04d3027be6ccfc9c66fba58d9c from https://github.com/ocaml/dune/pull/1329.

I don't have a self-contained repro yet, but figured I'd open an issue in case there are any quick comments. The symptom is warnings (that a later commit makes into errors) such as:
```
File unavailable: /Users/jjb/.opam/sledge/lib/llvm/llvm_analysis.cmxa
```
This come from building a library with `(libraries llvm.analysis ...)` in its `dune`. Note that the `llvm_analysis.cmxa` file is actually present as `/Users/jjb/.opam/sledge/lib/llvm/static/llvm_analysis.cmxa`. Note the added `static` directory. This comes from the `META.llvm` file, which declares packages with archives in the `static` subdirectory:
```
name = "llvm"
version = "7.0.0svn"
description = "LLVM OCaml bindings"
archive(byte) = "static/llvm.cma"
archive(native) = "static/llvm.cmxa"
directory = "llvm"

package "analysis" (
    requires = "llvm"
    version = "7.0.0svn"
    description = "Intermediate representation analysis for LLVM"
    archive(byte) = "static/llvm_analysis.cma"
    archive(native) = "static/llvm_analysis.cmxa"
)
```
I don't know if `META` files are not supposed to do that, but it worked with dune 1.6.

FWIW, looking at the patch, the use of `basename` [here](https://github.com/ocaml/dune/commit/bec9fbb95c79dd04d3027be6ccfc9c66fba58d9c#diff-8828fb37258a6e3cca668a8169428ea0R75) looked suspicious to me.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #1885

### CODE REVIEW

**Comment by diml** [comment]
I checked manually that it fixes the issue.

File: src/dune_package.ml [hunk 1]
```diff
@@ -30,8 +30,18 @@ module Lib = struct
...
-    let map_path p = Path.relative dir (Path.basename p) in
+        ~version ~orig_src_dir ~dir ~is_external =
+    let map_path =
+      if is_external then
+        fun p ->
+          match Path.kind p with
+          | External _ -> p
+          | Local _ ->
+            Exn.code_error "Lib.make got local path for an external library"
+              [ "path", Path.to_sexp p ]
```
Comment (rgrinberg) [inline src/dune_package.ml]: Can't we just omit the flag and use this branch for local libs?

Comment (diml) [reply src/dune_package.ml]: Yes, that makes sense

Comment (diml) [reply src/dune_package.ml]: Done

**Comment by jberdine** [comment]
Thanks! I've pinned this PR and tested locally: problem solved.

File: CHANGES.md [hunk 2]
```diff
@@ -11,6 +11,13 @@ unreleased
 
 - Format `dune printenv` output (#1867, fix #1862, @emillon)
 
+1.7.3 (unreleased)
+------------------
+
+- Fix interpretation of `META` files containing archives with `/` in
+  the filename. This was causing llvm to be unusable with dune (#1889,
```
Comment (jberdine) [inline CHANGES.md]: It might be more helpful to people reading the changelog if a less specific description was given. I don't think that llvm is so special, wouldn't the same issue arise for any lib with sublibs?

**Review by rgrinberg — APPROVED** [review]

File: CHANGES.md (hunk 2 above)
Comment (diml) [reply CHANGES.md]: Before dune, all sublibs were usually installed in the main directory since that was the easiest thing to do. Sublibs installed in subdirs generally have a `directory` field (that's what dune does for instance) and since filenames are relative to that directory, filenames still don't contain slashes.

So llvm is probably one of a very small set of projects to be affected, so it seems worth mentioning to me. I added "for instance" to make it clear it's just an example

Comment (jberdine) [reply CHANGES.md]: I see, thanks for the explanation. (Maybe there is too much flexibility somewhere...)
