### PR TITLE
fix: account for workspace binaries when generating rules for `./.bin`

### LINKED ISSUE #6220: "No rule found" when using "binaries" defined in "env" stanza in dune-workspace
I'll make an MR with a reproduction case in a minute.

### PR DESCRIPTION
**Pull request by anmonteiro**
fixes #6220

- [x] changes entry

### CODE REVIEW

File: src/dune_rules/env_node.ml [hunk 1]
```diff
@@ -40,9 +41,24 @@ let make
...
+      let* config_binaries =
+        Memo.parallel_map
+          config_binaries
+          ~f:(File_binding_expand.expand ~dir ~f:(expand_str_lazy expander))
+      in
+      match Path.Build.drop_build_context dir with
+      | None -> Memo.return config_binaries
+      | Some dir_src ->
+        let* workspace = Workspace.workspace () in
+        (match Path.Source.equal workspace.dir dir_src with
```
Comment (rgrinberg) [inline src/dune_rules/env_node.ml]: This check seems a bit fishy. The directory of the workspace file shouldn't be relevant, there's only a single workspace file that is global to the entire build.

Comment (anmonteiro) [reply src/dune_rules/env_node.ml]: But we only want to generate the rules for those binaries in the root .bin dir. do you suggest we do that more explicitly?

Comment (rgrinberg) [reply src/dune_rules/env_node.ml]: Yes, because the workspace.dir isn't necessarily the root. The workspace file can exist anywhere if you set it explicitly with `--workspace`

Comment (anmonteiro) [reply src/dune_rules/env_node.ml]: I think it becomes slightly tricker when there are overlapping `env` stanzas (e.g. `dune-workspace` and `dune` file) that specify the same binary. I'm working on a test case that shows that. My thought was that, for this reason, you'd want this logic to live together. Do you have a better alternative?

Comment (Alizter) [reply src/dune_rules/env_node.ml]: That should be `Path.equal Path.root (Path.source dir_src)` instead I suppose

Comment (Alizter) [reply src/dune_rules/env_node.ml]: or better yet `Path.is_root`. This gets set when dune is started and the workspace root is found by crawling up to the top project or the first dune-workspace file.

Comment (rgrinberg) [reply src/dune_rules/env_node.ml]: > I think it becomes slightly tricker when there are overlapping env stanzas (e.g. dune-workspace and dune file) that specify the same binary. I'm working on a test case that shows that

Just to make sure we're on the same page: in this case, the env stanza in the dune file should take precedence.

> I'm working on a test case that shows that. My thought was that, for this reason, you'd want this logic to live together. Do you have a better alternative?

IMO, the env node should not discriminate by the path at all. The basic principle that we follow is that a node _may_ have a parent node. The rules to decide the parent node are as follows (reciting from memory here - this might not be precise)

1. The workspace node has no parent
2. The context node in a workspace file may have 1. as the parent.
3. The node at the root of the project may have 2. as the parent
4. All other nodes look up their `Path.parent` to find their parent node

This logic is usually implemented by passing in the correct parent to `~inherit_from`. The function `inherited` is supposed to supply the default when needed.

For local binaries, things are a bit more complicated because we need to both populate the artifacts db, and prepare a special directory that will be added to PATH.

It seems like it's the latter that is broken here and the artifacts db is indeed set correctly (needs confirming). If so, I'd look for an approach that does away with `Env_node.local_binaries` entirely. For example, make `Artifacts.add_binaries` remember all binaries added by a particular directory. Then, gen rules could just get the binaries it needs to setup with `Artifacts.local_dir : dir:Path.Build.t -> File_binding.Expanded.t list`.

With this approach, both context and workspace binaries would be added with the context root as the directory, and the order in which this is done would decide what gets the higher priority.

I haven't looked at this code for a long time, so all of this could be nonsense. But the changes in this PR don't seem like they're clarifying things. For example, I wonder what does it mean for a node to have both a parent (`inherit_from`) and a default (`default_env_node`)?

Comment (anmonteiro) [reply src/dune_rules/env_node.ml]: > Just to make sure we're on the same page: in this case, the env stanza in the dune file should take precedence.

Yep, I'm aware of this, and it remains codified this way. The `inherit_from` logic is clear wrt how the inheritance flows.

> With this approach, both context and workspace binaries would be added with the context root as the directory, and the order in which this is done would decide what gets the higher priority.


OK that's great. It's a slightly more invasive change, but one that makes it clearer what's happening. I have a good idea of what to do, thanks!

Comment (anmonteiro) [reply src/dune_rules/env_node.ml]: > It seems like it's the latter that is broken here and the artifacts db is indeed set correctly (needs confirming)

I think this is true, it's the local binary logic that's wrong. We could likely use all the added artifacts instead and do away with `local_binaries` as you said.

Comment (anmonteiro) [reply src/dune_rules/env_node.ml]: @rgrinberg I pushed a new fix that defines `local_binaries` in terms of Artifacts.

**Review by rgrinberg — APPROVED** [review]
