### PR TITLE
fix(subst): skip large files on 32-bit

### LINKED ISSUE #9538: dune subst crashes on large files (32-bit systems)
`dune subst` crashes on 32-bit systems when a large file is present:

(true as of 3.12.1)

```
  Error: exception Invalid_argument("Bytes.create")
  Raised by primitive operation at Stdune__Io.Make.eagerly_input_string in file
    "otherlibs/stdune/src/io.ml", line 273, characters 14-30
  Called from Stdune__Io.Make.read_all.(fun) in file
    "otherlibs/stdune/src/io.ml", line 308, characters 16-40
  Called from Stdune__Exn.protectx in file "otherlibs/stdune/src/exn.ml", line
    10, characters 8-11
  Re-raised at Stdune__Exn.protectx in file "otherlibs/stdune/src/exn.ml", line
    16, characters 4-11
  Called from Dune__exe__Subst.subst_file in file "bin/subst.ml", line 113,
    characters 10-27
  Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
  Called from Fiber__Core.O.(>>|).(fun) in file "vendor/fiber/src/core.ml",
    line 252, characters 36-41
  Called from Fiber__Scheduler.exec in file "vendor/fiber/src/scheduler.ml",
    line 76, characters 8-11
  Re-raised at Stdune__Exn.raise_with_backtrace in file
    "otherlibs/stdune/src/exn.ml", line 38, characters 27-56
  Called from Fiber__Scheduler.exec in file "vendor/fiber/src/scheduler.ml",
    line 76, characters 8-11
```

### PR DESCRIPTION
**Pull request by emillon**
Fixes #9538

When `subst` tries to work on a file, it first loads it in memory as an OCaml `string`. This type has a maximum size, `Sys.max_string_length`. This is not an issue on 64-bit systems, but the 32-bit limit can be below the size of actual files.

However, it is unlikely that these files need substitutions, so we just log a warning in this case.

### CODE REVIEW

File: bin/subst.ml [hunk 1]
```diff
@@ -110,15 +110,18 @@ let subst_string s path ~map =
...
-    if Path.is_root (Path.parent_exn path) && Package.is_opam_file path
-    then "version: \"%%" ^ "VERSION_NUM" ^ "%%\"\n" ^ s
-    else s
-  in
-  match subst_string s ~map path with
-  | None -> ()
-  | Some s -> Io.write_file path s
+  match Io.read_file path with
+  | exception Io.Large_file ->
+    User_warning.emit [ Pp.textf "Ignoring large file: %s" (Path.to_string path) ]
```
Comment (Leonidas-from-XIV) [inline bin/subst.ml:115]: The warning is very useful, that way we can also monitor via bug reports if this is a problem that we would need to solve in a different way, e.g. by streaming the file.

I think it would be useful to add a `hint` to tell the user that the file is too large for 32 bit platforms.

File: bin/subst.ml [hunk 2]
```diff
@@ -110,15 +110,18 @@ let subst_string s path ~map =
...
+  | s ->
+    let s =
+      if Path.is_root (Path.parent_exn path) && Package.is_opam_file path
```
Comment (Leonidas-from-XIV) [inline bin/subst.ml:118]: I know that this is from the original code but this looks like it needs to be adopted if we generate OPAM files in the `opam/` subdirectory.

File: otherlibs/stdune/src/io.ml [hunk 3]
```diff
@@ -270,6 +272,7 @@ struct
      This can be detected by checking that the length of the resulting string is
      less than [len]. *)
   let eagerly_input_string ic len =
```
Comment (Leonidas-from-XIV) [inline otherlibs/stdune/src/io.ml:274]: Add `_exn` as s suffix here?

File: otherlibs/stdune/src/io.mli [hunk 4]
```diff
@@ -9,6 +9,10 @@ val input_lines : in_channel -> string list
     unrelated channels because it uses a statically-allocated global buffer. *)
 val copy_channels : in_channel -> out_channel -> unit
 
+(** This is raised when [read_all] or similar functions try to operate on files larger than [Sys.max_string_length]. This should be an issue only on 32-bit systems where this is 16 MiB. *)
+exception Large_file
+
+(** Read all of a channel. Can raise [Large_file]. *)
 val read_all : in_channel -> string
```
Comment (Leonidas-from-XIV) [inline otherlibs/stdune/src/io.mli:16]: Likewise, should probably be `read_all_exn`.

Comment (emillon) [reply otherlibs/stdune/src/io.mli:16]: Yes, even if in most cases we don't have to handle it, it might be a good nudge. I think I'll make that change in a separate PR.

**Comment by rgrinberg** [comment]
The change looks fine, but we need to be careful with introducing new exceptions. The issue is that exceptions don't get marshalled automatically over RPC so you can just break things internally when this error is raised. Instead, I propose the following:

1. Introduce a function `val read_file_unless_large : path -> (string, unit) result`
2. use this function to implement the current `read_file`. The `Error` case can be turned into a Code_error which is a safe exceptions to use
3. In the subst code, use `read_file_unless_large` directly.

File: bin/subst.ml (hunk 1 above)
Comment (emillon) [reply bin/subst.ml]: done. not too sure about the wording, let me know what you think

**Comment by emillon** [comment]
Thanks. I adapted that to the new API.

File: bin/subst.ml (hunk 1 above)
Comment (Leonidas-from-XIV) [reply bin/subst.ml]: Looks good to me!

**Review by Leonidas-from-XIV — APPROVED** [review]
