### PR TITLE
fix(pkg): print depexts message when a program is not found

### LINKED ISSUE #10988: pkg: No depexts message when the command is not found.
## Expected Behavior 

```
File "dune.lock/conf-r.pkg", line 4, characters 6-7:
4 |  (run R CMD BATCH check.r))
          ^
Error: Program R not found in the tree or in PATH
 (context: default)

You may want to verify the following depexts are installed:
- r-base-core
```

## Actual Behavior
Printing
```
File "dune.lock/conf-r.pkg", line 4, characters 6-7:
4 |  (run R CMD BATCH check.r))
          ^
Error: Program R not found in the tree or in PATH
 (context: default)
```

## Reproduction
```
curl https://get.dune.build/install | bash
dune init proj depext_test
# add conf-r to dune-project and bin/dune
dune pkg lock
dune build
```

## Additional information
When replacing `R` inside `dune.lock/conf-r.pkg` by `dune`.  it prints what was intended,  the depexts message above.

```
File "dune.lock/conf-r.pkg", line 4, characters 6-10:
4 |  (run dune CMD BATCH check.r))
          ^^^^
Error: Logs for package conf-r
dune: unknown command 'CMD', must be one of 'build', 'cache', 'clean', 'coq', 'describe', 'diagnostics', 'exec', 'external-lib-deps', 'fmt', 'format-dune-file', 'help', 'init', 'install', 'installed-libraries', 'internal', 'monitor', 'ocaml', 'ocaml-merlin', 'pkg', 'printenv', 'promote', 'promotion', 'rpc', 'rules', 'runtest', 'show', 'shutdown', 'subst', 'test', 'top', 'uninstall', 'upgrade' or 'utop'.
Usage: dune COMMAND …
Try 'dune --help' for more information.

You may want to verify the following depexts are installed:
- r-base-core
```

### PR DESCRIPTION
**Pull request by moyodiallo**
Fixes #10988.

### CODE REVIEW

File: src/dune_rules/pkg_rules.ml [hunk 1]
```diff
@@ -702,7 +709,11 @@ module Run_with_path = struct
       let open Fiber.O in
       let display = !Clflags.display in
       match prog with
-      | Error e -> Action.Prog.Not_found.raise e
+      | Error e ->
+        let _, loc = pkg in
+        let depexts_msg = if List.is_empty depexts then [] else Depexts.message depexts in
+        let error_msg = (Action.Prog.Not_found.message e).paragraphs in
+        raise (User_error.E (error_msg @ depexts_msg |> User_message.make ~loc))
```
Comment (gridbugs) [inline src/dune_rules/pkg_rules.ml:716]: It might be simpler to set the `hint` field of `e`. The benefit is that it would let us avoid adding new code to the engine.

Comment (maiste) [reply src/dune_rules/pkg_rules.ml:716]: Is there a particular reason to not use `User_error.raise`? I feel it makes the code easier to mentally parse.

Comment (moyodiallo) [reply src/dune_rules/pkg_rules.ml]: The suggestion of @gridbugs was good one that simplifies the code.
