### PR TITLE
Fix #2974

### LINKED ISSUE #2974: Missing "-I stdlib" when building OCaml compiler tree
As discussed with @diml there appears to be a regression from dune 2.0.0 to 2.1.0 seen when building the OCaml compiler.  It looks like "`-I stdlib`" is now omitted from the command line, leading to an error about `std_exit.cmx` being missing.

Using 2.1.0 (note missing "`-I stdlib`"):
```
$ (cd _build/default && <path>/ocamlopt.opt -w
@1..3@5..28@30..39@43@46..47@49..57@61..62-40 -strict-sequence -strict-formats
-short-paths -keep-locs -w +a-4-9-40-41-42-44-45-48 -principal -nostdlib -g -o
tools/make_opcodes.exe stdlib/stdlib.cmxa runtime/runtimeopt.cmxa -I runtime
tools/.make_opcodes.eobjs/native/dune__exe.cmx
tools/.make_opcodes.eobjs/native/dune__exe__Make_opcodes.cmx)
```
This fails with:
```
File "_none_", line 1:
Error: Cannot find file std_exit.cmx 
```

Using 2.0.0:
```
(cd _build/default && <path>/ocamlopt.opt -w
@1..3@5..28@30..39@43@46..47@49..57@61..62-40 -strict-sequence -strict-formats
-short-paths -keep-locs -w +a-4-9-40-41-42-44-45-48 -principal -nostdlib -g -o
tools/make_opcodes.exe -I runtime -I stdlib stdlib/stdlib.cmxa
runtime/runtimeopt.cmxa tools/.make_opcodes.eobjs/native/dune__exe.cmx
tools/.make_opcodes.eobjs/native/dune__exe__Make_opcodes.cmx)
```

### PR DESCRIPTION
**Pull request by ghost**
We used to pass all `-I` for all library dependencies when linking an executable. Since 2.1, we only pass `-I` for library dependencies that have C stubs.

The stdlib doesn't have C stubs, however it has the `std_exit.cmx` module that is looked up, so we still need to pass a `-I` for the stdlib. This PR fixes this.

It's a bit difficult to test, so I didn't write a test for this, but I checked that it fixes `dune build @world` in the OCaml compiler.

### CODE REVIEW

**Comment by diml** [comment]
I also removed the test building the stdlib without a `stdlib.ml` file as this test was broken and we don't care about this case anyway. Indeed, the real stdlib has a `stdlib.ml` file.

File: src/dune/lib.ml [hunk 1]
```diff
@@ -426,17 +426,26 @@ module Link_params = struct
...
-        dirs lib_files
+      let files =
+        match Lib_info.exit_module t.info with
+        | None -> files
+        | Some _ ->
+          (* The exit module is copied next to the archive, so we add the
+             archive here so that its directory ends up in [include_dirs]. *)
+          files @ deps
+      in
+      (* TODO: Remove the above unsafe call to [parent_exn] by separating files
```
Comment (snowleopard) [inline src/dune/lib.ml]:
```suggestion
      (* TODO: Remove the below unsafe call to [parent_exn] by separating files
```

**Review by snowleopard — APPROVED** [review]
Looks good!
