### PR TITLE
Better error message for old versions of Git

### LINKED ISSUE #10976: dune pkg: improve behavior when available git is too old
When trying the dune developer preview I had to do a manual upgrade of `git`. The git that's packaged by `ubuntu 20.04.6 LTS` is too old for `dune pkg`.

```sh
$ /usr/bin/git --version
git version 2.25.1
```

`dune pkg lock` resulted in an internal error for me, displaying the "I must not crash" poem.

<summary>
<details>
<pre>
$ dune pkg lock
Internal error, please report upstream including the contents of _build/log.
Description:
  ("git returned non-zero exit code",
   { exit code = 129
   ; dir = External "/home/mathieu/.cache/dune/git-repo"
   ; git = External "/usr/bin/git"
   ; args =
       [ "fetch"
       ; "--no-write-fetch-head"
       ; "https://github.com/ocaml-dune/opam-overlays.git"
       ; "9bad4501e6dd4feb7b61b48d29812241d1d711f9"
       ]
   ; output = []
   })
Raised at Stdune__Code_error.raise in file
  "otherlibs/stdune/src/code_error.ml", line 10, characters 30-62
Called from Fiber__Core.O.(>>|).(fun) in file "vendor/fiber/src/core.ml",
  line 253, characters 36-41
Called from Fiber__Scheduler.exec in file "vendor/fiber/src/scheduler.ml",
  line 76, characters 8-11
Re-raised at Stdune__Exn.raise_with_backtrace in file
  "otherlibs/stdune/src/exn.ml" (inlined), line 38, characters 27-56
Called from Stdune__Exn_with_backtrace.reraise in file
  "otherlibs/stdune/src/exn_with_backtrace.ml", line 20, characters 33-71
Called from Fiber__Scheduler.exec in file "vendor/fiber/src/scheduler.ml",
  line 76, characters 8-11

I must not crash.  Uncertainty is the mind-killer. Exceptions are the
little-death that brings total obliteration.  I will fully express my cases. 
Execution will pass over me and through me.  And when it has gone past, I
will unwind the stack along its path.  Where the cases are handled there will
be nothing.  Only I will remain.
</pre>
</details>
</summary>

I think in this git version, `git fetch` doesn't know the `--no-write-fetch-head` flag.

It would be nice if `dune` warned you somehow, instead of throwing some internal error. What's the minimal version that `dune pkg` requires?

Upgrading git to `2.46.2` fixed it, I am not blocked on this.

### PR DESCRIPTION
**Pull request by Sudha247**
Old versions of git don't support the `--no-write-fetch-head` flag. This patch detects this particular failure and prints an error message hinting that. Fixes #10976. Prints the following error message --

```
Error: Your git version doesn't support the '--no-write-fetch-head' flag.
Hint: Please update your git version.
```

### CODE REVIEW

File: boot/libs.ml
Comment (maiste) [inline boot/libs.ml:1]: This file should be removed from your commits.

File: src/dune_pkg/rev_store.ml [hunk 1]
```diff
@@ -168,14 +168,34 @@ end
...
+    match exit_code with
+    | 129
+      when String.is_prefix ~prefix:"error: unknown option `no-write-fetch-head'" stderr
+      ->
+      User_error.raise
+        [ Pp.text "Your git version doesn't support the '--no-write-fetch-head' flag." ]
+        ~hints:[ Pp.text "Please update your git version." ]
+    | _ ->
+      ();
+      Error { Git_error.dir; args; exit_code; output = [] })
```
Comment (maiste) [inline src/dune_pkg/rev_store.ml:198]:
```suggestion
    | _ -> Error { Git_error.dir; args; exit_code; output = [] })
```
Maybe I misunderstand something: why do you need `()`?

File: src/dune_rules/setup.defaults.ml [hunk 2]
```diff
@@ -11,7 +11,7 @@ let roots : string option Install.Roots.t =
   ; libexec_root = None
   }
 
+let prefix : string option = None
```
Comment (maiste) [inline src/dune_rules/setup.defaults.ml:14]: Is it necessary to add the type here? I don't see where it is used in the code above.

Comment (Leonidas-from-XIV) [reply src/dune_rules/setup.defaults.ml:14]: This seems to be an unrelated change that happens due to the changes from #11172. I've created a PR to commit it separately: #11198.

**Review by Leonidas-from-XIV — CHANGES_REQUESTED** [review]
Nice. I like that it doesn't add additional calls to detect that flag!

Added some comments to improve and probably needs to either be rebased on #11198 when it is merged or just exclude the change to `setup.default.ml`.

File: src/dune_pkg/rev_store.ml [hunk 3]
```diff
@@ -168,14 +168,34 @@ end
...
   if allow_codes exit_code
   then Ok exit_code
-  else Error { Git_error.dir; args; exit_code; output = [] }
+  else (
+    match exit_code with
+    | 129
+      when String.is_prefix ~prefix:"error: unknown option `no-write-fetch-head'" stderr
+      ->
+      User_error.raise
+        [ Pp.text "Your git version doesn't support the '--no-write-fetch-head' flag." ]
```
[the remark this answers is not in the document]
Comment (Sudha247) [reply src/dune_pkg/rev_store.ml]: Makes sense, done.

File: src/dune_pkg/rev_store.ml (hunk 1 above)
Comment (Sudha247) [reply src/dune_pkg/rev_store.ml]: Missed it during refactoring a previous attempt. Removed now. Nice spot!

File: src/dune_pkg/rev_store.ml [hunk 4]
```diff
@@ -168,14 +168,34 @@ end
...
+        | Error exn -> raise exn
+        | Ok path ->
+          let stderr_to = Process.Io.file path Out in
+          let+ (), exit_code =
+            Process.run ~dir ~display ~stdout_to ~stderr_to ~env failure_mode git args
+          in
+          Stdune.Io.read_file path, exit_code)
+      ~prefix:"dune"
+      ~suffix:"run_with_exit_code"
+      ~dir:(Path.of_string (Filename.get_temp_dir_name ()))
```
[the remark this answers is not in the document]
Comment (Sudha247) [reply src/dune_pkg/rev_store.ml:184]: As far as I can tell, it'd be computed the same number of times if it were in the function definition - I checked it with some debug prints, but maybe I'm missing something.

**Review by maiste — APPROVED** [review]
LGTM :+1: 
(CI issue is unrelated to this PR)
