### PR TITLE
fix(coq): make loading of theories in scope lazier 

### LINKED ISSUE #7747: regression: coq-stdlib.8.17.0
Hi,

`coq-stdlib.8.17.0` does not build correctly with `dune.3.8.0~alpha3`, while it did with `3.7.1`.
See [this build](https://toxis.caelum.ci.dev/github/ocaml/opam-repository/commit/b442a4abc1e8535be3f0490fd4ac4311c31650f3/variant/compilers,4.14,dune-configurator.3.8.0~alpha3,revdeps,coq-stdlib.8.17.0).

```
#=== ERROR while compiling coq-stdlib.8.17.0 ==================================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.4.14.1 | file:///home/opam/opam-repository
# path                 ~/.opam/4.14/.opam-switch/build/coq-stdlib.8.17.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build ./configure -prefix /home/opam/.opam/4.14 -mandir /home/opam/.opam/4.14/man -libdir /home/opam/.opam/4.14/lib/coq -native-compiler no
# exit-code            1
# env-file             ~/.opam/log/coq-stdlib-7-f87a35.env
# output-file          ~/.opam/log/coq-stdlib-7-f87a35.out
### output ###
# cannot guess a path for Coq libraries; please use -coqlib option or ensure you have installed the package containing Coq's stdlib (coq-stdlib in OPAM) If you intend to use Coq without a standard library, the -boot -noinit options must be used.
# Error: Error while running /home/opam/.opam/4.14/bin/coqc --config
# Exit code: 1
# Output:
# 
```

I bisected that to 98de95004d753a3e30b0f4a3bbb09312541e892b (#7047).

@Alizter can you have a look?

### PR DESCRIPTION
**Pull request by Alizter**
We make the loading of theories even lazier in scope.ml. This required refactoring the coq db into a Memo.Lazy.t. I'm open to a better way of doing this but this at least fixes the bug observed in #7747 and #7748.

I added a test case for #7747 and showed that this patch fixes it also.

This PR fixes the following issues, however they will be closed on a new run of the opam ci:
- #7747 
- #7748

### CODE REVIEW

File: src/dune_rules/scope.ml [hunk 1]
```diff
@@ -289,14 +290,15 @@ module DB = struct
...
+      Memo.lazy_ @@ fun () ->
+      let+ public_theories = Memo.Lazy.force public_theories in
+      coq_scopes_by_dir db_by_project_dir projects_by_dir public_theories
+        coq_stanzas
     in
     let coq_db_find dir =
-      lazy
-        (let map = Lazy.force coq_scopes_by_dir in
-         Path.Source.Map.find_exn map dir)
+      Memo.lazy_ @@ fun () ->
```
Comment (anmonteiro) [inline src/dune_rules/scope.ml:299]: I think you can use `Memo.Lazy.map` here.

File: src/dune_rules/scope.ml [hunk 2]
```diff
@@ -289,14 +290,15 @@ module DB = struct
              (project, db))
     in
     let coq_scopes_by_dir =
-      lazy
-        (coq_scopes_by_dir db_by_project_dir projects_by_dir public_theories
-           coq_stanzas)
+      Memo.lazy_ @@ fun () ->
```
Comment (anmonteiro) [inline src/dune_rules/scope.ml:293]: I think you can use Memo.Lazy.map here.

File: src/dune_rules/scope.ml [hunk 3]
```diff
@@ -163,7 +163,9 @@ module DB = struct
          ~parent:(Some installed_theories)
 
   let public_theories ~find_db ~installed_theories coq_stanzas =
-    lazy (public_theories ~find_db ~installed_theories coq_stanzas)
+    Memo.lazy_ @@ fun () ->
```
Comment (anmonteiro) [inline src/dune_rules/scope.ml:166]: I think you can use Memo.Lazy.map here.

**Review by ejgallego — APPROVED** [review]
Thanks a lot for the quick fix @Alizter , code looks good to me, and indeed the new type seems like the right one.

Sorry for the oversight in the initial implementation.

**Comment by ejgallego** [comment]
> fixes https://github.com/ocaml/dune/issues/7747

should also fix the other one, tho your previous PR did also fix that one, so maybe we can mark both PRs as fixing that bug.

**Comment by Alizter** [comment]
Actually, I will let @emillon close those since he will do another opam build.

**Comment by ejgallego** [comment]
> Actually, I will let @emillon close those since he will do another opam build.

Changelog / PRs description should reflect bugs numbers tho, right?

**Comment by Alizter** [comment]
I'll mention them in the PR description but we don't need a changelog since we are fixing a bug about a feature we just introduced in this version.

**Comment by Alizter** [comment]
OK so in the first case, the first error is the one we want, however because it is very lazy it is being delayed until rule loading causing it to emit both errors. Ideally we would want only the first error like before. Not sure what the best way to fix this is. Perhaps during rule loading, we can force the database to be constructed.

The second one also looks like a straight up bug.

**Comment by ejgallego** [comment]
Indeed our current approach to side-effects seems kind of fragile, I do dislike the style where we recover the scope imperatively inside coq_rules helper functions. We should make sure the library resolution is actually memoized, and we are not scanning twice. We resolve now the Coq DB a lot of times per-module, so beware of performance impact.

I would be much more comfortable if we would try to resolve a bit more in the top-level (but again this needs to be done with care)

As for the second error, that's indeed strange, is the test running with the cache enabled?

Indeed we may have a soundness bug here, as the DB build needs to depend on the contents of the directories that are in COQPATH and user contrib. (Rules should already depend on that)

**Comment by Alizter** [comment]
@ejgallego I'm not sure there will be a perf impact since the database we are resolving is memod.

The other test does not have caching enabled.

**Comment by ejgallego** [comment]
> I'm not sure there will be a perf impact since the database we are resolving is memod.

I meant we should make sure the DB is memoed properly.

> The other test does not have caching enabled. (as in behaves the same when explicitly disabling)

I see thanks.

> @ejgallego I'd appreciate if you could take a look since I am not sure what more I can do here any longer.

I did have a look and I have no idea what is going on.

I need to leave now, I'd try to put a few printfs in the DB creation code to try to see if the DB code is called and with what paths.

**Comment by ejgallego** [comment]
Thanks @emillon , @Alizter if we don't get the cycles to look at why the DB is being too lazy in this case, IMHO it is fine to open an issue and get 3.8.0 like this, WDTY?

**Comment by Alizter** [comment]
I don't mind the "multiple rules generated" error message since that is just extra noise essentially, however the other error is a bit more serious. In that case, the duplicate checking in the install directory isn't being carried out, so I would prefer to fix that.

**Comment by Alizter** [comment]
OK so the missing duplicate checking was actually an incorrectly set up test. Good thing we caught it. I've fixed that and a few other tests now. I will have a look at the multiple rules issue now.

**Comment by ejgallego** [comment]
Great work, thanks @Alizter . Indeed the duplicate target error is a bit annoying but really a corner case, if someone complains we can fine-tune it easily.
