### PR TITLE
fix: name suggestion on opam context

### LINKED ISSUE #10721: Add a hint to context name error
## Context

Hi,
When you specify an `Opam` switch with a _path_ instead of a `name`:
```dune
(context
  (opam
    (switch /path/to/switch)))
```
you get the following error message:
```
Error: Generated context name "/path/to/switch" is invalid
Please specify a context name manually with the (name ..) field
```

## Modification proposed

There are two modifications (discussed on the ocamllabs slack), we could make to improve the readability:
- Add `The generated context name "..." from the switch name is invalid` to the error message
- Provide a hint about it: `Hint: you may want to add (name switch-name)`

The message would be the following:
```
Error: Generated context name
"/path/to/switch" is invalid
The generated context name "/path/to/switch" from the switch name is invalid.
Please specify a context name manually with the (name ..) field

Hint: you may want to add (name switch-name) 
```

### PR DESCRIPTION
**Pull request by maiste**
Hi,
This PR fixes #10721. It provides more information when someone set a switch using an absolute path.
The new error message is:
```
Error: Generated context name
"/path/to/switch" is invalid
The generated context name "/path/to/switch-name" from the switch name is invalid.
Please specify a context name manually with the (name ..) field
Hint: you may want to add (name switch-name) 
```

### CODE REVIEW

**Comment by emillon** [comment]
Thanks. Can you add a test for this?

File: src/dune_rules/workspace.ml [hunk 1]
```diff
@@ -462,6 +462,14 @@ module Context = struct
       Common.equal base t.base && Opam_switch.equal switch t.switch
     ;;
 
+    let name_hint_opt name =
+      if name <> "" && String.contains name '/'
```
Comment (emillon) [inline src/dune_rules/workspace.ml:466]: The test for `""` is unnecessary, but what do you think about just checking at the beginning for absolute paths? (`String.is_prefix ~prefix:"/"`)

File: src/dune_rules/workspace.ml [hunk 2]
```diff
@@ -479,7 +487,10 @@ module Context = struct
              | None ->
                User_error.raise
                  ~loc:loc_switch
-                 [ Pp.textf "Generated context name %S is invalid" name
+                 ?hints:(name_hint_opt name)
```
Comment (emillon) [inline src/dune_rules/workspace.ml:490]: There's an opportunity to refactor to use `Context_name.of_string_user_error` instead of `of_string_opt` (see `Stringlike_intf`).
Then you can use the `Stringlike` API to implement that hint, by defining a `hint_valid` function (which can use your basename implementation if the string looks like an absolute path, or something less elegant otherwise)

File: src/dune_rules/workspace.ml (hunk 1 above)
Comment (maiste) [reply src/dune_rules/workspace.ml:466]: Is it necessary an absolute or could it work with relative path?

Comment (emillon) [reply src/dune_rules/workspace.ml:466]: I think that opam switch names are either absolute paths (local switches) or strings without `/` (global switches), but there might be other code paths that try to build context names from user input.

Comment (maiste) [reply src/dune_rules/workspace.ml:466]: I think we can keep the heuristic that it starts with a `/` then as the last scenario seems uncommon.

File: src/dune_rules/workspace.ml (hunk 2 above)
Comment (maiste) [reply src/dune_rules/workspace.ml:490]: After investigating, I will finally keep the error like this. Indeed, if I take this path, the error would look like: 
```
File "dune-workspace", line 5, characters 12-45:
5 |     (switch /path/to/the/opam/switch/named/dune)))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: "/path/to/the/opam/switch/named/dune" is an invalid context name.
It must not be empty, be the exact string "log", contain slashes, contain
backslashes or start with the symbol  ".".
Hint: (name dune) would be a correct context name
```
It makes the error message more obscure as it totally eclipse the context where it happens...

Comment (emillon) [reply src/dune_rules/workspace.ml:490]: Sorry, what's specifically wrong about that error message? You don't have to define `description_of_valid_string` if it doesn't make sense.

File: test/blackbox-tests/test-cases/github10721.t [hunk 3]
```diff
@@ -0,0 +1,21 @@
+
+  $ cat > dune-project << EOF
+  > (lang dune 3.0)
+  > EOF
+
+  $ cat > dune-workspace << EOF
+  > (lang dune 3.0)
+  > (context
+  >   (opam
```
Comment (emillon) [inline test/blackbox-tests/test-cases/github10721.t:9]: we use a 1 space indent in the test suite

File: test/blackbox-tests/test-cases/github10721.t [hunk 4]
```diff
@@ -0,0 +1,21 @@
...
+  >     (switch /absolute/path/to/opam/switch)))
+  > EOF
+
+  $ dune build
+  File "dune-workspace", line 4, characters 12-41:
+  4 |     (switch /absolute/path/to/opam/switch)))
+                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
+  Error: The generated context name "/absolute/path/to/opam/switch" from the
+  switch name is invalid.
```
Comment (emillon) [inline test/blackbox-tests/test-cases/github10721.t:18]: How about: this switch name can not be used as a context name?

File: src/dune_rules/workspace.ml (hunk 2 above)
Comment (maiste) [reply src/dune_rules/workspace.ml:490]: Yes, I can remove it, but, IMHO, this is not the problem here. If we remove the `match ... with` we lost the information about the fact that the user should add `(name ...)` field in case we don't have it in the `(opam (switch ...))` context.

I don't know a way to specify this using the `Stringlike` API as the `hint_valid` name, insert a suggestion into an already existing string: `Format.sprintf "%s would be a correct context name" (f_extracted_from_hint_valid s)`.  I attempt to modify the `hint_valid` function with my `name_hint_opt` function, but the result does not look informative enough (as you can see in the output above).

Furthermore, I don't see a way to specify the additional message, as it was suggested in the original discussion on Slack:
```
The generated context name "..." from the switch name is invalid, Please specify a context name manually with the (name ..) field.
```
This message makes sens because the user has the information that the name what generated from the `switch` and that it should manually add the `(name ...)` field. Maybe I'm misunderstanding how the `Stringlike` API work and there is a more elegant way to do it? :confused:

File: test/blackbox-tests/test-cases/github10721.t (hunk 4 above)
Comment (maiste) [reply test/blackbox-tests/test-cases/github10721.t:18]: I think this is the same issue we have in https://github.com/ocaml/dune/pull/10723#discussion_r1678073928: users won't understand why Dune is talking about `context  name` whereas we never express a context name. The information that it generated and that we need a `(name ...)` to prevent the automatic generation should be mandatory IMO.

Comment (emillon) [reply test/blackbox-tests/test-cases/github10721.t:18]: Ok, then how about something like this:

> This switch name can not be used as a context name. Please use (name) to disambiguate
> Hint: (name xxx) would be a valid context name

Something like that.

My points are:
- we don't need to repeat the switch name because it's pointed by the loc in the error message
- It's clear that we're defining a context. We're in a `(context)` field.

File: src/dune_rules/workspace.ml (hunk 2 above)
Comment (emillon) [reply src/dune_rules/workspace.ml:490]: let's scratch that idea, it's just an implementation detail

**Comment by emillon** [comment]
Can you open a PR with just the test? it will show how this PR changes the error message.

File: test/blackbox-tests/test-cases/github10721.t (hunk 4 above)
Comment (maiste) [reply test/blackbox-tests/test-cases/github10721.t:18]: I agree with this message, but I would still emphases the fact it is auto generated. I would add:

> The name generated from this switch can not be used as a context name. Please use (name) to disambiguate
> Hint: (name xxx) would be a valid context name

WDYT?

I agree on both of your points :+1:

Comment (emillon) [reply test/blackbox-tests/test-cases/github10721.t:18]: Yes, that would work

**Comment by maiste** [comment]
I pushed the fixes and opened the test PR :+1:

**Review by emillon — APPROVED** [review]

**Comment by emillon** [comment]
Thanks!
