### PR TITLE
fix(cram): remove cram file after it is read

### LINKED ISSUE #4776: `runtest` in tests behave badly when using `dune lang 3.0`
On `main`, when in a test using dune lang `3.0`, calling `dune runtest` from inside the test triggers an unexpected diff with the `run.t` file itself, as if the sandbox was breached.

Here is a test illustrating the issue:
```lisp
  $ cat >dune-project <<EOF
  > (lang dune 2.8)
  > EOF

  $ cat >dune <<EOF
  > (rule
  >  (alias runtest)
  >  (action (diff hello.expected hello.output)))
  > EOF

  $ echo 'foo' > hello.expected 
  $ echo 'foo' > hello.output 

  $ dune runtest

  $ cat >dune-project <<EOF
  > (lang dune 3.0)
  > EOF

  $ dune runtest
  File "run.t", line 1, characters 0-0:
  Error: Files _build/default/run.t and _build/default/run.t.corrected differ.
  [1]
```

I discovered this while writing tests for the new mds stanza. It sometimes led me to an infinite nesting of sandbox folders:
```
_build/.sandbox/40844c15a584a31fa740640e0eb87c89/default/test/blackbox-tests/test-cases/mdx-stanza/new-deps-field.t
/_build/.sandbox/4d7d3316b70f5fc71abfb2d8c509c0d9/default/_build/.sandbox/4d7d3316b70f5fc71abfb2d8c509c0d9
/default/_build/.sandbox/4d7d3316b70f5fc71abfb2d8c509c0d9/default/_build/.sandbox
/4d7d3316b70f5fc71abfb2d8c509c0d9/default/_build/.sandbox/4d7d3316b70f5fc71abfb2d8c509c0d9/default/_build
/.sandbox/4d7d3316b70f5fc71abfb2d8c509c0d9/default/_build/.sandbox/4d7d3316b70f5fc71abfb2d8c509c0d9/default
/_build/.sandbox/4d7d3316b70f5fc71abfb2d8c509c0d9/default/_build/.sandbox/4d7d3316b70f5fc71abfb2d8c509c0d9
/default/_build/.sandbox/4d7d3316b70f5fc71abfb2d8c509c0d9/default/_build/.sandbox
/4d7d3316b70f5fc71abfb2d8c509c0d9/default/_build/.sandbox/4d7d3316b70f5fc71abfb2d8c509c0d9/default/_build
/.sandbox/4d7d3316b70f5fc71abfb2d8c509c0d9/default/_build/.sandbox/4d7d3316b70f5fc71abfb2d8c509c0d9/default
/_build/.sandbox/4d7d3316b70f5fc71abfb2d8c509c0d9/default/_build/.sandbox/4d7d3316b70f5fc71abfb2d8c509c0d9/
```

However I am not sure yet what triggers the infinite nesting.

If i add another `$ dune runtest` at the end of the test it just hangs with 100% cpu.

### PR DESCRIPTION
**Pull request by rgrinberg**
tests shouldn't be able to observe the test files

Fix #4776

### CODE REVIEW

**Comment by rgrinberg** [comment]
@jeremiedimino I modified this to restore the test file if there's a diff. Seems to work fine.

**Comment by jeremiedimino** [comment]
Cool

File: src/dune_rules/cram_exec.ml [hunk 1]
```diff
@@ -135,6 +135,13 @@ let cram_stanzas lexbuf =
 
 let run_expect_test file ~f =
   let file_contents = Io.read_file ~binary:false file in
+  (* nasty hack so that the user doesn't observe the test file he's running.
```
Comment (jeremiedimino) [inline src/dune_rules/cram_exec.ml:138]: we don't know the user's gender:

```suggestion
  (* nasty hack so that the user doesn't observe the test file they are running.
```

File: src/dune_rules/cram_exec.ml [hunk 2]
```diff
@@ -135,6 +135,13 @@ let cram_stanzas lexbuf =
 
 let run_expect_test file ~f =
   let file_contents = Io.read_file ~binary:false file in
+  (* nasty hack so that the user doesn't observe the test file they are running.
+
+     Eventually, we should just have a way to read the source from outside the
+     sandbox. *)
+  let temp_dir = Temp.create Dir ~prefix:"cram-staging" ~suffix:"" in
```
Comment (jeremiedimino) [inline src/dune_rules/cram_exec.ml:142]: Shouldn't we delete `temp_dir` eventually?

BTW, we already have the whole file contents in memory (in the variable `file_contents`), so instead of moving it we could simply delete it and re-create it with `Io.write_file` in case of mismatch.

**Review by jeremiedimino — CHANGES_REQUESTED** [review]

File: src/dune_rules/cram_exec.ml (hunk 2 above)
Comment (rgrinberg) [reply src/dune_rules/cram_exec.ml]: The temp_dir is deleted on at_exit. I still changed to it to use write_file

Comment (jeremiedimino) [reply src/dune_rules/cram_exec.ml]: We should still delete temporary things when we know they are no longer needed, to avoid holding on to leftover temporary files and directories for too long. This is especially important when using the watch mode.

**Review by jeremiedimino — APPROVED** [review]
Looks good
