### PR TITLE
fix(pkg): remove wildcard behaviour for sys vars

### LINKED ISSUE #8765: Remove wildcard behaviour for solver system environment variables
The current behaviour of the dependency solver is to treat comparisons against any unset system environment variables as "true". The goal of this behaviour is to produce lockdirs that will work on as many systems as possible, but it creates some strange behaviour in some cases.

E.g.
```
depends: [
  "uring" {os = "linux"}
  "luv" {!(os = "linux")}
]
```

The current behaviour would always pick `uring` and never pick `luv`.

Generic lockdirs isn't part of the MVP and since trying to support it is leading to this problem let's simplify things by requiring each system environment variable to be assigned a specific value while solving dependencies. The value should be derived from the current system by default but it should be possible to override variables in the build context (ie. configuration in the `dune-workspace` file).

### PR DESCRIPTION
**Pull request by gridbugs**
Fixes https://github.com/ocaml/dune/issues/8765

### CODE REVIEW

File: bin/pkg.ml [hunk 1]
```diff
@@ -438,22 +390,15 @@ module Lock = struct
...
-              "Set opam system environment variables based on the current system when \
-               solving dependencies. This will restrict packages to just those which can \
-               be installed on the current system. Note that this will mean that the \
-               generated lockdir may not be compatible with other systems. If the build \
-               context(s) specify system environment variables then the solver will use \
-               the union of the environment variables inferred from the current system \
-               and the environment variables set in the build context(s). If the current \
-               system and the build context(s) disagree on the value of an environment \
-               variable then an error is raised.")
+              "Don't derive system solver variables from the current system. Values \
```
Comment (rgrinberg) [inline bin/pkg.ml:400]: Could you explain the option a bit more?

What happens when the solver needs to evaluate `%{os}` and we passed this option.

Comment (gridbugs) [reply bin/pkg.ml:418]: I've updated the description. Hopefully it is clearer now.
