### PR TITLE
pkg: don't recreate Pkg_rules.DB values

### LINKED ISSUE #12693: pkg: Performance regression in no-op builds when using dune package management
## Expected Behavior

Once all dependencies have been installed, there should be virtually no observable perf difference between running `dune build` in a project with and without use of dune package management. 

We agree that ~500ms penalty seems like a generous allowance at the outer limit. So to fix this, if bring perf of null builds using dune package management to within 500ms of using opam for package management, we will solve this.

## Actual Behavior

There is a degradation of 3 orders of magnitude in the build perf of no-op builds between these two scenarios:

- A: Using `dune pkg` to managed dependencies via `dune pkg lock`
- B: Only using opam to manage dependencies

I.e.:

- In case (A) null `dune build` take less than 1 second.
- In case (B) null `dune build` runs can take nearly 13 seconds.

Here's some bench-marking on my old Mac laptop. I am running all the builds on the main branch of [mirage/ocaml-cohttp](https://github.com/mirage/ocaml-cohttp).

### Version `3.20.2` using opam deps

The released version

```
$ opam switch create . # approximate set up
$ dune --version 
3.20.2
$ dune build 
$ hyperfine "dune build"      
Benchmark 1: dune build
  Time (mean ± σ):     850.6 ms ±  30.8 ms    [User: 603.6 ms, System: 221.1 ms]
  Range (min … max):   784.5 ms … 911.6 ms    10 runs
```

## Version `2025-11-06T02:31:54Z` with a lock directory

The latest nightly (at the time), using `dune pkg`

```
$ rm -rf _opam # and other measures to be sure I am not in a switch managing the deps 
$ dune --version 
"Dune Developer Preview: build 2025-11-06T02:31:54Z, git revision
25157844468bcf5706e1a498fd9eb18e935d87f5"
$ dune pkg lock 
$ dune build                                    
$ hyperfine "dune build"
Benchmark 1: dune build
  Time (mean ± σ):     12.289 s ±  0.107 s    [User: 8.696 s, System: 3.530 s]
  Range (min … max):   12.135 s … 12.474 s    10 runs
$ dune build --verbose # just to show it's not reporting pkg install during the build
Shared cache: enabled
Shared cache location: .../.cache/dune/db
Workspace root: .../mirage/ocaml-cohttp
Auto-detected concurrency: 12
Dune context:
 { name = "default"
 ; kind = lock { default = true }
 ; profile = Dev
 ; merlin = true
 ; fdo_target_exe = None
 ; build_dir = In_build_dir "default"
 ; instrument_with = []
 }
Actual targets:
- alias @@default
```

## Version [`b202280`](https://github.com/ocaml/dune/commit/b202280451141e33ecd99e831ccc576028eb0f7b) using opam deps

```
$ opam switch create . # approximate setup
$ dune --version
...-gb202280
$ dune build
$ hyperfine --warmup 5 "dune build"       
Benchmark 1: dune build
  Time (mean ± σ):     853.2 ms ±   1.5 ms    [User: 599.4 ms, System: 230.8 ms]
  Range (min … max):   850.3 ms … 855.8 ms    10 runs
```

## Version [`b202280`](https://github.com/ocaml/dune/commit/b202280451141e33ecd99e831ccc576028eb0f7b) using dune pkg

```
$ rm -rf _opam # and other measures to be sure I am not in a switch managing the deps
$ dune --version
...-gb202280
$ dune pkg lock
$ dune build
$ hyperfine --warmup 5 "dune build"
Benchmark 1: dune build
  Time (mean ± σ):      9.574 s ±  0.061 s    [User: 5.896 s, System: 3.626 s]
  Range (min … max):    9.491 s …  9.685 s    10 runs
$ dune build --verbose 
Shared cache: enabled
Shared cache location: /Users/sf/.cache/dune/db
Workspace root: /Users/sf/Repos/mirage/ocaml-cohttp
Auto-detected concurrency: 12
Dune context:
 { name = "default"
 ; kind = lock { default = true }
 ; profile = Dev
 ; merlin = true
 ; fdo_target_exe = None
 ; build_dir = In_build_dir "default"
 ; instrument_with = []
 }
Actual targets:
- alias @@default
```

### PR DESCRIPTION
**Pull request by Alizter**
This table is only created and used twice. We add an Id.t field so that
it can easily be compared later when it's values are memoized in the
of_ctx call.

The old hash and equality functions were expensive an unnecessary.

Before:
```
[ocaml-cohttp]$ hyperfine "dune build"
Benchmark 1: dune build
  Time (mean ± σ):      1.722 s ±  0.043 s    [User: 1.438 s, System: 0.281 s]
  Range (min … max):    1.664 s …  1.814 s    10 runs
```

After:
```
[ocaml-cohttp]$ hyperfine "dune build"
Benchmark 1: dune build
  Time (mean ± σ):      1.064 s ±  0.020 s    [User: 0.790 s, System: 0.274 s]
  Range (min … max):    1.032 s …  1.090 s    10 runs
```

### CODE REVIEW

File: src/dune_rules/pkg_rules.ml [hunk 1]
```diff
@@ -1335,22 +1335,29 @@ module DB = struct
...
+      || (Pkg_table.equal t.pkg_digest_table pkg_digest_table
+          && Package.Name.Set.equal t.system_provided system_provided)
+    ;;
 
-  let hash = `Do_not_hash
-  let _ = hash
-  (* Because t is large, hashing is expensive, so much so that hashing the db in Input.t
-     below slowed down the dune call in the test repo described in #12248 from 1s to
-     2s. *)
+    let hash { pkg_digest_table = _; system_provided = _ } = 0
```
Comment (rgrinberg) [inline src/dune_rules/pkg_rules.ml]: Instead of doing this, how about you just generate an id using Stdune.Id and return that? That way you won't need physical equality and you'll have a decent hash function.

File: src/dune_rules/pkg_rules.ml [hunk 2]
```diff
@@ -1335,22 +1321,40 @@ module DB = struct
...
+
+            let to_dyn { id; pkg_digest_table; system_provided } =
+              Dyn.record
+                [ "id", Id.to_dyn id
+                ; "pkg_digest_table", Dyn.opaque pkg_digest_table
+                ; "system_provided", Dyn.opaque system_provided
+                ]
+            ;;
+          end)
+        Memo.return
```
Comment (rgrinberg) [inline src/dune_rules/pkg_rules.ml]: You don’t need memo if this is your implementation. A regular table would do.

File: src/dune_rules/pkg_rules.ml [hunk 3]
```diff
@@ -1335,22 +1321,24 @@ module DB = struct
...
-  let _ = hash
-  (* Because t is large, hashing is expensive, so much so that hashing the db in Input.t
-     below slowed down the dune call in the test repo described in #12248 from 1s to
-     2s. *)
+  let create =
+    let table = Table.create (module Id) 16 in
+    fun ~pkg_digest_table ~system_provided ->
+      let id = Id.gen () in
+      let t = { id; pkg_digest_table; system_provided } in
+      Table.set table id t;
```
Comment (rgrinberg) [inline src/dune_rules/pkg_rules.ml]: You also need to look up things in this table for it to be useful

Comment (Alizter) [reply src/dune_rules/pkg_rules.ml]: I need to think a bit more about this, I appear to be quite confused.

Comment (Alizter) [reply src/dune_rules/pkg_rules.ml]: I've gotten rid of that table entirely, its useless.

Comment (rgrinberg) [reply src/dune_rules/pkg_rules.ml]: I don't think so. You're still creating this value on every invocation of `of_dev_tool` which isn't memoized.

Comment (Alizter) [reply src/dune_rules/pkg_rules.ml]: Wouldn't the more sensible thing be to just memoize that separately then? Not sure what more I can do from the DB values.

Comment (rgrinberg) [reply src/dune_rules/pkg_rules.ml]: I think that's a bit fragile and loses some sharing. When you're memoizing a create a function, you want to make sure that it's impossible to create the record without going through the memoization, and you want to share the value as much as possible between all the code paths.

**Review by rgrinberg — APPROVED** [review]
The previous code was needlessly convoluted so your attempt at memoization lost sharing. I refactored things to be clearer and gained back the sharing.

**Comment by shonfeder** [comment]
Contributes to #12693
