### PR TITLE
fix(coq): delay boot type detection

### LINKED ISSUE #9818: regression on missing Coq
## Expected Behavior

Consider the following toy demo repository:

https://github.com/vzaliva/coq-dune-examlpe

In an opam switch **without** Coq installed, with dune 3.12.2 it builds without errors using following command:

`dune build -p example-ocaml`

(this is expected)

## Actual Behavior

However, with dune 3.13.0 it gives build error:

```
$ dune build -p example-ocaml
Error: Couldn't find Coq standard library, and theory is not using (stdlib
no)
```

(this is a regression)

It is related to the following bug https://github.com/ocaml/dune/issues/8099
See the discussion there.

## Specifications
```
$ dune --version
3.13.0
$ ocaml --version
The OCaml toplevel, version 4.13.1
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 23.04
Release:	23.04
Codename:	lunar
```
## Additional information 

```
dune build -p example-ocaml --verbose
Shared cache: disabled
Shared cache location: /home/lord/.cache/dune/db
Workspace root: /home/lord/src/coq-dune-examlpe
Auto-detected concurrency: 12
Dune context:
 { name = "default"
 ; kind = "default"
 ; profile = Release
 ; merlin = true
 ; fdo_target_exe = None
 ; build_dir = In_build_dir "default"
 ; installed_env =
     map
       { "INSIDE_DUNE" : "/home/lord/src/coq-dune-examlpe/_build/default"
       ; "OCAML_COLOR" : "always"
       ; "OPAMCOLOR" : "always"
       }
 ; instrument_with = []
 }
Actual targets:
- recursive alias @install
Error: Couldn't find Coq standard library, and theory is not using (stdlib
no)
```

### PR DESCRIPTION
**Pull request by rgrinberg**
Signed-off-by: Rudi Grinberg <me@rgrinberg.com>

Fixes #9818

### CODE REVIEW

File: src/dune_rules/coq/coq_rules.ml [hunk 1]
```diff
@@ -235,25 +235,29 @@ end = struct
...
-  let make ~dir ~use_stdlib ~wrapper_name ~coq_lang_version coq_module =
-    let* scope = Scope.DB.find_by_dir dir in
-    let+ boot_lib =
+  let make ~scope ~use_stdlib ~wrapper_name ~coq_lang_version coq_module =
+    let open Resolve.Memo.O in
+    let* boot_lib =
       Scope.coq_libs scope
+      |> Resolve.Memo.lift_memo
       >>= Coq_lib.DB.resolve_boot ~coq_lang_version
-      |> Resolve.Memo.read_memo
```
Comment (rgrinberg) [inline src/dune_rules/coq/coq_rules.ml:243]: This is a no-no because it break the rules in the entire directory if the library isn't found.

File: src/dune_rules/coq/coq_rules.ml [hunk 2]
```diff
@@ -235,25 +235,29 @@ end = struct
...
       match boot_lib with
       | None ->
         if coq_lang_version >= (0, 8)
         then
-          User_error.raise
-            [ Pp.text
-                "Couldn't find Coq standard library, and theory is not using (stdlib no)"
-            ]
-        else Implicit
+          Resolve.Memo.fail
```
Comment (rgrinberg) [inline src/dune_rules/coq/coq_rules.ml:251]: Instead of raising, we save the error.

File: src/dune_rules/coq/coq_rules.ml [hunk 3]
```diff
@@ -289,7 +293,8 @@ let coqc_file_flags ~dir ~theories_deps ~wrapper_name ~boot_type ~ml_flags
     ; A wrapper_name
     ]
   in
-  [ Bootstrap.flags boot_type; S file_flags ]
+  let boot_flags = Resolve.Memo.read boot_type |> Action_builder.map ~f:Bootstrap.flags in
+  [ Dyn boot_flags; S file_flags ]
```
Comment (rgrinberg) [inline src/dune_rules/coq/coq_rules.ml:297]: And here we resurface the error, but this time only when we try to execute the relevant rule that needs this.

**Comment by emillon** [comment]
FTR, this does fix #9818.

**Review by ejgallego — APPROVED** [review]
Thanks a lot @rgrinberg !

It would be good if we try to push the test case, however I'm unsure how can we make a test such that we ensure `coqc` is not available, maybe we could mock `coqc` to fail, but that's not exactly the same.

**Comment by emillon** [comment]
@ejgallego you can make a `path` directory with just `dune` and `ocamlc` copied from the PATH, and set `PATH` to just that directory. See https://github.com/ocaml/dune/blob/3.13.0/test/blackbox-tests/test-cases/melange/missing-melc.t for example.

**Comment by ejgallego** [comment]
Thanks @emillon ! Will add this test, as this seems like an easy to get wrong case.

@rgrinberg , PR looks ready for merging to me, however a tweak on Coq's test-suite is needed due to the output being more verbose now on error.

**Comment by rgrinberg** [comment]
Sure, feel free to update the output if it looks good to you. I don't have coq installed at the moment.
