### PR TITLE
fix(pkg): validate duplicate lock dirs

### LINKED ISSUE #9356: Forbid duplicate repositories and duplicate lock directory definitions in workspace files

### PR DESCRIPTION
**Pull request by Alizter**
Fixes https://github.com/ocaml/dune/issues/9356

### CODE REVIEW

File: src/source/workspace.ml [hunk 1]
```diff
@@ -993,6 +1002,19 @@ let step1 clflags =
...
+        with
+        | Result.Ok _ -> ()
+        | Error (path, lock_dir1, lock_dir2) ->
+          User_error.raise
+            ~loc:lock_dir2.Lock_dir.loc
+            [ Pp.textf
+                "Lock directory %S is defined multiple times:"
+                (Path.Source.to_string path)
+            ; Pp.enumerate ~f:Loc.pp_file_colon_line [ lock_dir1.loc; lock_dir2.loc ]
+            ]);
```
Comment (shonfeder) [inline src/source/workspace.ml]: nit: As with the other PR, this could potentially be put into a named function with improved.

**Review by shonfeder — APPROVED** [review]

**Review by Leonidas-from-XIV — APPROVED** [review]

File: src/source/workspace.ml (hunk 1 above)
Comment (Alizter) [reply src/source/workspace.ml]: I'm against introducing named functions when they are only used once, but I can add comments to aid readability.

Comment (Alizter) [reply src/source/workspace.ml]: I'll wait for #12548 to be merged, then perhaps we can even share the dupe checker.

Comment (shonfeder) [reply src/source/workspace.ml]: > I'm against introducing named functions when they are only used once

Too bad, as they are a good way to reduce the cognitive load of monster functions. But this is a matter of taste, so no worries.

File: src/source/workspace.ml [hunk 2]
```diff
@@ -965,21 +993,13 @@ let step1 clflags =
...
-                  ~f:Loc.pp_file_colon_line
-                  [ fst (Repository.opam_url repo1); fst (Repository.opam_url repo2) ]
-              ]);
+         check_no_duplicates
+           (module Repository.Name.Map)
+           user_defined_repos
+           ~get_key:Repository.name
+           ~get_loc:(fun repo -> fst (Repository.opam_url repo))
+           ~what:"Repository"
+           ~key_to_string:Repository.Name.to_string;
```
Comment (shonfeder) [inline src/source/workspace.ml]: Hmmm, so IMO this is worse than just inlining the functions. The point of the named function I was suggesting wast to make the code simpler to read and thus make it easier to understand what is being done at a glance.

IMO, any gains on that here (which I'm not sure about, given the amount of arguments that are supplied) are now countered by making the location where the function is actually defined much harder to understand, thanks to all the additional abstractions and language constructs used. The most obvious signs of this added complexity are the sudden appearance of a first class module and locally abstract type! XD

To be clear, my suggestion for a named function was to optimize for code readability, not for code reuse.

If reuse were paramount, this abstraction seems to be on the wrong level, IMO. Something like this would be less heavy

```ocaml
type duplicate_error =
  { kind : string
  ; item : string
  ; loc : Loc.t
  ; loc' : Loc.t
  }

let handle_duplicate_error = function
  | Ok _ -> ()
  | Error { kind; item; loc; loc' } ->
    User_error.raise
      ~loc
      [ Pp.textf "%s %S is defined multiple times:" kind item
      ; Pp.enumerate ~f:Loc.pp_file_colon_line [ loc; loc' ]
      ]
```

Which could then be used to save repetition just in the error reporting (which seems the suitably abstractable: 

```ocaml
         user_defined_repos
         |> Repository.Name.Map.of_list_map ~f:(fun repo -> Repository.name repo, ())
         |> Result.map_error ~f:(fun (name, repo1, repo2) ->
           { kind = "Repository"
           ; item = Repository.Name.to_string name
           ; loc = fst (Repository.opam_url repo1)
           ; loc' = fst (Repository.opam_url repo2)
           })
         |> handle_duplicate_error;

```

However, I don't think this is worth the effort or the added complexity, and my preference is that you either help readability by having simple named functions that allow us to read

```ocaml
         ensure_no_overides user_defined_repos;
         ensure_no_duplicates user_defined_repos;
```

or you just keep the operations inlined.

**Review by shonfeder — APPROVED** [review]
As explained in the comment, I am not a fan of the code reuse here, as I think it makes readability worse, and the reuse achieved is not nearly worth the added complexity.

I explain my reasoning for the sake of building up shared understanding of how we think about code and readability, not to push my opinion. I am fine with merging this in any of the 3 forms considered:

1. The original code.
2. The named functions I suggested.
3. The `check_no_duplicates` you have introduced.

But, IMO, (3) is the worst of the options :grin:

File: src/source/workspace.ml (hunk 2 above)
Comment (Alizter) [reply src/source/workspace.ml]: I don't agree with it, I think it reads better when its inline. However, I also don't feel strongly enough about it. I've put all the validation in separate functions with descriptive names.

Comment (shonfeder) [reply src/source/workspace.ml]: I would be happy to defer to your stylistic preference here, but I can confirm that I find the current iteration much more digestible! I'll merge this now to save any further churn, but I would not reject a follow up to change to the style you prefer. Thanks!
