### PR TITLE
fix: add display options in --help

### LINKED ISSUE #526: jbuilder --display is hard to figure out
The command line doesnt tell you what the options are:

```
$ jbuilder --display
jbuilder: option `--display' needs an argument
Usage: jbuilder COMMAND ...
Try `jbuilder --help' for more information.
```

But then `--help` points to a non-existent manual page:

```
       --display=MODE
           Control the display mode of Jbuilder. See dune-config(5) for more
           details.
```

### PR DESCRIPTION
**Pull request by rgrinberg**
We now enumerate all the values in --display in dune --help.

Fixes #526

Signed-off-by: Rudi Grinberg <me@rgrinberg.com>

### CODE REVIEW

**Comment by rgrinberg** [comment]
The original ticket mentioned doing this in cmdliner, but we can keep this hack until cmdliner is improved.

File: bin/common.ml [hunk 1]
```diff
@@ -300,7 +304,7 @@ let display_term =
     Arg.(
       value
       & opt (some (enum Display.all)) None
-      & info [ "display" ] ~docs:copts_sect ~docv:"MODE"
+      & info [ "display" ] ~docs:copts_sect ~docv
```
Comment (anmonteiro) [inline bin/common.ml:307]: I'd probably keep `MODE` here and list the options in the `~doc:` description.

File: bin/common.ml [hunk 2]
```diff
@@ -298,12 +298,16 @@ let display_term =
      in
      Option.some_if verbose { Display.verbosity = Verbose; status_line = true })
     Arg.(
+      let doc =
+        let all = Display.all |> List.map ~f:fst |> String.concat ~sep:", " in
```
Comment (Alizter) [inline bin/common.ml:302]:
```suggestion
        let all = Display.all |> List.map ~f:fst |> String.enumerate_and in
```

File: bin/common.ml [hunk 3]
```diff
@@ -298,12 +298,16 @@ let display_term =
...
+        sprintf
+          "Control the display mode of Dune. See $(b,dune-config\\(5\\)) for \
+           more details. Valid values for this option are: %s"
```
Comment (Alizter) [inline bin/common.ml:305]:
```suggestion
           more details. Valid values for this option are: %s."
```

**Review by emillon — APPROVED** [review]
