### PR TITLE
dialects: allow extensions containing periods

### LINKED ISSUE #7777: Support multiple extensions in (dialect) patterns
## Desired Behavior

Dream currently recommends `.eml.ml` files, to take advantage of partial syntax highlighting of their ML parts. This is currently not possible with `(dialect)`:

```
(lang dune 2.0)

(dialect
 (name eml)
 (implementation
  (extension eml.ml)
  (preprocess (run %{bin:dream_eml} --stdout %{input-file})))
 (interface
  (extension emli)
  (format (run cat))))
```

results in

```
Entering directory '/home/antron/code/dreamworld'
File "dream/example/7-template/dune-project", line 6, characters 13-19:
6 |   (extension eml.ml)
                 ^^^^^^
Error: extension must not contain '.'
```

Is it possible to support such extensions?

## Example

```
(lang dune 2.0)

(dialect
 (name eml)
 (implementation
  (extension eml.ml)
  (preprocess (run %{bin:dream_eml} --stdout %{input-file})))
 (interface
  (extension emli)
  (format (run cat))))
```

See https://github.com/aantron/dream/pull/228#issuecomment-1557242558.

### PR DESCRIPTION
**Pull request by nojb**
Allow defining `dialect`s with extensions containing periods (eg `cppo.ml`). Fixes #7777.

@aantron @emillon can you give it a try?

### CODE REVIEW

**Comment by aantron** [comment]
Works for me! Thank you!

File: src/dune_rules/dialect.ml [hunk 1]
```diff
@@ -77,10 +77,14 @@ let decode =
         (map
            ~f:(fun (loc, x) -> (loc, x, []))
            (located Action.decode_dune_file))
-    in
+    and+ syntax_ver = Syntax.get_exn Stanza.syntax in
     let extension =
-      if String.contains extension '.' then
-        User_error.raise ~loc [ Pp.textf "extension must not contain '.'" ];
+      if String.length extension > 0 && extension.[0] = '.' then
```
Comment (rgrinberg) [inline src/dune_rules/dialect.ml:82]: Would it be possible to share this with the extension parsing code in `melange_stanzas`?  Some consistency around extensions would be very good to have. I would also suggest for such generic extension code to be moved to `dune_lang`.

Comment (nojb) [reply src/dune_rules/dialect.ml]: Yes, I pushed a commit sharing this code with `Melange_stanzas`, as suggested. Thanks!

File: src/dune_sexp/decoder.mli [hunk 2]
```diff
@@ -189,6 +189,10 @@ val plain_string : (loc:Loc.t -> string -> 'a) -> 'a t
 (** A valid filename, i.e. a string other than "." or ".." *)
 val filename : Filename.t t
 
+(** An extension: a string not starting with ".". The value returned by the
+    parser is prefixed with ".". *)
+val extension : string t
```
Comment (rgrinberg) [inline src/dune_sexp/decoder.mli:194]: I think this can be `Filename.Extension.t t`

**Review by rgrinberg — APPROVED** [review]

**Comment by emillon** [comment]
It seems risky to add that to 3.8 with no extra testing and I don't want to do an extra alpha run for this, so I'm removing the milestone.

File: src/dune_sexp/decoder.mli (hunk 2 above)
Comment (nojb) [reply src/dune_sexp/decoder.mli:194]: I am not sure about this one because `Filename.Extension.t` is related to the `Filename.extension` function which is a different notion (it does not admit multiple period-separated components).

**Comment by nojb** [comment]
> It seems risky to add that to 3.8 with no extra testing and I don't want to do an extra alpha run for this, so I'm removing the milestone.

OK. I guess it will be then for 3.9? (I need to update the version guard.)

File: CHANGES.md [hunk 3]
```diff
@@ -165,6 +165,9 @@ Unreleased
 - Bump minimum version of the dune language for the melange syntax extension
   from 3.7 to 3.8 (#7665, @jchavarri)
 
+- Extensions used in `(dialect)` can include embedded dots (eg `cppo.ml`) for
```
Comment (christinerose) [inline CHANGES.md:168]:
```suggestion
- Extensions used in `(dialect)` can include embedded dots (e.g., `cppo.ml`) for
```

File: doc/dune-files.rst [hunk 4]
```diff
@@ -75,9 +75,10 @@ dialect
 
          Specify the file extension used for this dialect.
 
-         The extension string must not contain any dots and be unique in a given
+         The extension string must not start with a dot and be unique in a given
          project (so that a given extension can be mapped back to a
-         corresponding dialect).
+         corresponding dialect). In Dune 3.8 and later, the extension string may
+         contain embedded dots (eg `cppo.ml`).
```
Comment (christinerose) [inline doc/dune-files.rst:81]:
```suggestion
         contain embedded dots (e.g., `cppo.ml`).
```

File: test/blackbox-tests/test-cases/dialects/dots.t/run.t [hunk 5]
```diff
@@ -0,0 +1,26 @@
+Test the (dialect ...) stanza inside the dune-project file.
```
Comment (christinerose) [inline test/blackbox-tests/test-cases/dialects/dots.t/run.t:1]:
```suggestion
Test the (dialect ...) stanza inside the `dune-project` file.
```

File: test/blackbox-tests/test-cases/dialects/dots.t/run.t [hunk 6]
```diff
@@ -0,0 +1,26 @@
...
+
+  $ { echo '(lang dune 3.7)'; cat dune-project.in; } >dune-project
+
+  $ dune build --display short
+  File "dune-project", line 5, characters 13-20:
+  5 |   (extension cppo.ml)
+                   ^^^^^^^
+  Error: the possibility of defining extensions with embedded dots is only
+  available since version 3.8 of the dune language. Please update your
```
Comment (christinerose) [inline test/blackbox-tests/test-cases/dialects/dots.t/run.t:10]:
```suggestion
  available since version 3.8 of the Dune language. Please update your
```

File: test/blackbox-tests/test-cases/dialects/dots.t/run.t [hunk 7]
```diff
@@ -0,0 +1,26 @@
...
+  dune-project file to have (lang dune 3.8).
```
Comment (christinerose) [inline test/blackbox-tests/test-cases/dialects/dots.t/run.t:11]:
```suggestion
  `dune-project` file to have (lang dune 3.8).
```

**Review by christinerose — CHANGES_REQUESTED** [review]
minor formatting fixes :)

File: test/blackbox-tests/test-cases/dialects/dots.t/run.t (hunk 6 above)
Comment (nojb) [reply test/blackbox-tests/test-cases/dialects/dots.t/run.t]: This message is not introduced by the present PR, so it would have to be treated elsewhere.

File: test/blackbox-tests/test-cases/dialects/dots.t/run.t (hunk 7 above)
Comment (nojb) [reply test/blackbox-tests/test-cases/dialects/dots.t/run.t]: This message is not introduced by the present PR, so it would have to be treated elsewhere.
