### PR TITLE
Path.Local: backslashes are not canonical on Windows

### LINKED ISSUE #4717: merlin broken with (include_subdirs unqualified)
`merlin` 4.2 + OCaml 4.12 + dune 2.8 seems broken when using `(include_subdirs unqualified)`. Concretely, given a dune file in `applications/apropos/addins/dune` containing `(include_subdirs unqualified)`, when editing the file `applications/apropos/addins/models/local_vol_hull_white_model.mf` I get:
```
No config found for file "local_vol_hull_white_model.mf" in "applications\\apropos\\addins\\models". Try calling `dune build`.
```
(This is under Windows).

cc @voodoos

### PR DESCRIPTION
**Pull request by nojb**
Currently, `Path.Local_gen.parse_string_exn` has a fast path for when the argument is already "canonical", see
https://github.com/ocaml/dune/blob/26f5e57d1aef71f476a6dc40990b9d6a517f7849/otherlibs/stdune-unstable/path.ml#L341-L347

The function `is_canonicalized` checks a number of conditions such as whether there are two slashes in a row, etc. However, I think on Windows it should also check for the presence of backslashes since these are not canonical (a value of type `Path.Local.t` is represented with forward slashes only).

This PR should fix #4717 which is blocking the use of `merlin` on Windows when using `(include_subdirs unqualified)`. It would be fantastic if we could get this in 2.9.

Fixes #4717

### CODE REVIEW

**Review by voodoos — APPROVED** [review]
Ok so the idea is that if there is a backslash in the path the test will fail and we will call `relative` that rebuilds a canonicalized path (with slashes).

And it is important that slashes are used in the path because other Dune Path functions relies on it, like `Path.parent`(as mentionned in #4717).

That sounds good to me, but I am no  Windows expert. 
Maybe @emillon will be interested in also looking at this ?

File: otherlibs/stdune-unstable/path.ml [hunk 1]
```diff
@@ -310,6 +310,7 @@ end = struct
         match s.[i] with
```
Comment (voodoos) [inline otherlibs/stdune-unstable/path.ml:310]: It might be a good idea to add a comment describing more directly what Dune considers being a "canonical" path.

Comment (nojb) [reply otherlibs/stdune-unstable/path.ml:312]: Good idea, done.

File: otherlibs/stdune-unstable/path.ml [hunk 2]
```diff
@@ -302,6 +302,8 @@ end = struct
       User_error.raise ?loc:error_loc
         [ Pp.textf "path outside the workspace: %s from %s" path (to_string t) ]
 
+  (* Check whether a path is in canonical form: no '.' or '..' components, no
+     repeated '/' components, and no backslashes '\\' (on Windows only) *)
```
Comment (voodoos) [inline otherlibs/stdune-unstable/path.ml:306]: And the function also always returns false if the path ends with a `/` (even when path is the root `/` and is, in fact, already canonical...)

**Comment by nojb** [comment]
I'm planning to merge this today, please speak up if you object!
