### PR TITLE
Adjust program and args when running executables on Windows

### LINKED ISSUE #11174: On windows, `(run ./configure)` results in `CreateProcess(): Exec format error`
Windows uses file extensions to determine how to open files. This means that actions that run shell scripts without extensions (such as configure scripts) do not work on windows. Opam has explicit support for running scripts, added in https://github.com/ocaml/opam/pull/3348. Dune should be extended in the same way.

Without this change, dune is unable to install any packages with configure scripts. Notably this includes the ocaml compiler itself.

### PR DESCRIPTION
**Pull request by punchagan**
Windows doesn't support shebang lines and build rules generated from opam build instructions could have rules like `(build (run <executable-script>))`, which would fail to run on Windows. This commit adds support to parse shebang lines of such executable scripts on Windows and run them with an appropriate executable.

Closes #11174

### CODE REVIEW

File: otherlibs/stdune/src/proc.ml [hunk 1]
```diff
@@ -23,6 +23,49 @@ let restore_cwd_and_execve prog argv ~env =
     Unix.execve prog argv env)
 ;;
 
+let get_win32_prog_and_args ~env ~dir prog args =
+  let get_cmd_and_args prog args =
+    let cmd, extra_args =
+      try
```
Comment (Leonidas-from-XIV) [inline otherlibs/stdune/src/proc.ml]: I would recommend wrapping the try around the code that really throws that `Not_found` exception, because looking at this I don't really know what that would be.

In many cases I find `match foo with | … | exception Not_found ->` better to read, since there is no massive block of code in the `try (...)` branch that each has to be interpreted as potentially throwing exceptions.

File: otherlibs/stdune/src/proc.ml [hunk 2]
```diff
@@ -23,6 +23,49 @@ let restore_cwd_and_execve prog argv ~env =
...
+      let path = Option.value env ~default:Env.initial |> Env_path.path in
+      (match Bin.which ~path cmd with
+       | None -> prog, args
+       | Some cmd ->
+         let prog_str = Path.reach_for_running ?from:dir prog in
+         let args = List.concat [ extra_args; prog_str :: args ] in
+         cmd, args)
+  in
+  (* Check if we are on Windows and change the prog being used if required *)
+  if not Sys.win32 then prog, args else get_cmd_and_args prog args
```
Comment (Leonidas-from-XIV) [inline otherlibs/stdune/src/proc.ml]: I find it weird to call this `get_win32_…` but then always call it, even in non-Win32 cases. Thus I'd rather have `parse_prog_and_args` which conditionally calls `parse_win32_prog_and_args` to signal that this isn't accidentally calling `get_win32_…`.

File: otherlibs/stdune/src/proc.mli [hunk 3]
```diff
@@ -57,3 +57,11 @@ type wait =
    When successful, returns information about the reaped process.
  *)
 val wait : wait -> Unix.wait_flag list -> Process_info.t option
+
+(* FIXME: What's the right place to put this? *)
```
Comment (Leonidas-from-XIV) [inline otherlibs/stdune/src/proc.mli]: Besides this on which I can't help (seems alright to me, however), I think it would be nice to explain what it does on a high level and describe that it matches what OPAM does (does it?).

File: src/dune_engine/process.ml [hunk 4]
```diff
@@ -1003,6 +1048,7 @@ let run_internal
       | Some p -> if Path.is_root p then None else Some p
     in
     let id = Running_jobs.Id.gen () in
+    let prog, args = parse_prog_and_args ~env ~dir prog args in
```
Comment (Alizter) [inline src/dune_engine/process.ml]: I think it would be clearer if you pull the windows check here. Then you can rename the function to `adjust_prog_and_args_for_windows` or something

Comment (punchagan) [reply src/dune_engine/process.ml]: Makes sense!

**Comment by Alizter** [comment]
Could you add a test in `test/blackbox-tests/test-cases/actions/run-shebang.t`. You can also mark it with 
```
(cram
 (applies_to run-shebang)
 (alias runtest-windows))
```
This will run on macOS and Linux by default, and additionally on Windows which is what we want to fix.

File: src/dune_engine/process.ml [hunk 5]
```diff
@@ -850,6 +850,49 @@ let await ~timeout { response_file; pid; _ } =
...
+        let parts = String.split_on_char ~sep:' ' line in
+        match parts with
+        | [] -> None, [] (* Empty shebang line *)
+        | executable_path :: exe_args ->
+          let exe_name = Filename.basename executable_path in
+          let exe, extra_args =
+            if exe_name <> "env"
+            then
+              ( Some exe_name
+              , if exe_args <> [] then [ String.concat ~sep:" " exe_args ] else [] )
```
Comment (Leonidas-from-XIV) [inline src/dune_engine/process.ml]: To avoid the polymorphic compare, I'd suggest `List.is_non_empty`.

File: src/dune_engine/process.ml [hunk 6]
```diff
@@ -850,6 +850,49 @@ let await ~timeout { response_file; pid; _ } =
...
+   appropriate executable on the system to execute the script with. *)
+let adjust_prog_and_args_on_windows ~env ~dir prog args =
+  let parse_win32_prog_and_args prog =
+    Stdune.Io.with_file_in ~binary:true prog ~f:(fun ic ->
+      if really_input_string ic 2 <> "#!"
+      then None, []
+      else (
+        let line = input_line ic |> String.trim in
+        let parts = String.split_on_char ~sep:' ' line in
+        match parts with
```
Comment (Leonidas-from-XIV) [inline src/dune_engine/process.ml]: Given this is a fairly complex logic, for readability sake I would pull it out into a separate function, outside of the I/O function `with_file_in`. That way the pure function could also be tested.

File: src/dune_engine/process.ml [hunk 7]
```diff
@@ -850,6 +850,49 @@ let await ~timeout { response_file; pid; _ } =
   process_info, termination_reason
 ;;
 
+(* This function allows transparently using executable scripts correctly in run
+   lang on Windows. The function tries to parse the shebang line and find the
+   appropriate executable on the system to execute the script with. *)
+let adjust_prog_and_args_on_windows ~env ~dir prog args =
+  let parse_win32_prog_and_args prog =
+    Stdune.Io.with_file_in ~binary:true prog ~f:(fun ic ->
```
Comment (Leonidas-from-XIV) [inline src/dune_engine/process.ml]: Is the `Stdune.` prefix necessary?

Comment (punchagan) [reply src/dune_engine/process.ml]: Yes, it seems to be. There are other places in the file which use `Stdune.Io`.  I could fix that in a separate clean-up commit.

Comment (Leonidas-from-XIV) [reply src/dune_engine/process.ml]: Well, let's keep it like this and maybe fix it in a follow-up PR.

File: src/dune_engine/process.ml [hunk 8]
```diff
@@ -850,6 +850,52 @@ let await ~timeout { response_file; pid; _ } =
   process_info, termination_reason
 ;;
 
+let maybe_parse_shebang_line ic =
```
Comment (Leonidas-from-XIV) [inline src/dune_engine/process.ml]: Better put the IO stuff in one function and the pure stuff in another, that way there's pure functions that can potentially be tested.

Comment (punchagan) [reply src/dune_engine/process.ml]: Fair enough! I've now extracted it.

File: src/dune_engine/process.ml [hunk 9]
```diff
@@ -850,6 +850,55 @@ let await ~timeout { response_file; pid; _ } =
...
+        | "-S" :: [] -> None, [] (* env -S with no args *)
+        | "-S" :: name :: cmd_args ->
+          Some name, cmd_args (* env -S allows multiple args *)
+        | name :: _ -> Some name, [] (* env with a single arg *))
+    in
+    exe, extra_args
+;;
+
+(* This function allows transparently using executable scripts correctly in run
+   lang on Windows. The function tries to parse the shebang line and find the
```
Comment (Leonidas-from-XIV) [inline src/dune_engine/process.ml]: This sentence does not seem to make too much sense ("run lang"), I suggest rewriting it.

File: test/blackbox-tests/test-cases/actions/run-shebang.t [hunk 10]
```diff
@@ -0,0 +1,41 @@
+Shows what happens when Dune tries to run an executable script on Windows
```
Comment (Leonidas-from-XIV) [inline test/blackbox-tests/test-cases/actions/run-shebang.t]: I think this is not just on Windows, I'd say it shows that running an executable script works on all our supported platforms.

(I assume that `run-shebang.t` is also running on Unices, which it should!)

File: test/blackbox-tests/test-cases/actions/run-shebang.t [hunk 11]
```diff
@@ -0,0 +1,41 @@
...
+  > EOF
+  $ chmod +x executable.sh
+
+  $ dune build --root . @all
+  $ cat _build/default/output
+  Executable ran successfully using sh!
+
+  $ cat >executable.sh <<EOF
+  > #!/usr/bin/env -S sh -v
+  > echo "Executable ran successfully using sh!"
```
Comment (Leonidas-from-XIV) [inline test/blackbox-tests/test-cases/actions/run-shebang.t]: I would suggest `echo`-ing a slightly different message here, to show that it was actually re-run successfully in line 40.

**Review by Leonidas-from-XIV — APPROVED** [review]
Code looks good to me, the implementation makes sense and the tests are fine.

Some minor concerns about wording but otherwise its good to go from my perspective. Thanks for the fix!

File: test/blackbox-tests/test-cases/actions/run-shebang.t [hunk 12]
```diff
@@ -0,0 +1,41 @@
+Shows what happens when Dune tries to run an executable script on Windows
+
+  $ cat > dune-project <<EOF
+  > (lang dune 2.0)
```
Comment (Alizter) [inline test/blackbox-tests/test-cases/actions/run-shebang.t]:
```suggestion
  > (lang dune 3.22)
```

File: test/blackbox-tests/test-cases/actions/run-shebang.t [hunk 13]
```diff
@@ -0,0 +1,41 @@
...
+  > EOF
+
+  $ cat > dune << EOF
+  > (rule (with-stdout-to output (run ./executable.sh)))
```
Comment (Alizter) [inline test/blackbox-tests/test-cases/actions/run-shebang.t]:
```suggestion
  > (rule
  >  (action
  >   (with-stdout-to output (run ./executable.sh))))
```

File: src/dune_engine/process.ml [hunk 14]
```diff
@@ -850,6 +850,55 @@ let await ~timeout { response_file; pid; _ } =
...
+  let parse_win32_prog_and_args prog =
+    Stdune.Io.with_file_in ~binary:true prog ~f:(fun ic ->
+      if really_input_string ic 2 <> "#!"
+      then None, []
+      else (
+        let line = input_line ic |> String.trim in
+        parse_shebang_line line))
+  in
+  match parse_win32_prog_and_args prog with
+  | (exception Not_found) | None, _ -> prog, args
```
Comment (Alizter) [inline src/dune_engine/process.ml]: Who is raising Not_found?

**Review by rgrinberg — COMMENTED** [review]
The most important thing about this change is to make sure that we only do it once per executable.

Also copying @nojb for awareness.

**Comment by punchagan** [comment]
> The most important thing about this change is to make sure that we only do it once per executable.

Makes sense. I've now added a Hashtbl to keep track of the executable paths we discovered. Let me know if that's too simplistic and we should do better.

**Comment by nojb** [comment]
I am not aware of the context, but this seems of limited usefulness to me: is there any reason to expect Windows builds to have executables such as `sh`, etc available in the environment? Is that the case when using OPAM? Anyway, am not opposed.

**Comment by Leonidas-from-XIV** [comment]
Can we do the caching per executable with `Memo` somehow? If we keep track of the input we should be able to memoize the resolved value and also be able to recompute it when the input is updated…

@nojb This is mostly about `dune` files that use `./foo.sh` which breaks even when run in an Unix emulation environment where `sh` or other commands would be available, simply because Windows does not support shebangs. It copies [the same behavior from OPAM](https://github.com/ocaml/opam/blob/40d198913c9daffd882be12d058ccb25aa4bfbae/src/core/opamProcess.ml#L407-L440).

**Comment by nojb** [comment]
> @nojb This is mostly about `dune` files that use `./foo.sh` which breaks even when run in an Unix emulation environment where `sh` or other commands would be available, simply because Windows does not support shebangs. It copies [the same behavior from OPAM](https://github.com/ocaml/opam/blob/40d198913c9daffd882be12d058ccb25aa4bfbae/src/core/opamProcess.ml#L407-L440).

Thanks for the pointer. Of course, it would be better for users to call the shell explicitly: `(run sh ./foo.sh)`, but I understand the point of the PR. Thanks!

**Comment by Alizter** [comment]
@nojb The decision to change the semantics of `run` on Windows is something that was discussed previously in: 
- https://github.com/ocaml/dune/issues/1417
- https://github.com/ocaml/dune/issues/9128
- https://github.com/ocaml/dune/issues/11174

This PR is intending to resolve the discussion by allowing the same behaviour (of running scripts) across platforms. This is not a simple change and will require careful consideration about whether or not we would like it and if it makes sense for dune as a whole.

## Motivation

The motivating use-case for this PR is that when we translate opam build instructions into dune actions and serialise them to a lock file, we cannot know if a given file is an executable or a script without running the action. This means that so far we have only translated such build instructions into `(run)` actions.

This of course leads into trouble when running such actions on Windows since we can only execute executable files (with extension .exe). There are some edge-cases for handling batch and powershell scripts, but they are not relevant here.

Ultimately, the analogy we draw in Dune between Windows' `CreateProcess()` and Unix's `exec` breaks down when it comes to shebangs. Shebangs amongst Unixes are not even standardised. In fact, they are explicitly left undefined in POSIX:

>  If the first line of a file of shell commands starts with the
>  characters #!, the results are unspecified.

See here for more details: https://www.in-ulm.de/~mascheck/various/shebang/

## Solution

The solution here is (or should be) to understand if a given file is an executable before running it on Windows. If it is, then proceed as usual with `CreateProcess()` which `spawn` does for us. However, if it is a script, then we need to inspect the first line, parse it as a shebang, and use whatever interpreter we can understand (if we are aiming for maximum flexibility). I don't know if Windows can detect if a file is/was marked as executable, which might affect things here. There is no "marking as executable" on Windows AFAIK. Git on Windows certainly can do some tracking, but I am not too familiar with the details here.

The main difficulty comes from the flexibility in the definition of a shebang. I am inclined to think that we should be more restrictive with the kinds of interpreters we allow, for example `bash` and `sh` in their standard "locations" should be good enough. However there are scripts in the Wild with `python3` and even `ocaml` in the shebang, so we need to make an explicit choice here.

## Prior "art"

Other build systems have considered making analogous changes that may be worth reading:

  - Bazel
    -  https://github.com/bazelbuild/bazel/issues/3589
  - Meson
    - https://github.com/mesonbuild/meson/issues/7362

Both cases had a different problem, required the analogous script detection as a possible fix but ultimately ended up with fixing the original problem a different way. That's maybe something we should consider doing here.  

## Alternatives

For solving the issue with lock directories on Windows, we can consider introducing an alternative `run` action that is used on all platforms which avoids us from having to make such an invasive change here. The reason this change is invasive here is because its a problem outside of lock directories.

If an author has written:

```
(rule
 (alias do-thing)
 (deps my-script.sh)
 (action
  (run ./my-script.sh)))
```
Is there really a good reason to fail this on Windows?

File: src/dune_engine/process.ml [hunk 15]
```diff
@@ -850,6 +850,70 @@ let await ~timeout { response_file; pid; _ } =
   process_info, termination_reason
 ;;
 
+(* Parse a shebang line (without the #! prefix) and return the executable name
+   and its arguments. *)
+let parse_shebang_line line =
+  let parts = String.split_on_char ~sep:' ' line in
```
Comment (Alizter) [inline src/dune_engine/process.ml]: Double spaces will create empty arguments here.

File: test/blackbox-tests/test-cases/actions/run-shebang.t [hunk 16]
```diff
@@ -0,0 +1,42 @@
...
+  > EOF
+
+  $ cat >executable.sh <<EOF
+  > #!/bin/sh
```
Comment (Alizter) [inline test/blackbox-tests/test-cases/actions/run-shebang.t]: Missing case for direct interpreter with an argument.

File: test/blackbox-tests/test-cases/actions/run-shebang.t [hunk 17]
```diff
@@ -0,0 +1,42 @@
...
+  > #!/usr/bin/env -S sh -v
+  > echo "Executable ran successfully using sh -v!"
+  > EOF
+  $ chmod +x executable.sh
+
+  $ dune build --root . @all
+  #!/usr/bin/env -S sh -v
+  echo "Executable ran successfully using sh -v!"
+  $ cat _build/default/output
+  Executable ran successfully using sh -v!
```
Comment (Alizter) [inline test/blackbox-tests/test-cases/actions/run-shebang.t]: Some further test cases:
- What happens when you pass an empty file?
- Any file with contents and no shebang
- Non-executable binary encoded file
- Interpreter not in PATH
- Shebang with double spaces

File: src/dune_engine/process.ml [hunk 18]
```diff
@@ -850,6 +850,70 @@ let await ~timeout { response_file; pid; _ } =
...
+module Windows_executables = struct
+  module H = Stdlib.Hashtbl.Make (String)
+
+  let executables = H.create 8
+
+  (* This function adds support for shebang line parsing on Windows to allow
+     running scripts in run actions using the correct executable. *)
+  let adjust_prog_and_args ~env ~dir prog args =
+    let parse_win32_prog_and_args prog =
+      Stdune.Io.with_file_in ~binary:true prog ~f:(fun ic ->
```
Comment (Alizter) [inline src/dune_engine/process.ml]: Might be worth adding a CR here that we would probably like to limit how many bytes we are reading here. Otherwise huge files would just eat up memory when "run".

Comment (Alizter) [reply src/dune_engine/process.ml]: These might be relevant to picking a number, doesn't have to be perfect https://www.in-ulm.de/~mascheck/various/shebang/#length

File: src/dune_engine/process.ml [hunk 19]
```diff
@@ -850,6 +850,70 @@ let await ~timeout { response_file; pid; _ } =
...
+        if really_input_string ic 2 <> "#!"
```
Comment (Alizter) [inline src/dune_engine/process.ml]: For < 2 bytes?

File: src/dune_engine/process.ml (hunk 18 above)
Comment (Alizter) [inline src/dune_engine/process.ml]: If the file is missing, this will raise IINM. Worth trying to test in case we aren't checking this. You can try something dumb like progn which deletes or renames the file that's about to be run.

File: src/dune_engine/process.ml [hunk 20]
```diff
@@ -850,6 +850,70 @@ let await ~timeout { response_file; pid; _ } =
...
+        then None, []
+        else (
+          let line = input_line ic |> String.trim in
+          parse_shebang_line line))
+    in
+    match parse_win32_prog_and_args prog with
+    | (exception Not_found) | None, _ -> prog, args
```
Comment (Alizter) [inline src/dune_engine/process.ml]: I only see `Sys_error` and `End_of_file` here so this doesn't seem to be doing anything. Let's avoid exceptions to begin with otherwise we cannot easily understand error handling.

File: src/dune_engine/process.ml [hunk 21]
```diff
@@ -850,6 +850,70 @@ let await ~timeout { response_file; pid; _ } =
...
+
+  (* This function adds support for shebang line parsing on Windows to allow
+     running scripts in run actions using the correct executable. *)
+  let adjust_prog_and_args ~env ~dir prog args =
+    let parse_win32_prog_and_args prog =
+      Stdune.Io.with_file_in ~binary:true prog ~f:(fun ic ->
+        if really_input_string ic 2 <> "#!"
+        then None, []
+        else (
+          let line = input_line ic |> String.trim in
```
Comment (Alizter) [inline src/dune_engine/process.ml]: This will raise if there is no new line I believe.

File: src/dune_engine/process.ml [hunk 22]
```diff
@@ -850,6 +850,70 @@ let await ~timeout { response_file; pid; _ } =
...
+        ( Some exe_name
+        , if List.is_empty exe_args then [] else [ String.concat ~sep:" " exe_args ] )
+        (* shebang lines only support a single argument *)
+      else (
+        match exe_args with
+        | [] -> None, [] (* env command with no args *)
+        | "-S" :: [] -> None, [] (* env -S with no args *)
+        | "-S" :: name :: cmd_args ->
+          Some name, cmd_args (* env -S allows multiple args *)
+        | name :: _ -> Some name, [] (* env with a single arg *))
```
Comment (Alizter) [inline src/dune_engine/process.ml]: Consider `#!/usr/bin/env python -u`. On Unix this will fail because `env` will say cannot find `python -u` but here it will be silently dropped and run `python`. I think we should be touching the rest of the arguments.

File: src/dune_engine/process.ml [hunk 23]
```diff
@@ -850,6 +850,70 @@ let await ~timeout { response_file; pid; _ } =
...
+      if exe_name <> "env"
+      then
+        ( Some exe_name
+        , if List.is_empty exe_args then [] else [ String.concat ~sep:" " exe_args ] )
+        (* shebang lines only support a single argument *)
+      else (
+        match exe_args with
+        | [] -> None, [] (* env command with no args *)
+        | "-S" :: [] -> None, [] (* env -S with no args *)
+        | "-S" :: name :: cmd_args ->
```
Comment (Alizter) [inline src/dune_engine/process.ml]: There are many other flags that `env -S` support before the program name unfortunately.

File: src/dune_engine/process.ml [hunk 24]
```diff
@@ -850,6 +850,70 @@ let await ~timeout { response_file; pid; _ } =
...
+        | None ->
+          let path = Option.value env ~default:Env.initial |> Env_path.path in
+          (match Bin.which ~path cmd with
+           | Some p as s ->
+             H.add executables cmd p;
+             s
+           | None -> None)
+      in
+      (match executable with
+       | None -> prog, args
```
Comment (Alizter) [inline src/dune_engine/process.ml]: This should be an error. If we couldn't interpret the shebang, we cannot run the script to begin with.

**Review by Alizter — CHANGES_REQUESTED** [review]
I've pointed out some issues I found reading through the code. In general, this is not a straightforward problem to solve, but we can probably make some smarter choices that will make this easier to implement.

**Comment by nojb** [comment]
> This PR is intending to resolve the discussion by allowing the same behaviour (of running scripts) across platforms. This is not a simple change and will require careful consideration about whether or not we would like it and if it makes sense for dune as a whole.

Thanks for the context @Alizter! With all that information in mind let me rephrase my comment above: this PR makes it easier to run shebang scripts on Windows, but implicitly requires that the build take place in an environment with Unix tools available. This seems backwards: everything is moving in the opposite direction, ie less dependence on Unix tooling. Certainly a Windows user should not be assumed to have some kind of UNIX-compatible environment to use Dune or OPAM packages.

I understand that this mechanism may play a role in a transient manner while many packages have not yet been fully cross-platform and still depend on shell scripts and the like, but at the very least we should emit a warning when this mechanism is triggered to alert both users and developers that the package is not really cross-platform. Or perhaps expose this mechanism as a kind of opt-in (which Dune could do by default when building packages) so as to make it clear that the general direction is _not_ requiring Unix tooling for Windows users.

Do you all agree?

**Comment by Leonidas-from-XIV** [comment]
> this PR makes it easier to run shebang scripts on Windows, but implicitly requires that the build take place in an environment with Unix tools available.

If  I have a `(run ./generate.py)`, what should it do? Maybe the right equivalent of running the shebang on Windows should be to run the same handler that would be run if I double click. That would potentially be more windows-y, but I suspect would allow less builds to succeed on Windows, as that would require the Python interpreter to be registered as handler for `.py` files.

**Comment by nojb** [comment]
> If I have a `(run ./generate.py)`, what should it do?

One can argue that this use of `(run)` is a mistake from a cross-platform perspective, because `generate.py` is not an executable file. Instead, one should use `(run python generate.py)`. I understand that there are many existing build scripts that use the shebang though, but by its very nature doing so is not portable to Windows.

**Comment by Alizter** [comment]
Let's continue the discussion on Zulip [#dune > (run)ning scripts on Windows](https://ocaml.zulipchat.com/#narrow/channel/527834-dune/topic/.28run.29ning.20scripts.20on.20Windows/with/568018887).

This PR is currently under review, so its best we don't interleave discussion. Worst-case we will pick a more conservative change for getting lock directories to work on Windows. However I think the general topic is interesting and would be worth discussing further.

**Comment by shonfeder** [comment]
@Alizter 

> I don't know if Windows can detect if a file is/was marked as executable

AFAIR, this is not possible on Windows without either inspecting the contents of the files or deciding based on the  file extension.

**Comment by rgrinberg** [comment]
I think what @nojb says is convincing enough. The only point of this construct is to make it easy to port opam packages. I don't see why we should be encouraging or supporting this in the rest of dune then.

How about we just move the support to actions that build packages? It will be easier to implement as well, as we won't have to worry about repeating this computation on the same executables anymore.

**Comment by Alizter** [comment]
Rather than relying on existing utilities like `wc` which can differ annoyingly in implementation, try adding such functionality to the `dune_cmd` utility if it doesn't exist already. You can see similar replacements for stat and sed there. That way we can have a consistent program output.

**Comment by Leonidas-from-XIV** [comment]
`dune_cmd` has an implementation of `count-lines`, so pretty much `wc -l`.

**Comment by punchagan** [comment]
> I think what @nojb says is convincing enough. The only point of this construct is to make it easy to port opam packages. I don't see why we should be encouraging or supporting this in the rest of dune then.
> 
> How about we just move the support to actions that build packages? It will be easier to implement as well, as we won't have to worry about repeating this computation on the same executables anymore.

Thanks for all the inputs and discussions on this PR (and on Zulip). I agree that it is better to restrict this functionality only to the action that builds packages.  I've updated the PR with this change, and added more tests to address the review comments. 

I think the PR is ready for another review, now. Thanks!

File: src/dune_rules/run_with_path.ml [hunk 25]
```diff
@@ -157,6 +243,18 @@ module Spec = struct
           | None -> Some dune_folder
           | Some path -> Some (sprintf "%s:%s" dune_folder path))
```
Comment (Alizter) [inline src/dune_rules/run_with_path.ml]: This seems suspicious on Windows

File: src/dune_rules/run_with_path.ml [hunk 26]
```diff
@@ -73,6 +73,92 @@ end = struct
   ;;
 end
 
+module Windows_executables = struct
+  module H = Stdlib.Hashtbl.Make (String)
```
Comment (Alizter) [inline src/dune_rules/run_with_path.ml]: `String.Table` should have what you need

File: src/dune_rules/run_with_path.ml [hunk 27]
```diff
@@ -73,6 +73,92 @@ end = struct
...
+      Stdune.Io.with_file_in ~binary:true prog ~f:(fun ic ->
+        match really_input_string ic 2 <> "#!" with
+        | true | (exception End_of_file) -> None, []
+        | false ->
+          (* CR-someday: Limit how many bytes we read here? *)
+          let line = input_line ic |> String.trim in
+          let prog, args = parse_shebang_line line in
+          (match prog with
+           | None ->
+             User_error.raise
```
Comment (Alizter) [inline src/dune_rules/run_with_path.ml:125]: Maybe show shebang line here for easier debug?

File: test/blackbox-tests/test-cases/pkg/build-with-executable-script-on-windows.t [hunk 28]
```diff
@@ -0,0 +1,89 @@
...
+
+Executable couldn't be found
+
+  $ pkg foo ./fake.sh <<EOF
+  > #!/bin/fake
+  > echo "no"
+  > EOF
+  $ dune build @pkg-install 2>&1 | grep Error
+  Error: fake.sh: No such file or directory
+  [1]
```
Comment (Alizter) [inline test/blackbox-tests/test-cases/pkg/build-with-executable-script-on-windows.t:145]: More test cases:
- Running an executable and not a script file (this should work still)
- whitespace only shebang `#!    `.
- scripts with CRLF

File: src/dune_rules/run_with_path.ml (hunk 25 above)
Comment (Alizter) [reply src/dune_rules/run_with_path.ml]: Something like `  |> Env_path.cons ~dir:(Path.of_string dune_folder)` should be better

File: src/dune_rules/run_with_path.ml [hunk 29]
```diff
@@ -73,6 +73,92 @@ end = struct
...
+      in
+      exe, extra_args
+  ;;
+
+  (* This function adds support for shebang line parsing on Windows to allow
+     running scripts in run actions using the correct executable. *)
+  let adjust_prog_and_args ~metadata ~path ?dir prog args =
+    let { Process.loc; annots; _ } = metadata in
+    let prog_name = Path.basename prog in
+    let parse_win32_prog_and_args prog =
```
Comment (Alizter) [inline src/dune_rules/run_with_path.ml:115]: An alternative:
```
  let parse_win32_prog_and_args prog =
    match Io.file_line prog 1 with
    | exception _ -> None, []
    | line ->
      match String.drop_prefix line ~prefix:"#!" with
      | None -> None, []
      | Some rest -> parse_shebang_line rest

```

The string.trim is stripping the trailing `\r` we get on Windows which is a bit confusing. Also unsure about the binary mode.

File: src/dune_rules/run_with_path.ml (hunk 25 above)
Comment (punchagan) [reply src/dune_rules/run_with_path.ml]: Great catch! I this this would fix #12433. Do you think this change can come as a separate PR?

File: src/dune_rules/run_with_path.ml (hunk 29 above)
Comment (punchagan) [reply src/dune_rules/run_with_path.ml:115]: Wouldn't `Io.file_line prog 1` end up reading a lot of unnecessary data, especially from binary files when a newline character doesn't appear anywhere near the beginning of the file? My implementation tries to read only the first 2 characters before trying to process the first line.  

Also, I don't understand what you mean by "stripping the trailing `\r`" being confusing.

Comment (Leonidas-from-XIV) [reply src/dune_rules/run_with_path.ml:115]: `Io.file_line` sets `binary` to false (so Windows line endings turn from `\r\n` to `\n`) and skips lines in a loop. It doesn't read the whole file, thus `file_line prog 1` is basically just a single `input_line` on a non-binary file.

File: src/dune_rules/run_with_path.ml (hunk 25 above)
Comment (Leonidas-from-XIV) [reply src/dune_rules/run_with_path.ml]: I don't think it would, because that piece of code only ever adds a path with a `dune` executable to the path.

But yeah, feel free to update it, a separate PR seems like the right way to go about it.

File: src/dune_rules/run_with_path.ml (hunk 29 above)
Comment (punchagan) [reply src/dune_rules/run_with_path.ml:115]: I did look at the source of `Io.file_line` and I understand it that on a non-binary file it does read the first line correctly.  But on a binary file, we could end-up reading too many chars, if the newline doesn't appear anywhere the beginning.   But, I guess I don't need to worry about it since the [DOS Stub](https://0xrick.github.io/win-internals/pe3/#dos-stub) ends with a newline, and this code only runs on Windows.

Comment (rgrinberg) [reply src/dune_rules/run_with_path.ml:115]: How does opam do it? Perhaps we should just copy them.

File: test/blackbox-tests/test-cases/pkg/build-with-executable-script-on-windows.t [hunk 30]
```diff
@@ -0,0 +1,109 @@
...
+  $ mkdir scripts/
+
+  $ cat > dune-project <<EOF
+  > (lang dune 3.22)
+  > EOF
+
+  $ cat > dune-workspace <<EOF
+  > (lang dune 3.22)
+  > (pkg enabled)
+  > EOF
```
Comment (Alizter) [inline test/blackbox-tests/test-cases/pkg/build-with-executable-script-on-windows.t]: This is unnecessary since we have a lock file.

File: src/dune_rules/run_with_path.ml (hunk 29 above)
Comment (punchagan) [reply src/dune_rules/run_with_path.ml:115]: I wrote the initial version after looking at the [opam workaround](https://github.com/ocaml/opam/blob/master/src/core/opamProcess.ml#L410-L426) shared by David in https://github.com/ocaml/dune/issues/11174#issuecomment-2762344653 . I guess, I should've explicitly mentioned that earlier. (I had context from #11174 which others looking at this PR may be missing!)

**Review by Alizter — APPROVED** [review]
I'm happy with the state that this PR is in. If issues arise on Windows with typical build scripts we can of course always revisit this problem.

I have only a few user-facing concerns:

If we see an invalid shebang, what should a user do? We could probably give a little more information in the error message such as the location for the (build) expression and perhaps telling them to report it if they believe its a valid shebang etc.

**Comment by punchagan** [comment]
> If we see an invalid shebang, what should a user do? We could probably give a little more information in the error message such as the location for the (build) expression and perhaps telling them to report it if they believe its a valid shebang etc.

I've added a user-facing message to this effect.  Let me know if there's anything else I need to fix in this PR, before we are able to merge this.

File: src/dune_rules/run_with_path.ml [hunk 31]
```diff
@@ -73,6 +73,88 @@ end = struct
...
+               ; Pp.textf "  #!/path/to/env <executable>"
+               ; Pp.textf "  #!/path/to/env -S <executable> <arg1> <arg2> ..."
+               ; Pp.textf
+                   "If this is a valid shebang line that should be parsed by Dune, \
+                    please report upstream including the contents of the shebang line."
+               ]
+           | _ -> prog, args))
+    in
+    match parse_win32_prog_and_args prog with
+    | exception Sys_error _ -> prog, args
```
Comment (Leonidas-from-XIV) [inline src/dune_rules/run_with_path.ml]: What is throwing exceptions here?

File: test/blackbox-tests/test-cases/pkg/build-with-executable-script-on-windows.t [hunk 32]
```diff
@@ -0,0 +1,131 @@
...
+  $ cat > dune-project <<EOF
+  > (lang dune 3.22)
+  > EOF
+
+  $ pkg() {
+  > make_lockpkg $1 <<EOF
+  > (build (run $2))
+  > (version dev)
+  > EOF
+  > local files="${source_lock_dir}/$1.files"
```
Comment (Leonidas-from-XIV) [inline test/blackbox-tests/test-cases/pkg/build-with-executable-script-on-windows.t:24]: While `>` works here, I think it would still be better to use `$` for these commands, as they are all separate.

File: test/blackbox-tests/test-cases/pkg/build-with-executable-script-on-windows.t [hunk 33]
```diff
@@ -0,0 +1,131 @@
...
+  $ make_lockdir
+
+  $ mkdir scripts/
+
+  $ cat > dune-project <<EOF
+  > (lang dune 3.22)
+  > EOF
+
+  $ pkg() {
+  > make_lockpkg $1 <<EOF
```
Comment (Leonidas-from-XIV) [inline test/blackbox-tests/test-cases/pkg/build-with-executable-script-on-windows.t:20]: Is the `>` here correct?

File: test/blackbox-tests/test-cases/pkg/build-with-executable-script.t [hunk 34]
```diff
@@ -0,0 +1,82 @@
...
+  $ make_lockdir
+
+  $ mkdir scripts/
+
+  $ cat > dune-project <<EOF
+  > (lang dune 3.22)
+  > EOF
+
+  $ pkg() {
+  > make_lockpkg $1 <<EOF
```
Comment (Leonidas-from-XIV) [inline test/blackbox-tests/test-cases/pkg/build-with-executable-script.t:15]: Same concerns as in the other test.

File: test/blackbox-tests/test-cases/pkg/build-with-executable-script-on-windows.t (hunk 32 above)
Comment (punchagan) [reply test/blackbox-tests/test-cases/pkg/build-with-executable-script-on-windows.t:24]: I thought `>` can used for continuation lines? I'm defining a bash function pkg and all of these lines are a part of that?

File: test/blackbox-tests/test-cases/pkg/build-with-executable-script-on-windows.t (hunk 33 above)
Comment (punchagan) [reply test/blackbox-tests/test-cases/pkg/build-with-executable-script-on-windows.t:20]: I thought `>` can used for continuation lines? I'm defining a bash function pkg and all of these lines are a part of that?

File: src/dune_rules/run_with_path.ml (hunk 31 above)
Comment (punchagan) [reply src/dune_rules/run_with_path.ml]: `Stdune.Io.with_file_in` would throw when `prog` doesn't exist.

File: test/blackbox-tests/test-cases/pkg/build-with-executable-script-on-windows.t (hunk 32 above)
Comment (Leonidas-from-XIV) [reply test/blackbox-tests/test-cases/pkg/build-with-executable-script-on-windows.t:24]: Yes they can be, but that makes them all "the same command", thus e.g. errors would only show up at the end. I assume the timing mechanism also counts everything in here also as one command.

File: test/blackbox-tests/test-cases/pkg/build-with-executable-script-on-windows.t (hunk 33 above)
Comment (Leonidas-from-XIV) [reply test/blackbox-tests/test-cases/pkg/build-with-executable-script-on-windows.t:20]: Ah yes, you're right. I was worried it was getting interpreted as stdin redirection but this works just fine.

File: src/dune_rules/run_with_path.ml (hunk 31 above)
Comment (Leonidas-from-XIV) [reply src/dune_rules/run_with_path.ml]: Ah, I see. Maybe worth defining `with_file_in_opt` that just wraps `Stdune.Io.with_file_in` to contain the exception?

**Comment by Alizter** [comment]
As we've discussed before. There were a few more changes I would like:
- `#!` on its own line gives `End_of_file` from `input_line`
- having a space after a shebang and before `\r\n` causes some issues with the parsing
- removing the hash table (I think this was done?)

**Comment by punchagan** [comment]
Thanks for listing out the changes!

> * `#!` on its own line gives `End_of_file` from `input_line`

I've added a test case for this and tweaked the code to handle this correctly. 

>     * having a space after a shebang and before `\r\n` causes some issues with the parsing

I've added a test case for this, but couldn't find any issues. If you have an example handy, that would be helpful. 

>     * removing the hash table (I think this was done?)

Yes, I've removed this.

File: src/dune_rules/run_with_path.ml (hunk 31 above)
Comment (punchagan) [reply src/dune_rules/run_with_path.ml]: I'm happy to do that in a separate PR. I think it's better to keep this one focused on the Windows related change?

Comment (Leonidas-from-XIV) [reply src/dune_rules/run_with_path.ml]: This PR introduces the exceptions into this context (thrown by `with_file_in` but caught around `parse_win32_prog_and_args`), so it would make sense to keep the code exception-free from the start instead of merging it and then removing it later.

File: src/dune_rules/run_with_path.ml [hunk 35]
```diff
@@ -73,6 +73,88 @@ end = struct
...
+          (* CR-someday: Limit how many bytes we read here? *)
+          let line = input_line ic in
+          let prog, args = parse_shebang_line line in
+          (match prog with
+           | None ->
+             User_error.raise
+               ?loc
+               ~annots
+               [ Pp.textf "Dune could not parse the shebang line in %s:" prog_name
+               ; Pp.textf "  #!%s" line
```
Comment (Alizter) [inline src/dune_rules/run_with_path.ml]: May want to `String.trim` here or else `\r` may be returned.

**Review by Alizter — APPROVED** [review]

File: src/dune_rules/run_with_path.ml (hunk 35 above)
Comment (punchagan) [reply src/dune_rules/run_with_path.ml]: Fixed, thanks!

Comment (punchagan) [reply src/dune_rules/run_with_path.ml]: That seemed to have caused [one of the cram tests to fail](https://github.com/ocaml/dune/actions/runs/21587597359/job/62200203984?pr=13293#step:12:27) on Windows. I reverted the change.

**Review by rgrinberg — APPROVED** [review]
LGTM.

I think it would be better to test this behavior on every OS by making it possible to enable it in a config. Few of us have access to Windows otherwise.
