### PR TITLE
rpc status: fix for Win32

### LINKED ISSUE #8799: windows: dune rpc status not working
## Expected Behavior

`dune rpc status` should work correctly on windows.

## Actual Behavior

`duen rpc status` reports that there is no running RPC server. This is not true as ocamllsp is able to connect to it just fine.

## Reproduction

1. On Windows with dkml ocaml, start dune in watch mode in a project.
2. From another terminal do `dune rpc status`
3. Dune will complain nothing is running.

## Specifications

- Version of `dune` (output of `dune --version`): 3.10.0
- Version of `ocaml` (output of `ocamlc --version`): 4.14.0
- Operating system (distribution and version): Windows 11

### PR DESCRIPTION
**Pull request by nojb**
Beginning of a fix for #8799, but not complete because `dune rpc status` does not seem to be fully working:

image

(no data is reported for the connected client)

cc @Alizter

### CODE REVIEW

**Comment by nojb** [comment]
After further testing, it seems to be working:

image

@Alizter, can you give it a try on your side to confirm? Thanks!

**Review by Alizter — APPROVED** [review]
Works great, thanks!

cc @emillon any chance we can get this backported for 3.9-3.11? Or at least add it to a list in case another point release is decided.

File: otherlibs/dune-rpc/private/where.ml [hunk 1]
```diff
@@ -151,20 +151,22 @@ module Make
          | Ok s -> Ok (Some s)
          | Error exn -> Error exn)
     | None ->
-      let of_file f =
-        let+ contents = IO.read_file f in
-        match contents with
-        | Error e -> Error e
-        | Ok contents ->
-          (match of_string contents with
+      (match default ~build_dir () with
```
Comment (rgrinberg) [inline otherlibs/dune-rpc/private/where.ml:154]: I don't know what the issue is yet, but this fix doesn't seem right to me. Previously, the code would look at the socket inside the build directory to connect, and now it's just assuming the address is the default address.

**Review by rgrinberg — CHANGES_REQUESTED** [review]

File: otherlibs/dune-rpc/private/where.ml (hunk 1 above)
Comment (nojb) [reply otherlibs/dune-rpc/private/where.ml:154]: Nothing has changed here for Unix systems: `default ~build_dir ()` still returns the socket inside the build directory:

https://github.com/ocaml/dune/blob/071cb4718d4c23f9b3645c8c254028df6d1a35c2/otherlibs/dune-rpc/private/where.ml#L130-L134

Comment (rgrinberg) [reply otherlibs/dune-rpc/private/where.ml:154]: Okay, but even on Windows, the workflow to connect should be:

1. Inspect the file _build/.rpc/dune
2. If it's a socket, connect to it (will never happen on windows)
3. If it's a normal file, read it and get the connection string from here. On windows, that connection string will have the address we want to connect on.

Comment (nojb) [reply otherlibs/dune-rpc/private/where.ml]: Oops, you are right. I hadn't grasped the logic behind the client/server split. Now I pushed a commit with the right fix I think.

File: src/dune_rpc_client/where.ml [hunk 2]
```diff
@@ -47,10 +47,7 @@ let to_socket = function
   | `Ip (`Host host, `Port port) -> Unix.ADDR_INET (Unix.inet_addr_of_string host, port)
 ;;
 
-let to_string = function
-  | `Unix p -> sprintf "unix://%s" p
-  | `Ip (`Host host, `Port port) -> sprintf "%s:%d" host port
-;;
+let to_string t = Dune_rpc_private.Where.to_string t
```
Comment (nojb) [inline src/dune_rpc_client/where.ml:50]: Use the right "dbus" format so that it can be parsed back in https://github.com/ocaml/dune/blob/071cb4718d4c23f9b3645c8c254028df6d1a35c2/otherlibs/dune-rpc/private/where.ml#L154-L162

File: doc/changes/8806.md [hunk 3]
```diff
@@ -0,0 +1 @@
+- Fix `dune rpc status` on Windows (#8806, fixes #8799, @nojb)
```
Comment (rgrinberg) [inline doc/changes/8806.md:1]: This fixes a little more than `status`. It should fix all `dune rpc` commands in fact.

**Review by rgrinberg — APPROVED** [review]

File: doc/changes/8806.md (hunk 3 above)
Comment (Alizter) [reply doc/changes/8806.md]: Looks like `monitor` too.

Comment (nojb) [reply doc/changes/8806.md]: Thanks for the review. I amended the Changes entry.

**Comment by emillon** [comment]
> Works great, thanks!
> 
> cc @emillon any chance we can get this backported for 3.9-3.11? Or at least add it to a list in case another point release is decided.

Sure. To be clear, this is a regression introduced in 3.9.0?

**Comment by nojb** [comment]
> > Works great, thanks!
> > cc @emillon any chance we can get this backported for 3.9-3.11? Or at least add it to a list in case another point release is decided.
> 
> Sure. To be clear, this is a regression introduced in 3.9.0?

I suspect this has never worked on Windows, until this PR.

**Comment by emillon** [comment]
OK. Note a huge rush then. I'll backport that to 3.11.1.
