### PR TITLE
fix(oxcaml): generate merlin config for library parameters

### LINKED ISSUE #12546: Library parameter flags should be added to the merlin config file generated by Dune
## Expected Behavior

The `.merlin` config file generated by Dune should contain path's to library parameter cmi files as well as compiler flags to compile it. A merlin config in this case looks something like this:

```
$ tree
├── a
│   ├── a.mli
│   └── dune
├── b
│   ├── b.mli
│   └── dune
├── dune
├── dune-project
├── param.opam
└── p.ml

$ dune ocaml dump-dot-merlin
EXCLUDE_QUERY_DIR
STDLIB /home/sudha/.opam/oxcaml/lib/ocaml
SOURCE_ROOT /home/sudha/ocaml/sudha/testing-ground/parameterised
B /home/sudha/ocaml/sudha/testing-ground/parameterised/_build/default/.parameterised.objs/byte
B /home/sudha/ocaml/sudha/testing-ground/parameterised/_build/default/a/.a.objs/byte
B /home/sudha/ocaml/sudha/testing-ground/parameterised/_build/default/b/.b.objs/byte
S /home/sudha/ocaml/sudha/testing-ground/parameterised
S /home/sudha/ocaml/sudha/testing-ground/parameterised/a
S /home/sudha/ocaml/sudha/testing-ground/parameterised/b
INDEX /home/sudha/ocaml/sudha/testing-ground/parameterised/_build/default/.parameterised.objs/cctx.ocaml-index
INDEX /home/sudha/ocaml/sudha/testing-ground/parameterised/_build/default/a/.a.objs/cctx.ocaml-index
INDEX /home/sudha/ocaml/sudha/testing-ground/parameterised/_build/default/b/.b.objs/cctx.ocaml-index
FLG -w @1..3@5..28@31..39@43@46..47@49..57@61..62@67@69-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -parameter A -parameter B
```

## Actual Behavior

The `.merlin` config generated does not include the `-parameter` flag and the whole `FLG` field is commented out - maybe there's a dune flag to activate this?

```
$ dune ocaml dump-dot-merlin
EXCLUDE_QUERY_DIR
STDLIB /home/sudha/.opam/oxcaml/lib/ocaml
SOURCE_ROOT /home/sudha/ocaml/sudha/testing-ground/parameterised
B /home/sudha/ocaml/sudha/testing-ground/parameterised/_build/default/.parameterised.objs/byte
B /home/sudha/ocaml/sudha/testing-ground/parameterised/_build/default/a/.a.objs/byte
B /home/sudha/ocaml/sudha/testing-ground/parameterised/_build/default/b/.b.objs/byte
S /home/sudha/ocaml/sudha/testing-ground/parameterised
S /home/sudha/ocaml/sudha/testing-ground/parameterised/a
S /home/sudha/ocaml/sudha/testing-ground/parameterised/b
INDEX /home/sudha/ocaml/sudha/testing-ground/parameterised/_build/default/.parameterised.objs/cctx.ocaml-index
INDEX /home/sudha/ocaml/sudha/testing-ground/parameterised/_build/default/a/.a.objs/cctx.ocaml-index
INDEX /home/sudha/ocaml/sudha/testing-ground/parameterised/_build/default/b/.b.objs/cctx.ocaml-index
# FLG -w @1..3@5..28@31..39@43@46..47@49..57@61..62@67@69-40 -strict-sequence -strict-formats -short-paths -keep-locs -g
```

## Reproduction

- PR with a reproducing test: 

<!-- Otherwise, please detail how the behavior can be reproduced -

The repo is here: https://github.com/Sudha247/parameterised-libraries-sample. Clone the repository and run `dune ocaml dump-dot-merlin` in the root.

## Specifications

- Version of `dune` (output of `dune --version`): `main` branch at 3802d479eb868e34da379d74bfb4fd36f413c44d
- Version of `ocaml` (output of `ocamlc --version`): 5.2.0+ox
- Operating system (distribution and version): Ubuntu 22

### PR DESCRIPTION
**Pull request by Sudha247**
Fixes #12546.

With @art-w, we discovered the library parameter flag `-parameter` was being added to the compilation context but did not propagate to the merlin config. This takes the information from compilation context and feeds into the merlin config generation.

### CODE REVIEW

File: src/dune_rules/lib_rules.ml [hunk 1]
```diff
@@ -636,6 +637,7 @@ let library_rules
       ~dialects:(Dune_project.dialects (Scope.project scope))
       ~ident:(Merlin_ident.for_lib (Library.best_name lib))
       ~modes:(`Lib (Lib_info.modes lib_info))
+      ~parameters (* ["-parameter"; "A"; "-parameter"; "B"] *)
```
Comment (shonfeder) [inline src/dune_rules/lib_rules.ml]: nit: This seems like a slightly strange place for the example comment, IMO. Perhaps it would be more helpful and obviously placed in the documentation comment for the argument where `Merline.make` is defined?

File: src/dune_rules/merlin/merlin.mli [hunk 2]
```diff
@@ -52,6 +52,7 @@ val make
   -> dialects:Dialect.DB.t
   -> ident:Merlin_ident.t
   -> modes:[ `Lib of Lib_mode.Map.Set.t | `Exe | `Melange_emit ]
+  -> parameters:Module_name.t list Resolve.t
```
Comment (shonfeder) [inline src/dune_rules/merlin/merlin.mli:55]: This looks to me like the right place for the documentation comment about the representation of the parameters.

File: test/blackbox-tests/test-cases/oxcaml/library-field-parameters.t [hunk 3]
```diff
@@ -380,3 +380,79 @@ A library can have more parameters than its dependencies:
   > EOF
 
   $ dune build
+  $ dune ocaml dump-dot-merlin lib2
+  EXCLUDE_QUERY_DIR
+  STDLIB /home/sudha/.opam/oxcaml2/lib/ocaml
```
Comment (shonfeder) [inline test/blackbox-tests/test-cases/oxcaml/library-field-parameters.t]: Looks like this info is not getting masked correctly. It looks like this can be addressed by adding a suitable pattern to the `BUILD_PREFIX_MAP` envvar, based on this example:

https://github.com/ocaml/dune/blob/14533edaecedcb46b2413b18b8398b36387f1389/test/blackbox-tests/test-cases/melange/merlin.t#L3-L8

File: src/dune_rules/lib_rules.ml (hunk 1 above)
Comment (rgrinberg) [inline src/dune_rules/lib_rules.ml]: Remove the comment please

File: test/expect-tests/persistent_tests.ml [hunk 4]
```diff
@@ -48,7 +48,7 @@ let%expect_test "persistent digests" =
     ---
 
     merlin-conf version 7
-    a14a4700929a15bb2030e36f71e66d20
+    699a5c5c686662da218d0be3cb2f161c
```
Comment (rgrinberg) [inline test/expect-tests/persistent_tests.ml:51]: This change means that you should bump the merlin-conf version from 7 to 8

**Review by rgrinberg — CHANGES_REQUESTED** [review]

**Review by shonfeder — COMMENTED** [review]
Had some pending suggestions which I forget to submit :)

File: test/expect-tests/persistent_tests.ml (hunk 4 above)
Comment (Sudha247) [reply test/expect-tests/persistent_tests.ml:51]: Updated!

File: src/dune_rules/lib_rules.ml (hunk 1 above)
Comment (Sudha247) [reply src/dune_rules/lib_rules.ml]: You're right, it was a debug comment for myself. I've moved it to `merlin.mli`.

File: test/blackbox-tests/test-cases/oxcaml/library-field-parameters.t [hunk 5]
```diff
@@ -379,4 +383,84 @@ A library can have more parameters than its dependencies:
   > (library (name lib2) (parameters a b c) (libraries lib))
   > EOF
 
+  $ ocamlc_where="$(ocamlc -where)"
```
Comment (rgrinberg) [inline test/blackbox-tests/test-cases/oxcaml/library-field-parameters.t:386]: How about filtering the output for these commands that aren't related to the test? It would make the test a lot clearer if the output reflected what's being tested rather than all the general merlin stuff that is already tested elsewhere.

Comment (shonfeder) [reply test/blackbox-tests/test-cases/oxcaml/library-field-parameters.t:386]: I'd be in favor of that. IIUC, concretely that will just look like piping thru a grep to pick out the addition of the lines we need to see.
