### PR TITLE
fix: better handling of mkdir races

### LINKED ISSUE #5461: Cache: Error: mkdir(/Users/runner/.cache/dune/db/temp): File exists
https://github.com/ocsigen/lwt/runs/5262157265?check_suite_focus=true

```
+ /Users/runner/.opam/opam-init/hooks/sandbox.sh "build" "dune" "build" "-p" "csexp" "-j" "3" "@install" (CWD=/Users/runner/work/lwt/lwt/_opam/.opam-switch/build/csexp.1.5.1)
[ERROR] The compilation of csexp.1.5.1 failed at "dune build -p csexp -j 3 @install".
- Error: mkdir(/Users/runner/.cache/dune/db/temp): File exists
- Error: mkdir(/Users/runner/.cache/dune/db/temp): File exists
```

### PR DESCRIPTION
**Pull request by rgrinberg**
This PR fixes the race that occurs when:

1. we want to `$ mkdir -p x/y`
2. `x` does not exist
3. we successfully create `x`
4. we try creating `y`
5. but someone else already created `y` for us

Maybe this fixes #5461?

### CODE REVIEW

File: otherlibs/stdune/fpath.ml [hunk 1]
```diff
@@ -31,12 +31,17 @@ let rec mkdir_p ?(perms = 0o777) t_s =
...
-      match mkdir_p ~perms parent with
-      | Created | Already_exists ->
+      match mkdir_p ?perms parent with
+      | Created | Already_exists -> (
         (* The [Already_exists] case might happen if some other process managed
            to create the parent directory concurrently. *)
-        Unix.mkdir t_s perms;
-        Created)
+        match mkdir t_s ?perms with
+        | Created | Already_exists -> Created
```
Comment (snowleopard) [inline otherlibs/stdune/fpath.ml:39]: It's odd that we return `Created` if we hit both `Already_exists` branches. It probably doesn't matter much but it may be confusing if two concurrent calls to `mkdir_p` on the same path succeed with `Created`.

**Review by snowleopard — APPROVED** [review]
Wow, creating directories is tricky! Thanks for the fix.

File: otherlibs/stdune/fpath.ml (hunk 1 above)
Comment (rgrinberg) [reply otherlibs/stdune/fpath.ml:39]: Good point. I'll return the value from `mkdir`
