### PR TITLE
fix(cram): make sure directory is empty during cram execution

### LINKED ISSUE #12321: dune 3.20.0: Cram tests now have hidden file `.cram.run.t`
## Expected Behavior
I have a cram test `run.t`:
```cram
List all files

  $ ls -a
  .
  ..

The directory should be empty save for current directory and parent directory
```
Then `dune runtest` runs the test which passes.

## Actual Behavior
The test fails:
```diff
File "test/run.t", line 1, characters 0-0:
diff --git a/_build/default/test/run.t b/_build/default/test/run.t.corrected
index e2b1fee..36596dc 100644
--- a/_build/default/test/run.t
+++ b/_build/default/test/run.t.corrected
@@ -3,5 +3,6 @@ List all files
   $ ls -a
   .
   ..
+  .cram.run.t
 
 The directory should be empty save for current directory and parent directory
```

## Reproduction

The bug can be reproduced with the above cram test

## Specifications

- Version of `dune` (output of `dune --version`): 3.20.0 (not a problem with 3.19.1!)
- Version of `ocaml` (output of `ocamlc --version`): 5.2.1
- Operating system (distribution and version): debian 13

## Additional information 

I suspect this PR introduced the bug: https://github.com/ocaml/dune/pull/11994

### PR DESCRIPTION
**Pull request by Alizter**
- fix https://github.com/ocaml/dune/issues/12321
- [x] changelog

### CODE REVIEW

File: src/dune_util/persistent.ml [hunk 1]
```diff
@@ -71,6 +71,7 @@ module Make (D : Desc) = struct
 
   let dump =
     let dump file v =
+      Path.mkdir_p (Path.parent_exn file);
```
Comment (rgrinberg) [inline src/dune_util/persistent.ml]: Can you move this to the caller? Seems undesirable to pay this penalty in every `dump` call.

**Review by rgrinberg — CHANGES_REQUESTED** [review]
The fix is fine, but we don't want to a bunch of pointless `mkdir` everywhere

**Comment by Alizter** [comment]
I've moved the mkdir to the caller.

File: src/dune_rules/cram/cram_exec.ml [hunk 2]
```diff
@@ -443,14 +443,19 @@ let run_and_produce_output ~src ~env ~dir:cwd ~script ~dst ~timeout =
   let lexbuf = Lexbuf.from_string script_contents ~fname:(Path.to_string script) in
   let temp_dir = make_temp_dir ~script in
   let cram_stanzas = cram_stanzas lexbuf in
-  Path.unlink_exn script;
+  (* We don't want the ".cram.run.t" dir around when executing the script. *)
+  Path.rm_rf (Path.parent_exn script);
```
Comment (rgrinberg) [inline src/dune_rules/cram/cram_exec.ml:474]: Shouldn't we be clearing this directory rather than deleting it? This way we don't have to do the mkdir_p?

Comment (Alizter) [reply src/dune_rules/cram/cram_exec.ml:474]: If we clear the directory, then the empty directory will be present in the test. `Path.rm_rf` will already clear and then delete the directory.

The behaviour before is essentially what you said since we only have a single file, the `.cram.testname.t/script` file at this point.

Comment (Alizter) [reply src/dune_rules/cram/cram_exec.ml:474]: A strange behaviour is that this directory doesn't appear for directory cram tests, so perhaps we are misconfiguring a directory somewhere. I couldn't find it, so this is the solution I chose.

**Review by rgrinberg — APPROVED** [review]
