### PR TITLE
fix: correctly print multi-line excerpts

### LINKED ISSUE #7905: Location Parsing Bug
I have the following stack trace:

```
/usr/local/home/nroberts/.opam/ocaml-base-compiler/bin/dune diagnostics
Error: exception Invalid_argument("Bytes.create")
Raised by primitive operation at Stdlib__Bytes.make in file "[bytes.ml](http://bytes.ml/)", line
  42, characters 10-18
Called from Stdlib__String.make in file "[string.ml](http://string.ml/)" (inlined), line 41,
  characters 2-12
Called from Stdune__loc.pp_file_excerpt.pp_file_excerpt in file
  "otherlibs/stdune/src/[loc.ml](http://loc.ml/)", line 72, characters 52-73
Called from Stdune__result.bind in file "otherlibs/stdune/src/[result.ml](http://result.ml/)"
  (inlined), line 33, characters 12-15
Called from Stdune__result.O.(>>=) in file "otherlibs/stdune/src/[result.ml](http://result.ml/)"
  (inlined), line 68, characters 20-29
Called from Stdune__loc.pp_file_excerpt in file
  "otherlibs/stdune/src/[loc.ml](http://loc.ml/)", line 117, characters 6-158
Called from Stdune__loc.pp in file "otherlibs/stdune/src/[loc.ml](http://loc.ml/)", line 140,
  characters 5-72
Called from Main__diagnostics.format_diagnostic in file "bin/[diagnostics.ml](http://diagnostics.ml/)",
  line 25, characters 67-77
Called from Main__diagnostics.exec.(fun) in file "bin/[diagnostics.ml](http://diagnostics.ml/)", line
  50, characters 55-78
Called from Stdlib__List.iter in file "[list.ml](http://list.ml/)", line 110, characters 12-15
Called from Fiber__core.O.(>>|).(fun) in file "otherlibs/fiber/src/[core.ml](http://core.ml/)",
  line 250, characters 36-41
Called from Fiber__scheduler.exec in file "otherlibs/fiber/src/[scheduler.ml](http://scheduler.ml/)",
  line 73, characters 8-11

I must not crash.  Uncertainty is the mind-killer. Exceptions are the
little-death that brings total obliteration.  I will fully express my cases.
Execution will pass over me and through me.  And when it has gone past, I
will unwind the stack along its path.  Where the cases are handled there will
be nothing.  Only I will remain.
```

And that the commit from which this error was triggered is: https://github.com/ocaml-flambda/flambda-backend/commit/7ae108896b7c4f62ffabdcd14d4df9b2d4b8345d

### PR DESCRIPTION
**Pull request by rgrinberg**
The previous code would pretend that a multi-line excerpt was
single-line whenever the stop character was outside the line.

Fixes #7905

Signed-off-by: Rudi Grinberg <me@rgrinberg.com>

### CODE REVIEW

**Comment by rgrinberg** [comment]
@emillon perhaps we can consider this for 3.8.2?

**Comment by emillon** [comment]
yes, that would work

File: otherlibs/stdune/src/loc.ml [hunk 1]
```diff
@@ -57,21 +57,27 @@ let pp_file_excerpt ~context_lines ~max_lines_to_print_in_full { start; stop } :
...
+        let* line =
+          Result.try_with (fun () -> Io.String_path.file_line file line_num)
+        in
+        let len = stop_c - start_c in
+        let open Pp.O in
+        Ok
+          (`Singleline
+            (pp_line padding_width (line_num_str, line)
+            ++ pp_left_pad (stop_c + padding_width + 3) (String.make len '^')
+            ++ Pp.newline))
```
Comment (nojb) [inline otherlibs/stdune/src/loc.ml:76]: I would push this code under the `Ok Singleline` case below (similarly to the other case).

**Review by nojb — APPROVED** [review]
LGTM, but I left a stylistic suggestion.

**Comment by rgrinberg** [comment]
@emillon I put this as 3.9.0 tentatively, but feel free to re-adjust to 3.8.2
