### PR TITLE
fix(ctypes): mismatch between modules field and ctypes stanza

### LINKED ISSUE #12018: crash when using ctypes stanza
Hi,

This seems quite similar to #5561 which should have been fixed in #6374. But I am using dune `3.19.1` with `(lang dune 3.19)`.

```shell-session
$ dune b @all --profile release
Internal error, please report upstream including the contents of _build/log.
Description:
  ("link_many: unable to find module",
   { main_module_name = "SDL3__type_gen"
   ; modules =
       Modules
         (Wrapped
            { group =
                { alias =
                    { source =
                        { path = [ "Dune__exe" ]
                        ; files =
                            { impl =
                                Some
                                  { path =
                                      In_build_dir
                                        "default/src/sdl/.sdl.eobjs/dune__exe.ml-gen"
                                  ; original_path =
                                      In_build_dir
                                        "default/src/sdl/.sdl.eobjs/dune__exe.ml-gen"
                                  ; dialect = "ocaml"
                                  }
                            ; intf = None
                            }
                        }
                    ; obj_name = "dune__exe"
                    ; pp = None
                    ; visibility = "public"
                    ; kind = Alias []
                    ; install_as = Some "dune__exe.ml"
                    }
                ; name = "Dune__exe"
                ; modules =
                    map
                      { "Function_description" :
                          module
                            { source =
                                { path = [ "Function_description" ]
                                ; files =
                                    { impl =
                                        Some
                                          { path =
                                              In_build_dir
                                                "default/src/sdl/function_description.ml"
                                          ; original_path =
                                              In_build_dir
                                                "default/src/sdl/function_description.ml"
                                          ; dialect = "ocaml"
                                          }
                                    ; intf = None
                                    }
                                }
                            ; obj_name = "dune__exe__Function_description"
                            ; pp = None
                            ; visibility = "public"
                            ; kind = Impl
                            ; install_as = None
                            }
                      ; "Sdl" :
                          module
                            { source =
                                { path = [ "Sdl" ]
                                ; files =
                                    { impl =
                                        Some
                                          { path =
                                              In_build_dir
                                                "default/src/sdl/sdl.ml"
                                          ; original_path =
                                              In_build_dir
                                                "default/src/sdl/sdl.ml"
                                          ; dialect = "ocaml"
                                          }
                                    ; intf =
                                        Some
                                          { path =
                                              In_build_dir
                                                "default/src/sdl/sdl.mli"
                                          ; original_path =
                                              In_build_dir
                                                "default/src/sdl/sdl.mli"
                                          ; dialect = "ocaml"
                                          }
                                    }
                                }
                            ; obj_name = "dune__exe__Sdl"
                            ; pp = None
                            ; visibility = "public"
                            ; kind = Impl
                            ; install_as = None
                            }
                      ; "Type_description" :
                          module
                            { source =
                                { path = [ "Type_description" ]
                                ; files =
                                    { impl =
                                        Some
                                          { path =
                                              In_build_dir
                                                "default/src/sdl/type_description.ml"
                                          ; original_path =
                                              In_build_dir
                                                "default/src/sdl/type_description.ml"
                                          ; dialect = "ocaml"
                                          }
                                    ; intf = None
                                    }
                                }
                            ; obj_name = "dune__exe__Type_description"
                            ; pp = None
                            ; visibility = "public"
                            ; kind = Impl
                            ; install_as = None
                            }
                      }
                }
            ; wrapped_compat = map {}
            ; wrapped = Simple true
            })
   })
Raised at Stdune__Code_error.raise in file
  "otherlibs/stdune/src/code_error.ml", line 10, characters 30-62
Called from Dune_rules__Exe.link_many.(fun) in file "src/dune_rules/exe.ml",
  lines 312-316, characters 12-15
Called from Fiber__Scheduler.exec in file "vendor/fiber/src/scheduler.ml",
  line 76, characters 8-11
-> required by ("<unnamed>", ())
-> required by ("load-dir", In_build_dir "default/src/sdl")
-> required by ("toplevel", ())

I must not crash.  Uncertainty is the mind-killer. Exceptions are the
little-death that brings total obliteration.  I will fully express my cases. 
Execution will pass over me and through me.  And when it has gone past, I
will unwind the stack along its path.  Where the cases are handled there will
be nothing.  Only I will remain.
```

```shell-session
$ cat _build/log
# dune b @all --profile release
# OCAMLPARAM: unset
# Shared cache: enabled-except-user-rules
# Shared cache location: /home/XXX/.cache/dune/db
# Workspace root: /home/XXX/dev/ml/frost
# Auto-detected concurrency: 16
# Dune context:
#  { name = "default"
#  ; kind = "default"
#  ; profile = Release
#  ; merlin = true
#  ; fdo_target_exe = None
#  ; build_dir = In_build_dir "default"
#  ; instrument_with = []
#  }
$ /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/bin/ocamlc.opt -config > /tmp/nix-shell-193993-0/dune_b2b6ba_output
$ (cd _build/default && /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/bin/ocamlc.opt -w -40 -w -49 -nopervasives -nostdlib -g -bin-annot -bin-annot-occurrences -I src/.frost.objs/byte -no-alias-deps -o src/.frost.objs/byte/frost.cmo -c -impl src/frost.ml-gen)
$ (cd _build/default && /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/bin/ocamldep.opt -modules -impl src/widget.ml) > _build/default/src/.frost.objs/frost__Widget.impl.d
$ (cd _build/default && /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/bin/ocamlopt.opt -w -40 -w -49 -nopervasives -nostdlib -g -I src/.frost.objs/byte -I src/.frost.objs/native -intf-suffix .ml-gen -no-alias-deps -o src/.frost.objs/native/frost.cmx -c -impl src/frost.ml-gen)
$ (cd _build/default && /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/bin/ocamldep.opt -modules -impl src/syntax.ml) > _build/default/src/.frost.objs/frost__Syntax.impl.d
$ (cd _build/default && /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/bin/ocamldep.opt -modules -impl src/app.ml) > _build/default/src/.frost.objs/frost__App.impl.d
$ (cd _build/default && /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/bin/ocamlc.opt -w -40 -g -bin-annot -bin-annot-occurrences -I src/.frost.objs/byte -I /nix/store/3f0792c94m7b9ljs2kdk6cqpz928n4q6-ocaml5.3.0-stdlib-shims-0.3.0/lib/ocaml/5.3.0/site-lib/stdlib-shims -I /nix/store/59apxbjkg7k2a5fxnshb109d056168kp-ocaml5.3.0-ctypes-foreign-0.23.0/lib/ocaml/5.3.0/site-lib/ctypes-foreign -I /nix/store/a44yl02l5nqm9vdnjx940nqli0fnmsfx-ocaml5.3.0-tsdl-1.1.0/lib/ocaml/5.3.0/site-lib/tsdl -I /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/lib/ocaml/threads -I /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/lib/ocaml/unix -I /nix/store/iyqyw7ghjih4y0p457q1vjyjp1ii9aw7-ocaml5.3.0-ctypes-0.23.0/lib/ocaml/5.3.0/site-lib/ctypes -I /nix/store/lbi4ar4862bkkkrn3kd1d6cnflqirix9-ocaml5.3.0-integers-0.7.0/lib/ocaml/5.3.0/site-lib/integers -I /nix/store/n9rp862mirbyrvjwh8xhi5zfn9a2cpgn-ocaml5.3.0-fmt-0.10.0/lib/ocaml/5.3.0/site-lib/fmt -I /nix/store/wsaxw9iwpjn8xh6pildyqfjs8fl19996-ocaml5.3.0-bigarray-compat-1.1.0/lib/ocaml/5.3.0/site-lib/bigarray-compat -no-alias-deps -open Frost -o src/.frost.objs/byte/frost__Syntax.cmo -c -impl src/syntax.ml)
$ (cd _build/default && /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/bin/ocamlopt.opt -w -40 -g -I src/.frost.objs/byte -I src/.frost.objs/native -I /nix/store/3f0792c94m7b9ljs2kdk6cqpz928n4q6-ocaml5.3.0-stdlib-shims-0.3.0/lib/ocaml/5.3.0/site-lib/stdlib-shims -I /nix/store/59apxbjkg7k2a5fxnshb109d056168kp-ocaml5.3.0-ctypes-foreign-0.23.0/lib/ocaml/5.3.0/site-lib/ctypes-foreign -I /nix/store/a44yl02l5nqm9vdnjx940nqli0fnmsfx-ocaml5.3.0-tsdl-1.1.0/lib/ocaml/5.3.0/site-lib/tsdl -I /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/lib/ocaml/threads -I /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/lib/ocaml/unix -I /nix/store/iyqyw7ghjih4y0p457q1vjyjp1ii9aw7-ocaml5.3.0-ctypes-0.23.0/lib/ocaml/5.3.0/site-lib/ctypes -I /nix/store/lbi4ar4862bkkkrn3kd1d6cnflqirix9-ocaml5.3.0-integers-0.7.0/lib/ocaml/5.3.0/site-lib/integers -I /nix/store/n9rp862mirbyrvjwh8xhi5zfn9a2cpgn-ocaml5.3.0-fmt-0.10.0/lib/ocaml/5.3.0/site-lib/fmt -I /nix/store/wsaxw9iwpjn8xh6pildyqfjs8fl19996-ocaml5.3.0-bigarray-compat-1.1.0/lib/ocaml/5.3.0/site-lib/bigarray-compat -intf-suffix .ml -no-alias-deps -open Frost -o src/.frost.objs/native/frost__Syntax.cmx -c -impl src/syntax.ml)
$ (cd _build/default && /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/bin/ocamlc.opt -w -40 -g -bin-annot -bin-annot-occurrences -I src/.frost.objs/byte -I /nix/store/3f0792c94m7b9ljs2kdk6cqpz928n4q6-ocaml5.3.0-stdlib-shims-0.3.0/lib/ocaml/5.3.0/site-lib/stdlib-shims -I /nix/store/59apxbjkg7k2a5fxnshb109d056168kp-ocaml5.3.0-ctypes-foreign-0.23.0/lib/ocaml/5.3.0/site-lib/ctypes-foreign -I /nix/store/a44yl02l5nqm9vdnjx940nqli0fnmsfx-ocaml5.3.0-tsdl-1.1.0/lib/ocaml/5.3.0/site-lib/tsdl -I /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/lib/ocaml/threads -I /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/lib/ocaml/unix -I /nix/store/iyqyw7ghjih4y0p457q1vjyjp1ii9aw7-ocaml5.3.0-ctypes-0.23.0/lib/ocaml/5.3.0/site-lib/ctypes -I /nix/store/lbi4ar4862bkkkrn3kd1d6cnflqirix9-ocaml5.3.0-integers-0.7.0/lib/ocaml/5.3.0/site-lib/integers -I /nix/store/n9rp862mirbyrvjwh8xhi5zfn9a2cpgn-ocaml5.3.0-fmt-0.10.0/lib/ocaml/5.3.0/site-lib/fmt -I /nix/store/wsaxw9iwpjn8xh6pildyqfjs8fl19996-ocaml5.3.0-bigarray-compat-1.1.0/lib/ocaml/5.3.0/site-lib/bigarray-compat -no-alias-deps -open Frost -o src/.frost.objs/byte/frost__Widget.cmo -c -impl src/widget.ml)
$ (cd _build/default && /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/bin/ocamlc.opt -w -40 -g -bin-annot -bin-annot-occurrences -I src/.frost.objs/byte -I /nix/store/3f0792c94m7b9ljs2kdk6cqpz928n4q6-ocaml5.3.0-stdlib-shims-0.3.0/lib/ocaml/5.3.0/site-lib/stdlib-shims -I /nix/store/59apxbjkg7k2a5fxnshb109d056168kp-ocaml5.3.0-ctypes-foreign-0.23.0/lib/ocaml/5.3.0/site-lib/ctypes-foreign -I /nix/store/a44yl02l5nqm9vdnjx940nqli0fnmsfx-ocaml5.3.0-tsdl-1.1.0/lib/ocaml/5.3.0/site-lib/tsdl -I /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/lib/ocaml/threads -I /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/lib/ocaml/unix -I /nix/store/iyqyw7ghjih4y0p457q1vjyjp1ii9aw7-ocaml5.3.0-ctypes-0.23.0/lib/ocaml/5.3.0/site-lib/ctypes -I /nix/store/lbi4ar4862bkkkrn3kd1d6cnflqirix9-ocaml5.3.0-integers-0.7.0/lib/ocaml/5.3.0/site-lib/integers -I /nix/store/n9rp862mirbyrvjwh8xhi5zfn9a2cpgn-ocaml5.3.0-fmt-0.10.0/lib/ocaml/5.3.0/site-lib/fmt -I /nix/store/wsaxw9iwpjn8xh6pildyqfjs8fl19996-ocaml5.3.0-bigarray-compat-1.1.0/lib/ocaml/5.3.0/site-lib/bigarray-compat -no-alias-deps -open Frost -o src/.frost.objs/byte/frost__App.cmo -c -impl src/app.ml)
$ (cd _build/default && /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/bin/ocamlc.opt -w -40 -g -a -o src/frost.cma src/.frost.objs/byte/frost.cmo src/.frost.objs/byte/frost__Syntax.cmo src/.frost.objs/byte/frost__Widget.cmo src/.frost.objs/byte/frost__App.cmo)
$ (cd _build/default && /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/bin/ocamlc.opt -w -40 -g -bin-annot -bin-annot-occurrences -I src/.alex.eobjs/byte -I /nix/store/3f0792c94m7b9ljs2kdk6cqpz928n4q6-ocaml5.3.0-stdlib-shims-0.3.0/lib/ocaml/5.3.0/site-lib/stdlib-shims -I /nix/store/59apxbjkg7k2a5fxnshb109d056168kp-ocaml5.3.0-ctypes-foreign-0.23.0/lib/ocaml/5.3.0/site-lib/ctypes-foreign -I /nix/store/a44yl02l5nqm9vdnjx940nqli0fnmsfx-ocaml5.3.0-tsdl-1.1.0/lib/ocaml/5.3.0/site-lib/tsdl -I /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/lib/ocaml/threads -I /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/lib/ocaml/unix -I /nix/store/iyqyw7ghjih4y0p457q1vjyjp1ii9aw7-ocaml5.3.0-ctypes-0.23.0/lib/ocaml/5.3.0/site-lib/ctypes -I /nix/store/lbi4ar4862bkkkrn3kd1d6cnflqirix9-ocaml5.3.0-integers-0.7.0/lib/ocaml/5.3.0/site-lib/integers -I /nix/store/n9rp862mirbyrvjwh8xhi5zfn9a2cpgn-ocaml5.3.0-fmt-0.10.0/lib/ocaml/5.3.0/site-lib/fmt -I /nix/store/wsaxw9iwpjn8xh6pildyqfjs8fl19996-ocaml5.3.0-bigarray-compat-1.1.0/lib/ocaml/5.3.0/site-lib/bigarray-compat -I src/.frost.objs/byte -no-alias-deps -o src/.alex.eobjs/byte/dune__exe__Alex.cmi -c -intf src/alex.mli)
$ (cd _build/default && /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/bin/ocamlopt.opt -w -40 -g -I src/.frost.objs/byte -I src/.frost.objs/native -I /nix/store/3f0792c94m7b9ljs2kdk6cqpz928n4q6-ocaml5.3.0-stdlib-shims-0.3.0/lib/ocaml/5.3.0/site-lib/stdlib-shims -I /nix/store/59apxbjkg7k2a5fxnshb109d056168kp-ocaml5.3.0-ctypes-foreign-0.23.0/lib/ocaml/5.3.0/site-lib/ctypes-foreign -I /nix/store/a44yl02l5nqm9vdnjx940nqli0fnmsfx-ocaml5.3.0-tsdl-1.1.0/lib/ocaml/5.3.0/site-lib/tsdl -I /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/lib/ocaml/threads -I /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/lib/ocaml/unix -I /nix/store/iyqyw7ghjih4y0p457q1vjyjp1ii9aw7-ocaml5.3.0-ctypes-0.23.0/lib/ocaml/5.3.0/site-lib/ctypes -I /nix/store/lbi4ar4862bkkkrn3kd1d6cnflqirix9-ocaml5.3.0-integers-0.7.0/lib/ocaml/5.3.0/site-lib/integers -I /nix/store/n9rp862mirbyrvjwh8xhi5zfn9a2cpgn-ocaml5.3.0-fmt-0.10.0/lib/ocaml/5.3.0/site-lib/fmt -I /nix/store/wsaxw9iwpjn8xh6pildyqfjs8fl19996-ocaml5.3.0-bigarray-compat-1.1.0/lib/ocaml/5.3.0/site-lib/bigarray-compat -intf-suffix .ml -no-alias-deps -open Frost -o src/.frost.objs/native/frost__Widget.cmx -c -impl src/widget.ml)
$ (cd _build/default && /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/bin/ocamlopt.opt -w -40 -g -I src/.frost.objs/byte -I src/.frost.objs/native -I /nix/store/3f0792c94m7b9ljs2kdk6cqpz928n4q6-ocaml5.3.0-stdlib-shims-0.3.0/lib/ocaml/5.3.0/site-lib/stdlib-shims -I /nix/store/59apxbjkg7k2a5fxnshb109d056168kp-ocaml5.3.0-ctypes-foreign-0.23.0/lib/ocaml/5.3.0/site-lib/ctypes-foreign -I /nix/store/a44yl02l5nqm9vdnjx940nqli0fnmsfx-ocaml5.3.0-tsdl-1.1.0/lib/ocaml/5.3.0/site-lib/tsdl -I /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/lib/ocaml/threads -I /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/lib/ocaml/unix -I /nix/store/iyqyw7ghjih4y0p457q1vjyjp1ii9aw7-ocaml5.3.0-ctypes-0.23.0/lib/ocaml/5.3.0/site-lib/ctypes -I /nix/store/lbi4ar4862bkkkrn3kd1d6cnflqirix9-ocaml5.3.0-integers-0.7.0/lib/ocaml/5.3.0/site-lib/integers -I /nix/store/n9rp862mirbyrvjwh8xhi5zfn9a2cpgn-ocaml5.3.0-fmt-0.10.0/lib/ocaml/5.3.0/site-lib/fmt -I /nix/store/wsaxw9iwpjn8xh6pildyqfjs8fl19996-ocaml5.3.0-bigarray-compat-1.1.0/lib/ocaml/5.3.0/site-lib/bigarray-compat -intf-suffix .ml -no-alias-deps -open Frost -o src/.frost.objs/native/frost__App.cmx -c -impl src/app.ml)
$ (cd _build/default && /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/bin/ocamlopt.opt -w -40 -g -a -o src/frost.cmxa src/.frost.objs/native/frost.cmx src/.frost.objs/native/frost__Syntax.cmx src/.frost.objs/native/frost__Widget.cmx src/.frost.objs/native/frost__App.cmx)
$ (cd _build/default && /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/bin/ocamlopt.opt -w -40 -g -I src/.alex.eobjs/byte -I src/.alex.eobjs/native -I /nix/store/3f0792c94m7b9ljs2kdk6cqpz928n4q6-ocaml5.3.0-stdlib-shims-0.3.0/lib/ocaml/5.3.0/site-lib/stdlib-shims -I /nix/store/59apxbjkg7k2a5fxnshb109d056168kp-ocaml5.3.0-ctypes-foreign-0.23.0/lib/ocaml/5.3.0/site-lib/ctypes-foreign -I /nix/store/a44yl02l5nqm9vdnjx940nqli0fnmsfx-ocaml5.3.0-tsdl-1.1.0/lib/ocaml/5.3.0/site-lib/tsdl -I /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/lib/ocaml/threads -I /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/lib/ocaml/unix -I /nix/store/iyqyw7ghjih4y0p457q1vjyjp1ii9aw7-ocaml5.3.0-ctypes-0.23.0/lib/ocaml/5.3.0/site-lib/ctypes -I /nix/store/lbi4ar4862bkkkrn3kd1d6cnflqirix9-ocaml5.3.0-integers-0.7.0/lib/ocaml/5.3.0/site-lib/integers -I /nix/store/n9rp862mirbyrvjwh8xhi5zfn9a2cpgn-ocaml5.3.0-fmt-0.10.0/lib/ocaml/5.3.0/site-lib/fmt -I /nix/store/wsaxw9iwpjn8xh6pildyqfjs8fl19996-ocaml5.3.0-bigarray-compat-1.1.0/lib/ocaml/5.3.0/site-lib/bigarray-compat -I src/.frost.objs/byte -I src/.frost.objs/native -intf-suffix .ml -no-alias-deps -o src/.alex.eobjs/native/dune__exe__Alex.cmx -c -impl src/alex.ml)
$ (cd _build/default && /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/bin/ocamlopt.opt -w -40 -g -shared -linkall -I src -o src/frost.cmxs src/frost.cmxa)
$ (cd _build/default && /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/bin/ocamlopt.opt -w -40 -g -o src/alex.exe /nix/store/n9rp862mirbyrvjwh8xhi5zfn9a2cpgn-ocaml5.3.0-fmt-0.10.0/lib/ocaml/5.3.0/site-lib/fmt/fmt.cmxa /nix/store/3f0792c94m7b9ljs2kdk6cqpz928n4q6-ocaml5.3.0-stdlib-shims-0.3.0/lib/ocaml/5.3.0/site-lib/stdlib-shims/stdlib_shims.cmxa /nix/store/lbi4ar4862bkkkrn3kd1d6cnflqirix9-ocaml5.3.0-integers-0.7.0/lib/ocaml/5.3.0/site-lib/integers/integers.cmxa -I /nix/store/lbi4ar4862bkkkrn3kd1d6cnflqirix9-ocaml5.3.0-integers-0.7.0/lib/ocaml/5.3.0/site-lib/integers /nix/store/wsaxw9iwpjn8xh6pildyqfjs8fl19996-ocaml5.3.0-bigarray-compat-1.1.0/lib/ocaml/5.3.0/site-lib/bigarray-compat/bigarray_compat.cmxa /nix/store/iyqyw7ghjih4y0p457q1vjyjp1ii9aw7-ocaml5.3.0-ctypes-0.23.0/lib/ocaml/5.3.0/site-lib/ctypes/ctypes.cmxa -I /nix/store/iyqyw7ghjih4y0p457q1vjyjp1ii9aw7-ocaml5.3.0-ctypes-0.23.0/lib/ocaml/5.3.0/site-lib/ctypes /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/lib/ocaml/unix/unix.cmxa /nix/store/d4jraihk93chmcwvcfhnaxh0k5kplqvq-ocaml-5.3.0/lib/ocaml/threads/threads.cmxa /nix/store/59apxbjkg7k2a5fxnshb109d056168kp-ocaml5.3.0-ctypes-foreign-0.23.0/lib/ocaml/5.3.0/site-lib/ctypes-foreign/ctypes_foreign.cmxa -I /nix/store/59apxbjkg7k2a5fxnshb109d056168kp-ocaml5.3.0-ctypes-foreign-0.23.0/lib/ocaml/5.3.0/site-lib/ctypes-foreign /nix/store/a44yl02l5nqm9vdnjx940nqli0fnmsfx-ocaml5.3.0-tsdl-1.1.0/lib/ocaml/5.3.0/site-lib/tsdl/tsdl.cmxa -I /nix/store/a44yl02l5nqm9vdnjx940nqli0fnmsfx-ocaml5.3.0-tsdl-1.1.0/lib/ocaml/5.3.0/site-lib/tsdl src/frost.cmxa src/.alex.eobjs/native/dune__exe__Alex.cmx)
```

### PR DESCRIPTION
**Pull request by Alizter**
When the ctypes stanza asks for some modules, but these are not included
in the modules field, we get a code error later during linking.

We fix this issue by checking for the required modules beforehand and raising a user error if they are missing.

I'm not sure if we need to do something similar for any other generated modules.

- fix https://github.com/ocaml/dune/issues/12018

### CODE REVIEW

File: src/dune_rules/buildable_rules.ml [hunk 1]
```diff
@@ -135,6 +137,29 @@ let modules_rules
...
+  let* () =
+    match ctypes with
+    | Some ctypes ->
+      let (ctypes : Ctypes_field.t) = ctypes in
+      let modules = Modules.With_vlib.modules modules in
+      (ctypes.type_description.functor_loc, ctypes.type_description.functor_)
+      :: List.map
+           ~f:(fun (x : Ctypes_field.Function_description.t) -> x.functor_loc, x.functor_)
+           ctypes.function_description
+      |> Memo.parallel_iter ~f:(fun ((functor_loc, m) : Loc.t * Module_name.t) ->
```
Comment (rgrinberg) [inline src/dune_rules/buildable_rules.ml:154]: Why not just `List.iter`? Also, that `List.map` is unnecesasry.

**Review by rgrinberg — CHANGES_REQUESTED** [review]

File: src/dune_rules/buildable_rules.ml (hunk 1 above)
Comment (Alizter) [reply src/dune_rules/buildable_rules.ml:154]: If we don't use the parallel iter, then we can't get all the error messages at once. I think it is more useful for users to see all the errors rather than one at a time.

Comment (Alizter) [reply src/dune_rules/buildable_rules.ml:154]: The `tpye_description` and `function_description` records are different but they have similar fields. We need to pick the fields that we wish to act on. Therefore the List.map becomes necessary. If you know of a better way to do that, let me know.

File: test/blackbox-tests/test-cases/ctypes/gh12018.t [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+  3 |  (modules foo)
+                ^^^
+  Error: Module Function_description is required by ctypes at dune:13 but is
+  missing in the modules field of the stanza.
+  File "dune", line 3, characters 10-13:
+  3 |  (modules foo)
+                ^^^
+  Error: Module Type_description is required by ctypes at dune:10 but is
+  missing in the modules field of the stanza.
+  [1]
```
Comment (Alizter) [inline test/blackbox-tests/test-cases/ctypes/gh12018.t:56]: @rgrinberg Here is an error message that will collapse to the first if I use `List.iter`.

File: src/dune_rules/buildable_rules.ml (hunk 1 above)
Comment (rgrinberg) [reply src/dune_rules/buildable_rules.ml:154]: I see. You should leave a comment to explain that you're relying on `parallel_iter` to raise more than one error. Raising multiple errors is a fiber primitive, it's a shame we need to it in a roundabout way here.

File: src/dune_rules/buildable_rules.ml [hunk 3]
```diff
@@ -135,6 +137,29 @@ let modules_rules
...
+        match Modules.With_vlib.find modules m with
+        | Some _ -> Memo.return ()
+        | None ->
+          User_error.raise
+            ?loc:modules_loc
```
Comment (rgrinberg) [inline src/dune_rules/buildable_rules.ml]: When this location is absent, you could use `Loc.in_dir`.

**Review by rgrinberg — APPROVED** [review]

File: src/dune_rules/buildable_rules.ml (hunk 1 above)
Comment (Alizter) [reply src/dune_rules/buildable_rules.ml:154]: Done.

File: src/dune_rules/buildable_rules.ml (hunk 3 above)
Comment (Alizter) [reply src/dune_rules/buildable_rules.ml]: Done.

Comment (Alizter) [reply src/dune_rules/buildable_rules.ml]: I wasn't happy with `Loc.in_dir dir` as a fallback, so I instead threaded `buildable_loc` too. If they are both missing then I chose `Loc.in_dir`. I don't think it's worth it to give anything more than this at this point.
