### PR TITLE
fix(runtest): don't run in all contexts

### LINKED ISSUE #13904: 3.22.0 crash due to an internal error
Dune 3.22.0 crashes where 3.21.0 does not in OxCaml CI.
https://github.com/oxcaml/oxcaml/actions/runs/23483647746/job/68336421179?pr=5685

Stack trace:
```
  ("Map.find_exn: failed to find key", { key = "default"; keys = [ "main" ] })
Raised at Stdune__Code_error.raise in file "stdune__Code_error.ml", line 11,
  characters 30-62
Called from Dune_exe__Runtest_common.make_request.(fun) in file
  "dune_exe__Runtest_common.ml", line 188, characters 8-64
Called from Stdlib__List.rev_map.rmap_f in file "list.ml", line 107,
  characters 22-25
Called from Stdune__List.map in file "stdune__List.ml" (inlined), line 6,
  characters 19-33
Called from Dune_exe__Runtest_common.make_request in file
  "dune_exe__Runtest_common.ml", lines 177-203, characters 2-22
Called from Dune_engine__Action_builder.eval in file
  "dune_engine__Action_builder.ml", line 107, characters 25-30
Called from Fiber__Scheduler.exec in file "fiber__Scheduler.ml", line 77,
  characters 8-11
-> required by ("toplevel", ())
```

OCaml compiler: 5.4.0

### PR DESCRIPTION
**Pull request by Alizter**
When choosing which context to find and run our tests, we always choose the default context and if that is not available a unique context. When there is no good choice we error.

- Fixes https://github.com/ocaml/dune/issues/13904
- [x] Changelog

### CODE REVIEW

**Review by shonfeder — APPROVED** [review]

**Review by rgrinberg — CHANGES_REQUESTED** [review]
A couple of things:

1. If we're going to pick a context in a semi random way, we should document the rules for doing so. I.e. something like the "first context that occurs" in the workspace file.

2. Did we consider just improving the error message? I don't understand why we should making a decision for the user at all here and tests can certainly be defined in a context dependant way.

**Comment by Alizter** [comment]
> 1. If we're going to pick a context in a semi random way, we should document the rules for doing so. I.e. something like the "first context that occurs" in the workspace file.

I've reverted my changes picking a context since I was also not happy with it. I've now gone with finding tests per-(super)context.

> 2. Did we consider just improving the error message? I don't understand why we should making a decision for the user at all here and tests can certainly be defined in a context dependant way.

This is technically a regression, since something that worked before is no longer working. See #13904. Therefore introducing an error message, especially since in the oxcaml case there is an obvious context to pick, seems like a bad user experience.

For context, oxcaml have been running `dune runtest` on its own and they have a `main` context and no `default` context. There are a few other places in dune that would also break due to making similar assumptions.

At the time of implementing `dune runtest` for ml tests, it seemed like a sensible choice to pick `default`, I can see now that is not a good idea.

**Comment by Alizter** [comment]
> and tests can certainly be defined in a context dependant way.

Just so we are on the same page, could you elaborate on what you have in mind here?

**Comment by Leonidas-from-XIV** [comment]
> This is technically a regression, since something that worked before is no longer working. 

What was it doing before? I am worried that the behavior before was not reasonable, thus it could make more sense to error out now with a sensible error message instead of silently doing the wrong thing.

**Comment by Alizter** [comment]
@Leonidas-from-XIV Before we started running ml tests, we did not need to know anything about contexts. They were threaded throughout and used by the existing context handling mechanisms.

Since #13064 we now have to classify ml tests, this requires a super context to do so since we use `dir_contents` to load ml sources.

In 3.22.0 we are picking an arbitrary context in order to carry this out, this fix we will do the classification for each separate context, avoiding the need for a choice.

**Comment by rgrinberg** [comment]
I don't think we should fixate on this being a regression. If the previous behavior was intentional, I was certainly unaware of it. We haven't offered backwards compatibility for any commands apart from those used for release builds. I don't think we should start now, especially over something so simple. We can fix their CI script.

Instead, let's focus on providing good semantics for this command. If choosing the main context is so obvious, could you spell out the criteria? The previous implementation in this PR was hardly obvious to me. The new implementation is to run the tests in every context, which I suppose is more sensible, but is still incomplete.

What happens when a test is defined in one context but not another? This can happen when a test has enabled_if on it. I guess that in your implementation, that contexts where the test is undefined should be skipped? I don't think it's working this way at the moment.

I argue that running the tests in every context is also bad user experience. The automatic building of everything in every context is a reason why contexts are mostly avoided in the first place. I would instead go for something like this:

1. We can select an individual context with `--context` like we do for other commands.
2. Absent of a selection, we choose the default context. If there's only one context defined, we can assume it's the default context.
3. To run tests in all contexts, we can either defer to the build command, or introduce something else.

**Comment by Alizter** [comment]
> Absent of a selection, we choose the default context. If there's only one context defined, we can assume it's the default context.

Right, this is the part that is missing here actually. The `main` context from oxcaml is the only context, therefore it is the "obvious choice" that I was mentioning earlier.

My previous idea of picking the first in the list would work in this case too, but would break down when using two non-default contexts. My thinking there was that "at this point, this is on the user", but that's exactly the kind of thinking that caused the issue in the first place.

I think outside of an obvious choice, we should just error. `dune runtest` already supports `--context` and building in multiple contexts by passing `_build/default _build/other` as the args.

Will this fix their CI? No. But at least they can rework it to be `dune runtest --context main`.

**Comment by Alizter** [comment]
@rgrinberg The fix is to now choose `default`, if that's not available then the member of the singleton set of contexts and that's not a singleton we error.

This changes the tested behaviour of `dune runtest`.

**Comment by shonfeder** [comment]
From the release perspective, if the decision is that the previous behavior was undefined and that this is not therefor a regression, then I don't think it belongs in the patch release. In particular, if this will not actually fix the build failures reported in https://github.com/ocaml/dune/issues/13904, then I don't think it needs to be in 3.22.1.   The less that is added there the less risk, and the quicker we can actually fix the genuine regressions. 

With the understanding that a [software regression](https://en.wikipedia.org/wiki/Software_regression) is "a type of software bug where a feature that has worked before stops working correctly" and that a fix for such a bug would be restoring the correct behavior of the feature, is this a fix for a regression?

**Comment by rgrinberg** [comment]
Is there an adequate workaround for this issue? If not, I think applying this fix in the patch release makes sense as well.

File: bin/runtest_common.ml [hunk 1]
```diff
@@ -184,7 +184,20 @@ let make_request ~scontexts ~to_cwd ~test_paths =
...
+        let sctx =
+          match Context_name.Map.find scontexts Context_name.default with
+          | Some sctx -> sctx
+          | None ->
+            (match Context_name.Map.to_list scontexts with
+             | [ (_, sctx) ] -> sctx
+             | _ ->
+               User_error.raise
+                 [ Pp.text
+                     "Multiple contexts are defined but no default context was found. \
```
Comment (rgrinberg) [inline bin/runtest_common.ml:196]: Shall we add a test case for this error?

**Review by rgrinberg — APPROVED** [review]

**Comment by Alizter** [comment]
> From the release perspective, if the decision is that the previous behavior was undefined and that this is not therefor a regression, then I don't think it belongs in the patch release. In particular, if this will not actually fix the build failures reported in #13904, then I don't think it needs to be in 3.22.1. The less that is added there the less risk, and the quicker we can actually fix the genuine regressions.

Please include this in 3.22.1. It's easier for us to fix dune than it is to communicate workarounds to users. I don't see the risk in including this.

**Comment by shonfeder** [comment]
Since it in fact fixes the behavior and doesn't still require a workaround, I think it should indeed be included! My question was at a point in the discussion where that wasn't decided, IIUC. Thanks!
