### PR TITLE
Add Cygwin job + fix cygwin bootstrap

### LINKED ISSUE #12316: Dune 3.20.0 broken on Cygwin/Windows x86_64
## Expected Behavior
  Dune 3.20.0 should compile successfully on Cygwin/Windows x86_64 systems during the bootstrap
  process.

## Actual Behavior

  Dune 3.20.0 compilation fails during the bootstrap phase with linking errors related to
  unresolved Blake3 symbols:

  ** Cannot resolve symbols for blake3_dispatch.o:
  [...]
   blake3_compress_xof_avx512
   blake3_compress_xof_sse2
   blake3_compress_xof_sse41
   blake3_hash_many_avx2
   blake3_hash_many_avx512
   blake3_hash_many_sse2
   blake3_hash_many_sse41
   blake3_xof_many_avx512
  File "caml_startup", line 1:
  Error: Error during linking (exit code 2)

## Reproduction
 This occurs when trying to install any package that depends on Dune in a fresh opam environment
  on Cygwin/Windows:

  1. Initialize opam with a recent opam-repository commit: opam init --bare default
  git+https://github.com/ocaml/opam-repository.git#d87894f816bea883931937e050bb5be4f108e50a
  2. Create a switch with system OCaml: opam switch create default ocaml-system
  3. Try to install any package requiring Dune: opam install lwt 

see https://github.com/arozovyk/opam/actions/runs/17233978247/job/48894396963

## Specifications

- Version of `dune` 3.20.0 (from opam-repository#d87894f816bea883931937e050bb5be4f108e50a)
- Version of `ocaml` 4.14.2
- Operating system (distribution and version): Cygwin on Windows x86_64

related to https://github.com/ocaml/dune/pull/11735 (cygwin is not tested by the CI)

### PR DESCRIPTION
**Pull request by Alizter**
In this PR we add a small CI job for testing the bootstrap process for Cygwin.

We also fix the bootstrap process on Cygwin. We have to use the portable blake3 implementation since the assembly causes segfaults and I don't think it's worth finding out why.

- Fixes https://github.com/ocaml/dune/issues/12316

cc @maiste for inclusion in 3.20.2

### CODE REVIEW

File: boot/duneboot.ml [hunk 1]
```diff
@@ -1164,8 +1164,8 @@ module Library = struct
             let extra_flags =
               if String.starts_with ~prefix:"blake3_" fn
               then (
-                match architecture with
-                | "x86" | "i386" | "i486" | "i586" | "i686" ->
+                match Sys.cygwin, architecture with
```
Comment (rgrinberg) [inline boot/duneboot.ml]: Could you write this with an if statement instead?

Comment (Alizter) [reply boot/duneboot.ml]: Done

File: boot/duneboot.ml [hunk 2]
```diff
@@ -1164,14 +1164,19 @@ module Library = struct
             let extra_flags =
               if String.starts_with ~prefix:"blake3_" fn
               then (
-                match architecture with
-                | "x86" | "i386" | "i486" | "i586" | "i686" ->
+                let is_32_bit_arch =
+                  match architecture with
+                  | "x86" | "i386" | "i486" | "i586" | "i686" -> true
```
Comment (rgrinberg) [inline boot/duneboot.ml]: Isn't there something like word size in the ocaml config?

Comment (Alizter) [reply boot/duneboot.ml]: We have `Sys.word_size` which I've now used.

Comment (rgrinberg) [reply boot/duneboot.ml]: You can't use that unfortunately. We can only use information from the ocaml config

File: boot/duneboot.ml [hunk 3]
```diff
@@ -1163,15 +1163,15 @@ module Library = struct
           then (
             let extra_flags =
               if String.starts_with ~prefix:"blake3_" fn
-              then (
-                match architecture with
-                | "x86" | "i386" | "i486" | "i586" | "i686" ->
+              then
+                if Sys.cygwin || Sys.word_size == 32
```
Comment (rgrinberg) [inline boot/duneboot.ml]: You should pass `word_size` to this function (like`ext_obj`) and obtain this value from the ocaml config.

**Review by rgrinberg — CHANGES_REQUESTED** [review]

File: boot/duneboot.ml (hunk 3 above)
Comment (Alizter) [reply boot/duneboot.ml]: Done. Do you want to do the same for `os_type`? I can replace our other uses of `Sys` with that too.

Comment (rgrinberg) [reply boot/duneboot.ml]: It's not strictly required, but I think it would be cleaner, yes.

The issue is that the bootstrap is building dune for a different version of OCaml than it's running when using a secondary compiler. This is like cross compilation, but the target/host OS is always the same (that is why it's not strictly required).

**Review by rgrinberg — APPROVED** [review]

File: boot/duneboot.ml (hunk 3 above)
Comment (Alizter) [reply boot/duneboot.ml]: IINM the `Sys.os_type` values are determined at compile-time and not run-time, so I don't think they would affect cross-compilation.

Comment (rgrinberg) [reply boot/duneboot.ml]: You are right that it is determined at compile time, but the problem is that they are determined for the wrong OCaml here. We need these values for the OCaml that we are targeting, not the one executing the bootstrap.
