### PR TITLE
Fix #1426

### LINKED ISSUE #1426: executable bit change doesn't trigger re-copy
Consider the following simple project:

```sh
cat >dune <<EOF
(rule
 (targets a)
 (action (with-stdout-to a (run ./b.sh))))
EOF

cat >b.sh <<EOF
#!/bin/sh
echo hi
EOF

dune build a
# fails because b.sh does not have executable bit set

chmod +x b.sh
./b.sh
# prints hi

dune build a
# should succeed, but fails again because permissions of _build/default/b.sh were not updated
```

### PR DESCRIPTION
**Pull request by rgrinberg**
I've revived #1438 but chose to do things in a slightly different way. I think we can just keep the permissions as part of the digest as we already did for the directories. There's no need to leak this information outside this module.

### CODE REVIEW

File: src/utils.ml [hunk 1]
```diff
@@ -201,6 +201,7 @@ module Cached_digest = struct
   type file =
     { mutable digest            : Digest.t
     ; mutable timestamp         : float
+    ; mutable permissions       : Unix.file_perm
     ; mutable timestamp_checked : int
```
Comment (diml) [inline src/utils.ml]: This should no longer be called `timestamp_checked` given that we also check the permissions. What about `stats_checked`?

Comment (rgrinberg) [reply src/utils.ml]: done
