### PR TITLE
fix: Add or remove dune from package sets to allow resolving packages depending on it

### LINKED ISSUE #11096: dune dependency error with `dune pkg lock`
The #10918 introduced a bug or a regression in the way the `dune pkg lock` command work. I checked and the behavior wasn't present in the commit before.

## Expected Behavior

When running a project with `dune` in the `depends` stanza of a _dune-project_ file, it should build without any error. It was the previous behaviour before the mentioned PR.

## Actual Behavior

The computation fails, and it prints the following stack trace:
```
Internal error, please report upstream including the contents of _build/log.
Description:
  ("can't find a valid solution for the dependencies", { name = "foo" })
Raised at Stdune__Code_error.raise in file
  "otherlibs/stdune/src/code_error.ml", line 10, characters 30-62
Called from Dune_pkg__Opam_solver.reject_unreachable_packages.(fun) in file
  "src/dune_pkg/opam_solver.ml", lines 830-832, characters 14-56
Called from Stdlib__Map.Make.merge in file "map.ml", line 406, characters
  44-63
Called from Stdlib__Map.Make.merge in file "map.ml", line 403, characters
  64-79
Called from Stdlib__Map.Make.merge in file "map.ml", line 403, characters
  25-40
Called from Stdlib__Map.Make.merge in file "map.ml", line 403, characters
  25-40
Called from Stdlib__Map.Make.merge in file "map.ml", line 403, characters
  64-79
Called from Dune_pkg__Opam_solver.reject_unreachable_packages.(fun) in file
  "src/dune_pkg/opam_solver.ml", lines 802-841, characters 6-32
Called from Dune_pkg__Opam_solver.solve_lock_dir.(fun) in file
  "src/dune_pkg/opam_solver.ml", line 949, characters 10-78
Called from Fiber__Scheduler.exec in file "vendor/fiber/src/scheduler.ml",
  line 76, characters 8-11
Re-raised at Stdune__Exn.raise_with_backtrace in file
  "otherlibs/stdune/src/exn.ml", line 38, characters 27-56
Called from Fiber__Scheduler.exec in file "vendor/fiber/src/scheduler.ml",
  line 76, characters 8-11

I must not crash.  Uncertainty is the mind-killer. Exceptions are the
little-death that brings total obliteration.  I will fully express my cases. 
Execution will pass over me and through me.  And when it has gone past, I
will unwind the stack along its path.  Where the cases are handled there will
be nothing.  Only I will remain.
```

## Reproduction

You can find some logs in the binary distribution preview test: https://github.com/ocaml-dune/binary-distribution/actions/runs/11656938519/job/32453884724#step:7:49

Otherwise, to reproduce, you just need to run with an executable of dune build from `main`:

```sh
dune init proj foo 
cd foo
dune pkg lock
```

If you remove the `dune` dependency from the `(depends ...)` stanza of the _dune-project_ file, it will work without error.

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
There's multiple ways to go about it:

1. Add some dune package in the space of valid packages. I was not sure how to get the dune version out of `dune_rpc` or whether that would even be the right thing, so I set the version to `dev`.
2. Remove `dune` from the dependency formulas. `Dependency_formula.remove_package formula (Package_name.Set.singleton Dune_dep.name)` is an alternate solution. 

Fixes #11096

### CODE REVIEW

File: src/dune_pkg/opam_solver.ml [hunk 1]
```diff
@@ -810,7 +810,13 @@ let reject_unreachable_packages =
             [ "name", Package_name.to_dyn name ]
         | Some (pkg : Lock_dir.Pkg.t), None -> Some (List.map pkg.depends ~f:snd)
         | None, Some (pkg : Local_package.For_solver.t) ->
-          let formula = pkg.dependencies |> Dependency_formula.to_filtered_formula in
+          (* remove Dune from the formula as we remove it from solutions *)
+          let formula =
```
Comment (maiste) [inline src/dune_pkg/opam_solver.ml:814]: This is mostly a question to understand the behavior. Will it keep the constraint on Dune somewhere, even if we remove it from the formula? This is just to understand the way it is computed underneath.

**Review by maiste — APPROVED** [review]
One question to understand but it LGTM :+1:

File: src/dune_pkg/opam_solver.ml (hunk 1 above)
Comment (Leonidas-from-XIV) [reply src/dune_pkg/opam_solver.ml:814]: This is just to check which packages are reachable, it is not what is used to compute the solution. As you can see in CI, the `implicit-dune-deps.t` test that checks the dune version against a constraint is passing.

**Review by rgrinberg — APPROVED** [review]

**Comment by rgrinberg** [comment]
We need to do a combination of 1 and 2. We need to pick the correct deps for a formula like `("a" "dune" {> 3}) | ("b" "dune" {< 3})`.

So we give the right dune version when evaluating the formula and then filtering out dune from the evaluated list. We do the same for external deps as well.

I pushed something along those lines.
