### PR TITLE
fix: propagate compiler pins to dev tool solver

### LINKED ISSUE #12868: Dev tools and special compiler branches
There are certain dev tools like `ocamllsp` that require to have a matching compiler version as the project. The check currently assumes the compiler package is `ocaml` and installs the dev tool with the same `ocaml` package.

https://github.com/ocaml/dune/blob/da89573a9c282f5db84ac4ef6597b8402fc3424e/bin/lock_dev_tool.ml#L98-L152

However, this does not capture other possible compilers. #12834 proposes to improve this by taking into account more possible compiler packages, such as `ocaml-variants`, `ocaml-base-compiler`. However, it doesn't cover the cases where the user has special compiler branches pinned, as @rgrinberg explained here: https://github.com/ocaml/dune/pull/12834#issuecomment-3609206926. In this case it should ideally go through compiler pins and add it as a pin to the dev tool.

### PR DESCRIPTION
**Pull request by benodiwal**
Closes #12868

### CODE REVIEW

File: bin/lock_dev_tool.ml [hunk 1]
```diff
@@ -3,6 +3,15 @@ open Import
 module Lock_dir = Dune_pkg.Lock_dir
 module Pin = Dune_pkg.Pin
 
+(* Package names that are considered compiler packages. When these are pinned
+   in the project, the pins should be propagated to dev tools that need to be
+   built with the same compiler. *)
+let compiler_package_names =
+  List.map
+    ~f:Package_name.of_string
+    [ "ocaml"; "ocaml-base-compiler"; "ocaml-variants"; "ocaml-compiler" ]
```
Comment (Sudha247) [inline bin/lock_dev_tool.ml]: This is also present in: https://github.com/ocaml/dune/blob/3b5f1c958ccafc658dff8298af75a72159fab3c9/src/dune_rules/pkg_toolchain.ml#L54-L61.

It would be good to share these to not end up hardcoding the same thing twice, perhaps somewhere in `dune_pkg`.

File: test/blackbox-tests/test-cases/pkg/ocamllsp/dev-tool-ocamllsp-pinned-compiler.t [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+
+  $ mkrepo
+  $ make_mock_ocamllsp_package
+  $ mk_ocaml 5.2.0
+
+Create a fake pinned compiler source. This simulates a scenario where the user
+has pinned a custom compiler branch (e.g., OxCaml).
+
+  $ mkdir -p pinned-compiler
+  $ cat > pinned-compiler/ocaml.opam <<EOF
```
Comment (Sudha247) [inline test/blackbox-tests/test-cases/pkg/ocamllsp/dev-tool-ocamllsp-pinned-compiler.t]: Nitpick: I think we should make ocaml-base-compiler or ocaml-variants as the compiler package to reflect how opam does it.

**Review by Sudha247 — COMMENTED** [review]
I think this is an improvement over the current situation. However, it would be better not to hardcode the compiler packages. Unfortunately, I don’t currently have a solution for determining this without hardcoding.

**Comment by benodiwal** [comment]
@Sudha247 I have made the suggested changes

File: bin/lock_dev_tool.ml [hunk 3]
```diff
@@ -66,6 +66,26 @@ let make_local_package_wrapping_dev_tool ~dev_tool ~dev_tool_version ~extra_depe
...
+(* Collect all pins from all projects and filter to only compiler packages.
+   This allows dev tools to use the same pinned compiler as the main project. *)
+let compiler_pins =
+  let open Memo.O in
+  Dune_rules.Dune_load.projects ()
+  >>| List.fold_left ~init:Pin.DB.empty ~f:(fun acc project ->
+    let pins = project_and_package_pins project in
+    Pin.DB.combine_exn acc pins)
+  >>| Pin.DB.filter_by_package_names
+        ~package_names:Dune_pkg.Dev_tool.compiler_package_names
```
Comment (rgrinberg) [inline bin/lock_dev_tool.ml]: Are these functions copy-pasted from somewhere?

Comment (benodiwal) [reply bin/lock_dev_tool.ml]: Based on `project_pins` from `bin/pkg/lock.ml`, with an additional filter to only keep compiler packages.
https://github.com/ocaml/dune/blob/8e0cc96/bin/pkg/lock.ml#L523-L528

Comment (rgrinberg) [reply bin/lock_dev_tool.ml]: Could you please reuse the functions in pkg/lock?

**Review by rgrinberg — CHANGES_REQUESTED** [review]

File: bin/lock_dev_tool.ml (hunk 3 above)
Comment (benodiwal) [reply bin/lock_dev_tool.ml]: made the requested change

File: src/dune_pkg/pin.mli [hunk 4]
```diff
@@ -13,6 +13,10 @@ module DB : sig
   val combine_exn : t -> t -> t
   val add_opam_pins : t -> Dune_lang.Package.t Package_name.Map.t -> t
 
+  (** [filter_by_package_names t ~package_names] returns a new pin database
+      containing only the pins for packages whose names are in [package_names]. *)
+  val filter_by_package_names : t -> package_names:Package_name.t list -> t
```
Comment (rgrinberg) [inline src/dune_pkg/pin.mli]: Where is this function being used?

Comment (benodiwal) [reply src/dune_pkg/pin.mli]: https://github.com/ocaml/dune/pull/13033/files

**Comment by rgrinberg** [comment]
Thanks. Merged with a couple of fixes.
