### PR TITLE
fix(install): do substitution for sites files

### LINKED ISSUE #10317: gettext-camomile fails to build on nix (3.15.0~alpha1)
https://github.com/nix-ocaml/nix-overlays/actions/runs/8438106703/job/23120699845?pr=1349

```
Running phase: checkPhase
File "test/test-camomile/dune", line 2, characters 7-11:
2 |  (name test)
           ^^^^
(cd _build/default/test/test-camomile && ./test.exe -test-dir ../testdata)
Fatal error: exception File "src/configImpl.ml", line 1, characters 58-64: Assertion failed
                                   
error: builder for '/nix/store/pww9d1y40cp8im0ggsaw051j2v6j163q-ocaml4.14.2-gettext-camomile-0.4.2.drv' failed with exit code 1;
       last 15 log lines:
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/rz68lchjc6v1i9p1cahqlhvif4acfpsr-source
       > source root is source
       > Running phase: patchPhase
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > no configure script, doing nothing
       > Running phase: buildPhase
       > Running phase: checkPhase
       > File "test/test-camomile/dune", line 2, characters 7-11:
       > 2 |  (name test)
       >            ^^^^
       > (cd _build/default/test/test-camomile && ./test.exe -test-dir ../testdata)
       > Fatal error: exception File "src/configImpl.ml", line 1, characters 58-64: Assertion failed
       >
       For full logs, run 'nix log /nix/store/pww9d1y40cp8im0ggsaw051j2v6j163q-ocaml4.14.2-gettext-camomile-0.4.2.drv'.
```

### PR DESCRIPTION
**Pull request by emillon**
Fixes #10317

### CODE REVIEW

File: bin/install_uninstall.ml [hunk 1]
```diff
@@ -142,7 +142,6 @@ module Special_file = struct
 end
 
 type copy_kind =
```
Comment (anmonteiro) [inline bin/install_uninstall.ml:144]: there isn't really a difference between this type and `option` now, but it's up to you if you find the names more descriptive.

**Review by anmonteiro — APPROVED** [review]

File: bin/install_uninstall.ml (hunk 1 above)
Comment (emillon) [reply bin/install_uninstall.ml:144]: I agree; but this also documents that we're actually using artifact subtitution in this case, and also #10302 will touch a bit that part so I expect a third variant to appear in there.
