### PR TITLE
fix(pkg): allow locking relative path outside the workspace

### LINKED ISSUE #10254: pkg: error when locking when a pin stanza contains a relative path outside the workspace
If the `url` of the pin stanza is a `file://` path which is relative and refers to a location outside of the current workspace, `dune pkg lock` prints the error:
```
Error: path outside the workspace: ../foo from .
```

Here's an example `dune-project` file that causes this issue.
```
(lang dune 3.14)
 (pin
  (url file://../foo)
  (package (name foo)))
 (package
  (name bar)
  (depends foo))
```

Repro PR: TODO

### PR DESCRIPTION
**Pull request by shunueda**
Closes https://github.com/ocaml/dune/issues/10254.

The linked issue has been labeled "bug", and I agree with this as (afaik) Opam allows relative paths outside the workspace, though open to discussion here.

### CODE REVIEW

File: src/dune_rules/lock_dir.ml [hunk 1]
```diff
@@ -308,7 +308,11 @@ let source_kind (source : Dune_pkg.Source.t) =
   let loc, url = source.url in
   if OpamUrl.is_local url && url.backend = `rsync
   then (
-    let path = Path.External.of_string url.path in
+    let path =
+      Path.of_string_allow_outside_workspace url.path
+      |> Path.to_absolute_filename
+      |> Path.External.of_string
```
Comment (rgrinberg) [inline src/dune_rules/lock_dir.ml]: Can't you pattern match on the result of `Path.of_string_allow_outside_workspace url.path` and construct the right path directly for `Fs_memo.path_kind`?

Comment (shunueda) [reply src/dune_rules/lock_dir.ml]: Yes, though required some refactoring so I split it into a separate commit.

**Comment by rgrinberg** [comment]
LGTM. Do you mind adding a change log entry?
