### PR TITLE
Fix #1101

### LINKED ISSUE #1101: 'dune exec' behaves differently with DUNE_BUILD_DIR set to absolute path
If I try to set `DUNE_BUILD_DIR` to an absolute path `dune exec` fails:
```
% DUNE_BUILD_DIR="$PWD/_custom" dune exec test/test_main.exe
File unavailable: /Users/andreypopp/Workspace/esy-ocaml/repromise/_custom/default/test/test_main.exe
```
while relative `DUNE_BUILD_DIR` (or an absence of such) works:
```
% dune exec test/test_main.exe
Testing library 'repromise'...
......................................................
Ok. 54 tests ran, 0 tests skipped
```
```
% DUNE_BUILD_DIR="./_custom" dune exec test/test_main.exe
Testing library 'repromise'...
......................................................
Ok. 54 tests ran, 0 tests skipped
```

Hitting this with `esy` on [aantron/repromise](https://github.com/aantron/repromise) but the snippets above are replicated with opam.

### PR DESCRIPTION
**Pull request by rgrinberg**
cc @andreypopp. The code in this main module is getting hairy. We should probably re-organize our CLI soon-ish.

### CODE REVIEW

**Review by emillon — APPROVED** [review]

File: bin/main.ml [hunk 1]
```diff
@@ -658,75 +658,87 @@ let check_path contexts =
             name
             (hint name (String.Set.to_list contexts))
 
-let resolve_targets ~log common (setup : Main.setup) user_targets =
+let resolve_path path ~(setup : Main.setup) =
+  let check_path = check_path setup.contexts in
```
Comment (diml) [inline bin/main.ml]: In both `resolve_path` and `resolve_target`, `check_path` is now used only once, so we don't need to partially apply it anymore

File: bin/main.ml [hunk 2]
```diff
@@ -658,75 +658,87 @@ let check_path contexts =
...
-                else
-                  None)
-            with
-            | [] -> can't_build path
-            | l  -> Ok l
-        end
-      )
-    in
+      List.map user_targets ~f:(function
+        | `String s -> resolve_target common ~setup s
```
Comment (diml) [inline bin/main.ml]: Could you use a plain variant here? I find polymorphic variants more error prone and they provide no real benefit here

**Review by ghost — CHANGES_REQUESTED** [review]

**Comment by rgrinberg** [comment]
@diml good call. i addressed your review

**Review by ghost — APPROVED** [review]
